### ISSUE TITLE
Language Detection Bug introduced in Rest API

### ISSUE THREAD

**Issue by Letgamer** [ltb-project/self-service-password#1002]
There was a bug introduced with the change to move the language detection outside of the repository.
The `htdocs/index.php` was changed but not the `rest/v1/include.php` , therefore it tries to require_once the non existing `/lib/detectbrowserlanguage.php`

=> Language detection in the API is no longer working
=> The Rest API itself is broken as PHP throws a a fatal error and will stop execution

**Comment by Letgamer** [comment]
Just noticed, that this is a duplicate, will close now

**Comment by coudot** [comment]
Indeed, see #996

We will release a fix version soon

**Comment by coudot** [comment]
1.7.1 was released today
