### ISSUE TITLE
HTTPS?

### ISSUE THREAD

**Issue by cabefe** [ltb-project/self-service-password#1014]
Is it possible to enable HTTPS on the docker machine? I can't find anything in the documentation. 
Thanks.

**Comment by davidcoutadeur** [comment]
You can enable https by different ways:
- add an https frontend in front of ssp
- tweak the ssp apache vhost, and mount it as a config map. In this case, you have to get the ssp apache vhost in the container, configure the TLS options, generate your certificates and private key, and mount all these in the container.

**Comment by davidcoutadeur** [comment]
Also, if you have questions, please don't use the issue system. Use the github discussions or the mailing list
