### ISSUE TITLE
Error: unknown cache type:

### ISSUE THREAD

**Issue by cp61** [ltb-project/self-service-password#1021]
Hello, 

I have a version in 1.6.1 which works without problem.

When I migrate to version 1.7.1, I get a blank page and in the logs I have the following messages:

Sun Dec 15 22:20:55.224368 2024] [php:warn] [pid 658:tid 658] [client 192.168.61.61:40076] PHP Warning:  Undefined variable $cache_type in /usr/share/self-service-password/htdocs/index.php on line 125
[Sun Dec 15 22:20:55.224406 2024] [php:warn] [pid 658:tid 658] [client 192.168.61.61:40076] PHP Warning:  Undefined variable $cache_type in /usr/share/self-service-password/htdocs/index.php on line 128
[Sun Dec 15 22:20:55.224413 2024] [php:warn] [pid 658:tid 658] [client 192.168.61.61:40076] PHP Warning:  Undefined variable $cache_type in /usr/share/self-service-password/htdocs/index.php on line 135
[Sun Dec 15 22:20:55.224420 2024] [php:warn] [pid 658:tid 658] [client 192.168.61.61:40076] PHP Warning:  Undefined variable $cache_type in /usr/share/self-service-password/htdocs/index.php on line 143
[Sun Dec 15 22:20:55.224425 2024] [php:notice] [pid 658:tid 658] [client 192.168.61.61:40076] Error: unknown cache type:

I don't know how to fix this problem despite my research.

Thanks

**Comment by davidcoutadeur** [comment]
Hello @cp61,

I don't know how you proceed to the migration, but there is clearly a problem with the main configuration file: `/etc/self-service-password/config.inc.php`.

You can give a look to the one provided in the repository: https://github.com/ltb-project/self-service-password/blob/master/conf/config.inc.php

In version 1.7.1, there is indeed a new cache system. The default variable in config.inc.php is:

```
$cache_type = "File";
````

Regards

**Comment by cp61** [comment]
Hello

Thank you for your response.

When I migrated, I didn't change the conf file so variables were missing. Everything is ok!!!

THANKS
