### ISSUE TITLE
Use Smarty framework

### ISSUE THREAD

**Issue by Kage** [ltb-project/self-service-password#109]
I've become a big fan of the [Silex PHP framework](https://silex.sensiolabs.org), and was wondering what your thoughts are on rewriting it to fit?  That way it has a proper router, dependency injection, etc., and dependencies can be easily managed with Composer.

I have a FOSS project I'll be publishing soon on [my community](https://github.com/HackThisCode) that could also work as an excellent skeleton framework to merge this into.

So.. thoughts?

**Comment by coudot** [comment]
Why not. For LTB White Pages I used Smarty which is also a good solution.

**Comment by plewin** [comment]
I believe SSP should implement the first PSRs (coding standard, code style, logging, autoloader) and refactor most of the code before thinking about porting to a microframework or even any framework.
This could be targetted for 1.2.

**Comment by coudot** [comment]
Yes, there is a lot of work before this. I think if we achieve to rewrite SSP with a framework, we could release it as 2.0. For the moment we will try to release 1.1 and add new features in 1.x branch.

**Comment by ntoniazzi** [comment]
Silex has [officially been deprecated](http://symfony.com/blog/the-end-of-silex), so another framework would be needed (Symfony).

**Comment by plewin** [comment]
Yes silex is deprecated, I work on an new major version based on symphony
components

**Comment by Kage** [comment]
Indeed.  I would recommend [Slim Framework](https://www.slimframework.com) instead of a full-fledged Symfony app for two reasons:

1. Symfony 3.4 is quite cumbersome, and Symfony 4+ requires PHP 7.2 (thus severely limiting the audience for SSP).  Integrating SSP into either would probably be quite onerous and require a complete recode of everything.
2. Slim allows for basic framework control (router, PSR by default), but is very lightweight and would probably allow for reusing a lot of existing SSP code.

I've noticed Smarty mentioned elsewhere, and I would instead strongly recommend using Twig for templating.  Smarty is also cumbersome, whereas Twig is quite lightweight and has much more community support.

**Comment by coudot** [comment]
I used Smarty for LTB White Pages and it would be better for me to have the same framework for SSP

**Comment by Kage** [comment]
Fair enough. :P

**Comment by coudot** [comment]
Work done by @JuJuMDX, a PR is coming
