### ISSUE TITLE
Documentation latest link

### ISSUE THREAD

**Issue by roumano** [ltb-project/self-service-password#110]
Hi,

the lastest documentation : 
  https://ltb-project.org/documentation/self-service-password/latest/start

is a link to Documentation for version 1.0 

it's should be for the 1.1 version.

**Comment by plewin** [comment]
Hi @roumano,

Version 1.0 is the current stable and latest released version of SSP.
Version 1.1 is not finished.

Linking to the 1.0 documentation is definitely the way to go.

**Comment by roumano** [comment]
Ok sorry
