### ISSUE TITLE
Show what characters are forbidden

### ISSUE THREAD

**Issue by THS-on** [ltb-project/self-service-password#113]
Hello,
I disallowed some characters because they play not nice with some applications. Now if I enter one of the forbidden characters I get the following message: "You password contains forbidden characters".  
For me it's clear witch characters are forbidden, but for a normal user it's not.
I can add my forbidden characters to the translation file but this is only a workaround.
Maybe a better message would be: You password contains on of " $pwd_forbidden_chars" forbidden characters".  

Best regards
THS-on

**Comment by coudot** [comment]
Note that you have an option to show policy if there is an error: https://ltb-project.org/documentation/self-service-password/latest/config_ppolicy#show_policy

By security, we don't display any security rule by default.

**Comment by THS-on** [comment]
@coudot Thanks, this is reasonable. For me it's ok to show the policy, so I'll use that.
