### ISSUE TITLE
Force specific language?

### ISSUE THREAD

**Issue by sfieux** [ltb-project/self-service-password#115]
I'm trying to force the use of english for my installation of self-service-password. It seems that this piece of code from `index.php` is causing my trouble:

```
require_once("conf/config.inc.php"); # contains line $lang ="en"; 
(...)
$lang = detectLanguage($lang, $languages);
require_once("lang/$lang.inc.php");
```

The way I understand it is: the language is defined in `config.inc.php`, and afterwards this information is discarded to read it from browser settings in `detectLanguage`.

Am I missing something?

If I'm not, would you be interested in a PR to change this behaviour? I would change the default language value to "auto" in `config.inc.php` and only try to detect the browser language if the value is different:

```
if ( $lang == "auto" ) {
    $lang = detectLanguage($lang, $languages);
}
require_once("lang/$lang.inc.php");
if (file_exists("conf/$lang.inc.php")) {
    require_once("conf/$lang.inc.php");
}
```

**Comment by coudot** [comment]
Maybe the best would be to configure a list of authorized languages. Then this would require a new parameter which will be an array. If it is empty, all available languages will be authorized, else this parameter will be used to limit which languages could be used.

**Comment by sfieux** [comment]
What would be the expected behaviour when several languages are authorized but the detected one is not part of the list? Une the first authorized one? Use initial `$lang` value?

**Comment by coudot** [comment]
if the lang is not one authorized, then fall back to default lang

**Comment by plewin** [comment]
I'm closing this issue because the PR was merged.
Thank you for your contribution @sfieux.

**Comment by sfieux** [comment]
No problem, I'm the one who needed it :)
