### ISSUE TITLE
LDAP Multipage Access

### ISSUE THREAD

**Issue by cayetano** [ltb-project/self-service-password#123]
I'm have a big Active Directory > 2000 users.

When access LDAp (AD ) i'm receive this error:
 PHP Warning:  ldap_search(): Partial search results returned: Sizelimit exceeded in /var/www/html/glpi/reset/pages/change.php on line 109

Thanks, and .. sorry , I have a poor english

Regards
Cayetano

**Comment by plewin** [comment]
Hi @cayetano,
What did you put in your configuration for $ldap_filter?

**Comment by cayetano** [comment]
First thanks for you response...

$ldap_filter = "(&(objectClass=user)(objectCategory=person))";

¿ is correct ?

Regards
Cayetano

2017-07-11 19:03 GMT+02:00 Philippe Lewin <notifications@github.com>:

> Hi @cayetano,
> What did you put in your configuration for $ldap_filter?
>

**Comment by plewin** [comment]
this filter is not correct. This filter will ask the data for all your
users, SSP need a filter that will return only one result.
You need to be more specific in your filter and use {login}
see also for an example
https://ltb-project.org/documentation/self-service-password/latest/config_ldap

**Comment by plewin** [comment]
I'm closing this issue because the solution has been provided.
