### ISSUE TITLE
proxy support for ReCaptcha

### ISSUE THREAD

**Issue by mohaja** [ltb-project/self-service-password#126]
Hi, my server is behind a corporate firewall and using proxy to access internet. How can i configure the recaptcha feature to use proxy ? Already set http_proxy & https_proxy in /etc/environment in my server (CentOS 7) but no success. Please advise. 

Thank you

**Comment by coudot** [comment]
Try https://stackoverflow.com/questions/16914034/google-recaptcha-using-proxy

**Comment by mohaja** [comment]
where should i set/edit this ?

**Comment by coudot** [comment]
You can set it in config.inc.php

**Comment by plewin** [comment]
Hi @mohaja, did you have success with using recaptcha behind a proxy  ? 

I do not think it is possible easily without hacking.

Proxy support in the embedded recaptcha lib is not implemented (cf. https://github.com/google/recaptcha/issues/46)

The easiest way to make it work would be to edit this file your proxy details
https://github.com/ltb-project/self-service-password/blob/v1.0/lib/vendor/ReCaptcha/RequestMethod/Post.php#L64
See this page for details
https://stackoverflow.com/questions/1336262/file-get-contents-behind-a-proxy

Also, I submitted a PR that solves this problem, when it will be merged you will be able to declare/code in the config file a custom "request method" that use your proxy.

**Comment by coudot** [comment]
@mohaja, @plewin, the PR is merged. Please close the issue if this is ok for you.

**Comment by mohaja** [comment]
My SSP already gone production. So if I am to apply this solution, can I just yum update it ? FYI my version is self-service-password-1.0-2.el7.noarch. If I have to wait for ver 1.1, then sure I'll update later when it'll release. Thanks to the SSP team for the effort.

**Comment by coudot** [comment]
Yes, when 1.1 will be released, you will just need to update.
