### ISSUE TITLE
Multidomain support

### ISSUE THREAD

**Issue by gino909** [ltb-project/self-service-password#127]
Hi
Thanks for this great script.
It will me help a lot to give our users the easy possibility to change theire password.
Only thing i miss is support for multidomain... is there a possibility already existing?

Basically may it should work with mulitple values in $ldap_base like

$ldap_base = "ou=group,dc=domain,dc=com; ou=group,dc=domain,dc=net; ou=group,dc=domain,dc=eu"

or to work with wildcard and read the domain from the email Adress, but this works only if the login is the email address....

Please let me know

Thank you

**Comment by coudot** [comment]
Indeed this is not yet implemented and would require a huge work.

What you can do is install several SSP interfaces and bind them to the good domain. Then just communicate the good URL to users.

**Comment by gino909** [comment]
ok, thank you for your reply...

**Comment by plewin** [comment]
Hi @gino909, I have a trick but I am unsure if it will fit your need.

You can have multiple domains for one single SSP instance.
ex: client1-ssp.yourcompany.com, client2-ssp.yourcompany.com, client3-ssp.yourcompany.com
SSP has 1 master config file + 1 override config file per client (in your case the file will override only $ldap_base = "ou=group,dc=domain,dc=com" in config.client1.inc.php)

Would this help you ?

**Comment by gino909** [comment]
Hi, thank you for your suggestion

I have solved this issue by calling the SSP instance with the domain where the user is assigned.
So I have several server_name entries in nginx for the same instance, for example reset.domain1.com and reset.domain2.net

I have modified the config.inc.php in following method:

# select correct ldap_base based on the current domain
$domain= substr($_SERVER['HTTP_HOST'], 6, strlen($_SERVER['HTTP_HOST'])-6);
$dotpos = strpos($domain, ".");
$domainname = substr($domain, 0, $dotpos);
$tld = substr($domain, $dotpos + 1, 10);
$ldap_base = "ou=Group,dc=".$domainname.",dc=".$tld;

Hope this helps someone!

**Comment by plewin** [comment]
Wow thank you @gino909 , that's brillant !

**Comment by corvy** [comment]
Thanks this helps me as-well! Great contribution!

**Comment by corvy** [comment]
A quick update if anyone wants to use this for iRedMail installations. I modified config local like follows:

> $host_names = explode(".", $_SERVER['HTTP_HOST']);
> $domain_tld = $host_names[count($host_names)-2] . "." . $host_names[count($host_names)-1];
> $ldap_base = "ou=Users,domainName=".$domain_tld.",o=domains,dc=**domain**,dc=**tld**";

Just replace "domain" with your domainname for the server installed and "tld" with your installed tld name (both in bold above). All hosted email domains and accounts are in the O domains. Hope this is helpful for someone, and thanks again to @gino909 for getting me on-track for this simple solution.

**Comment by plewin** [comment]
Thank you all for the inputs, I'm closing this issue because it was solved.
