### ISSUE TITLE
Add extra parameter on token-page

### ISSUE THREAD

**Issue by Netcie** [ltb-project/self-service-password#129]
Is it possible to add a parameter to the token-page? 
I would like to verify a static value from the AD/User/Description to verify my users.

**Comment by plewin** [comment]
Hi Netcie,

If I understand good you would like to have in the page "index.php?action=sendtoken" the fields "Login", "Mail" + one extra like postal code, date of birth, or even maybe an answer to a security question.

That is not something currently supported.
I doubt that the current demand for this feature is worth the increase in complexity of SSP's code that this feature requires.

If you are not afraid to code a bit and to have to port the changes each time you upgrade SSP I can give you an example.

**Comment by coudot** [comment]
I agree with @plewin, this is very specific. You can adapt SSP code for your own needs, it is quite easy.
