### ISSUE TITLE
recaptcha uses file_get_contents to retrive data

### ISSUE THREAD

**Issue by jwacalex** [ltb-project/self-service-password#130]
Issue
==
When allow_url_fopen is disabled, the ReCaptcha plugin is unable to validate the result

Expected Result
==
ReCaptcha is validated.  If allow_url_fopen is disabled another method should be used. A lot of setups have disabled this, because allowing fopen to urls is discouraged by [OWASP](https://www.owasp.org/index.php/PHP_Top_5#How_to_Protect_Against_It) security recommendations

Actual Result
==
A Warning is raised and the process fails because the captcha cannot be validated
`Warning file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 .vendor/ReCaptcha/RequestMethod/Post.php`

Steps to reproduce
==
1. Enable ReCaptcha
1. Set `allow_url_fopen=0` via php.ini
1. Try to reset password and submit formular with recaptcha

**Comment by plewin** [comment]
Hi @jwacalex, thank you for reporting this issue.

ReCaptcha offers alternative request methods to avoid this problem. SSP does not yet offers the possibility to override the default one.

**Comment by coudot** [comment]
Please close if PR #131 is ok for you

**Comment by jwacalex** [comment]
thank you for your fast improvement of the tool. this replaces my quick fix by replacing the method!
