### ISSUE TITLE
Get extended ldap error in case of  "passworderror" from LDAP directory

### ISSUE THREAD

**Issue by konvergence** [ltb-project/self-service-password#133]
Hi,

I use OpenLDAP with ppolicy.
When use self-password , and  get error from openldap, cause of "password policy" into openldap, "self-password return only "Password was refused by the LDAP directory".

Could you get the extended error to be able to display the message coming from openldap ?

I do the following change into "change.php", but I suppose that I must do also "setquestions.php", "resetbytoken.php" and "resetbyquestions.php" ?

```
define("LDAP_OPT_DIAGNOSTIC_MESSAGE", 0x0032);
 $ldap_extended_error = "" ;
 if ( $result === "passworderror" ) {
     ldap_get_option($ldap, LDAP_OPT_DIAGNOSTIC_MESSAGE, $ldap_extended_error);
  }

<div class="result alert alert-<?php echo get_criticity($result) ?>">
<p><i class="fa <?php echo get_fa_class($result) ?>" aria-hidden="true"></i> <?php echo $messages[$result] . ":" . $ldap_extended_error ; ?></p>
</div>

```

**Comment by plewin** [comment]
Hi @konvergence,

I'm unsure that it is a good idea to display these details to the users, they are very technical and specific to each server/version.

In theory, if the password policy is not complex the "Password was refused by the LDAP directory" should not appear unless the password is in the list of previous passwords, for this specific case there is a PR in the work https://github.com/ltb-project/self-service-password/pull/101.
The local password policy https://github.com/ltb-project/self-service-password/blob/master/conf/config.inc.php#L78 should be able to tell the user that the password will not be accepted.

See https://github.com/ltb-project/self-service-password/pull/101#issuecomment-291276073 something similar was discussed

What errors do you get in the LDAP_OPT_DIAGNOSTIC_MESSAGE ? Can they be prevented by ajusting the local password policy or if the PR dealing with old passwords was merged ?

**Comment by konvergence** [comment]
Hi @plewin,

If I get the error "Password was refused by the LDAP directory", I whant to know why ...
The error case "Password is in history of old passwords" is not the only reason.

In my case, because I had define a ppolicy with "pwdMinAge", I get the error "Password is too young to change". 
But anyway, if the policy defined into "self-password" is not aligned or not cover the real policy into openldap, you will get the ldap error.

When ad_mode is activated, you started to test "ldap extended error". But also, I'm not sure that you cover all cases, when the  error 49 appears.

I suggest the following approach 
-  add an option into "config.inc.php" to display the "extended ldap error".
 Ex : $show_extented_ldap_error = true ;

-  each time, you what to cast the "ldap error" (ad_mode or not),  display the "ldap extended error" if the error is not cover ito the code and $show_extented_ldap_error = true ;

I will continue, the update , in my branch, and will update you when it will finalized.

**Comment by coudot** [comment]
Note that there is a current work in PHP to fully support ppolicy control (there will be a conference on this subject soon: https://ldapcon.org/2017/maintaining-and-extending-php-ldap/)

The best is to send the ppolicy control an get the control response. But maybe we can have a workaround for the moment.

I will look at your PR as soon as possible

**Comment by plewin** [comment]
@coudot, 
Do you know if there will be a publicly accessible video of this ldapcon talk you mentioned ?

**Comment by coudot** [comment]
I don't know for the video, but slides will be published.

**Comment by coudot** [comment]
Done in #367 and #156
