### ISSUE TITLE
sendtoken.php send http link instead of https

### ISSUE THREAD

**Issue by konvergence** [ltb-project/self-service-password#137]
Hi,

I use self-password behind haproxy that handles SSL .
under the code you choose to write https if $_SERVER['HTTPS'] is non empty.
But I my case $_SERVER['HTTPS'] is empty

```       
        if ( !empty($_SERVER['HTTPS']) ) { $method .= "s"; }
```

**Do you have any suggestion ?**

I find several solutions : 
- Solution inside sendtoken.php  :
 inspect $SERVER['X-FORWARDED-PROTO'] to detect HTTPS support, as a workaround for weak implementation of $SERVER['HTTPS'] 

```
if(!empty($_SERVER['HTTPS']) || (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https')){
    $method .= "s";  
}
```
...
```
 # Force server port if non standard port
        if (   ( $method === "http"  and $server_port != "80"  )
            or ( $method === "https" and $server_port != "443" )
        ) {
          if( isset($_SERVER['HTTP_X_FORWARDED_PORT'])) {
               $server_name .= ":".$_SERVER['HTTP_X_FORWARDED_PORT'];
            } else {
               $server_name .= ":".$server_port;
            }
        }

```
- Solution inside Apache : 
In httpd-modules.conf, uncomment this line.
```
LoadModule setenvif_module modules/mod_setenvif.so
```
In httpd-php.conf, add this line.
```
#
# Set HTTPS environment variable if we came in over secure
#  channel.
SetEnvIf x-forwarded-proto https HTTPS=on
```

**Comment by coudot** [comment]
Use the `$reset_url` parameter: https://ltb-project.org/documentation/self-service-password/latest/config_tokens#reset_url
