### ISSUE TITLE
SSP in compact mode

### ISSUE THREAD

**Issue by mohaja** [ltb-project/self-service-password#140]
Will it possible to make it 'compact' instead of 'cozy' ? I think it is useful for application that calls it. I can remove the banner/logo but still it would be better to make things smaller. And when will the 1.1 release ?

Thank for sharing a wonderful app.

**Comment by coudot** [comment]
We use bootstrap which is designed to fit different screen sizes (mobile, pad, computers, ...)

You can try to put your own bootstrap theme to have a compact view, or override bootstrap classes in local CSS.

**Comment by XavierHx** [comment]
Cannot access LDAP directory.  Why?

![image](https://user-images.githubusercontent.com/31462646/29853519-15aaf1dc-8d73-11e7-961e-03de3d8d3d45.png)

**Comment by coudot** [comment]
We also know that we have some work to split code and design, for example by using Silex or Smarty (#109). It requires some work.

Hope the answer helped you, I'm closing this issue.
