### ISSUE TITLE
Invalid Token error

### ISSUE THREAD

**Issue by sudermanjr** [ltb-project/self-service-password#144]
Hello,

First, thanks a bunch for this great project.  It has been fantastically easy to get this working.

I am seeing an issue where I see an Invalid token error after clicking the link in the email reset message.  I am not sure where to start looking to fix this error.  I have turned on debug and attached a screenshot of the page, but the errors there look like all warning or lower.

Thanks for any advice.

PS. I am working directly from master, so if this is expected then go ahead and close this.  I am hoping to use some of the ssh key functionality, so I decided to start using the latest code instead of the 1.0 code.

<img width="900" alt="screen shot 2017-08-30 at 3 23 41 pm" src="https://user-images.githubusercontent.com/7624765/29895748-8dd70550-8d97-11e7-8271-16b6290683dd.png">

**Comment by plewin** [comment]
Hi @sudermanjr,

It is possible that you have the same issue as https://github.com/ltb-project/self-service-password/issues/128

Would you mind sharing your phpinfo details in a gist please ?

Also, if you have some time, would you mind trying the 2 potential solutions proposed here
https://github.com/ltb-project/self-service-password/issues/128#issuecomment-326113374
https://github.com/ltb-project/self-service-password/issues/128#issuecomment-326121064

**Comment by sudermanjr** [comment]
@plewin 

I am using the docker php:7-apache container for this, and adding this to the end of my dockerfile fixed the issue:

`RUN echo "output_buffering = On" >> /usr/local/etc/php/php.ini`

Thanks for the quick response!  I believe you can go ahead and close this as a duplicate of #128

**Comment by plewin** [comment]
And very thank to you, now I understand why this happens and how to fix.
