### ISSUE TITLE
Add a module for self-register/update

### ISSUE THREAD

**Issue by konvergence** [ltb-project/self-service-password#147]
Hi,

Did you plan to add modules "self-register" and self-update" ?

Regards

**Comment by coudot** [comment]
See https://github.com/ltb-project/self-service-password/issues/112

**Comment by konvergence** [comment]
Well I will test something ... and keep you inform

**Comment by plewin** [comment]
I am closing this issue because there is a previous duplicate where this issue can be discussed
cf https://github.com/ltb-project/self-service-password/issues/112
