### ISSUE TITLE
Change key feature never notifies

### ISSUE THREAD

**Issue by plewin** [ltb-project/self-service-password#148]
This if never returns false, copy / paste error
https://github.com/ltb-project/self-service-password/blob/cff9035ccf4c5efe4cd8f07506de2c868a6a1de7/pages/changesshkey.php#L165

should be sshkeychanged

Mail notification for change ssh is dead code
https://github.com/ltb-project/self-service-password/blob/cff9035ccf4c5efe4cd8f07506de2c868a6a1de7/pages/changesshkey.php#L224

@praymann

**Comment by coudot** [comment]
@plewin Indeed, do you want to fix it for 1.1? I can do it too.

**Comment by plewin** [comment]
@coudot I let you do it
