### ISSUE TITLE
bindpw in config file: can it be hashed?

### ISSUE THREAD

**Issue by DarkFranX** [ltb-project/self-service-password#15]
Hello!

In "self-service-password/conf/config.inc.php"

I would like to store the ldap_bindpw in a hashed format instead of clear text, is that possible?

**Comment by coudot** [comment]
No it's not, as we need the cleartext password to bind on directory. You need to use another authentication method (X509 client certificates, Kerberos, ...) in order to not use a password.

**Comment by DarkFranX** [comment]
Alright, thanks anyway!
