### ISSUE TITLE
samba_mode = true - password denied by LDAP server

### ISSUE THREAD

**Issue by marcinpr** [ltb-project/self-service-password#159]
This feature works fine only with E-mail reset password mode. When used with normal password change it gives message: Password denied by LDAP server, and errors in log:
- ldap_mod_replace(): Modify: Insufficient access in /usr/share/self-service-password/lib/functions.inc.php on line 364
- LDAP - Modify password error 50 (Insufficient access)
I use 389 ldap server, and "Directory Manager" as ldap_binddn. 
With samba_mode = false, password change function works fine.

**Comment by coudot** [comment]
Hello @marcinpr 

this is because you use `$who_change_password = "user";` and the user can change userPassword attributes but not sambaNTPassword.

Change the ACLs in the directory, or use `$who_change_password = "manager";`

**Comment by marcinpr** [comment]
Hello,
Thant you very much!
I did not notice this option.

**Comment by duanzhanling** [comment]
$who_change_password = "manager";

very use
