### ISSUE TITLE
Sender email name

### ISSUE THREAD

**Issue by DarkFranX** [ltb-project/self-service-password#16]
Is it possible to give a name to the sender email? 

That way, users would see "Account Password" instead of email@example.com.

Thanks!

**Comment by coudot** [comment]
You can try to set:
`$mail_from = "Account Password <admin@example.com>";`

**Comment by DarkFranX** [comment]
That made it, great! Thank you

**Comment by coudot** [comment]
Note that in 1.0 we will use PHPMailer, and the name can be set in $mail_from_name configuration parameter. See details in #26.
