### ISSUE TITLE
Question: SSP and php7

### ISSUE THREAD

**Issue by wtps0n** [ltb-project/self-service-password#163]
Hi,

I'm a commiter of FreeBSD port for ssp. I've found that php7.1+ mcrypt is "depreciated", so it should not be used. And a question is how to setup SSP dependencies for FreeBSD port to make SSP and php happy :-)) 

Maybe I should add libsodium as dependency and forget about mcrypt? Then SSP port will be more "independent" of php version (56, 70, 71, 72)?

Also I've found that there is phar needed (lib/vendor/defuse-crypto.phar)? Should I add php-phar as dependency? Or is it optional?

I've tried found answers for my questions with documentation but I was not able... 

Thanks a lot for your answers

**Comment by plewin** [comment]
Hi @wtps0n ,

mcrypt is not required for SSP 1.1

SSP 1.1 use random_compat (included in the defuse-crypto phar) to be independent of php version and still provide strong random generators.
Basically, random_compat will use native random_bytes and random_int when available (php >= 7.0), if php is too old random_compat  will try to find an available alternative : libsodium openssl mcrypt or /dev/urandom readable.
If you are interested in how the library is choosen this is explained here 
https://github.com/paragonie/random_compat/blob/v2.0.11/RATIONALE.md

SSP 1.1 absolutely need phar support in php. SSP cannot work if the phar cannot be loaded.

**Comment by wtps0n** [comment]
OK, Thanks a lot for your answer. Now it is much more clear which dependencies I should put into FreeBSD port.
