### ISSUE TITLE
there is a problem with my ldaps connection conf

### ISSUE THREAD

**Issue by LeeMoumou** [ltb-project/self-service-password#164]
i download self-service-password a few days ago, i want use it to connect AD and change the password itself. but i meet a problem.
it should use "ldaps" to cunnect  AD ,when i use "ldap"  it works ,but when i change it to "ldaps" it wrong .
who can tell me why?  how can i solve the problem?  help!!! help !!!  help !!!

**Comment by coudot** [comment]
You need to configure the certificate authority, see https://ltb-project.org/documentation/self-service-password/latest/config_ldap

**Comment by LeeMoumou** [comment]
yes , i set /etc/openldap/ldap.conf   to TLS_REQCERT allow
should i install "openldap"?
another question is how to check the version of self-service-password?

**Comment by coudot** [comment]
You don't need openldap, just openldap libs that should have been installed with php ldap.

Where did you download Self Service Password ?

**Comment by LeeMoumou** [comment]
i download it from https://ltb-project.org/download
i have installed php-ldap ,and i cann't connect AD with "ldaps",  i don't know why!
i want to cry!!!

**Comment by coudot** [comment]
The version is in the name of the file, I think you downloaded the 1.1 version which is the latest.

If disabling certificate checking is not enough, be sure that your AD server is answering on LDAPS port, for example:
`openssl s_client -connect your_ad_ip:636`

If this works, try to get the AD Certificate Authority file and install it on your SSP server.

See also https://ltb-project.org/documentation/general/active_directory_certificates

**Comment by LeeMoumou** [comment]
i have solve thr problem  ,i use this command  slapd -h "ldaps:AD ip"  and it works .
i also don't know why

thanks u very much !!!
么么哒~
