### ISSUE TITLE
Multiple SMS tokens could be requested if an attacker finds one username, leading to big expenses

### ISSUE THREAD

**Issue by Emi94** [ltb-project/self-service-password#165]
Hi,
Reset by SMS requires only the username to send a token. It is not very difficult for an attacker to find one username and use it to make multiple requests to reset by SMS, leading to possibly big expenses to the SMS provider. I recommend it to ask the user for the phone number too and check that it matches with the one from the LDAP, same as it's done for reset by email. In advance it would be good to have the possibility to set a period of time that needs to pass before the same user can request another reset by SMS.

**Comment by coudot** [comment]
@Worteks is looking at it (thanks @armfem)
