### ISSUE TITLE
Opportunistic TLS problem

### ISSUE THREAD

**Issue by Foxi352** [ltb-project/self-service-password#166]
While trying to get SSP to work with our exchange server i run into a TLS problem.
We use self signed certificates on our exchange server, so i wanted SSP to use plain SMTP without SSL or TLS. So i changed `$mail_smtp_secure = 'tls';` to `$mail_smtp_secure = '';` in `config.inc.php`.

Unfortunately, according to from PHPMAILER Github page:
> PHPMailer 5.2.10 introduced opportunistic TLS - if it sees that the server is advertising TLS encryption (after you have connected to the server), it enables encryption automatically, even if you have not set SMTPSecure. 

Our exchange always advertises TLS and so PHPMAILER tries to to use it. But then it runs into the next problem. This is still copied from PHPMAILER Github page:

> In a change from earlier versions, PHP 5.6 verifies certificates on SSL connections. If the SSL config of the server you are connecting to is not correct, you will get an error like this:
> 
> ```
>Warning: stream_socket_enable_crypto(): SSL operation failed with code 1.
>OpenSSL Error messages: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate >verify failed
>```

The solution is also described in that same Github page. I inserted the following line in SSP's `index.php` into the mailer config section:
```

$mailer->SMTPAutoTLS   = false;

```
And now it works like a charm.
So i would propose to add the `SMTPAutoTLS` option to the mail section of config.inc.php.

**Comment by coudot** [comment]
Thanks for the report!

**Comment by coudot** [comment]
Done.
