### ISSUE TITLE
No LDAP access after change

### ISSUE THREAD

**Issue by scifire91** [ltb-project/self-service-password#170]
Hey,

i´ve just installed this nice tool and getting it to work. But i run into that issue:
A user can change his password one time via SSP, if he tries a second time i got the error "No Access to LDAP". Of course i didn´t change anything to the config between the trys.
If i reset the password via AD then i can also reset it one time again via SSP. 

Setup is:
Server: Ubuntu 16.04.3
Web: Apache2
Installed: via apt-get from your rep

LDAP: Active Directory on W2K16

config:

```
$ldap_url = "ldaps://server001.ad1.company.com:636";
$ldap_starttls = false;
$ldap_binddn = "CN=ssp,CN=Users,DC=ad1,DC=company,DC=com" ;
$ldap_bindpw = "mystrongpassword" ;
$ldap_base = "ou=User company,dc=ad1,dc=company,dc=com";
$ldap_login_attribute = "sAMAccountName";
$ldap_fullname_attribute = "cn";
$ldap_filter = "(&(objectClass=user)(sAMAccountName={login})(!(userAccountControl:1.2.840.113556.1.4.803:=2)))";
$ad_mode = true;
$ad_options['force_unlock'] = true;
$ad_options['force_pwd_change'] = false;
$ad_options['change_expired_password'] = true;
$who_change_password = "manager";

```

error log output:
```
[Thu Dec 07 16:15:28.555939 2017] [:error] [pid 8683] [client 10.30.10.16:53403] PHP Warning:  ldap_bind(): Unable to bind to server: Can't contact LDAP server in /usr/share/self-service-password/pages/change.php on line 86, referer: http://password.ad1.company.com/index.php
[Thu Dec 07 16:15:28.556248 2017] [:error] [pid 8683] [client 10.30.10.16:53403] LDAP - Bind error -1  (Can't contact LDAP server), referer: http://password.ad1.company.com/index.php

```
If you need anything else please let me know.

Thanks,

**Comment by coudot** [comment]
Hello,

this message indeed indicates that when user tries to change password a second time, the old password is wrong.  Are you sure that you are using the second time as old password the new password of the first time?

You must check directly in AD that the password was well changed.

**Comment by scifire91** [comment]
Hey,

thanks for fast reply! Yes i think so but let me explain:
User has _password_ so i change this to _password1_ which is working fine. Then i want to change again so i type for old _password1_ and for new _password2_ . But this isn´t working. I checked one time if password changed has worked (try to login with the new password) but not all the time cause i trusted the confirm message.

How should i check directly in AD that it chagend well?

The error messages confused me cause connection to AD is working... possible to change this?

**Comment by plewin** [comment]
Hi,
`PHP Warning:  ldap_bind(): Unable to bind to server: Can't contact LDAP server in /usr/share/self-service-password/pages/change.php on line 86, referer: http://password.ad1.company.com/index.php`
Unless this line is from an unrelated problem, it means that your manager account (CN=ssp,CN=Users,DC=ad1,DC=company,DC=com) can not connect.

Can you add
`ldap_set_option(NULL, LDAP_OPT_DEBUG_LEVEL, 7);`
At the end of your config file please (you will need to remove when moving ssp to production to avoid getting to much log) ? It may gives more details on the "Can't contact LDAP" problem.

**Comment by scifire91** [comment]
Hey,

today i started again testing with extended log... No single problem occurred, all worked fine.
Don´t know what changed or what was the problem, maybe i was yesterday just too stupid to copy the right password....
I close this issue, if something happens again i will write here that you can reopen
