### ISSUE TITLE
Application "caches" the last user changed and won't authenticate other users

### ISSUE THREAD

**Issue by mdebord1** [ltb-project/self-service-password#171]
Hi - I have an odd one. 

self-service-password works fine for only the first password change. 

After that, it will continue to attempt to change the pass for that specific user. 

**For example, I have 3 users:** 
- Test Dev (uid=testdev)
- Test Dev2 (uid=testdev2)
- Test Dev3 (uid=testdev3)

**Steps taken to produce problem:** 
1. Access LTB Self-Service-Password, attempt to change password for Test Dev. 
Result: Password is changed succesfully! 

2. Access LTB Self-Service-Password, and attempt to change password for Test Dev2
Result: `"Login or password incorrect"`
Logs: `INVALID_CREDENTIALS: Bind failed: ERR_229 Cannot authenticate user cn=Test Dev,ou=users,dc=mysite,dc=local>, res_matched: <>`

My config example - All my users are under that ldap_base. Since it succesfully changes password for the first user, it shows me that the connection is fine to LDAP. 

**Config:**
```$ldap_url = "ldap://xxxxx";
$ldap_starttls = true;
$ldap_binddn = "xxxx";
$ldap_bindpw = "xxxx";
$ldap_base = "ou=users,dc=mysite,dc=local";
$ldap_login_attribute = "uid";
$ldap_fullname_attribute = "cn";
$ldap_filter = "(objectClass=inetOrgPerson)";
```

I have verified EVERY user has a separate `uid` in LDAP. 
If I change the`cn` full name of the user that it continues to attempt authentication against, it **WILL reflect in logs** -- This proves that self service password is indeed trying to authenticate against the exact same ldap object (even though a different uid was entered at the gui). 

*In order to "resolve" I had to delete the user!!*

**Once the user was deleted from LDAP, I was able to change the password for a different user!** -- However after changing the password for the next user, that user becomes the "cached" user and self service will continue to attempt auth against that user regardless of what `uid` is typed into the GUI. 

Here is a tail of the logs: 
```
** ld 0x563fe057b490 Connections:
* host: xxxxxxxxx  port: xxxxx  (default)
  refcnt: 2  status: Connected
  last used: Thu Dec  7 17:33:13 2017


** ld 0x563fe057b490 Outstanding Requests:
 * msgid 3,  origid 3, status InProgress
   outstanding referrals 0, parent count 0
  ld 0x563fe057b490 request count 1 (abandoned 0)
** ld 0x563fe057b490 Response Queue:
   Empty
  ld 0x563fe057b490 response count 0
ldap_chkResponseList ld 0x563fe057b490 msgid 3 all 1
ldap_chkResponseList returns ld 0x563fe057b490 NULL
ldap_int_select
read1msg: ld 0x563fe057b490 msgid 3 all 1
read1msg: ld 0x563fe057b490 msgid 3 message type bind
read1msg: ld 0x563fe057b490 0 new referrals
read1msg:  mark request completed, ld 0x563fe057b490 msgid 3
request done: ld 0x563fe057b490 msgid 3
res_errno: 49, res_error: <INVALID_CREDENTIALS: Bind failed: ERR_229 Cannot authenticate user cn=Test Dev,ou=users,dc=mysite,dc=local>, res_matched: <>
ldap_free_request (origid 3, msgid 3)
ldap_parse_result
ldap_msgfree
ldap_err2string
ldap_err2string
ldap_msgfree
ldap_free_connection 1 1
ldap_send_unbind
ldap_free_connection: actually freed
```

**Comment by plewin** [comment]
Hi, there is a problem in your config file.

You need {login} somewhere in $ldap_filter.
**Otherwise SSP will change the password of the first entry it finds at the base you provided** 

See the default $ldap_filter for an example.
`$ldap_filter = "(&(objectClass=person)($ldap_login_attribute={login}))";`

I will submit a PR detecting the missing {login} so users of future versions know that there is a configuration problem.

**Comment by mdebord1** [comment]
Thank you - this solved my problem.

**Comment by plewin** [comment]
Great ! I am closing this issue then.
