### ISSUE TITLE
Improved nl.lang.php

### ISSUE THREAD

**Issue by AlbertPluton** [ltb-project/self-service-password#174]
Hi,

I've attached an improved (IMO) version of nl.lang.php

Changes:
Line 38: 'ZelfService' is not quite right in my view. In Dutch we either borrow the english word Self Service or use the Dutch zelfbediening. ZelfService is a mix and seems weird.

I translated the following lines to Dutch as well (were still in English):
25, 28, 116-123

Line 124 looked like google translate, I made the sentence into correct Dutch

Line 83: the word 'Privé e-mail' (private email) was technically correct but in a corporate setting confusing.  I changed that to 'Uw emailadres' (your email)

Line 124 - 133: I replaced the word key (from SSH key) into sleutel (SSH sleutel)

Line 131: The entire file uses the formal 'uw' (for your) except for this line where the informal 'je´  was used. For consistency I changed this in 'uw'

[nl.inc.php.zip](https://github.com/ltb-project/self-service-password/files/1591294/nl.inc.php.zip)

**Comment by plewin** [comment]
Closing because this issue was converted into PR https://github.com/ltb-project/self-service-password/pull/176
