### ISSUE TITLE
PHPMailer ignoring TLS settings in config.inc.php

### ISSUE THREAD

**Issue by rwwest7** [ltb-project/self-service-password#180]
Email not working. 
1.1
Debug:

SERVER -> CLIENT: 220 relay.server ESMTP
CLIENT -> SERVER: EHLO client.server
SERVER -> CLIENT: 250-relay.server250-SIZE 20480000250-STARTTLS250 AUTH LOGIN
CLIENT -> SERVER: STARTTLS
SERVER -> CLIENT: 220 Ready to start TLS
SMTP Error: Could not connect to SMTP host.
CLIENT -> SERVER: QUIT

Settings in conf:

$mail_smtp_secure = false;
$mail_smtp_autotls = false;

No matter what I do, it insists on trying TLS, which won't work with my current setup and isn't needed.

**Comment by plewin** [comment]
Hi @rwwest7,

Yes sorry, phpmailer in ssp 1.1 will try to use tls when it thinks it can (you have openssl installed and your server is advertising tls. 

This was already reported and fixed for 1.2. With the new setting "$mail_smtp_autotls = false;"
In 1.1 $mail_smtp_autotls is not recognized.

If you do not want to tweak your installation (removing php openssl / make your relay stop advertising starttls) you can add this line to index.php : https://github.com/ltb-project/self-service-password/blob/be3b510f1fd82e25f65a3f1aacf85c014d690eb8/index.php#L158

cf https://github.com/ltb-project/self-service-password/issues/166

**Comment by rwwest7** [comment]
That worked, thank you!
