### ISSUE TITLE
Message incorrect when resetting using email but not supplying email (minor)

### ISSUE THREAD

**Issue by BShadeWork** [ltb-project/self-service-password#182]
When the settings are $mail_address_use_ldap = true; and the email field (correctly) does not appear, the message give about is wrong - i.e
"Enter your user name and your email address to reset your password. When you receive the email, click the link inside to complete the password reset."

Should be
"Enter your user name to reset your password. When you receive the email, click the link inside to complete the password reset."

**Comment by coudot** [comment]
It is already implemented in pages/sendtoken.php:
```php
<?php
if ( $show_help ) {
    echo "<div class=\"help alert alert-warning\"><p>";
    echo "<i class=\"fa fa-fw fa-info-circle\"></i> ";
    if ( $mail_address_use_ldap ) {
        echo $messages["sendtokenhelpnomail"];
    } else {
        echo $messages["sendtokenhelp"];
    }
    echo "</p></div>\n";
}
?>
```
