### ISSUE TITLE
PHP Fatal Error

### ISSUE THREAD

**Issue by emic17** [ltb-project/self-service-password#184]
Hi,
i installed SSP 1.2 on "openSUSE Leap 42.1" distro, and Mail recovery password does't work.
This is the log:
`[Mon Jan 22 12:28:32.115230 2018] [php5:error] [pid 5179] [client 10.0.1.152:20651] PHP Fatal error:  Class 'Defuse\\Crypto\\Crypto' not found in /srv/www/htdocs/ssp/lib/functions.inc.php on line 436, referer: https://intranet.uslumbria2.it/ssp/index.php?action=sendtoken`

defuse-crypto exists:
wp2016:/srv/www/htdocs/ssp/lib/vendor # ll
total 68
drwxrwxr-x 1 wwwrun root   136 Nov 22 17:38 PHPMailer
drwxrwxr-x 1 wwwrun root   152 Nov 22 17:38 ReCaptcha
-rw-rw-r-- 1 wwwrun root  1170 Nov 22 17:38 autoload.php
-rw-rw-r-- 1 wwwrun root 61069 Nov 22 17:38 defuse-crypto.phar
-rw-rw-r-- 1 wwwrun root   801 Nov 22 17:38 defuse-crypto.phar.sig

**Comment by plewin** [comment]
Hi,

Do you have the php extension php-phar installed?

'''
zypper in php5-phar
'''

**Comment by emic17** [comment]
I'va installed. It works!

But now have new error:
`[Tue Jan 23 11:20:31.739013 2018] [php5:error] [pid 27552] [client 10.0.1.152:41482] PHP Warning:  ldap_mod_replace(): Modify: Insufficient access in /srv/www/htdocs/ssp/lib/functions.inc.php on line 389, referer: https://intranet.uslumbria2.it/ssp/index.php?action=resetbytoken&token=3vUCAEZ6coJWqzTtssCgGgrjhHcvAfwPjYQvtnSHpUZokzVNZZqN9OdC10PFi%2BhU%2FfaXsfKQvmfaBnHEw6XLGqv1eeWbd9ryICS4wJUogp9zS6ltbO5ws1eNL7tAotJqD2QhV7yw7P7lYF51f06TgbGAyQfNIGqKssXVsOA7n0eRACebvs1UZA%3D%3D
ldap_err2string
[Tue Jan 23 11:20:31.739046 2018] [php5:error] [pid 27552] [client 10.0.1.152:41482] LDAP - Modify password error 50 (Insufficient access), referer: https://intranet.uslumbria2.it/ssp/index.php?action=resetbytoken&token=3vUCAEZ6coJWqzTtssCgGgrjhHcvAfwPjYQvtnSHpUZokzVNZZqN9OdC10PFi%2BhU%2FfaXsfKQvmfaBnHEw6XLGqv1eeWbd9ryICS4wJUogp9zS6ltbO5ws1eNL7tAotJqD2QhV7yw7P7lYF51f06TgbGAyQfNIGqKssXVsOA7n0eRACebvs1UZA%3D%3D
[Tue Jan 23 11:20:31.739105 2018] [php5:error] [pid 27552] [client 10.0.1.152:41482] PHP Notice:  Undefined variable: source in /srv/www/htdocs/ssp/pages/resetbytoken.php on line 209, referer: https://intranet.uslumbria2.it/ssp/index.php?action=resetbytoken&token=3vUCAEZ6coJWqzTtssCgGgrjhHcvAfwPjYQvtnSHpUZokzVNZZqN9OdC10PFi%2BhU%2FfaXsfKQvmfaBnHEw6XLGqv1eeWbd9ryICS4wJUogp9zS6ltbO5ws1eNL7tAotJqD2QhV7yw7P7lYF51f06TgbGAyQfNIGqKssXVsOA7n0eRACebvs1UZA%3D%3D`

Account used to bind AD ldap is DomainAdmin.

**Comment by plewin** [comment]
First thing I would try is to change

>  $who_change_password = "manager";

To see if the error message differ.

If it does not change, I guess you are are not using LDAPS and you need it.
AD is strict by default and does not allow change of passwords on insecure ldap transports.

The best resources to configure this would be probably the contributed documentation for Windows here.
Starting from section 4).
https://ltb-project.org/documentation/self-service-password/1.2/start

Read also :
https://ltb-project.org/documentation/general/active_directory_certificates

And the yellow box "LDAP certificate management in PHP"
https://ltb-project.org/documentation/self-service-password/1.2/config_ldap

**Comment by plewin** [comment]
Closing this issue because it was already answered. Please comment here or open a new issue if you still need help.
