### ISSUE TITLE
Issue on Register answer

### ISSUE THREAD

**Issue by emic17** [ltb-project/self-service-password#185]
I'm trying to record the secret answer, but this is the error:
`[Tue Jan 23 11:28:19.446523 2018] [php5:error] [pid 27500] [client 10.0.1.152:41609] PHP Warning:  ldap_mod_replace(): Modify: No such attribute in /srv/www/htdocs/ssp/pages/setquestions.php on line 151, referer: https://intranet.uslumbria2.it/ssp/index.php?action=setquestions
ldap_err2string
[Tue Jan 23 11:28:19.446641 2018] [php5:error] [pid 27500] [client 10.0.1.152:41609] LDAP - Modify answer (error 16 (No such attribute), referer: https://intranet.uslumbria2.it/ssp/index.php?action=setquestions
ldap_free_connection 1 1
ldap_send_unbind
ldap_free_connection: actually freed
ldap_msgfree`

![image](https://user-images.githubusercontent.com/35722009/35270917-c8df6410-0030-11e8-8ecc-3140b9765ec4.png)

**Comment by plewin** [comment]
Hi,

What are your configuration for $answer_attribute and $answer_objectClass ?
The error says that you user does not have the configured attribute.

Reference :
https://ltb-project.org/documentation/self-service-password/1.2/config_questions
The yellox box is particularly important if your are on ad.

**Comment by emic17** [comment]
I've modified in:
`# Answer attribute should be hidden to users!`
`$answer_objectClass = "user";`
`$answer_attribute = "comment";`

Now the error is:
`[Tue Jan 23 12:27:48.319908 2018] [php5:error] [pid 27576] [client 10.0.1.152:1351] PHP Warning:  ldap_mod_replace(): Modify: Insufficient access in /srv/www/htdocs/ssp/pages/setquestions.php on line 151, referer: https://intranet.uslumbria2.it/ssp/index.php?action=setquestions
ldap_err2string
[Tue Jan 23 12:27:48.320029 2018] [php5:error] [pid 27576] [client 10.0.1.152:1351] LDAP - Modify answer (error 50 (Insufficient access), referer: https://intranet.uslumbria2.it/ssp/index.php?action=setquestions`

**Comment by plewin** [comment]
To use this feature, you need
$who_change_password = "manager";

Or to configure an ACL on AD so an user can write and not read its comment attribute.

**Comment by emic17** [comment]
Is yet setted to: user
# Who changes the password?
# Also applicable for question/answer save
# user: the user itself
# manager: the above binddn
$who_change_password = "user";

**Comment by plewin** [comment]
Closing this issue because it was already answered, please open a new issue if you still need help on something.
