### ISSUE TITLE
two-way encryption to an Openldap and another Active Directory in same time

### ISSUE THREAD

**Issue by vlepetit** [ltb-project/self-service-password#186]
Hi,

I work on Directory syntonization project, from Openldap to Active Directory.

There is some tool to sync account data, this is not a problem. But password sync it's never simple.

My approach is to update password in a two-way encryption in the two directory in same time.

So i like to use self-service-password to do that. But at this time i think ssp can update only one directory each time.

Can we work to enhanced ssp to update account password in two different directory (Openldap and AD for example) in same time ?

Regards,
vlepetit

**Comment by coudot** [comment]
You can use the posthook to update the password in the second directory: https://ltb-project.org/documentation/self-service-password/latest/config_posthook

**Comment by vlepetit** [comment]
Great !!

Can i use this posthook to recall an spp script to update second directory ?

Which code can i use to update ad account password ?

**Comment by coudot** [comment]
No there is no script provided by SSP for the hook. You could just use ldapmodify to update the second directory.

**Comment by coudot** [comment]
For the record, another solution is to use SASL delegation: https://ltb-project.org/documentation/general/sasl_delegation

**Comment by vlepetit** [comment]
Ok

So the tool that i choose to sync openldap to ad is lsc-project and i see that you work on it to :)

Maybe it's easy to pass the uid and new password to lsc throuth the hook and let's lsc update AD password for this account ?

I have to ask this question in lsc-project side ?

vlepetit

**Comment by coudot** [comment]
This won't work with LSC. LSC does not take values as execution parameters. Just use ldapmodify or a simple Perl/Python/... scri

**Comment by vlepetit** [comment]
Ok

I had found some ldapmodify way to update Active Directory password account here :
http://richmegginson.livejournal.com/25991.html

Regards,
vlepetit
