### ISSUE TITLE
ldap_mod_replace(): Modify: Constraint violation error

### ISSUE THREAD

**Issue by sachinbanugariya** [ltb-project/self-service-password#194]
hello,

centos 7
php 7

after self-service-password installation and configuration,
we will getting below backend error:

[Mon Mar 26 16:30:25 2018] PHP Warning:  ldap_mod_replace(): Modify: Constraint violation in /var/www/html/self-service-password/lib/functions.inc.php on line 275, referer: https://oursite.com/
[Mon Mar 26 16:30:25 2018] PHP Stack trace:, referer: https://oursite.com/
[Mon Mar 26 16:30:25 2018] PHP   1. {main}() /var/www/html/self-service-password/index.php:0, referer: https://oursite.com/
[Mon Mar 26 16:30:25 2018] PHP   2. include() /var/www/html/self-service-password/index.php:136, referer: https://oursite.com/
[Mon Mar 26 16:30:25 2018] PHP   3. change_self-service-password() /var/www/html/self-service-password/pages/change.php:165, referer: https://oursite.com/
[Mon Mar 26 16:30:25 2018] PHP   4. ldap_mod_replace() /var/www/html/self-service-password/lib/functions.inc.php:275, referer: https://oursite.com/
[Mon Mar 26 16:30:25 2018] LDAP - Modify self-service-password error 19 (Constraint violation), referer: https://oursite.com/

and below is ldap connection error while try to change password:
res_errno: 19, res_error: <invalid password syntax - passwords with storage scheme are not allowed>, res_matched: <>

and below is the frontend error:
Password was refused by the LDAP directory

please let me know why we are not able to change ldap user password,
according to search i thing maybe there is user access to database is not configured but not sure and dont know how can i set that and from where.
so please give me details where and in which file i need to change.

thanks.

**Comment by plewin** [comment]
Hi,
What did you put in your config for "hash" ? Is it "clear" ?

**Comment by sachinbanugariya** [comment]
hello,
below is the hash values:
$hash_options['crypt_salt_prefix'] = "$6$";
$hash_options['crypt_salt_length'] = "6";

**Comment by plewin** [comment]
But do you have $hash = "clear"; ?

https://github.com/ltb-project/self-service-password/blob/master/conf/config.inc.php#L77

What I understand from the error message "invalid password syntax - passwords with storage scheme are not allowed" is that you have $hash set to something other than clear. Your LDAP server wants to have the password in cleartext, probably to perform checks on the cleartext version.

**Comment by sachinbanugariya** [comment]
Ok.
Yes
$hash = "SSHA";

**Comment by sachinbanugariya** [comment]
Thanks 
After change $hash="clear".
Issue resolved.
Thanks again.

**Comment by plewin** [comment]
Thank you for the feedback,
I am closing this thread because the issue was resolved.
