### ISSUE TITLE
reduce info released in error messages

### ISSUE THREAD

**Issue by r2evans** [ltb-project/self-service-password#196]
Do you think it's too much information to report `User ... not found` and `Mail ... does not match for user ...`? Similar to other authentication things, I suggest it might be better to reveal less, perhaps just `There was a problem ...`. Otherwise, I can use this mechanism to verify that usernames exist.

(Currently on version 1.0, intending to upgrade soon.)

**Comment by dgeo** [comment]
Le 1 avril 2018 02:38:44 GMT+02:00, r2evans <notifications@github.com> a écrit :
>Do you think it's too much information to report `User ... not found`
>and `Mail ... does not match for user ...`? Similar to other
>authentication things, I suggest it might be better to reveal less,
>perhaps just `There was a problem ...`. Otherwise, I can use this
>mechanism to verify that usernames exist.
>
>(Currently on version 1.0, intending to upgrade soon.)

Maybe 'user xxx not found or xxx not found', letting brained user sort out ?
-- 
geoffroy desvernay (mobile)

**Comment by r2evans** [comment]
In the interim, I'm trying a quasi-nuclear option in my `Dockerfile`:

```
for lng in ${SSP_INSTALL_DIR}lang/*.inc.php ; do
  BADPASS=$(sed -ne 's/.*badcredentials.* = "\([^"]\+\)".*$/\1/gp' ${lng} )
  sed -i -e 's/^\(.*\(nomatch\|passworderror\|sshkeyerror\|mailnomatch\|tokenattempts\).* \= \).*/\1'"\"${BADPASS}\""';/g' ${lng}
done
```

I quickly went through the list of messages and found those to be ones that I am willing to accept a little complaint from valid users in exchange for giving away no useful info to inappropriate users. If you can think of reasons to *not* do this (other than slightly-confused users) or other variables that should be added to my hasty list, I'm all ears.

**Comment by coudot** [comment]
You are right, we should not display such messages by default.

I think we can create an option to allow SSP do display these messages. By default, for security reason, a standard error message will be displayed.

**Comment by coudot** [comment]
The only sensible message displayed to users may be the 'mailnomatch'. Other errors are only displayed in server logs, and users have only 'badcredentials' message. Agree?

**Comment by r2evans** [comment]
I think `The email address does not match the submitted user name` is specifically a message that should not be presented to the user, as it verifies that the username is present/valid without assumption of a valid identity. Unless the user provides *strong assurance* (i.e., a verifiable "secret") that they are who they claim to be, anything else is a potential phishing expedition.

My logic is based on a premise of *paranoia*, assuming that "evil agents" are attempting to find some vector into the network. I choose to not willingly give them a mechanism to verify usernames or email addresses. I realize there is always a compromise between usability and convenience to the users and security, but I feel the right answer is to default to always-obscure while still allowing an admin (if they explicitly choose) to relax.

The current mechanism of having different messages for each type of failure should be retained, in my mind, for the admins who are not as paranoid as I am. With this, perhaps adding a config such as

```
# Keep failure messages obscure, such that a problem only returns "login or password incorrect",
# affects: nomatch, passworderror, sshkeyerror, mailnomatch, tokenattempts
# Note: setting to 'false' may allow a non-authorized user to validate internal account information
# Default: true
$obscure_failure_messages = true;
```

where internally a failure checks this and changes the message name to `badcredentials` if true.

An alternative is to provide a list of messages to override:

```
# Obscure failure messages for the following messages (look in lang/). Any message of the following
# types will be converted internally to that of "badcredentials" before passing to the un-verified user.
# Note: removing any of these may allow a non-verified user to validate internal account information.
$obscure_failure_messages = array("nomatch", "passworderror", "sshkeyerror", "mailnomatch", "tokenattempts");
```

**Comment by coudot** [comment]
I don't see the need to hide these message:
* nomatch: just mean that new password and confirmation password are not the same
* passworderror and sshkey error: can only be displayed if the user was first authenticated (by password/questions/token)
* tokenattempts: just display that the token is invalid

I agree for mailnomatch

**Comment by r2evans** [comment]
Thank you! I erred on the conservative side, I'm happy to hear the others are only provided post-authentication. (BTW: in the patch, is "discole" a typo for "disclose"?.)

**Comment by coudot** [comment]
Thanks, typo fixed
