### ISSUE TITLE
Prevent using old password during password reset 

### ISSUE THREAD

**Issue by richman1000000** [ltb-project/self-service-password#200]
Hi!
we found out that users can reset password via email to there old password regardless of domain policy.

**Comment by plewin** [comment]
Hi,
Are you using a service account or the domain admin account in SSP config ?
When configured with a domain admin account instead of a service account
the ldap server will ignore password policies.

**Comment by coudot** [comment]
We cannot prevent user from using old password in password reset as we don't know the old password at this step.

This is possible when user change its password in the standard change page:
```php
# Don't reuse the same password as currently
$pwd_no_reuse = true;
```

For password reset, as answered by @plewin, you must configure your LDAP directory to check password history and refuse the password.

**Comment by plewin** [comment]
Closing this issue because the question was answered. Please open a new thread or reopen this one if you encounter further issues.

**Comment by richman1000000** [comment]
Can we make Self-service to store password hashes in some database? So we can apply policy of of 5 last passwords?

**Comment by coudot** [comment]
I think it is a bad idea, we don't want password in an external base. The best will be to rely on LDAP password policy.

See also #57

**Comment by richman1000000** [comment]
"we don't want password in an external base. " "user+password  **hashes**"
I did not mean plain passwords, I meant  hashes.

PS. unfortunately users found out  that they can reset password via email to the same they had before. And now they using same password, just resetting it via email.

**Comment by coudot** [comment]
@richman1000000 as said in previous comments, the best is to configure your LDAP directory to refuse the same password when changing it.

**Comment by richman1000000** [comment]
That is impossible in active directory when password is reset, it is not changed by user itself, but by delegated account so Active Directory allows to reset password regardless of policies.

**Comment by coudot** [comment]
Yes, Active Directory is indeed bad designed.

What we could do is implement a prehook script, which would be called before the password change. With prehook and posthook, you will be able to create your own password database.

**Comment by richman1000000** [comment]
this is great idea, I think this will work

**Comment by coudot** [comment]
See #220
