### ISSUE TITLE
samba active directory failed to bind on the new installation version 1.2

### ISSUE THREAD

**Issue by pafcioooo** [ltb-project/self-service-password#203]
I have installed 1.2 version from tarball, set up ldap connection (ldaps with 636 port, bind user and password) and ldap_mode to work with Active Directory (this is samba4 as AD controller). Additionally I have added `TLS_REQCERT     never` to /etc/ldap/ldap.conf.

When I try to use some actions in SPP I get "can not connect to LDAP datavase).

In apache error log I get (sample log):
```
[Mon May 21 08:18:29.242906 2018] [fcgid:warn] [pid 47943] [client 10.20.40.2:53395] mod_fcgid: stderr: LDAP - Bind error -1 (Can't contact LDAP server), referer: https://hasla.indevops.com/index.php?action=sendsms
[Mon May 21 08:26:19.247802 2018] [fcgid:warn] [pid 47946] [client 10.20.40.2:53588] mod_fcgid: stderr: PHP Warning:  ldap_bind(): Unable to bind to server: Can't contact LDAP server in /home/hasla/public_html/hasla/pages/sendsms.php on line 133, referer: https://hasla.indevops.com/index.php?action=sendsms
[Mon May 21 08:26:19.247862 2018] [fcgid:warn] [pid 47946] [client 10.20.40.2:53588] mod_fcgid: stderr: LDAP - Bind error -1 (Can't contact LDAP server), referer: https://hasla.indevops.com/index.php?action=sendsms
```
I have some other applications php and ruby that can connect this AD successfully with the same credentials.

I have turned debug on, but I do not know where the debug info goes. I have read other ldap concerning issues here on github as well as SSP documentation.

This is: 
- 1.2 veriosn installed from tarball, 
- ubuntu 16.04, 
- apache2 from official repo 
- php7.2 from ppa:ondrej/php repo
- virtualmin controlled - php log goes to access_log and error_log in home directory of virtual server (this is what I add to initial note)

**Comment by pafcioooo** [comment]
I have changed TLS_REQCERT allow in /etc/ldap/ldap.conf with no success.

**Comment by plewin** [comment]
When you get
Bind error -1 (Can't contact LDAP server),
It is yes probably a network error or a certificate issue.

You activated debug mode good, you need to find where is php error log.
It's the only place where the bind error is explained.
On which distro are you? Have you installed php and apache from their
official repo?

**Comment by pafcioooo** [comment]
I have added to initial note: 
- installed from tarball, 
- ubuntu 16.04, 
- apache2 from official repo 
- php7.2 from ppa:ondrej/php repo
- virtualmin controlled - php log goes to access_log and error_log in home directory of virtual server (this is what I add to initial note)

**Comment by plewin** [comment]
If i understand well webmin, you posted what you found in /home/hasla/logs

I just read an article saying that ldap debug in php do not respect apache
virtual hosts error log configurations.

You need to find the global error log maybe
/var/log/apache2/error.log

Or somewhere webmin configured as global error log if it is not default.

Also try this command if you can't find, perhaps it can give you a path.

php --info | grep error

**Comment by pafcioooo** [comment]
Thanks @plewin:-) This is it. Debug is in /var/log/apache2/error.log.

After looking into it I have noticed typo in ldap port number: it was 686 instead of 636.

Now I have connected so I can carry on with configuration.

Thanks a lot:-) Cheers:-)
