### ISSUE TITLE
Index includes .swp files and crashes sites with error 500

### ISSUE THREAD

**Issue by bananitadolca** [ltb-project/self-service-password#204]
Hi,
While I have a file opened in vim the site crashes

[Wed May 23 20:09:06.782465 2018] [php7:error] [pid 1795] [client 172.30.227.231:35498] PHP Fatal error:  require_once(): Failed opening required 'lang/.es.swp.inc.php' (include_path='.:/usr/share/pear:/usr/share/php') in /usr/share/self-service-password/index.php on line 65, referer: https://site.company.com/index.php?action=resetbyquestions

**Comment by bananitadolca** [comment]
I've been trying 
$lang = detectLanguage($lang, $languages);
require_once("lang/$lang.inc.php");
if (file_exists("conf/$lang.inc.php")) {
#if (file_exists("conf/$lang.inc.php") && (substr( $lang, 0, 1 )!== ".")) {
    require_once("conf/$lang.inc.php");
}
 on line 65 of the index file but can't make it work.

I'm working with php7, btw :/

**Comment by coudot** [comment]
The code that parses the directory is above:
```php
$languages = array();
if ($handle = opendir('lang')) {
    while (false !== ($entry = readdir($handle))) {
        if ($entry != "." && $entry != ".." ) {
            $entry_lang = str_replace(".inc.php", "", $entry);
            # Only add language to possibilities if it is the default language or part of the allowed languages
            # empty $allowed_lang <=> all languages are allowed
            if ($entry_lang == $lang || empty($allowed_lang) || in_array($entry_lang, $allowed_lang) ) {
                array_push($languages, $entry_lang);
            }
        }
    }
    closedir($handle);
}
```

Maybe we could match only real language files here. Anyway, it is a bad idea to edit fhese files while site is running ;)

**Comment by plewin** [comment]
This issue reminds me on how files with a . prefix became hidden files.
https://plus.google.com/u/0/+RobPikeTheHuman/posts/R58WgWwN9jp

@bananitadolca do you want to contribute to SSP by making a PR for this ? Otherwise I will label it "good first issue"

**Comment by plewin** [comment]
I am adding a "good first issue" label to this issue.

Anyone interested in making a first easy contribution to self service password is welcome. Feel free to ask for help here on in a pull request.
