### ISSUE TITLE
posthook is not executed

### ISSUE THREAD

**Issue by muzzol** [ltb-project/self-service-password#205]
I'm using 1.2 version and I can't get any script to be executed with posthook attribute.

I've tried with default value and creating a very simple script:

    $posthook = "/usr/share/self-service-password/posthook.sh";

also tried different locations with no success.
maybe something related to php 7 restricions outside /var/www but I can't find the way to configure it. if is related to PHP it would be nice to leave a comment on config.inc.php and on docs.

**Comment by plewin** [comment]
Here is a list of things that can cause issues with the posthook:

* Typo in path/file missing (probably not your case)
* File is not configured to be executable by php
* SELinux is enabled
* php config was hardened (functions disabled)

Please check the log with debug mode enabled just in case some info is logged.

**Comment by muzzol** [comment]
I've found the problem, is another systemd quirk.

script is being executed but output is redirected to an special temporal directory.
you can read about it here: http://muras.eu/2017/12/06/apache-ubuntu-systemd-privatetmp/

to change it find your apache2.service and change PrivateTmp to false
reload systemd units with

     systemctl daemon-reload

and restart apache

**Comment by plewin** [comment]
Thank you for reporting this issue.

I have updated the documentation wiki with a new warning.
https://ltb-project.org/documentation/self-service-password/1.2/config_posthook

Hopefully it will prevent other people from getting this issue again.
