### ISSUE TITLE
encrypt tokens on reset password by mail not work correctly

### ISSUE THREAD

**Issue by elvquant** [ltb-project/self-service-password#207]
Sending encrypted token it urlencode() before sending, thats good. But before decrypt it is not urldecoded()!

```
*** pages/resetbytoken.php_bak	2018-06-10 20:24:10.857043847 +0200
--- pages/resetbytoken.php	2018-06-10 20:20:31.017857990 +0200
***************
*** 44,49 ****
--- 44,51 ----
  #==============================================================================
  if ( $result === "" ) {
  
+ 	$token = urldecode($token);
+ 
      # Open session with the token
      if ( $crypt_tokens ) {
          $tokenid = decrypt($token, $keyphrase);

```

**Comment by elvquant** [comment]
Same problem exists on SMS part, but i have not check it in detail nor correct it!

**Comment by plewin** [comment]
Hi @elvquant, sorry I do not understand your point.

Did you encountered an issue with the tokens?

See also the note on php.net about urldecode

> Warning
> The superglobals $_GET and $_REQUEST are already decoded. Using
urldecode() on an element in $_GET or $_REQUEST could have unexpected and
dangerous results.

**Comment by plewin** [comment]
I was not able to reproduce an issue, would you mind copy pasting here a mail with a token link from your SSP instance ? Also what is your mail software ?

At the line you want to a urldecode, I do not get a urlencoded token.
https://github.com/ltb-project/self-service-password/blob/v1.2/pages/resetbytoken.php#L46

Latest stable php for your distribution is recommended, 7.2 or 7.1 or 7.0

**Comment by elvquant** [comment]
Hallo elv,

Klicken Sie hier um Ihr Passwort zurückzusetzen:
http://elvhost:81/ssp/index.php?action=resetbytoken&token=3vUCANI45y4CRJKAQFDekdSO84KxbqeFwEuF5AC8vVx7UHnHtpCE23JYiNiA6da5tQw%2F9FIDSCtjBzYIhR5EXbVxQAZG%2FnHonWjE8c2LIC3asYL5Nh7dbT%2BRRTmcDa1AQfokBApTLbTCsuXdGnI%3D

Falls Sie keine Rücksetzung beantragt haben, ignorieren Sie dies bitte.


$keyphrase = "test0x07";



Jun 14 15:24:49 elvhost apache2: Send reset URL http://localhost:81/ssp/index.php?action=resetbytoken&token=3vUCANI45y4CRJKAQFDekdSO84KxbqeFwEuF5AC8vVx7UHnHtpCE23JYiNiA6da5tQw%2F9FIDSCtjBzYIhR5EXbVxQAZG%2FnHonWjE8c2LIC3asYL5Nh7dbT%2BRRTmcDa1AQfokBApTLbTCsuXdGnI%3D
Jun 14 15:27:05 elvhost apache2: crypto: decryption error Integrity check failed.
Jun 14 15:27:05 elvhost apache2: PHP Warning:  session_start(): Cannot start session with empty session ID in /usr/share/self-service-password/pages/resetbytoken.php on line 68
Jun 14 15:27:05 elvhost apache2: PHP Notice:  Undefined variable: _SESSION in /usr/share/self-service-password/pages/resetbytoken.php on line 69
Jun 14 15:27:05 elvhost apache2: Unable to open session

-----

Adding the urldecode(), all works fine!

**Comment by elvquant** [comment]
if ( $result === "" ) {

    error_log("resetbytoken.php: token $token");
//  $token = urldecode($token);

    # Open session with the token
    if ( $crypt_tokens ) {

=====

Jun 14 15:38:07 elvhost apache2: resetbytoken.php: token 3vUCANI45y4CRJKAQFDekdSO84KxbqeFwEuF5AC8vVx7UHnHtpCE23JYiNiA6da5tQw%2F9FIDSCtjBzYIhR5EXbVxQAZG%2FnHonWjE8c2LIC3asYL5Nh7dbT%2BRRTmcDa1AQfokBApTLbTCsuXdGnI%3D
Jun 14 15:38:08 elvhost apache2: crypto: decryption error Integrity check failed.
Jun 14 15:38:08 elvhost apache2: PHP Warning:  session_start(): Cannot start session with empty session ID in /usr/share/self-service-password/pages/resetbytoken.php on line 69
Jun 14 15:38:08 elvhost apache2: PHP Notice:  Undefined variable: _SESSION in /usr/share/self-service-password/pages/resetbytoken.php on line 70
Jun 14 15:38:08 elvhost apache2: Unable to open session

**Comment by elvquant** [comment]
if ( $result === "" ) {

    error_log("resetbytoken.php: token $token");
    $token = urldecode($token);
    error_log("resetbytoken.php: token $token");

    # Open session with the token
    if ( $crypt_tokens ) {

=====

Jun 14 15:41:44 elvhost apache2: resetbytoken.php: token 3vUCANI45y4CRJKAQFDekdSO84KxbqeFwEuF5AC8vVx7UHnHtpCE23JYiNiA6da5tQw%2F9FIDSCtjBzYIhR5EXbVxQAZG%2FnHonWjE8c2LIC3asYL5Nh7dbT%2BRRTmcDa1AQfokBApTLbTCsuXdGnI%3D
Jun 14 15:41:44 elvhost apache2: resetbytoken.php: token 3vUCANI45y4CRJKAQFDekdSO84KxbqeFwEuF5AC8vVx7UHnHtpCE23JYiNiA6da5tQw/9FIDSCtjBzYIhR5EXbVxQAZG/nHonWjE8c2LIC3asYL5Nh7dbT+RRTmcDa1AQfokBApTLbTCsuXdGnI=
Jun 14 15:41:45 elvhost apache2: crypto: decryption error Integrity check failed.
Jun 14 15:41:45 elvhost apache2: PHP Warning:  session_start(): Cannot start session with empty session ID in /usr/share/self-service-password/pages/resetbytoken.php on line 70
Jun 14 15:41:45 elvhost apache2: PHP Notice:  Undefined variable: _SESSION in /usr/share/self-service-password/pages/resetbytoken.php on line 71
Jun 14 15:41:45 elvhost apache2: Unable to open session

**Comment by elvquant** [comment]
error_log("resetbytoken.php: token $token");
$tempx = urldecode($token);
error_log("resetbytoken.php: token $tempx");

# Open session with the token
if ( $crypt_tokens ) {

=====

Jun 14 15:41:44 elvhost apache2: resetbytoken.php: token 3vUCANI45y4CRJKAQFDekdSO84KxbqeFwEuF5AC8vVx7UHnHtpCE23JYiNiA6da5tQw%2F9FIDSCtjBzYIhR5EXbVxQAZG%2FnHonWjE8c2LIC3asYL5Nh7dbT%2BRRTmcDa1AQfokBApTLbTCsuXdGnI%3D
Jun 14 15:41:44 elvhost apache2: resetbytoken.php: token 3vUCANI45y4CRJKAQFDekdSO84KxbqeFwEuF5AC8vVx7UHnHtpCE23JYiNiA6da5tQw/9FIDSCtjBzYIhR5EXbVxQAZG/nHonWjE8c2LIC3asYL5Nh7dbT+RRTmcDa1AQfokBApTLbTCsuXdGnI=
Jun 14 15:41:45 elvhost apache2: crypto: decryption error Integrity check failed.
Jun 14 15:41:45 elvhost apache2: PHP Warning: session_start(): Cannot start session with empty session ID in /usr/share/self-service-password/pages/resetbytoken.php on line 70
Jun 14 15:41:45 elvhost apache2: PHP Notice: Undefined variable: _SESSION in /usr/share/self-service-password/pages/resetbytoken.php on line 71
Jun 14 15:41:45 elvhost apache2: Unable to open session

**Comment by coudot** [comment]
Your problem is strange as the decoding should indeed be done by PHP

**Comment by elvquant** [comment]
Seems to be a special personal problem on my Raspberry Pi.

**Comment by plewin** [comment]
I was thinking it could be because of an lightweight browser or mail agent that do not support all the http protocol.

**Comment by elvquant** [comment]
As you can see in protocol i using apache2. Mails sended directly via smtp to my mail provider. 

No idea, the data are not urldecoded from _GET
