### ISSUE TITLE
Is it possible to change passwords for users in multiple AD domains

### ISSUE THREAD

**Issue by TCS-Taylor** [ltb-project/self-service-password#213]
We are currently running three different SAMBA AD domains, for reasons I can't really get into.  We are in the process of consolidating them, but that process is moving much more slowly than I would like.

We currently have our self-service-password set up to change the password of the user on the newest domain, which is the domain everything will consolidate into.

Each end user exists in all three domains, with the exact same username.

Would it be possible to tie SSP into the other two domains, so when the user changes their password it gets changed in all three domains?

Thanks in advance for any help you can provide!

Taylor

**Comment by coudot** [comment]
You can use post hook to do that: https://ltb-project.org/documentation/self-service-password/latest/config_posthook

You could also use [LSC](https://lsc-project.org) to synchronize passwords between your domains.

**Comment by plewin** [comment]
Thank you, closing this issue because it has been answered.
