### ISSUE TITLE
Password change for users with cheked account option „User must change password at next logon“

### ISSUE THREAD

**Issue by Edvinas2** [ltb-project/self-service-password#216]
Hello,
I want to ask abaut password reset for new Windows server 2016 users. I have configured Self Service Password tool. This tool is working. But if i want to change password for user with cheked account option „User must change password at next logon“ Self Service shows the error „Login or password incorrect“.
With unchecked „User must change password at next logon“ account option service is working.

„User must change password at next logon“  account option i need for all new users. For change they password at first login with 2 diferend ways. First one is standard at first login in operating system. Second is with self service.

**Comment by coudot** [comment]
Hello,

If you set AD mode in configuration, this should work by default. We have a code that catches the "User must change password at next logon" and allows password change : https://github.com/ltb-project/self-service-password/blob/4645d1c19df4c0d45939e953af23aeef3c5e54c8/pages/change.php#L142

**Comment by Edvinas2** [comment]
The situation shown above is with $ad_mode = false;
With $ad_mode = true; system shows error "Password was refused by the LDAP directory"

**Comment by coudot** [comment]
As the BIND does not succeed in this case, the password is changed with the `$ldap_binddn` which should have the right to do it.

**Comment by Edvinas2** [comment]
$ldap_binddn is the member of administrators; domain admins, enterprise admins, schema admins. Localy with this user i can change passwords and finaly this bind user working in $ad_mode = false;
Maybethis option is wrong? $hash = "clear";

**Comment by coudot** [comment]
You can have more logs by setting `$debug = true` in configuration.

**Comment by Edvinas2** [comment]
Error log:
Notice: Undefined variable: hash in C:\xampp\htdocs\self-service\pages\change.php on line 172
Warning: ldap_mod_replace(): Modify: Server is unwilling to perform in C:\xampp\htdocs\self-service\lib\functions.inc.php on line 389

**Comment by Edvinas2** [comment]
Hash fixed to $hash = "auto";
Still have this error:
Warning: ldap_mod_replace(): Modify: Server is unwilling to perform in C:\xampp\htdocs\self-service\lib\functions.inc.php on line 389

**Comment by coudot** [comment]
It may just be AD which refuses the password (not complex enough)

**Comment by Edvinas2** [comment]
When the user do not have rights to change password message is: Warning: ldap_mod_replace(): Modify: **Insufficient access** in C:\xampp\htdocs\self-service\lib\functions.inc.php on line 389
But here is Warning: ldap_mod_replace(): Modify: Server is **unwilling** to perform in C:\xampp\htdocs\self-service\lib\functions.inc.php on line 389.

**Comment by coudot** [comment]
Unwilling to perform is returned by AD if connection is on LDAP and not LDAPS or password quality is too low.

**Comment by Edvinas2** [comment]
Thank you. I have found the solution. In fact it was related to LDAPS.

**Comment by smegnl** [comment]
can you expand on what your solution was? Am having same issue.
