### ISSUE TITLE
take into account post-hook exit status

### ISSUE THREAD

**Issue by paulignari** [ltb-project/self-service-password#217]
As stated in #186 and other issues, we can use a post-hook to change the password in additional directories, but it seems to me that the exit code of the post-hook is not taken in place.

Without this check we cannot inform the user that one password is changed and the other(s) no.

The error string maybe the output of the command,  so one can choose how to inform his users of the fault.

Do you think this is a viable enhancement?

**Comment by coudot** [comment]
We can indeed display an info/warning message to the end user.

**Comment by coudot** [comment]
Done, and documentation updated: https://ltb-project.org/documentation/self-service-password/1.3/config_posthook
