### ISSUE TITLE
Where are debug mode logs files ?

### ISSUE THREAD

**Issue by waazdakka** [ltb-project/self-service-password#218]
Hello,
I'm still having a connection error to the directory (while I've succeed on another server / directory), while all settings seems to be good (I took the same settings than on my Nextcloud and other webapps using LDAP settings)
I activate debug mode but.. Can't find where the logs are recorded !

Any help ?

Thanks!

**Comment by plewin** [comment]
Hi.
Usually errors are shown on the page when debug is enabled..

If not detailled logs can be found in
/var/log/apache2/ssp_error.log for general errors
and
/var/log/apache2/error.log. (for LDAP protocol debug)
In debian.

**Comment by plewin** [comment]
Hi @waazdakka,
Do you need further assistance on your issue ?

**Comment by waazdakka** [comment]
Hi @plewin,

I finally get access to the logs, and here is what we get 👍 

/var/log/alternc/sites/2017-account/error.log :

[Thu Aug 02 14:05:40.746766 2018] [:error] [pid 32209] [client
91.194.61.205:40206] PHP Fatal error:  Uncaught exception
'Defuse\\Crypto\\Exception\\EnvironmentIsBrokenException' with message 'Your
system does not have a secure random number generator.' in
phar:///var/www/alternc/a/account/www/compte.croixrougeparis.fr/lib/vendor/de
fuse-crypto.phar/src/Core.php:110\nStack trace:\n#0
phar:///var/www/alternc/a/account/www/compte.croixrougeparis.fr/lib/vendor/de
fuse-crypto.phar/src/Key.php(23): Defuse\\Crypto\\Core::secureRandom(32)\n#1
phar:///var/www/alternc/a/account/www/compte.croixrougeparis.fr/lib/vendor/de
fuse-crypto.phar/src/RuntimeTests.php(85):
Defuse\\Crypto\\Key::createNewRandomKey()\n#2
phar:///var/www/alternc/a/account/www/compte.croixrougeparis.fr/lib/vendor/de
fuse-crypto.phar/src/RuntimeTests.php(60):
Defuse\\Crypto\\RuntimeTests::testEncryptDecrypt()\n#3
phar:///var/www/alternc/a/account/www/compte.croixrougeparis.fr/lib/vendor/de
fuse-crypto.phar/src/Crypto.php(178):
Defuse\\Crypto\\RuntimeTests::runtimeTest()\n#4
phar:///var/www/alternc/a/account/www/compte.croixrougeparis.fr/lib/vendor/de
fuse-crypto.phar/src/C in
phar:///var/www/alternc/a/account/www/compte.croixrougeparis.fr/lib/vendor/de
fuse-crypto.phar/src/Core.php on line 110, referer:
http://compte.croixrougeparis.fr/?action=sendtoken

It seems my server miss something... I can't get the right settings :(

Thanks for your help !

**Comment by plewin** [comment]
Hi,
You need strong cryptography functions available (for random_compat, php 7
or libsodium or /dev/urandom readable or php-mcrypt extension installed)
Upgrade your php (recommanded) or install libsodium or php-mcrypt

**Comment by waazdakka** [comment]
Hello,
mycrypt extension is activated, but I still have this issue :(

**Comment by plewin** [comment]
Hi @waazdakka.
have you solved your issue ?
Do you happen to have php version under 5.3.7 or exactly 5.6.10, 5.6.11 or 5.6.12 ?
SSP is using a library that do not trust mcrypt to be cryptographically secure in these php versions.
Also please check with a file containing <?php phpinfo(); ?> that mcrypt is activated and that apache is restarted

**Comment by waazdakka** [comment]
Hi @plewin, problem just solved (partially): PHP hadn't the rights to access urandom :)

Last issue for now : SFP works for users at root, but not users in sub groups :( 
Still working on it 

Thanks !

**Comment by plewin** [comment]
Thank you, closing this issue because it has been solved.
