### ISSUE TITLE
Login or password incorrect

### ISSUE THREAD

**Issue by comando2018** [ltb-project/self-service-password#230]
Hello list, when I try to change a user's password this is an error that gives me
"Login or password incorrect", if I analyze the apache.error log, I get the following

[: error] [pid 688] [client [: error] [pid 688] [client 172.18.68.6:46418] LDAP - User pepe not found, referer: https://172.18.68.7/self-service-password/index .php

**Comment by plewin** [comment]
Hi @comando2018, thank you for using SSP.
This is probably a configuration issue,
Please double check your config values for 
$ldap_base $ldap_login_attribute $ldap_fullname_attribute and $ldap_filter

**Comment by comando2018** [comment]
# LDAP
$ldap_url = "ldap://x.x.x.x:389";
$ldap_starttls = false;
$ldap_binddn = "cn=user,dc=my-domain,dc=some,dc=cu";
$ldap_bindpw = "user18**";
$ldap_base = "dc=my-domain,dc=some,dc=cu";
#$ldap_login_attribute = "sAMAccountName";
$ldap_login_attribute = "uid";
$ldap_fullname_attribute = "cn";
#$ldap_filter = "(&(objectClass=person)(uid={login}))";
$ldap_filter = "(&(objectClass=user)(sAMAccountName={login})(!(userAccountControl:1.2.840.113556.1.4.803:=2)))";

**Comment by plewin** [comment]
Hum. Your $ldap_filter looks good to me if you are using active directory.

In your error log, user pepe was not found, are you sure there is an user with  sAMAccountName=pepe in your directory ?

Also, if you are using active directory, your current ldap_url will not work. Active Directory does not allow password change on not secure protocol, you will have to use ldaps as mentioned in SSP documentation https://ltb-project.org/documentation/self-service-password/1.3/config_ldap#active_directory

**Comment by smegnl** [comment]
have you been able to resolve this? I get the exact same problem. I know you cant change the password NON-SSL but I dropped back to that for trouble shooting.  I can see it connecting but not find anyone. I checked in AD and verified that  the samaccountname is what I am typing in. I have tried it for multiple users.

**Comment by smegnl** [comment]
figured it out. Changed..
$ldap_login_attribute = "uid";
TO

$ldap_login_attribute = "sAMAccountName";

**Comment by plewin** [comment]
Thank you, I am closing this issue because it has been answered and also a bit diverted.
