### ISSUE TITLE
Cant connect ldaps

### ISSUE THREAD

**Issue by jmbertolotti** [ltb-project/self-service-password#234]
everytime i tried to change password i got the following at the apache error.log:
ldap_create
ldap_url_parse_ext(ldaps://10.42.4.252:636)
ldap_sasl_bind_s
ldap_sasl_bind
ldap_send_initial_request
ldap_new_connection 1 1 0
ldap_int_open_connection
ldap_connect_to_host: TCP 10.42.4.252:636
ldap_new_socket: 15
ldap_prepare_socket: 15
ldap_connect_to_host: Trying 10.42.4.252:636
ldap_pvt_connect: fd: 15 tm: -1 async: 0
TLS: can't connect: Error in the push function..
ldap_err2string
ldap_err2string
My config files looks as follows:

```
$ldap_url = "ldaps://10.42.4.252:636";
$ldap_starttls = false;
$ldap_binddn = "something@something.gov.ar";
$ldap_bindpw = "blach";
$ldap_base = "dc=rentascba,dc=gov,dc=ar";
$ldap_login_attribute = "sAMAccountName";
$ldap_fullname_attribute = "cn";
#$ldap_filter = "(&(objectClass=person)($ldap_login_attribute={login}))";
$ldap_filter = "(&(objectClass=user)(sAMAccountName={login})(!(userAccountControl:1.2.840.113556.1.4.803:=2)))";
```

**Comment by plewin** [comment]
Hi @jmbertolotti ,

I guess it is probably a tls certificate issue.

Have you read the warning about ldap.conf in this documentation page ?

You can also verify if it is a certificate issue with this command on the server where ssp is installed
```
openssl s_client -connect 10.42.4.252:636
this will check

**Comment by jmbertolotti** [comment]
this is what i get when running openssl


CONNECTED(00000003)
write:errno=104
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 176 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1533767917
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---

**Comment by jmbertolotti** [comment]
I got this:

CONNECTED(00000003)
write:errno=104
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 176 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1533767917
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---

**Comment by jmbertolotti** [comment]
i got this:
```
CONNECTED(00000003)
write:errno=104
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 176 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1533767917
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---
```

**Comment by jmbertolotti** [comment]
found this :[https://support.google.com/gsa/answer/2705182?hl=en](url) 
I need to work on my AD first, thanks!

**Comment by coudot** [comment]
Indeed, you need to define a certificate on AD to have LDAPS. See also https://ltb-project.org/documentation/general/active_directory_certificates
