### ISSUE TITLE
Could you please share guide "how to connect ldap to ad" 

### ISSUE THREAD

**Issue by paperplane90** [ltb-project/self-service-password#237]
Could you please share guide "how to connect ldap to ad" 

I have an error:

ldap_url_parse_ext(ldap://localhost/)
ldap_init: trying /etc/ldap/ldap.conf
ldap_init: using /etc/ldap/ldap.conf
ldap_init: HOME env is NULL
ldap_init: trying ldaprc
ldap_init: LDAPCONF env is NULL
ldap_init: LDAPRC env is NULL
ldap_create
ldap_url_parse_ext(ldaps://server:636)
ldap_sasl_bind_s
ldap_sasl_bind
ldap_send_initial_request
ldap_new_connection 1 1 0
ldap_int_open_connection
ldap_connect_to_host: TCP servser:636
ldap_new_socket: 14
ldap_prepare_socket: 14
ldap_connect_to_host: Trying server:636
ldap_pvt_connect: fd: 14 tm: -1 async: 0
attempting to connect:
connect success
TLS: peer cert untrusted or revoked (0x42)
TLS: can't connect: (unknown error code).
ldap_err2string
ldap_err2string

Probably there is error with the cert file.
error 18 at 0 depth lookup: self signed certificate

**Comment by coudot** [comment]
Indeed, there is an error with the certificate: 
```TLS: peer cert untrusted or revoked (0x42)```

See https://ltb-project.org/documentation/self-service-password/latest/config_ldap for connection settings

**Comment by paperplane90** [comment]
Yes, I have checked it. But I mean certificate request procces formAD

**Comment by coudot** [comment]
And did you solve your issue? See https://ltb-project.org/documentation/general/active_directory_certificates for AD certificates documentation

**Comment by paperplane90** [comment]
Sure, but I need certificate for connection. An I have a problem how to create request for certificate, because AD use there own request and i can't do it by using openssl(

**Comment by coudot** [comment]
See my link in the above answer on how to generate certificate on AD. This issue is not related to Self Service Password, I'm closing this issue.

**Comment by paperplane90** [comment]
I know how to generate certificate on AD. But for TLS connection I need certificate for server where SSP located. So I just ask  some help with it.

**Comment by coudot** [comment]
You need AD certificate authority installed on SSP server to be able to trust AD certificate for LDAPS connection.

You can also have an SSL certificate for HTTPS but this has nothing related with the LDAP connection. You will find a lot of documentation on the web to achieve this.
