### ISSUE TITLE
Provide a way to know the installed version

### ISSUE THREAD

**Issue by coudot** [ltb-project/self-service-password#238]
We can only know which version is installed if we check the package version. We should also store the version number inside the code, for example in index.php

**Comment by nqb** [comment]
+1

**Comment by nqb** [comment]
I guess we can duplicate this issue on https://github.com/ltb-project/white-pages

**Comment by nqb** [comment]
See https://github.com/ltb-project/white-pages/issues/50

**Comment by coudot** [comment]
Done when migration to Smarty (#109)
