### ISSUE TITLE
encrypt_answers.php only works with lower case attributes

### ISSUE THREAD

**Issue by pcurie** [ltb-project/self-service-password#240]
We use the question/awnser password reset method. We upgraded to 1.3 to encrypt them in LDAP.
Our config.inc.php is like this : 
```
$anwser_objectClass = "pwmUser";
$anwser_attribute = "pwmResponseSet";
```
Like this, I can set new questions and reset passwords, no problems, however I can't convert the old un-encrypted values with the script, it gives me the error message :
```
Connected to ldap://
4407 user entries found
0 modifications done
```
settings the options in lower case like this : 
```
$anwser_objectClass = "pwmuser";
$anwser_attribute = "pwmresponseset";
```
Solves the problem : 
```
Connected to ldap://
4407 user entries found
Encrypt answer value for uid=xxxxx
Answer updated in LDAP directory
1 modifications done
```
How ever, after this, I can't change the question anymore, I get an error message "your response hasn't been saved".

Changing back to lower/upper case and I can change the question.

I'll update this issue later when I can get apache logs regarding the details of the error.

**Comment by coudot** [comment]
I can make it work by having the objectClass value not in lower case:
```php
$answer_objectClass = "pwmUser";
$answer_attribute = "pwmresponseset";
```

This is normal: the objectClass is a value, and is case sensitive, and the attribute is the attribute key, which must be in lower case in PHP.

**Comment by coudot** [comment]
Documentation updated here: https://ltb-project.org/documentation/self-service-password/latest/config_questions#attribute_and_object_class
