### ISSUE TITLE
LDAP Search User Problem

### ISSUE THREAD

**Issue by satrioyoyo** [ltb-project/self-service-password#241]
Hi,
I had problem. when I trying to change password, the app said "Login or password incorrect"
I activate debug, and this is the
### **ssp_error_log**:
[Thu Sep 20 15:12:28.611136 2018] [:error] [pid 1860] [client x.x.x.x:63182] PHP Warning:  ldap_get_dn() expects parameter 2 to be resource, boolean given in /usr/share/self-service-password/pages/change.php on line 105, referer: http://x.x.x.x/
[Thu Sep 20 15:12:28.611176 2018] [:error] [pid 1860] [client x.x.x.x:63182] **LDAP - User xxxxxx not found**, referer: http://x.x.x.x/
[Thu Sep 20 15:12:28.611186 2018] [:error] [pid 1860] [client x.x.x.x:63182] PHP Notice:  Undefined variable: obscure_failure_messages in /usr/share/self-service-password/pages/change.php on line 187, referer: http://x.x.x.x/
[Thu Sep 20 15:12:28.611199 2018] [:error] [pid 1860] [client x.x.x.x:63182] PHP Warning:  in_array() expects parameter 2 to be array, null given in /usr/share/self-service-password/pages/change.php on line 187, referer: http://x.x.x.x/
[Thu Sep 20 15:12:28.611229 2018] [:error] [pid 1860] [client x.x.x.x:63182] PHP Notice:  Undefined variable: display_posthook_error in /usr/share/self-service-password/pages/change.php on line 194, referer: http://x.x.x.x/

### **http_error log:**
ldap_create
ldap_url_parse_ext(ldap://x.x.x.x:10389)
ldap_bind_s
ldap_simple_bind_s
ldap_sasl_bind_s
ldap_sasl_bind
ldap_send_initial_request
ldap_new_connection 1 1 0
ldap_int_open_connection
ldap_connect_to_host: TCP x.x.x.x:10389
ldap_new_socket: 12
ldap_prepare_socket: 12
ldap_connect_to_host: Trying x.x.x.x:10389
ldap_pvt_connect: fd: 12 tm: -1 async: 0
attempting to connect:
connect success
ldap_open_defconn: successful
ldap_send_server_request
ldap_result ld 0x559d7f27dfe0 msgid 1
wait4msg ld 0x559d7f27dfe0 msgid 1 (infinite timeout)
wait4msg continue ld 0x559d7f27dfe0 msgid 1 all 1
** ld 0x559d7f27dfe0 Connections:
* host: x.x.x.x  port: 10389  (default)
  refcnt: 2  status: Connected
  last used: Thu Sep 20 13:25:03 2018

** ld 0x559d7f27dfe0 Outstanding Requests:
 * msgid 1,  origid 1, status InProgress
   outstanding referrals 0, parent count 0
  ld 0x559d7f27dfe0 request count 1 (abandoned 0)
** ld 0x559d7f27dfe0 Response Queue:
   Empty
  ld 0x559d7f27dfe0 response count 0
ldap_chkResponseList ld 0x559d7f27dfe0 msgid 1 all 1
ldap_chkResponseList returns ld 0x559d7f27dfe0 NULL
ldap_int_select
read1msg: ld 0x559d7f27dfe0 msgid 1 all 1
read1msg: ld 0x559d7f27dfe0 msgid 1 message type bind
read1msg: ld 0x559d7f27dfe0 0 new referrals
read1msg:  mark request completed, ld 0x559d7f27dfe0 msgid 1
request done: ld 0x559d7f27dfe0 msgid 1
res_errno: 0, res_error: <>, res_matched: <>
ldap_free_request (origid 1, msgid 1)
ldap_parse_result
ldap_msgfree
ldap_search
put_filter: "(uid=%s)"
put_filter: simple
put_simple_filter: "uid=%s"
ldap_build_search_req ATTRS: *
ldap_send_initial_request
ldap_send_server_request
ldap_result ld 0x559d7f27dfe0 msgid 2
wait4msg ld 0x559d7f27dfe0 msgid 2 (infinite timeout)
wait4msg continue ld 0x559d7f27dfe0 msgid 2 all 1
** ld 0x559d7f27dfe0 Connections:
* host: x.x.x.x  port: 10389  (default)
  refcnt: 2  status: Connected
  last used: Thu Sep 20 13:25:03 2018

** ld 0x559d7f27dfe0 Outstanding Requests:
 * msgid 2,  origid 2, status InProgress
   outstanding referrals 0, parent count 0
  ld 0x559d7f27dfe0 request count 1 (abandoned 0)
** ld 0x559d7f27dfe0 Response Queue:
   Empty
  ld 0x559d7f27dfe0 response count 0
ldap_chkResponseList ld 0x559d7f27dfe0 msgid 2 all 1
ldap_chkResponseList returns ld 0x559d7f27dfe0 NULL
ldap_int_select
read1msg: ld 0x559d7f27dfe0 msgid 2 all 1
read1msg: ld 0x559d7f27dfe0 msgid 2 message type search-result
read1msg: ld 0x559d7f27dfe0 0 new referrals
read1msg:  mark request completed, ld 0x559d7f27dfe0 msgid 2
request done: ld 0x559d7f27dfe0 msgid 2
res_errno: 0, res_error: <>, res_matched: <>
ldap_free_request (origid 2, msgid 2)
ldap_parse_result
ldap_msgfree
ldap_free_connection 1 1
ldap_send_unbind
ldap_free_connection: actually freed

### **config.inc.php**
$debug = true;

$ldap_url = "ldap://x.x.x.x:10389";
$ldap_starttls = false;
$ldap_binddn = "uid=user,ou=Users,dc=domain,dc=local";
$ldap_bindpw = "user*pass#2018";
$ldap_base = "ou=Users,dc=domain,dc=local";
$ldap_login_attribute = "uid";
$ldap_fullname_attribute = "cn";
$ldap_filter = "(uid=%s)";

**Comment by coudot** [comment]
The configuration of $ldap_filter is false. Set this instead:
```php
$ldap_filter = "(uid={login})";
```

See https://ltb-project.org/documentation/self-service-password/latest/config_ldap#search_parameters

**Comment by satrioyoyo** [comment]
yep, it work! my fault. thank for your reply!
