### ISSUE TITLE
LDAP - Modify password error 53 (Server is unwilling to perform)

### ISSUE THREAD

**Issue by biroby** [ltb-project/self-service-password#244]
Hi to all,
i receive the error in object and i've tried solution find in this site but my problem persists.
I receive this error when I try to change user password in both page (change password and change password after send mail reset)
Can you help me to solve this issue?
[config.php.zip](https://github.com/ltb-project/self-service-password/files/2419245/config.php.zip)

**Comment by coudot** [comment]
In your configuration, you use LDAP and not LDAPS to connect to AD. LDAPS is mandatory on AD to change passwords.

See https://ltb-project.org/documentation/self-service-password/latest/config_ldap#active_directory

**Comment by rguy2001** [comment]
Hey Coudot, thanks again for making this, but I'm lost. 

I see the instructions to export crt but make note on server 2016 you can export cert in cer pfx and other formats. There are also available options like DER etc. 

How do we go about getting .crt format certification and where does this .crt need to live on the host server. 

If ldaps is A MUST, where do we place the crt on host so the application knows to look for it? If you say it needs to be save in /etc/ldap/ldap.conf where exactly do we find /etc/ldap when ldap or open ldap isn't even installed on centos or some other redhat distribution?

I'm so confused... Please assist
