### ISSUE TITLE
Possibility to set a solid background

### ISSUE THREAD

**Issue by Miouge1** [ltb-project/self-service-password#245]
Hi,

Is there a way to disable the background image? Things look cleaner with a solid white background rather than an image.
I would prefer to avoid to set a 1x1 white image as well :)

**Comment by coudot** [comment]
Just define nothing for background_image:
```php
$background_image = NULL;
```

**Comment by mrPsycho** [comment]
same as logo.

**Comment by plewin** [comment]
Thank you, I'm closing this issue because it has already been solved.
