### ISSUE TITLE
Certificate from LE untrusted or revoked

### ISSUE THREAD

**Issue by sebelk** [ltb-project/self-service-password#246]
Hi,

I have installed ssp on Debian Stretch. The problem is that ssp complains about certificate:
````
TLS: peer cert untrusted or revoked (0x42)
ldap_open_defconn: successful
````

My custom config is:

~~~~
$debug = true;
$ldap_url = "ldaps://ldap.example.com:636";
$ldap_binddn = "cn=Administrator,cn=Users,dc=example,dc=com";
$ldap_bindpw = "sdsdsdsdsdsd";
$ldap_base = "dc=example,dc=com";
$ldap_login_attribute = "sAMAccountName";
$ad_mode = true;
$who_change_password = "manager";
$answer_objectClass = "user";
$answer_attribute = "comment";
$messages['questions']['Animal'] = "¿Cuál es su animal favorito?";
$messages['questions']['Ciudad'] = "¿Cuál es su ciudad favorita?";
$messages['questions']['Película'] = "¿Cuál es su película favorita?";
$use_tokens = false;
$mail_address_use_ldap = true;
$mail_from = "noreply@example.com";
$mail_smtp_debug = 8;
$mail_smtp_host = '192.168.50.8';
$mail_smtp_user = 'stand';
$mail_smtp_pass = 'xxxxxxx';
$mail_smtp_port = 587;
$use_sms = false;
$keyphrase = "sldklskdlskdlkldksd";
~~~~

I edited `/etc/ldap/ldap.conf` and append at the end:

`TLS_REQCERT allow`

It worked as a workaround, but I wonder why the certificate is regarded as untrusted or revoked being its issuer Let's Encrypt.

Any ideas?

**Comment by plewin** [comment]
Hi,
To diagnose a certificate issue, on your Debian stretch, the same server of
SSP try this command

openssl s_client -connect ldap.example.com:636

It will explain why the certificate has issues

**Comment by sebelk** [comment]
Well, it's a SAMBA4 DC, should I modify something?

> Are you sure the certificat of the LDAP directory is LE? Seen your configuration, it seems you are binding to an Active Directory.

**Comment by sebelk** [comment]
> openssl s_client -connect ldap.example.com:636

That made the trick, shame on me, I was using the cert.pem file, but LE README says:

`fullchain.pem`: the certificate file used in most server software.

`cert.pem`     : **will break many server configurations, and should not be used
                 without reading further documentation.. **

So, replacing cert.pem by fullchain.pem both on `/etc/ldap/ldap.conf` and on `smb.conf` fixed the issue.

Thanks and nice project ssp!

**Comment by coudot** [comment]
Thanks for the feedback
