### ISSUE TITLE
Web Autocomplete

### ISSUE THREAD

**Issue by sinefile1** [ltb-project/self-service-password#250]
Good Day Sirs!
I hope I am in the right path here. We have running Ltb-SSP in our Active Directory environment, we're just using the reset password thru question and answer feature. It work splendid. 
Anyway we have issue right now, some of our users are complaining because the answers that they entering in the web are saved, I can disable that settings in the browser itself or in a group policy but before doing that, maybe our gurus here can change the default behavior of the SSP by turning off the autocomplete in the answer field.

Thanks in advance.
Sine

**Comment by coudot** [comment]
See #251

**Comment by sinefile1** [comment]
Thank you very much Mr. Clement.......
    On Thursday, 25 October 2018, 8:46:26 AM GMT+3, Clément OUDOT <notifications@github.com> wrote:  
 
 
Closed #250.
