### ISSUE TITLE
 Cannot access LDAP directory / LDAP - Bind error -1

### ISSUE THREAD

**Issue by gabuniag** [ltb-project/self-service-password#252]
I know there have been similar questions, but I wasn't able to resolve problem after reading those.

I'm running self service password tool on Ubuntu 18.04.1 LTS
OpenLDAP server is running on CentOS Linux release 7.5.1804
My config file looks like this:

```
$show_menu = false;
$show_help = true;
$debug = true;
$keyphrase = "askdjlkHJGAS76uy9769JHGJhg087986";
$login_forbidden_chars = "*()&|";

$ldap_url = "ldaps://ldapserver";
$ldap_starttls = false;
$ldap_binddn = "cn=root,dc=cm,dc=cluster";
$ldap_bindpw = "edited";
$ldap_base = "dc=cm,dc=cluster";

$ldap_login_attribute = "uid";
$ldap_fullname_attribute = "cn";
$ldap_filter = "(&(objectClass=person)($ldap_login_attribute={login}))";


$samba_mode = false;
$ad_mode = false;
```

My /etc/ldap/ldap.conf file has a cert, which I imported from server:
```
BASE    dc=cm,dc=cluster
URI     ldaps://ldapserver
TLS_CACERT      /etc/ssl/ca.crt
```
I am able to telnet to the port from client machine:
```
# telnet ldapserver 636
Trying 10.2.62.28...
Connected to ldapserver.
```
openssl test works as well, there are several ssl related apps on server, so I'm explicitly specifying servername:
```
# openssl s_client -servername ldapserver -connect 10.2.62.28:636 -CAfile /etc/ssl/ca.pem
***
SSL handshake has read 1877 bytes and written 525 bytes
Verification: OK
***
```

However I still get error in debug log:

> [Mon Nov 05 14:58:32.699493 2018] [php7:warn] [pid 2660] [client 127.0.0.1:39098] PHP Warning:  ldap_bind(): Unable to bind to server: Can't contact LDAP server in /usr/share/self-service-password/pages/change.php on line 80, referer: http://ssp/
> [Mon Nov 05 14:58:32.699535 2018] [php7:notice] [pid 2660] [client 127.0.0.1:39098] LDAP - Bind error -1  (Can't contact LDAP server), referer: http://ssp/
> [Mon Nov 05 14:58:32.699544 2018] [php7:notice] [pid 2660] [client 127.0.0.1:39098] PHP Notice:  Undefined variable: obscure_failure_messages in /usr/share/self-service-password/pages/change.php on line 186, referer: http://ssp/
> [Mon Nov 05 14:58:32.699552 2018] [php7:warn] [pid 2660] [client 127.0.0.1:39098] PHP Warning:  in_array() expects parameter 2 to be array, null given in /usr/share/self-service-password/pages/change.php on line 186, referer: http://ssp/
> [Mon Nov 05 14:58:32.699572 2018] [php7:notice] [pid 2660] [client 127.0.0.1:39098] PHP Notice:  Undefined variable: display_posthook_error in /usr/share/self-service-password/pages/change.php on line 193, referer: http://ssp/

 I have played with config file quite a bit, but I wasn't able to solve this problem, or even raise a new error

**Comment by coudot** [comment]
In your ldap.conf you have /etc/ssl/ca.crt and in your OpenSSL command line you have /etc/ssl/ca.pem, so you may have a bad file name in ldap.conf

**Comment by coudot** [comment]
Try with ldapsearch

**Comment by gabuniag** [comment]
Additional info, my ~/.ldaprc looks like this:
# cat .ldaprc 
```
# cat .ldaprc 
TLS_REQCERT try
TLS_CACERT  /etc/ssl/ca.pem
TLS_CERT    /etc/ssl/ldap.pem
TLS_KEY     /etc/ssl/ldap.key
SASL_MECH   external
```

and ldap search works:
```
# ldapsearch -x -D 'cn=root,dc=cm,dc=cluster' -w "W4CTwTCj8c5KbR80"
*****
# search result
search: 2
result: 0 Success
```

**Comment by coudot** [comment]
Seems fine, PHP LDAP should use your LDAP client configuration. I don't know why it fails. The debug mode should print LDAP debug information on the web page, don't you see anything?

**Comment by gabuniag** [comment]
No, On the web page I only see:
 Cannot access LDAP directory

Log messages I copied are from:
/var/log/apache2/ssp_error.log 

It still prints the same thing btw.

**Comment by coudot** [comment]
Don't use ldaprc with apache, apache is a system user. Put configuration in /etc/ldap/ldap.conf

**Comment by gabuniag** [comment]
Yeah, did that already, now ldap.conf looks like this:
```
BASE    dc=cm,dc=cluster
URI     ldaps://ldapserver

#TLS_CACERT      /etc/ssl/ca.pem

TLS_REQCERT try
TLS_CACERT  /etc/ssl/ca.pem
TLS_CERT    /etc/ssl/ldap.pem
TLS_KEY     /etc/ssl/ldap.key
SASL_MECH   external

```
But error is still same

**Comment by coudot** [comment]
In index.php you should have : 
```php
if($debug) {
    error_reporting(E_ALL);
    // Important to get error details in case of SSL/TLS failure at connection
    ldap_set_option(NULL, LDAP_OPT_DEBUG_LEVEL, 7);
}
```

You should see on web page or in error log what is failing.

**Comment by gabuniag** [comment]
Yes, there is:
```
#==============================================================================
# Error reporting
#==============================================================================
error_reporting(0);
if($debug) {
    error_reporting(E_ALL);
    // Important to get error details in case of SSL/TLS failure at connection
    ldap_set_option(NULL, LDAP_OPT_DEBUG_LEVEL, 7);
}
```
But there is no text other than this:

![screenshot from 2018-11-05 16-53-42](https://user-images.githubusercontent.com/24247660/48009162-633b5700-e11b-11e8-8438-3452bc763127.png)

**Comment by coudot** [comment]
Are you sure there is no other $debug parameter that is canceling the $debug in your configuration ?

**Comment by gabuniag** [comment]
Well, I also had one in config.inc.local.php, as shown in OP, but removing it didn't do anything

**Comment by gabuniag** [comment]
So, Clement, Any idea how should I proceed? :)

Have you tested tool on Ubuntu 18.04? 
PHP I'm running is:
PHP 7.2.10-0ubuntu0.18.04.1 (cli) (built: Sep 13 2018 13:45:02) ( NTS )

Maybe that is the issue? some php packages were dropped from 7.2, had to install them separately from various sources.

Anyway problem definitely is that ssp does not negotiate certs properly

**Comment by coudot** [comment]
No idea, SSP uses PHP LDAP, so we can't do anything in the code. The PHP LDAP debug mode should explain what is failing. Try to create a simple PHP page that connects to your LDAP server.

**Comment by mrPsycho** [comment]
@gabuniag just in case, have you tried to add `TLS_REQCERT allow` in `ldap.conf`?

**Comment by gabuniag** [comment]
It would not matter.

The reason why tool does not work, is that it won't allow explicit cert definition.

Meaning:
I need to create .ldaprc file in user's home to specify variables. 
```
TLS_CERT
TLS_KEY
```
My server configuration won't allow user to connect without it.

as per man 5 ldap.conf:
> This is a  user-only option.

Therefore they have to be defined in .ldaprc file in user's home. Defining them in ldap.conf has no effect.
If they are commented out from .ldaprc, command line tools like ldapsearch fail. 

I already commented above that the tool does not touch user's .ldaprc file, (even when copied to apache user's home dir). Without reading this file, and without proper options for configuration file, there is not way ltb tool would be aware of cert and key file.

I don't know php well enough to tinker with script. I'd rather take and modify some python tool, or write one from scratch

**Comment by mrPsycho** [comment]
https://serverfault.com/questions/588960/custom-ldap-conf-for-apache-2-2 - does this help?

**Comment by Duan-fei** [comment]
hi  you can add TLS_REQCERT never to /etc/ldap/ldap.conf on your self-service-password server

**Comment by plewin** [comment]
Hi @gabuniag, did you manage to solve your issue ?

**Comment by tamhankarni3** [comment]
hello everyone,
i am new to this.
i have done the installation and configure the application.
my active directory in on Windows 2016 server accessible on port 389.
Currently installed **self-service-password** on Centos 7.
I am getting error "Cannot Access LDAP Directory".

Request your help on this.
Thanks & Regards,
Ni3
![Error](https://user-images.githubusercontent.com/62698391/77639573-f9755480-6f7e-11ea-8a1f-d94e1c31d9f1.jpg)

**Comment by VGerris** [comment]
just a quick update, it is not **never** but **allow**:
TLS_REQCERT allow
add that to the end of the /etc/ldap/ldap.conf
as per
https://ltb-project.org/documentation/self-service-password/1.4/config_ldap
that makes it work with self signed certificates without further setup.

If that is not your problem, please read the docs carefully and follow the instructions that were given for debugging and make a NEW issue.
Make sure you are able to find the exact error that occurs so you don't have to ask people to dig through your config files because you did not do so yourself ;).
good luck
