### ISSUE TITLE
Do token resets require administrative rights on the directory tree?

### ISSUE THREAD

**Issue by tleuxner** [ltb-project/self-service-password#257]
I'm currently testing pw resets using tokens. While the basic functionality of changing the password using the old/new password works fine using read-only LDAP accounts, tokens seem to require an account being able to change other user passwords.

`$who_change_password = "user";`

Is this expected behavior for tokens?

**Comment by coudot** [comment]
Indeed, with tokens we are forced to bind with the admin account, as we don't have the user old password.

**Comment by tleuxner** [comment]
Thanks!

**Comment by pR0Ps** [comment]
Can this be added to the documentation please?

**Comment by coudot** [comment]
> Can this be added to the documentation please?

Done: https://ltb-project.org/documentation/self-service-password/latest/config_ldap#credentials

**Comment by pR0Ps** [comment]
Thank you!
