### ISSUE TITLE
request: facilitate by-email when SMTP auth is required

### ISSUE THREAD

**Issue by r2evans** [ltb-project/self-service-password#26]
The default PHP `mail()` is fine when authentication is not required, but this does not work in situations where the client must authenticate before sending. I know there are less-standard methods in PHP to allow authenticating-SMTP, how difficult is it to incorporate one of those methods into your package?

Thanks!

**Comment by coudot** [comment]
We should use PHPmailer.

From:
* http://tools.ltb-project.org/issues/813
* http://tools.ltb-project.org/issues/594
* http://tools.ltb-project.org/issues/567

**Comment by coudot** [comment]
Done.

Documentation updated: http://ltb-project.org/wiki/documentation/self-service-password/1.0/config_mail#phpmailer

**Comment by r2evans** [comment]
Clement, I really appreciate your recent changes (namely this and #31 ). Until release I'll pull `master.zip` from github, but do you have an expected delivery date for v1.0?

Thanks for maintaining this, it really helps!

**Comment by coudot** [comment]
It should be released this month.
