### ISSUE TITLE
Login or password incorrect

### ISSUE THREAD

**Issue by uknet8080** [ltb-project/self-service-password#260]
Hi,

Following is my configuration. I have made several changes but still I get loing name password incorrect. and Apache error message is as follow:
```
[Thu Jan 10 16:36:31 2019] [error] [client 172.17.140.255] PHP Notice:  Undefined variable: Change in /var/www/html/self-service-password-master/conf/config.inc.php on line 244, referer: https://itd.com/self-service-password-master/
```

This is the LDAP Setting:

```php
$ldap_url = "ldap://172.30.0.12/389";
$ldap_starttls = false;
$ldap_binddn = "cn=lms,cn=users,dc=stud,dc=local";
$ldap_bindpw = "l@1234";
$ldap_base = "cn=users,dc=stud,dc=local";
#$ldap_login_attribute = "uid";
$ldap_login_attribute = "sAMAccountName";
$ldap_fullname_attribute = "cn";
$ldap_filter = "(&(objectClass=person)($sAMAccountName={login}))";
#$ldap_filter = "(&(objectClass=person)(sAMAccountName={login})(!(userAccountControl:1.2.840.113556.1.4.803:=2)))";
#$ldap_filter = "(sAMAccountName={login})";
```

You help is highly appreciated.

Thanks,

Amin

**Comment by coudot** [comment]
You LDAP Filter value is bad, and your LDAP URL too.

Try:
```php
$ldap_url = "ldap://172.30.0.12:389";
$ldap_filter = "(&(objectClass=person)(sAMAccountName={login}))";
```

If you are using AD as LDAP directory, you must configure LDAPS to be able to change password.

**Comment by coudot** [comment]
Do you have some logs on server side?

You can try to use simple quotes instead of double quotes for bindpw, because @ is maybe interpreted by PHP:
```php
$ldap_bindpw = 'l@1234';
```

**Comment by uknet8080** [comment]
I have to change the setting to a single quote still having same error message.
Please find below error message after clicking on the Send button.

[Mon Jan 14 09:50:05 2019] [error] [client 172.17.134.253] PHP Notice:  Undefined variable: Change in /var/www/html/self-service-password-master/conf/config.inc.php on line 244, referer: https://172.30.0.12/self-service-password-master/
[Mon Jan 14 09:50:05 2019] [error] [client 172.17.134.253] PHP Notice:  Undefined variable: use_sms in /var/www/html/self-service-password-master/index.php on line 110, referer: https://172.30.0.12/self-service-password-master/
[Mon Jan 14 09:50:05 2019] [error] [client 172.17.134.253] PHP Notice:  Undefined variable: use_sms in /var/www/html/self-service-password-master/menu.php on line 32, referer: https://172.30.0.12/self-service-password-master/
[Mon Jan 14 09:50:05 2019] [error] [client 172.17.134.253] PHP Notice:  Undefined variable: logo in /var/www/html/self-service-password-master/index.php on line 209, referer: https://172.30.0.12/self-service-password-master/
[Mon Jan 14 09:50:05 2019] [error] [client 172.17.134.253] PHP Warning:  ldap_get_dn() expects parameter 2 to be resource, boolean given in /var/www/html/self-service-password-master/pages/change.php on line 105, referer: https://172.30.0.12/self-service-password-master/
[Mon Jan 14 09:50:05 2019] [error] [client 172.17.134.253] LDAP - User Labtest not found, referer: https://172.30.0.12/self-service-password-master/
[Mon Jan 14 09:50:05 2019] [error] [client 172.17.134.253] PHP Notice:  Undefined variable: obscure_failure_messages in /var/www/html/self-service-password-master/pages/change.php on line 186, referer: https://172.30.0.12/self-service-password-master/

**Comment by uknet8080** [comment]
I have to change the setting to a single quote still having the same error message.
Please find below error message after clicking on the Send button.

`[Mon Jan 14 09:50:05 2019] [error] [client 172.17.134.253] PHP Notice: Undefined variable: Change in /var/www/html/self-service-password-master/conf/config.inc.php on line 244, referer: https://172.30.0.12/self-service-password-master/
[Mon Jan 14 09:50:05 2019] [error] [client 172.17.134.253] PHP Notice: Undefined variable: use_sms in /var/www/html/self-service-password-master/index.php on line 110, referer: https://172.30.0.12/self-service-password-master/
[Mon Jan 14 09:50:05 2019] [error] [client 172.17.134.253] PHP Notice: Undefined variable: use_sms in /var/www/html/self-service-password-master/menu.php on line 32, referer: https://172.30.0.12/self-service-password-master/
[Mon Jan 14 09:50:05 2019] [error] [client 172.17.134.253] PHP Notice: Undefined variable: logo in /var/www/html/self-service-password-master/index.php on line 209, referer: https://172.30.0.12/self-service-password-master/
[Mon Jan 14 09:50:05 2019] [error] [client 172.17.134.253] PHP Warning: ldap_get_dn() expects parameter 2 to be resource, boolean given in /var/www/html/self-service-password-master/pages/change.php on line 105, referer: https://172.30.0.12/self-service-password-master/
[Mon Jan 14 09:50:05 2019] [error] [client 172.17.134.253] LDAP - User Labtest not found, referer: https://172.30.0.12/self-service-password-master/
[Mon Jan 14 09:50:05 2019] [error] [client 172.17.134.253] PHP Notice: Undefined variable: obscure_failure_messages in /var/www/html/self-service-password-master/pages/change.php on line 186, referer: https://172.30.0.12/self-service-password-master/`

**Comment by coudot** [comment]
The error seems to say that the login "Labtest" is not found in your LDAP directory. Are you sure that there is an entry matchin (sAMAccountName=Labtest) ?

**Comment by uknet8080** [comment]
That is what I thought.  I change the password number of times to make sure it is fine. but still doesn't work.

**Comment by plewin** [comment]
Hi @uknet8080, did you manage to solve your issue ?
