### ISSUE TITLE
I'm trying to access LDAP stuck at "Install PHP LDAP to use this tool". 

### ISSUE THREAD

**Issue by jeremyredkey** [ltb-project/self-service-password#262]
The error log shows the following message, even though the config file has all the right settings in place. Can you please help me with what you think the problem is?
<img width="565" alt="screen shot 2019-02-01 at 1 38 59 pm" src="https://user-images.githubusercontent.com/16844107/52151087-bf344f80-2626-11e9-856c-2e188332bb01.png">

Currently running LDAP not LDAPS
```
# LDAP
$ldap_url = "ldap://127.xx.xxx.xxx:389";
$ldap_starttls = false;
$ldap_binddn = "xxxxxx@sgmh.org";
$ldap_bindpw = "[REDACTED]";
$ldap_base = "dc=sangor,dc=ad";
$ldap_login_attribute = "uid";
$ldap_fullname_attribute = "cn";
$ldap_filter = "(&(objectClass=*)(sAMAccountName={login})";

# Active Directory mode
# true: use unicodePwd as password field
# false: LDAPv3 standard behavior
$ad_mode = true;
# Force account unlock when password is changed
$ad_options['force_unlock'] = true;
# Force user change password at next login
$ad_options['force_pwd_change'] = true;
# Allow user with expired password to change password
$ad_options['change_expired_password'] = true;

$who_change_password = "manager";
```

**Comment by dgeo** [comment]
Just install the LDAP module for PHP (php-ldap package on Debian, php71-ldap on FreeBSD, …) and restart php or apache service

**Comment by jeremyredkey** [comment]
When I execute pkg_info, (I'm running OpenBSD) -- this is what I receive:
```
brotli-1.0.5        generic lossless compressor
bzip2-1.0.6p9       block-sorting file compressor, unencumbered
curl-7.61.1         get files from FTP, Gopher, HTTP or HTTPS servers
cyrus-sasl-2.1.26p25 RFC 2222 SASL (Simple Authentication and Security Layer)
db-4.6.21p5v0       Berkeley DB package, revision 4
femail-1.0p1        simple SMTP client
femail-chroot-1.0p3 simple SMTP client for chrooted web servers
gettext-0.19.8.1p1  GNU gettext runtime libraries and programs
intel-firmware-20180807p0v0 microcode update binaries for Intel CPUs
jansson-2.11        library for manipulating JSON data
jpeg-2.0.0v0        SIMD-accelerated JPEG codec replacement of libjpeg
libiconv-1.14p3     character set conversion library
libxml-2.9.8p0      XML parsing library
lua-5.3.5           powerful, light-weight programming language (version 5.3.5)
mariadb-client-10.0.36v1 multithreaded SQL database (client)
mariadb-server-10.0.36p0v1 multithreaded SQL database (server)
nghttp2-1.33.0      library for HTTP/2
oniguruma-6.9.0     regular expressions library
openldap-client-2.4.46 open-source LDAP software (client)
openssl-1.0.2p      TLS/SSL library and tools
p5-Clone-0.38       recursively copy Perl datatypes
p5-DBD-mysql-4.042p0 MySQL drivers for the Perl DBI
p5-DBI-1.641        unified perl interface for database access
p5-FreezeThaw-0.5001 module for converting structures to strings and back
p5-MLDBM-2.05       store multi-level hash structure in single-level tied hash
p5-Math-Base-Convert-0.08p0 very fast base to base conversion
p5-Module-Runtime-0.016 runtime module handling
p5-Net-Daemon-0.48p0 extension for portable daemons
p5-Params-Util-1.07p1 utility to make parameter checking easier
p5-PlRPC-0.2020     module for writing rpc servers and clients
p5-SQL-Statement-1.407 SQL parsing and processing engine
pcre-8.41           perl-compatible regular expression library
pgp-5.0ip2          Pretty Good Privacy 5.0i (world wide use)
php-7.2.10          server-side HTML-embedded scripting language
php-curl-7.2.10     curl URL library extensions for php
php-ldap-7.2.10     ldap protocol extensions for php
php-mysqli-7.2.10   mysql database access extensions for php
png-1.6.35          library for manipulating PNG images
quirks-3.16         exceptions to pkg_add rules
screen-4.0.3p6      multi-screen window manager
xz-5.2.4            LZMA compression and decompression tools
```

**Comment by jeremyredkey** [comment]
Doesn't this mean that I have PHP LDAP as a dependency already and openldap-client-2.4.46... So my module is installed and I already restarted apache services. Still getting the same error.

**Comment by dgeo** [comment]
did you load the module ? (```cp /etc/php-7.2.sample/ldap.ini /etc/php-7.2/ldap.ini```)

**Comment by jeremyredkey** [comment]
> did you load the module ? (`cp /etc/php-7.2.sample/ldap.ini /etc/php-7.2/ldap.ini`)

Yes I did execute the line above. My OS of my web server is OpenBSD. when I cat ldap.ini

I have the uncommented line below:
```
extension=ldap.so
```

**Comment by jeremyredkey** [comment]
When I run in debug mode I get a 500 error when I run without debug mode I get the message: "You should install PHP LDAP to use this tool". So it is still broken and I'm unsure what the issue is.

**Comment by dgeo** [comment]
seems that php ldap module doesn't load…
does a simple phpinfo(); page shows LDAP ? Here it does (6.4 too).
If I find some spare time I'll try to run SSP on this machine, but don't expect too soon (if ever, time is hard to spare here… :(

**Comment by jeremyredkey** [comment]
No worries, I'm trying to just see if there is a simple fix. There is some dependency that I'm missing that I don't know about that I wanted to see if its a common thing. Below is a screenshot of my phpinfo page:
<img width="943" alt="screen shot 2019-02-05 at 9 53 45 am" src="https://user-images.githubusercontent.com/16844107/52293559-03c43180-292c-11e9-8a82-c212df477ffd.png">

**Comment by plewin** [comment]
Hi @jeremyredkey 
you have a php configuration issue.
I believe, php ldap module is not configured on your php installation.

phpinfo reports 'additional .ini files parsed' of only mysqli.ini, i guess it means that php-ldap is not loaded.

please
- check that your apache was correctly restarted
- permissions of the .ini file are correct
- refer to openbsd documentation

Here is what you should see in a phpinfo with php ldap installed "ldap support enabled"
![selection_095](https://user-images.githubusercontent.com/707245/52311529-82aa8000-29a7-11e9-92ae-8899e3ffb6a6.png)

**Comment by jeremyredkey** [comment]
So I uninstalled and reinstalled the php-ldap package and readded it and this error is thrown: 

```
File /etc/php-7.1.sample/ldap.ini could not be installed:
        No such file or directory
php-ldap-7.1.22: ok
```

Still stuck after restarting apache and referring to OpenBSD docs.

**Comment by plewin** [comment]
Hi @jeremyredkey, sorry I know it's been a year. did you solve your issue or need additional assistance on this issue ?
