### ISSUE TITLE
problem with password reset token

### ISSUE THREAD

**Issue by tomasberzinas** [ltb-project/self-service-password#265]
hi, i have this issue: when i press send button token is displayed and sent to my recovery email. As i understand it should not be displayed. Maybe someone can help me with this issue?

thank you.
![capture10](https://user-images.githubusercontent.com/47626313/52774399-c22b3900-3045-11e9-8c12-ea3577a2a300.PNG)

**Comment by coudot** [comment]
Strange, because this message should be in error log:
```
clement@ader-worteks:~/dev/self-service-password$ grep -r 'Send reset URL'
pages/sendsms.php:        error_log("Send reset URL $reset_url \n\n", 3, $reset_request_log);
pages/sendsms.php:        error_log("Send reset URL $reset_url");
pages/sendtoken.php:        error_log("Send reset URL $reset_url \n\n", 3, $reset_request_log);
pages/sendtoken.php:        error_log("Send reset URL $reset_url");
```

What is your configuration for `$reset_request_log`?

**Comment by tomasberzinas** [comment]
hi, my configuration:

/passch/pages/sendsms.php:        error_log("Send reset URL $reset_url \n\n", 3, $reset_request_log);
/passch/pages/sendsms.php:        error_log("Send reset URL $reset_url");
/passch/pages/sendtoken.php:        error_log("Send reset URL $reset_url \n\n", 3, $reset_request_log);
/passch/pages/sendtoken.php:        error_log("Send reset URL $reset_url");
/pages/sendsms.php:        error_log("Send reset URL $reset_url \n\n", 3, $reset_request_log);
/pages/sendsms.php:        error_log("Send reset URL $reset_url");


also when i change password i get:

![capture20](https://user-images.githubusercontent.com/47626313/52810513-68edf480-309b-11e9-8b6b-1f4757ee9bf6.PNG)

but it does change the password no problem there just stupid message in html.

**Comment by coudot** [comment]
You have a big issue in your installation, because error_log messages are displayed on the webpage.

You should install SSP with packages.

**Comment by tomasberzinas** [comment]
webpage is running on windows server, php 7.

**Comment by tomasberzinas** [comment]
maybe i can solve this by migrating to linux?

**Comment by coudot** [comment]
SSP should work on Windows, but I can't give any support on it.

Using GNU/Linux seems a wise choice.
