### ISSUE TITLE
Password change not working after adding mail to ldap filter

### ISSUE THREAD

**Issue by LucNig** [ltb-project/self-service-password#269]
Goal for us was to make it easy for the user to type their email adress instead of the username to reset the password.

So I added The mail attribute to my ldap filter: 
```php
$ldap_filter = "(&(objectClass=user)(|(mail={login})(sAMAccountName=login))(!(userAccountControl:1.2.840.113556.1.4.803:=2)))";
```

In the security log of the ad server it seams he resolves the mail address nicely to the right accountname But the tool gives the error "ldap server did not accept password"
And the following lines in the debug error log:
```
[Thu Mar 07 10:10:18.836859 2019] [:error] [pid 1625] [client 10.254.254.23:56114] PHP Warning:  ldap_modify_batch(): Batch Modify: Constraint violation in /var/www/linshare-ui-user/pwr/lib/functions.inc.php on line 396, referer: https:$
[Thu Mar 07 10:10:18.836916 2019] [:error] [pid 1625] [client 10.254.254.23:56114] LDAP - Modify password error 19 (Constraint violation), referer: https://cfs.server.com/
[Thu Mar 07 10:10:18.836928 2019] [:error] [pid 1625] [client 10.254.254.23:56114] PHP Notice:  Undefined variable: obscure_failure_messages in /pages/change.php on line 186, referer: https://cfs.server.com$
[Thu Mar 07 10:10:18.836936 2019] [:error] [pid 1625] [client 10.254.254.23:56114] PHP Warning:  in_array() expects parameter 2 to be array, null given in /pages/change.php on line 186, referer: https://cfs.server.com$
[Thu Mar 07 10:10:18.837082 2019] [:error] [pid 1625] [client 10.254.254.23:56114] PHP Notice:  Undefined variable: display_posthook_error in /pages/change.php on line 193, referer: https://cfs.server.com$
[Thu Mar 07 10:10:20.497378 2019] [:error] [pid 1625] [client 10.254.254.23:56114] PHP Notice:  Undefined variable: obscure_failure_messages in /pages/change.php on line 186, referer: https://cfs.server.com$
[Thu Mar 07 10:10:20.497420 2019] [:error] [pid 1625] [client 10.254.254.23:56114] PHP Warning:  in_array() expects parameter 2 to be array, null given in /pages/change.php on line 186, referer: https://cfs.$
[Thu Mar 07 10:10:20.497531 2019] [:error] [pid 1625] [client 10.254.254.23:56114] PHP Notice:  Undefined variable: display_posthook_error in /pages/change.php on line 193, referer: https://cfs.server.com$
```

Can someone point me in the right direction to fix this?

**Comment by coudot** [comment]
This error means AD has refused the password because it is not complex enough, or you are trying to update the password without using LDAPS.

**Comment by LucNig** [comment]
I know that it can mean complexity, but it seems not the case, i disabled complexity reqs completely for dev purposes without results. It started after changing the ldap filter without having changed anything.
I do use ldaps ( RTFM :) ) 

I will try to narrow down my issue a bit more.

**Comment by coudot** [comment]
Check your filter, you miss curly brackets:
```php
$ldap_filter = "(&(objectClass=user)(|(mail={login})(sAMAccountName={login}))(!(userAccountControl:1.2.840.113556.1.4.803:=2)))";
```

**Comment by LucNig** [comment]
Coudot,

Yes saw they where missing. I managed to narrow down the problem, but cant find out why.
When i set the tool to change password by manager it works fine, as soon as i try to let the user change te password it refuses. so nothing to do with PW complexity

**Comment by plewin** [comment]
Hi @LucNig did you find a solution to your issue ?

Sometimes I get this issue when I try a password that is complex but that was used before.
