### ISSUE TITLE
Non-english characters are being stipped in posthook call

### ISSUE THREAD

**Issue by thnilsen** [ltb-project/self-service-password#273]
The current posthook code will strip out a number of characters from the password string when it is passed via the escapeshellarg() command. 
https://github.com/ltb-project/self-service-password/blob/039804ebc46ffe8e77f37f6f94e7e53af8e0fb76/pages/change.php#L178

A password of "Testøæå123" will come out as "Test123". 

One possible way around this would be to base64 encode the string before calling escapeshellarg(), and have the posthook script handle decoding from base64. This could be made into an config option, something along the line of:

in config.inc.php add
```$posthook_config_encode` = true; `//true/false```

in libs/functions.php add
```function encode_posthook_arg( $text ) {
	global $posthook_config_encode;
	if ( $posthook_config_encode ) {
		return base64_encode($text);
	}
	return $text;
}
```

change the call to posthook to read something along the lines of  
```$command = escapeshellcmd($posthook).' '.escapeshellarg($login).' '.escapeshellarg(encode_posthook_arg($newpassword)).' '.escapeshellarg(encode_posthook_arg($oldpassword));```

Or are there other preferred ways to go about this? I can make a PR for this change if interested?

**Comment by coudot** [comment]
See http://php.net/manual/fr/function.escapeshellarg.php#99213

We could maybe fix this issue only by adding this in the code:
```php
setlocale(LC_CTYPE, "en_US.UTF-8");
```

Could you test?

**Comment by thnilsen** [comment]
Added setlocale(..) to the end of the config.inc.php file and it now handles the norwegian chars correctly. So this might be a good idea to include in any case. 

However, it will still make a mess of characters that are natively escaped by escapeshellarg() - such as the single quote character ('), # & ; * ? etc. One could always try and de-escape in the posthook script, but it won't be easy. I think a base64_encode option is still worth considering in some form.

**Comment by coudot** [comment]
Indeed, it can be interesting to add this option (I would call it `$posthook_password_encodebase64`) and we should maybe create a function to return the full posthook command instead of just the encoded password. This function should take as parameter `$login`, `$newpassword`, `$oldpassword` and `$posthook_password_encodebase64`.

I will add the setlocale in the main code.

**Comment by thnilsen** [comment]
Pull request #274 created. Take a look and see if you find it acceptable or if I should change it in any way.

**Comment by coudot** [comment]
Unit test added, and setlocale defined in configuration (as comment)
