### ISSUE TITLE
md5crypt hashing scheme?

### ISSUE THREAD

**Issue by Jkroczek** [ltb-project/self-service-password#277]
Hi, would it be possible to add the ability to set $hash to md5crypt when setting new passwords in self-service-password to an OpenLDAP server? If there is a way to do this currently let me know... I do not see this option listed in the documentation.

**Comment by coudot** [comment]
Hello,

you need to use `crypt` as hash format, and set salt prefix to `$1$` : 
```php
$hash = "crypt";
$hash_options['crypt_salt_prefix'] = "$1$";
$hash_options['crypt_salt_length'] = "8";
```

Note this is not a very secure algorithm.

**Comment by Jkroczek** [comment]
Thanks for the quick response, I appreciate it!
