### ISSUE TITLE
LDAPS Using Wildcard

### ISSUE THREAD

**Issue by dennisasilva** [ltb-project/self-service-password#278]
Hello Guys,

I'm trying to configure the LDAPS to reset users account in the AD on Windows Server 2012 R2 but I'm not sure if I can do then right thong and if I can use a wildcard certificate.

Could you help me? If you guys need the configuration file or more information, please let me know.

Thanks

**Comment by coudot** [comment]
Check https://ltb-project.org/documentation/general/active_directory_certificates

I don't think you can generate a wilcard certificate for AD.

**Comment by dennisasilva** [comment]
Hello coudot,

Actually I'm trying to use a 3rd party wildcard certificate that I bought to company and I read it in a microsoft kb that possibly I will be get some error.  I used the openssl command and I saw the apache log too but it seems fine.

Thanks in advance for your help.

**Comment by coudot** [comment]
If it works with openssl and Apache, then what is the issue?

**Comment by dennisasilva** [comment]
I'm not sure if the apache and openssl are working well.

Here the output commands the I would like request your help:

error.log
ldap_url_parse_ext(ldaps://*host*.com:636)
*for security reasons I omitted the domain and host server name
ldap_extended_operation_s
ldap_extended_operation
ldap_send_initial_request
ldap_new_connection 1 1 0
ldap_int_open_connection
ldap_connect_to_host: TCP host.domain.com:636
ldap_new_socket: 17
ldap_prepare_socket: 17
ldap_connect_to_host: Trying host:636
ldap_pvt_connect: fd: 17 tm: -1 async: 0
attempting to connect:
connect success
ldap_open_defconn: successful
ldap_send_server_request
ldap_result ld 0x55dbdf8598a0 msgid 1
wait4msg ld 0x55dbdf8598a0 msgid 1 (infinite timeout)
wait4msg continue ld 0x55dbdf8598a0 msgid 1 all 1
** ld 0x55dbdf8598a0 Connections:
* host: brdl01.daitan.com  port: 636  (default)
  refcnt: 2  status: Connected
  last used: Sat Mar 23 15:28:37 2019


** ld 0x55dbdf8598a0 Outstanding Requests:
 * msgid 1,  origid 1, status InProgress
   outstanding referrals 0, parent count 0
  ld 0x55dbdf8598a0 request count 1 (abandoned 0)
** ld 0x55dbdf8598a0 Response Queue:
   Empty
  ld 0x55dbdf8598a0 response count 0
ldap_chkResponseList ld 0x55dbdf8598a0 msgid 1 all 1
ldap_chkResponseList returns ld 0x55dbdf8598a0 NULL
ldap_int_select
read1msg: ld 0x55dbdf8598a0 msgid 1 all 1
read1msg: ld 0x55dbdf8598a0 msgid 1 message type extended-result
read1msg: ld 0x55dbdf8598a0 0 new referrals
read1msg:  mark request completed, ld 0x55dbdf8598a0 msgid 1
request done: ld 0x55dbdf8598a0 msgid 1
res_errno: 1, res_error: <00000000: LdapErr: DSID-0C090FF6, comment: TLS or SSL already in effect, data 0, v2580>, res_matched: <>
ldap_free_request (origid 1, msgid 1)
ldap_parse_extended_result
ldap_parse_result
ldap_msgfree
ldap_err2string
ldap_free_connection 1 1
ldap_send_unbind
ldap_free_connection: actually freed

openssl s_client -connect hostname:636 -CAfile /etc/ssl/certs/pwd.host.crt
CONNECTED(00000003)
....
depth=2 C = GB, ST = Greater Manchester, L = Salford, O = COMODO CA Limited, CN = COMODO RSA Certification Authority
verify return:1
depth=1 C = GB, ST = Greater Manchester, L = Salford, O = COMODO CA Limited, CN = COMODO RSA Organization Validation Secure Server CA
verify return:1
depth=0 C = BR, postalCode = 13091-904, ST = SAO PAULO, L = CAMPINAS, street = PREDIO 4 CJ 443/444 E PREDIO 3 CJ 342/343, street = AV SELMA PARADA 201, O = DAITAN LABS SOLUCOES EM TECNOLOGIA S/A, OU = Tecnologia da Informacao, OU = Hosted by Comodo Brasil Tecnologia Ltda, OU = PremiumSSL Wildcard, CN = *.daitan.com
verify return:1
---
Certificate chain
 0 s:/C=BR/postalCode=13091-904/ST=SAO PAULO/L=CAMPINAS/street=PREDIO 4 CJ 443/444 E PREDIO 3 CJ 342/343/street=AV SELMA PARADA 201/O=DAITAN LABS SOLUCOES EM TECNOLOGIA S/A/OU=Tecnologia da Informacao/OU=Hosted by Comodo Brasil Tecnologia Ltda/OU=PremiumSSL Wildcard/CN=*.daitan.com
   i:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Organization Validation Secure Server CA
 1 s:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Organization Validation Secure Server CA
   i:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Certification Authority
---
Server certificate
-----BEGIN CERTIFICATE-----
......
-----END CERTIFICATE-----
subject=/C=BR/postalCode=13091-904/ST=SAO PAULO/L=CAMPINAS/street=PREDIO 4 CJ 443/444 E PREDIO 3 CJ 342/343/street=AV SELMA PARADA 201/O=DAITAN LABS SOLUCOES EM TECNOLOGIA S/A/OU=Tecnologia da Informacao/OU=Hosted by Comodo Brasil Tecnologia Ltda/OU=PremiumSSL Wildcard/CN=*.daitan.com
issuer=/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Organization Validation Secure Server CA
---
No client certificate CA names sent
Client Certificate Types: RSA sign, DSA sign, ECDSA sign
Requested Signature Algorithms: RSA+SHA512:ECDSA+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA1:ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA1:DSA+SHA1
Shared Requested Signature Algorithms: RSA+SHA512:ECDSA+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA1:ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA1:DSA+SHA1
Peer signing digest: SHA1
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 4149 bytes and written 370 bytes
Verification: OK
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES256-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-SHA384
    Session-ID: F220000051F9474B697A8E5CC64F690192A84025BC36B92B88A28BF61FCB48A5
    Session-ID-ctx:
    Master-Key: 8595283267ADC7C1CCE351280ACF8683A5C5CFCE851AC88D4F867199B54DA851DAFB0D4247798E33700BCC2779AA4AE7
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1553355181
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: yes

Additionally, I going to send the SSP log application
....
[Sat Mar 23 15:39:00.394190 2019] [php7:notice] [pid 12182] [client 192.168.150.15:58044] LDAP - Unable to use StartTLS...

And the index.php page shows the message that can't access the LDAP directory.

Thanks again for the support and to answer my questions quickly.

**Comment by coudot** [comment]
Don't use startTLS and LDAPS at the same time.

Try to disable startTLS in your SSP configuration.

**Comment by dennisasilva** [comment]
Yes! It worked really well!

Thanks so much!
