### ISSUE TITLE
Multiple OU Change password with Self Service Password

### ISSUE THREAD

**Issue by AxtizFR** [ltb-project/self-service-password#282]
Hello,

I'm looking for changing the password for users in multiple OU.
Like :
dn: userid=User1,OU=OU1,dc=example,dc=com
dn: userid=User1,OU=OU2,dc=example,dc=com

i have tried same things like(in the config.inc.php)  : 
$ldap_base = ("ou=OU1,dc=z=example,dc=com" && "ou=OU2,dc=example,dc=com");

and tried :
$ldap_base = "ou=*,dc=z=example,dc=com" 
and : 
$ldap_base = "dc=example,dc=com" 

The thirst try set up de password only for OU1
The second doesn't work
the 3rd set up for the thirst matching OU and userid so OU1.

Can some one help me to find a solution ?

Regards,

**Comment by coudot** [comment]
Hello, you cannot set multiple bases.

If your LDAP directory is a standard LDAP directory like OpenLDAP, you have several solutions:
* Use extending matching filters in main LDAP filter:
```php
$ldap_filter = "(&(objectClass=person)($ldap_login_attribute={login})(|(ou:dn:=ou1)(ou:dn:=ou2)))";
```
* Use a technical account that only has rights on targeted branches

**Comment by AxtizFR** [comment]
Hi,
Thanks for the help ! 
I tried : 
$ldap_filter = "(&(objectClass=person)($ldap_login_attribute={login})(| (ou: dn: = Sales) (ou: dn: = Comm)))";
(Sales=OU1 and Comm=OU2)
but i have an error now to access to the directory

The user1 have the same uid in Sales and Comm, i need it in the two OU

**Comment by coudot** [comment]
You have extra spaces in your filter.

What is the LDAP directory?

**Comment by AxtizFR** [comment]
It's Openldap

**Comment by coudot** [comment]
So it should work if you remove spaces from the filter

**Comment by AxtizFR** [comment]
$ldap_filter = "(&(objectClass=person)($ldap_login_attribute={login})(|(ou:dn:=Sales)(ou:dn:=Comm)))";

It works for Sales but not for Comm,
thanks for your time

**Comment by AxtizFR** [comment]
I thought to make a script that automatically changes the password of the users1 in the OU COMM with that of the users1 in the OU Sales but it looks complicated

**Comment by coudot** [comment]
You can't update the password in 2 entries. There should not be several accounts for the same user.

If you really need it, try to create a posthook script: https://ltb-project.org/documentation/self-service-password/latest/config_posthook

**Comment by AxtizFR** [comment]
ok, i will try to do that, thanks !

**Comment by AxtizFR** [comment]
do you have an idea for the beginning of the script 😊

**Comment by AxtizFR** [comment]
I found a solution for my case, with your instructions :
script posthook : 

#!/bin/bash

LOGIN=$1
NEWPASSWORD=$2
OLDPASSWORD=$3

ldappasswd -H ldapi:/// -D "cn=managAccount,dc=example,dc=com" -w ManagementPW -a $OLDPASSWORD -s $NEWPASSWORD "uid=$LOGIN,ou=COMM,dc=example,dc=com"
echo `date` >> /tmp/posthook.log
echo "$LOGIN a un nouveau mot de passe >> /tmp/posthook.log
exho "" >> /tmp/posthook

Thanks a lot ! 
If someone need the solution, it works

Now I will try to make things more secure, have an idea to implement this command without having to enter the password management or another way to implement this strategy

**Comment by AxtizFR** [comment]
I close the issue thnks for the help @coudot

**Comment by coudot** [comment]
Thanks for the feedback!
