### ISSUE TITLE
Could you make a standard config step of AD self-passsword-service

### ISSUE THREAD

**Issue by Vincewan90** [ltb-project/self-service-password#283]
Dear Developer:
  Your product is great and useful, it can reduce a mount of time for IT operation people. But it's so hard to config the AD ssp by following the steps on ltb-project.org. and i also saw a lot of people ask the related problem about it too. So can you make a standard configuration step of AD ssp by anychance?  that would solved many peaple's problem and you don't need to answer so many config question.
  i still can't make the ssp work on my AD... i step by step follow your instruction on ltb-project.org 3 times...but still failure...

Unable to start TLS: Can't contact LDAP server in /usr/share/self-service-password/pages/sendsms.php on line 126, referer: http://10.3.2.220/index.php?action=sendsms

  i have no idea what to do, i am struggling on this for a month... can't find any other information about your ssp product in internet. i really hope someone who succeed upload the configuration to internet...if you can help me successfully setup. i will definitelly make this configration step...
  thank your for you watching

**Comment by cicob** [comment]
We use these settings successfully when connecting to AD:


`
$ldap_url = "ldap://name.of.ad.server";
$ldap_binddn = "cn=manager,dc=example,dc=com";
$ldap_bindpw = "xxxxxx";
$ldap_base = "dc=example,dc=com";
$ldap_login_attribute = "sAMAccountName";

$ldap_starttls = false;
$ldap_fullname_attribute = "cn";
$ldap_filter = "(&(objectClass=person)($ldap_login_attribute={login}))";

#####Active Directory mode
#####true: use unicodePwd as password field
#####false: LDAPv3 standard behavior
#####TODO: We have AD as TRUE by default
$ad_mode = true;

`

**Comment by Vincewan90** [comment]
@cicob Thank you for you reply
# LDAP
#$ldap_url = "ldaps://10.2.10.208:636";
$ldap_url = "ldap://10.2.10.208";
$ldap_starttls = false;
$ldap_binddn = "cn=administrator,dc=37,dc=com";
$ldap_bindpw = "********";
$ldap_base = "dc=37,dc=com";
#$ldap_login_attribute = "uid";
$ldap_login_attribute = "sAMAccountName";
$ldap_fullname_attribute = "cn";
$ldap_filter = "(&(objectClass=person)($ldap_login_attribute={login}))";
#$ldap_filter = "(&(objectClass=user)(sAMAccountName={login})(!(userAccountControl:1.2.840.113556.1.4.803:=2)))";

# Active Directory mode
# true: use unicodePwd as password field
# false: LDAPv3 standard behavior
$ad_mode = true;
i change the config as you told. but still error..

[Thu Apr 11 04:58:00.538502 2019] [php7:notice] [pid 12134] [client 10.5.10.18:30562] PHP Notice:  Undefined variable: obscure_failure_messages in /usr/share/self-service-password/pages/change.php on line 186, referer: http://10.3.2.220/index.php?action=sendsms
[Thu Apr 11 04:58:00.538573 2019] [php7:warn] [pid 12134] [client 10.5.10.18:30562] PHP Warning:  in_array() expects parameter 2 to be array, null given in /usr/share/self-service-password/pages/change.php on line 186, referer: http://10.3.2.220/index.php?action=sendsms
[Thu Apr 11 04:58:00.538601 2019] [php7:notice] [pid 12134] [client 10.5.10.18:30562] PHP Notice:  Undefined variable: display_posthook_error in /usr/share/self-service-password/pages/change.php on line 193, referer: http://10.3.2.220/index.php?action=sendsms
[Thu Apr 11 04:58:04.419782 2019] [php7:notice] [pid 12134] [client 10.5.10.18:30562] PHP Notice:  Undefined variable: obscure_failure_messages in /usr/share/self-service-password/pages/sendsms.php on line 318, referer: http://10.3.2.220/index.php
[Thu Apr 11 04:58:04.419844 2019] [php7:warn] [pid 12134] [client 10.5.10.18:30562] PHP Warning:  in_array() expects parameter 2 to be array, null given in /usr/share/self-service-password/pages/sendsms.php on line 318, referer: http://10.3.2.220/index.php
[Thu Apr 11 04:58:07.414058 2019] [php7:warn] [pid 12134] [client 10.5.10.18:30562] PHP Warning:  ldap_bind(): Unable to bind to server: Can't contact LDAP server in /usr/share/self-service-password/pages/sendsms.php on line 133, referer: http://10.3.2.220/index.php?action=sendsms
[Thu Apr 11 04:58:07.414164 2019] [php7:notice] [pid 12134] [client 10.5.10.18:30562] LDAP - Bind error -1  (Can't contact LDAP server), referer: http://10.3.2.220/index.php?action=sendsms
[Thu Apr 11 04:58:07.414181 2019] [php7:notice] [pid 12134] [client 10.5.10.18:30562] PHP Notice:  Undefined variable: obscure_failure_messages in /usr/share/self-service-password/pages/sendsms.php on line 318, referer: http://10.3.2.220/index.php?action=sendsms
[Thu Apr 11 04:58:07.414193 2019] [php7:warn] [pid 12134] [client 10.5.10.18:30562] PHP Warning:  in_array() expects parameter 2 to be array, null given in /usr/share/self-service-password/pages/sendsms.php on line 318, referer: http://10.3.2.220/index.php?action=sendsms
[Thu Apr 11 04:58:10.934473 2019] [php7:warn] [pid 12134] [client 10.5.10.18:30562] PHP Warning:  ldap_bind(): Unable to bind to server: Can't contact LDAP server in /usr/share/self-service-password/pages/sendsms.php on line 133, referer: http://10.3.2.220/index.php?action=sendsms
[Thu Apr 11 04:58:10.934525 2019] [php7:notice] [pid 12134] [client 10.5.10.18:30562] LDAP - Bind error -1  (Can't contact LDAP server), referer: http://10.3.2.220/index.php?action=sendsms
[Thu Apr 11 04:58:10.934542 2019] [php7:notice] [pid 12134] [client 10.5.10.18:30562] PHP Notice:  Undefined variable: obscure_failure_messages in /usr/share/self-service-password/pages/sendsms.php on line 318, referer: http://10.3.2.220/index.php?action=sendsms
[Thu Apr 11 04:58:10.934554 2019] [php7:warn] [pid 12134] [client 10.5.10.18:30562] PHP Warning:  in_array() expects parameter 2 to be array, null given in /usr/share/self-service-password/pages/sendsms.php on line 318, referer: http://10.3.2.220/index.php?action=sendsms

**Comment by coudot** [comment]
Error `LDAP - Bind error -1  (Can't contact LDAP server)` means your web server cannot contact your LDAP directory. Check firewall rules, SELinux, SSL configuration.
