### ISSUE TITLE
$messages['emptysendsmsform'] in fr.inc.php not display on SMS form

### ISSUE THREAD

**Issue by zargon19** [ltb-project/self-service-password#284]
Hi, i've just installed the LTB-SSP version 0.13 with lang="fr" and tips message in green is not display on index.php?action=sendsms page.
Thx.

**Comment by coudot** [comment]
Hello, I don't reproduce this issue.

Do you have some warnings in logs?

**Comment by zargon19** [comment]
I don't have logs.

[image: Mail-OK.jpg]

[image: SMS-PASOK.jpg]

Le dim. 14 avr. 2019 à 13:19, Clément OUDOT <notifications@github.com> a
écrit :

**Comment by zargon19** [comment]
i found a message on ssp_error after chenge debug = true; : [Mon Apr 15 23:37:37.253015 2019] [:error] [pid 784] [client 172.29.201.11:51765] PHP Notice:  Undefined index: crypttokensrequired in /usr/share/self-service-password/pages/sendsms.php on line 322, referer: http://172.29.0.158/index.php?action=sendsms

**Comment by zargon19** [comment]
sorry more logs:
[Mon Apr 15 23:41:27.925815 2019] [:error] [pid 785] [client 172.29.201.11:51770] PHP Notice:  Undefined variable: mail_smtp_secure in /usr/share/self-service-password/index.php on line 161, referer: http://172.29.0.158/index.php?action=sendsms
[Mon Apr 15 23:41:27.925987 2019] [:error] [pid 785] [client 172.29.201.11:51770] PHP Notice:  Undefined variable: mail_smtp_autotls in /usr/share/self-service-password/index.php on line 162, referer: http://172.29.0.158/index.php?action=sendsms
[Mon Apr 15 23:41:27.926124 2019] [:error] [pid 785] [client 172.29.201.11:51770] PHP Notice:  Undefined variable: obscure_failure_messages in /usr/share/self-service-password/pages/sendsms.php on line 318, referer: http://172.29.0.158/index.php?action=sendsms
[Mon Apr 15 23:41:27.926196 2019] [:error] [pid 785] [client 172.29.201.11:51770] PHP Warning:  in_array() expects parameter 2 to be array, null given in /usr/share/self-service-password/pages/sendsms.php on line 318, referer: http://172.29.0.158/index.php?action=sendsms
[Mon Apr 15 23:41:27.926315 2019] [:error] [pid 785] [client 172.29.201.11:51770] PHP Notice:  Undefined index: crypttokensrequired in /usr/share/self-service-password/pages/sendsms.php on line 322, referer: http://172.29.0.158/index.php?action=sendsms

**Comment by zargon19** [comment]
and my config.inc.php:
## SMS
# Use sms
$use_sms = true;
# SMS method (mail, api)
$sms_method = "api";
$sms_api_lib = "lib/smsapi.inc.php";
# GSM number attribute
$sms_attribute = "mobile";
# Partially hide number
$sms_partially_hide_number = true;
# Send SMS mail to address
$smsmailto = "{sms_attribute}@service.provider.com";
# Subject when sending email to SMTP to SMS provider
$smsmail_subject = "Provider code";
# Message
$sms_message = "{smsresetmessage} {smstoken}";
# Remove non digit characters from GSM number
$sms_sanitize_number = false;
# Truncate GSM number
$sms_truncate_number = false;
$sms_truncate_number_length = 10;
# SMS token length
$sms_token_length = 6;
# Max attempts allowed for SMS token
$max_attempts = 3;

**Comment by zargon19** [comment]
IT WORKS!!!

**Comment by coudot** [comment]
What was the issue?
