### ISSUE TITLE
Reset by Mail - cariage return before mail signature is missing

### ISSUE THREAD

**Issue by zargon19** [ltb-project/self-service-password#285]
Hi, could you add a cariage return before mail_signature on body of the mail send to user.  Ths.

**Comment by coudot** [comment]
Hello,

seems you can do it easily by setting it in the signature configuration:
```php
$mail_signature = "\nMy signature message";
```

Does it work for you?

**Comment by zargon19** [comment]
Yes, thx.

Le dim. 14 avr. 2019 à 13:22, Clément OUDOT <notifications@github.com> a
écrit :
