### ISSUE TITLE
could someone help me with smsapi.inc.php for ORANGE

### ISSUE THREAD

**Issue by zargon19** [ltb-project/self-service-password#286]
Hi , is there someone who can help me to write smsapi.inc.php for ORANGE... this is there website : https://contact-everyone.orange-business.com/api/docs/guides/#changements-depuis-la-v1-1

Thx for your answer.

**Comment by coudot** [comment]
You should read https://orange.developpez.com/tutoriels/api-sms/envoyer-sms/

**Comment by zargon19** [comment]
merci beaucoup! je vais essayer ça demain.

Le dim. 14 avr. 2019 à 18:51, Clément OUDOT <notifications@github.com> a
écrit :

**Comment by zargon19** [comment]
IT WORKS!!!!

**Comment by coudot** [comment]
Hello,

could you share you code? We could add it to this page: https://ltb-project.org/documentation/self-service-password/latest/sms_api
