### ISSUE TITLE
Strange behavior on the start page

### ISSUE THREAD

**Issue by schwejkj** [ltb-project/self-service-password#287]
I just installed the package. Now I m unable to reach the start page... 
PHP seems to be ok. 
It looks like that:
```
all languages are allowed if ($entry_lang == $lang || empty($allowed_lang) || in_array($entry_lang, $allowed_lang) ) { array_push($languages, $entry_lang); } } } closedir($handle); } $lang = detectLanguage($lang, $languages); require_once("lang/$lang.inc.php"); if (file_exists("conf/$lang.inc.php")) { require_once("conf/$lang.inc.php"); } #============================================================================== # PHP modules ....
```
Thanks for your help.

**Comment by coudot** [comment]
I would say PHP is not activated for the SSP vhost

**Comment by schwejkj** [comment]
Thx for your reply. It s a fresh setup. Is it really disabled by default on apache2?

**Comment by coudot** [comment]
How did you install the software?

**Comment by schwejkj** [comment]
From Debian-Package as mentioned on the project page.

**Comment by coudot** [comment]
Try 
```
a2enmod php7.2
```

You may adapt php version to the version installed on your server.

**Comment by schwejkj** [comment]
Thx. He replied that (browser behavior is still the same):


Considering dependency mpm_prefork for php7.2:
Considering conflict mpm_event for mpm_prefork:
Considering conflict mpm_worker for mpm_prefork:
Module mpm_prefork already enabled
Considering conflict php5 for php7.2:
Module php7.2 already enabled

**Comment by coudot** [comment]
Try to create a php file like this:
```php
<?php phpinfo(); ?>
```
Until you can't display it trough Apache, it means PHP is not configured. Try to fix this first.

**Comment by schwejkj** [comment]
That works fine in the same folder.

**Comment by coudot** [comment]
In this case, check rights on file index.php and also apache error logs

**Comment by schwejkj** [comment]
The index.php and my phpinfo file have the same permissions. Also the apache2 error logs don't show anything interesting.

**Comment by coudot** [comment]
Check that index.php file begins with `<?php`

**Comment by plewin** [comment]
Hi @schwejkj, did you manage to solve your issue ?
