### ISSUE TITLE
Page to set mail for use by "reset by token" feature

### ISSUE THREAD

**Issue by mohaja** [ltb-project/self-service-password#288]
I would like to request a page where user can set/change email address for use later in 'reset by token' page. Interface will be much like the change password with extra field for email address, and captha to prevent spamming. Anyway, great app and very useful in my school. Thanks

**Comment by coudot** [comment]
Hello,

we will see how to do it.

For the moment, we prefer to use FusionDirectory (https://www.fusiondirectory.org/) to let users change their informations.
