### ISSUE TITLE
Issue installing openldap-ltb

### ISSUE THREAD

**Issue by zach3821** [ltb-project/self-service-password#289]
When go to install openldap-ltb after following the instructions here, https://ltb-project.org/documentation/openldap-deb#apt_repository , I get this output: 

Setting up openldap-ltb (2.4.47.1) ...
addgroup: The group 'ldap' already exists as a system group. Exiting.
adduser: The user 'ldap' already exists, but is not a system user. Exiting.
dpkg: error processing package openldap-ltb (--configure):
 installed openldap-ltb package post-installation script subprocess returned error exit status 1
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Errors were encountered while processing:
 openldap-ltb
E: Sub-process /usr/bin/dpkg returned an error code (1)

I tried this on the server I am trying to set this up on as well as a fresh server and got the same issue. On Ubuntu Buster. I see that the errors involve the user/group ldap, but I have no idea why this is causing and issue. Thank you for you help.

**Comment by coudot** [comment]
Hello, you are on the wrong tracker. Please open your issue here: https://github.com/ltb-project/openldap-deb/issues
