### ISSUE TITLE
Password Management: Error when sending confirmation email

### ISSUE THREAD

**Issue by knut1er** [ltb-project/self-service-password#290]
I'm trying to use password renewal form, and mail confirmation feature.
Renewal form works fine.
When trying mail confirmation, there is "Error when sending confirmation email".

I set debug value to "true" in php config file.

I don't see logs for apache, or messages.
How can I find the source of error?

Thanks

**Comment by coudot** [comment]
You can change debug of mail function with:
```php
$mail_smtp_debug = 1;
```

**Comment by coudot** [comment]
See also : https://ltb-project.org/documentation/self-service-password/latest/config_mail

**Comment by knut1er** [comment]
I did not see the debugging option. The problem was due to TLS negotiation.
Now it works fine.
Merci Clément

**Comment by coudot** [comment]
Thanks for the feedback
