### ISSUE TITLE
SSP with AD on Server 2016

### ISSUE THREAD

**Issue by rguy2001** [ltb-project/self-service-password#291]
### Has anyone gotten this to work with Centos7, WinServer 2016 AD?

I keep getting Cannot access LDAP directory.

here is my configuration:
```php
# LDAP
#$ldap_url ="ldap://172.17.1.103:389";
$ldap_url = "ldaps://hostaddress:389";
$ldap_starttls = false;
$ldap_binddn = "cn=sspd,cn=Service Accounts,dc=pelotontx,dc=com";
$ldap_bindpw = "restricted";
$ldap_base = "dc=business,dc=com";
$ldap_login_attribute = "sAMAccountName";
$ldap_fullname_attribute = "cn";
#$ldap_filter = "(&(objectClass=user)(sAMAaccountName={login}($ldap_login_attribute={login}))";
$ldap_filter = "(&(objectClass=user)(sAMAccountName={login})(!(userAccountControl:1.2.840.113556.1.4.803:=2)))";


# Active Directory mode
# true: use unicodePwd as password field
# false: LDAPv3 standard behavior
$ad_mode = true;
# Force account unlock when password is changed
$ad_options['force_unlock'] = true;
# Force user change password at next login
$ad_options['force_pwd_change'] = true;
# Allow user with expired password to change password
$ad_options['change_expired_password'] = true;
```

I've tried both ldap and ldaps same issue.

using certification generated on win server 2016 certificate authority. Exported cert is DER x509 in *.cer format which was winscp to Centos /etc/ssl/certs/*.cer path

I was told I'm not required to install open ldap or any other pkgs for this to work. I'm trying to hook into AD using this but not getting anywhere. What am I missing here?

**Comment by coudot** [comment]
Did you followhttps://ltb-project.org/documentation/self-service-password/latest/config_ldap?

You can try to set `TLS_REQCERT allow` or adapt TLS version `TLS_CIPHER_SUITE TLSv1+RSA`

**Comment by rguy2001** [comment]
I've gotten this far and I know its able to contact AD but when attemting to reset it shows: 

Password was refused by the LDAP directory

Here is the log: 

[Thu Apr 25 08:12:13.638000 2019] [:error] [pid 12533] [client 172.17.2.201:56550] PHP Notice:  Undefined variable: display_posthook_error in /usr/share/self-service-password/pages/change.php on line 193, referer: http://172.17.2.140/
[Thu Apr 25 08:12:23.968705 2019] [:error] [pid 12536] [client 172.17.2.201:56689] PHP Warning:  ldap_mod_replace(): Modify: Insufficient access in /usr/share/self-service-password/lib/functions.inc.php on line 399, referer: http://172.17.2.140/
[Thu Apr 25 08:12:23.968755 2019] [:error] [pid 12536] [client 172.17.2.201:56689] LDAP - Modify password error 50 (Insufficient access), referer: http://172.17.2.140/
[Thu Apr 25 08:12:23.968767 2019] [:error] [pid 12536] [client 172.17.2.201:56689] PHP Notice:  Undefined variable: obscure_failure_messages in /usr/share/self-service-password/pages/change.php on line 186, referer: http://172.17.2.140/
[Thu Apr 25 08:12:23.968778 2019] [:error] [pid 12536] [client 172.17.2.201:56689] PHP Warning:  in_array() expects parameter 2 to be array

**Comment by rguy2001** [comment]
password error 50 insufficient access < guessing this is referencing the service account which I delegated to have reset password control. 

Unsure why this would be the case since I have set the proper permissions in the AD.

**Comment by coudot** [comment]
There is no other explanation: the password is refused by the Directory, the account has not enough rights to change it.

**Comment by rguy2001** [comment]
TLS_REQCERT allow

this did the trick for me

thanks

**Comment by ocoranes** [comment]
Hi guy2001, 
Have you installed open ldap or just hook into AD? 
Thanks!
