### ISSUE TITLE
Setup permissions best practices

### ISSUE THREAD

**Issue by AxtizFR** [ltb-project/self-service-password#292]
Hello,
I am trying to configure the permissions on two "sensitive" files because the LDAP admin passwords are in clear inside.
2 files preoccupy me: posthook.sh and config.inc.php
it may be basic as a question, but I am not a specialist in the security of websites.
Can you help me?
Knowing that posthook.sh is a script and I wonder what are the minimum permissions so that it can be started.
Best regards,
Axtiz

**Comment by coudot** [comment]
The config file must be readable by apache user, the posthook script must be executable by apache user

**Comment by JuJuMDX** [comment]
Answered by @coudot
