### ISSUE TITLE
ltb users mailing list bouncing messages

### ISSUE THREAD

**Issue by scylla999** [ltb-project/self-service-password#294]
Hello,
I tried sending a question via this mailing list:  ltb-users@mail.ltb-project.org
The message bounced back with this error:
    **********************************************
    **      THIS IS A WARNING MESSAGE ONLY      **
    **  YOU DO NOT NEED TO RESEND YOUR MESSAGE  **
    **********************************************

The original message was received at Wed, 1 May 2019 16:55:35 -0400
from aeneas.dgi.polymtl.ca [132.207.169.10]

   ----- Transcript of session follows -----
... while talking to mail.ltb-project.org.:
>>> DATA
<<< 454 4.7.1 <ltb-users@mail.ltb-project.org>: Relay access denied
<ltb-users@lists.ltb-project.org>... Deferred: 454 4.7.1 <ltb-users@mail.ltb-project.org>: Relay access denied
<<< 554 5.5.1 Error: no valid recipients
Warning: message still undelivered after 8 hours
Will keep trying until message is 2 days old

Reporting-MTA: dns; smtp.polymtl.ca
Arrival-Date: Wed, 1 May 2019 16:55:35 -0400

Final-Recipient: RFC822; ltb-users@mail.ltb-project.org
Action: delayed
Status: 4.7.1
Remote-MTA: DNS; mail.ltb-project.org
Diagnostic-Code: SMTP; 454 4.7.1 <ltb-users@mail.ltb-project.org>: Relay access denied
Last-Attempt-Date: Thu, 2 May 2019 00:59:53 -0400

Thank You!

**Comment by coudot** [comment]
Where did you get this address? The good one is ltb-users@lists.ltb-project.org

See https://lists.ltb-project.org/cgi-bin/mailman/listinfo/ltb-users

**Comment by scylla999** [comment]
That's the address I used.   The one I posted in the above message is the denied relay.
Here's the original message source:

############### Begin Message ###################
To: ltb-users@lists.ltb-project.org
From: Luc Lalonde <Luc.Lalonde@polymtl.ca>
Subject: posthook script not executed
Openpgp: preference=signencrypt
Autocrypt: addr=Luc.Lalonde@polymtl.ca; keydata=
 mQINBFvzDeQBEADLhLwuggbCmtk6cvf5O2yBJOdFKc6uSPwb/WBl9PKBz+SeuwfiySc3i/UA
 5DCsO9/NDyXgrHU1VcGFqutZ/FGoSxaHZl1RtVclXecDRuOezHTtrllazHbEKEgYDE+sEY0h
 TaR/tf0/QWT5Y7abstQxnOCY6EFahBa8yrLKWjQX3Mriz2Cb8xpJb/edceBV6zxxmFWhqI3R
 gIx3uqYU5EDUBxQA48M91VlVcswJE2orL9Yd1eZ+FI1mzsNH74byibJX/u/jlI1kOo0dg7J/
 mICxl5vFrRT9NvVayxe3ArDGeaLz/My6DY9m+nm/Zw5QtuR1lVZr3eliaocqrAW/R6SsXIUg
 lnMs4feET8ijqN795t3M3Sgiq+cwO1cR9/Kz7n13yyDc7MdfeiIyTuJ7UAaTDr1xjZ2BGG9T
 Py+3W0RpNk8pK3mFVphttXW6FbAq25AOq6oT9BzE58q0HkGqY9uOuEQbaSv+pDnyyH0ATuQY
 c3ookj5o6d9iXMvDiuKFR7PpFD+hcdAeUsxYz8UQKI8n2Cgvkv4mzKMwZ9D6xmQErJCWPvv+
 zD1fBHWiKizImOaWQFKlgb0NixBABnsBQ30k+hVk4dzjI4NUFQ5to+La/ioezh9HlXVbj99M
 xLlLmA8iqhckQOBrAFsSKbvGz26cViuepNqgK7xw+OLBxxzfcwARAQABtFNMdWMgTGFsb25k
 ZSwgw4ljb2xlIFBvbHl0ZWNobmlxdWUgZGUgTW9udHJlYWwsIGRlcHQuICBHSUdMIDxMdWMu
 TGFsb25kZUBwb2x5bXRsLmNhPokCVAQTAQgAPhYhBNPDSuj+e+C9I+CTaNZXH6EdsNXrBQJb
 +E9AAhsjBQkJZzEsBQsJCAcCBhUKCQgLAgQWAgMBAh4BAheAAAoJENZXH6EdsNXrGQQP/0HQ
 gdlJR7Qe5033kOsVkyM8KJJo+Cwoi8nHqbEWsEMP+rwJOuiN7hJ+PGfZUE/74tMvdfy4ksvl
 7FWwLcqQnD6TmR5yGb6POxrt8TLhw25vKfenvk93Wo2m1lFEEgCmMKbh7B/ifH7G90LX+OUG
 HxifnnwtxQDiUQrGYCgBn+13o9MWNlhdsqIv3P/LzAO+fSrkaGJKCTrFXMG+Q2Fjc1cDxaD5
 ALDQp4wQ6eSJJDJrVhgBxoW2nbADZROpN/v2hFjylINL7b8xGDpTr9sveqkk9Kcj6qOzVHcS
 9/tLw41SriA47wjKsDcg5XxAzpdc0dPN3it3eObREG3VxcOL7EC3Rl0q6RFaiJz4XzhRjgv2
 9dRjAsvE3kaLv0VSadqF0ICnbHZwsS6wtQLhwbPS02yNXOuMw4YYAUehxEFsY4Ye/iZAEqON
 jhqgp6lD/PRo8H1x0Pd5CSmLx9IRIhRUPKjbRCW7GJL+r3uQAdkXXk6dV30Y1wKezeRWMMqs
 Kiy6RW8kFrWkBRsogZVwC3HFCumROuagPO92EqXFCUjb+xB/b3D+eW3KS3I3yu/rNf5g0YVM
 szV1uRDte3N452M7A3nXbsID++c/ovyfm83zVqdY2QDSJ2zvu20L/eJIXnAzgkqD8px5ZvjD
 RXYvd3Fmnn+CK82NE88xecAEQ/nPvaluuQINBFvzDeQBEACvVYwbdnw7OQwfI9i0qeOo2O3N
 eSjzz6XHLUMecjawnuLSmeneeul2VE1QgjtjryO29Cv49VJ+sajnBTOOrxQ0+HQeGNmkp+pj
 7QKJpQQuojx26MHM0AFDA/6rCuVMC8an2mdldsgKM/+L7z0mCyuAFuIQrLcK5NJuSRGHjbBD
 J8u8E7Dl5pwdTa4pR9mmDqGd7XxPiIYCjJTORZu58n9IQSsr3jKCOe7gbqSQrPFA9cly2qd+
 hMO7XsWyzqbO41kyqCC7j60o41dp69Q3xAcUfaqyMw/ZJNqX5V9fSEv8OMXRuqJThkas8Z8b
 WejF11BtCPBYwIHW2VZvn7SdzZlSCIYUx8+hBmk9Vncmfnz+gO9+oviK/lkp7ymKj64H/1EE
 T1zm5/Q77WefcgOHaLpkaTwpv89cF4kpo7GDavQU8CWGhxqLrcnOhx6GJerv0Ir9lsoeinSK
 YSDzAcLmUFlrf6dDiFUIjRkLKC9bkLHiyUW5jhEiA5mpC2jKNg+w6KMIJstingy2syXFoADE
 6IK6Ve0U3+NNRLbRX3OvgbcMUHvaJuqTMgnxxmqJe8HwWc3Xf7CnINHe4Z0XOzW/hx9VJcdt
 nUHxCrDiGPbdbqS05jwqht/o1JYAv24fFj4dbcfu3cguYOzrnlh3/sje5DVWHGIasC2z1pUe
 8HbNKPOhoQARAQABiQI2BBgBCAAgFiEE08NK6P574L0j4JNo1lcfoR2w1esFAlvzDeQCGwwA
 CgkQ1lcfoR2w1esMtw/+OsVnQzWAMVCY1qtBuaDkvu1fKBwausowXDXbutHsRwZ1ul3fjjZE
 rcgveXTsRIKykKD059kuzeKtxAPMHUskYqpFXaWL/ZtTH83Grv98h6C102TE4J5g68kDc+ug
 aeHtyCMuCzEuR5MW6BcVCZIhWqxVA5GXHcX34TztVvXn5+IL9BAD1cO3QXTft/JamY0gJSdN
 eVKcXk1kEcSD9Ylv48N5sZ9JouNbsZ85cgqVwv35O6f9Ek7kqbmhyFLfCzy1B5J/4n9Pq/5f
 GHLTXrdyAcE1ClXaUrJVr1ytsbLczScqdVH/XOiOcHMcivg98BgqWh2mu9plNnFOJSXKtc1N
 t70RYnpSK2Yj+zpownEbEWXZKoFxMrGjSdaWGc0g62BfIYZYJYQpYSxiaH4zLf1wfkMGe4cW
 +35F8g1au+CPMx4h8A/uSXjBULqAhRc/tlI3EheII1oNsr3dPCCbffXjwcSls9pCD6/Ywhfd
 TA0cXqBTZ9EZvcGJHLAiy3vHLyhAZBtPhsU82ZCmu1pqou0gGh+TPcQWejULGIJlBWeu0gsr
 cXpZZtkv+7l+HPY58Ocf1hbC4E5iV+K36MgF+Eoq3DS4ctgh1eykq7N600PmF6f+agFJr8Kr
 4yQPGJvMVJjVqbgrmj7+Fnwt7Ki/2H1AxE77z/KJWFHXN7/fEeVStpo=
Message-ID: <4b18c289-531e-4653-dda3-fc71512f83bb@polymtl.ca>
Date: Wed, 1 May 2019 16:55:33 -0400
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101
 Thunderbird/60.6.1
MIME-Version: 1.0
Content-Type: multipart/signed; micalg=pgp-sha256;
 protocol="application/pgp-signature";
 boundary="boeH76c0dWJyCLiNlTw24JtzIAmkM8WPU"

This is an OpenPGP/MIME signed message (RFC 4880 and 3156)
--boeH76c0dWJyCLiNlTw24JtzIAmkM8WPU
Content-Type: multipart/mixed; boundary="8FQxZqV5u97zIQkNH6sPx8ZAVDt9vfPpO";
 protected-headers="v1"
From: Luc Lalonde <Luc.Lalonde@polymtl.ca>
To: ltb-users@lists.ltb-project.org
Message-ID: <4b18c289-531e-4653-dda3-fc71512f83bb@polymtl.ca>
Subject: posthook script not executed

--8FQxZqV5u97zIQkNH6sPx8ZAVDt9vfPpO
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable
Content-Language: en-US

Hello Folks,

I'm trying to get a script to execute with each password change...=C2=A0
However, I can't seem to get it to work.

It doesn't seem to be executed.=C2=A0=C2=A0 Are there special configurati=
on in the
PHP.INI?

I've made sure that the script is owned by the Apache user and that he
has permission to execute the script (Perl).

Here are snippets of errors in the logs:

PHP Notice:=C2=A0 Undefined variable: posthook_return...

PHP Notice:=C2=A0 Undefined offset: 0 ...

Any ideas?

Thank You!

--=20
Luc Lalonde, analyste
-----------------------------
D=C3=A9partement de g=C3=A9nie informatique:
=C3=89cole polytechnique de MTL
(514) 340-4711 x5049
Luc.Lalonde@polymtl.ca
-----------------------------



--8FQxZqV5u97zIQkNH6sPx8ZAVDt9vfPpO--

--boeH76c0dWJyCLiNlTw24JtzIAmkM8WPU
Content-Type: application/pgp-signature; name="signature.asc"
Content-Description: OpenPGP digital signature
Content-Disposition: attachment; filename="signature.asc"

-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEE08NK6P574L0j4JNo1lcfoR2w1esFAlzKB8YACgkQ1lcfoR2w
1evakBAAoghlDKPOe+FK9LoIsC2u9tlAPFkBO2WjMW6iIVzwnrOtJhyq2jvd4yry
9/b0rROFAEU2IcJa+ON3hQOetmNVNETr2cawO3OxsEagXX4jk5f3Y3PIjN6UwarT
QpqdfB1EIxYv5Sh4ESkWsS1p+z+/xlmf4rsbIOpxQMIrhDjyl5Xa5o5BsQlgKXVr
emDBuII64HIklFepW//1ukCvuwepouSlalv23u7iAuwC3LjjLYAwfeYMQZICQD4y
xiBdp2TFzWDbYN3x7VZjzn2/4WHNeeKqjJrvRxTo7zJrKB65mx01lFygGTdbL4OC
lXc+nerIuahev7ppOPtXqgXmqF+3zmfneczazsUJD9Z6dncrSWTaCQyixLsCLvcR
6FCVS4VuYqlj+Yo/ZTHULKPD5+/yyAi8pg8F9S2ZSbdicyy8T5VFA57MN7+oDUXX
Jx6xjaSgQU8Igl+SMaVTu16SmGczOeScnla7IFizMYmSo++mHh4vi5aYWoo4cFNF
thsENBwExl7x81NAqo8LW3+UZTOT1GVLJ5sCzM//flhDONPJusnNyPedbffFzJKa
9XB4icQKi5ftsIqGwMe9I+Htw0pva1KII6jdNsXknjPkl88Q7TKZ5Zmfb+ppMthL
vy2rzAIZq8sLAmgNSF4DVyX2NopoM6LI58ULvjP27EVfDubnJe0=
=f2qN
-----END PGP SIGNATURE-----

--boeH76c0dWJyCLiNlTw24JtzIAmkM8WPU--
############### End Message ###################

**Comment by coudot** [comment]
Here are some logs on the SMTP server:
```
/var/log/mail.info:May  1 22:47:57 sd-101135 postfix/smtp[12145]: 59027A0B50: to=<Luc.Lalonde@polymtl.ca>, relay=smtp.polymtl.ca[132.207.4.11]:25, delay=8, delays=0.02
/0.01/6/2, dsn=2.0.0, status=sent (250 2.0.0 x41KlouD027974 Message accepted for delivery)
/var/log/mail.info:May  1 22:50:16 sd-101135 postfix/smtp[12350]: 880FEA0B50: to=<Luc.Lalonde@polymtl.ca>, relay=smtp.polymtl.ca[132.207.4.11]:25, delay=7.5, delays=0.
01/0.01/5.7/1.8, dsn=2.0.0, status=sent (250 2.0.0 x41Ko9ED029113 Message accepted for delivery)
/var/log/mail.info:May  1 22:55:38 sd-101135 postfix/smtpd[12347]: NOQUEUE: reject: RCPT from smtp.polymtl.ca[132.207.4.11]: 454 4.7.1 <ltb-users@mail.ltb-project.org>
: Relay access denied; from=<Luc.Lalonde@polymtl.ca> to=<ltb-users@mail.ltb-project.org> proto=ESMTP helo=<smtp.polymtl.ca>
```

Your subscription was accepted but the mail seems to have been sent on ltb-users@mail.ltb-project.org

Anyway, I saw you solved your issue in #295

**Comment by coudot** [comment]
Hello, a fix was done in the DNS configuration, the list should work better now.

**Comment by scylla999** [comment]
It would be good to remove the ‘invalid’ label to this bug… since it was a real bug.

Thanks for fixing it!

Luc Lalonde, analyste
-----------------------------
Département de génie informatique et génie logiciel:
École polytechnique de MTL
(514) 340-4711 x5049
Luc.Lalonde@polymtl.ca
-----------------------------

**Comment by coudot** [comment]
In fact this is not an issue on the software itself. I move it to `question`
