### ISSUE TITLE
Self Service Password Unable to access LDAP server(AD 2008R2)

### ISSUE THREAD

**Issue by lxjmac** [ltb-project/self-service-password#297]
Install Self Service Password on centos7  PHP 5.6.13  Apache/2.4.29

Website comes up. Attempts to change AD (2008 R2) password via web-form or via email does not work.(Web page hints that Unable to access LDAP server), Documentation appears surprisingly disjointed. Extended research on open and closed issues has not solved it.

LDAP pertinent portion of config.inc.php below:
```php
$debug = true;

# LDAP
$ldap_url = "ldaps://172.16.8.5:636";
$ldap_starttls = false;
$ldap_binddn = "cn=sheldon.li,cn=LT,dc=goodjob,dc=com";
$ldap_bindpw = "password";
$ldap_base = "dc=goodjob,dc=com";
$ldap_login_attribute = "sAMAccountName";
$ldap_fullname_attribute = "cn";
$ldap_filter = "(&(objectClass=user)(sAMAccountName={login})(!(userAccountControl:1.2.840.113556.1.4.803:=2)))";

# Active Directory mode
# true: use unicodePwd as password field
# false: LDAPv3 standard behavior
$ad_mode = true;
# Force account unlock when password is changed
$ad_options['force_unlock'] = true;
# Force user change password at next login
$ad_options['force_pwd_change'] = false;
# Allow user with expired password to change password
```
```
[root@ssp ~]# tail -f /usr/local/apache2/logs/error_log

Tue May 14 17:50:23.947369 2019] [:error] [pid 94475:tid 139808038946560] [client 10.1.19.88:50432] PHP Notice:  Undefined variable: obscure_failure_messages in /usr/local/apache2/htdocs/ssp/pages/change.php on line 186
[Tue May 14 17:50:23.947439 2019] [:error] [pid 94475:tid 139808038946560] [client 10.1.19.88:50432] PHP Warning:  in_array() expects parameter 2 to be array, null given in /usr/local/apache2/htdocs/ssp/pages/change.php on line 186
[Tue May 14 17:50:23.947539 2019] [:error] [pid 94475:tid 139808038946560] [client 10.1.19.88:50432] PHP Notice:  Undefined variable: display_posthook_error in /usr/local/apache2/htdocs/ssp/pages/change.php on line 193
ldap_create
ldap_url_parse_ext(ldaps://172.16.8.5:636)
ldap_sasl_bind_s
ldap_sasl_bind
ldap_send_initial_request
ldap_new_connection 1 1 0
ldap_int_open_connection
ldap_connect_to_host: TCP 172.16.8.5:636
ldap_new_socket: 17
ldap_prepare_socket: 17
ldap_connect_to_host: Trying 172.16.8.5:636
ldap_pvt_connect: fd: 17 tm: -1 async: 0
attempting to connect: 
connect success
TLS trace: SSL_connect:before/connect initialization
TLS trace: SSL_connect:SSLv2/v3 write client hello A
TLS trace: SSL_connect:SSLv3 read server hello A
TLS certificate verification: depth: 0, err: 20, subject: , issuer: /DC=com/DC=goodjob.com/CN=Shenzhen Netcom CA
TLS certificate verification: Error, unable to get local issuer certificate
TLS trace: SSL3 alert write:fatal:unknown CA
TLS trace: SSL_connect:error in error
TLS trace: SSL_connect:error in error
TLS: can't connect: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed (unable to get local issuer certificate).
ldap_err2string
[Tue May 14 17:50:34.406657 2019] [:error] [pid 94475:tid 139808022161152] [client 10.1.19.88:50433] PHP Warning:  ldap_bind(): Unable to bind to server: Can't contact LDAP server in /usr/local/apache2/htdocs/ssp/pages/change.php on line 80, referer: https://ssp.goodjob.com/
ldap_err2string
[Tue May 14 17:50:34.406707 2019] [:error] [pid 94475:tid 139808022161152] [client 10.1.19.88:50433] LDAP - Bind error -1  (Can't contact LDAP server), referer: https://ssp.goodjob.com/
[Tue May 14 17:50:34.406721 2019] [:error] [pid 94475:tid 139808022161152] [client 10.1.19.88:50433] PHP Notice:  Undefined variable: obscure_failure_messages in /usr/local/apache2/htdocs/ssp/pages/change.php on line 186, referer: https://ssp.goodjob.com/
[Tue May 14 17:50:34.406763 2019] [:error] [pid 94475:tid 139808022161152] [client 10.1.19.88:50433] PHP Warning:  in_array() expects parameter 2 to be array, null given in /usr/local/apache2/htdocs/ssp/pages/change.php on line 186, referer: https://ssp.goodjob.com/
[Tue May 14 17:50:34.406838 2019] [:error] [pid 94475:tid 139808022161152] [client 10.1.19.88:50433] PHP Notice:  Undefined variable: display_posthook_error in /usr/local/apache2/htdocs/ssp/pages/change.php on line 193, referer: https://ssp.goodjob.com/
```

**Comment by coudot** [comment]
Error seems clear:
```
TLS: can't connect: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed (unable to get local issuer certificate).
```

Configure CA certificate or use`TLS_REQCERT never`

**Comment by lxjmac** [comment]
I have no idea what to do, I am struggling on this for a month..pls help me
![123](https://user-images.githubusercontent.com/50618576/57753421-b1f72880-771e-11e9-8660-877530ca2ad2.png)

**Comment by lxjmac** [comment]
Can someone help me?

**Comment by coudot** [comment]
You use `TLS_CACERTDIR` with a file..

From `man ldap.conf`:
```
       TLS_CACERT <filename>
              Specifies the file that contains certificates for all of the Certificate Authorities the client will recognize.

       TLS_CACERTDIR <path>
              Specifies  the  path  of  a  directory  that contains Certificate Authority certificates in separate individual files. The TLS_CACERT is always used
              before TLS_CACERTDIR.  This parameter is ignored with GnuTLS. On Debian openldap is linked against GnuTLS.

              When using Mozilla NSS, <path> may contain a Mozilla NSS cert/key database.  If <path> contains a Mozilla NSS cert/key database and CA  cert  files,
              OpenLDAP will use the cert/key database and will ignore the CA cert files.
```

**Comment by lxjmac** [comment]
@coudot  Thank you for your response，Now I'm going to solve the problem of not being able to connect to LDAP server(AD 2008R2), The following is the error 
[root@localhost ~]# tail -f /var/log/httpd/error_log

ldap_err2string
[Fri May 17 14:53:35 2019] [error] [client 10.1.19.88] LDAP - Bind error 49  (Invalid credentials), referer: http://172.16.9.171/
ldap_free_connection 1 1
ldap_send_unbind
ldap_free_connection: actually freed
ldap_create
ldap_url_parse_ext(ldap://172.16.8.4:389)
ldap_sasl_bind_s
ldap_sasl_bind
ldap_send_initial_request
ldap_new_connection 1 1 0
ldap_int_open_connection
ldap_connect_to_host: TCP 172.16.8.4:389
ldap_new_socket: 13
ldap_prepare_socket: 13
ldap_connect_to_host: Trying 172.16.8.4:389
ldap_pvt_connect: fd: 13 tm: -1 async: 0
attempting to connect:
connect success
ldap_open_defconn: successful
ldap_send_server_request
ldap_result ld 0x7ff01f95c080 msgid 1
wait4msg ld 0x7ff01f95c080 msgid 1 (infinite timeout)
wait4msg continue ld 0x7ff01f95c080 msgid 1 all 1
  refcnt: 2  status: Connected
  last used: Fri May 17 14:55:24 2019
** ld 0x7ff01f95c080 Response Queue:
   Empty
  ld 0x7ff01f95c080 response count 0
ldap_chkResponseList ld 0x7ff01f95c080 msgid 1 all 1
ldap_chkResponseList returns ld 0x7ff01f95c080 NULL
ldap_int_select
read1msg: ld 0x7ff01f95c080 msgid 1 all 1
read1msg: ld 0x7ff01f95c080 msgid 1 message type bind
read1msg: ld 0x7ff01f95c080 0 new referrals
read1msg:  mark request completed, ld 0x7ff01f95c080 msgid 1
request done: ld 0x7ff01f95c080 msgid 1
res_errno: 49, res_error: <80090308: LdapErr: DSID-0C0903A8, comment: AcceptSecurityContext error, data 52e, v1db1>, res_matched: <>
ldap_free_request (origid 1, msgid 1)
ldap_parse_result
ldap_msgfree
ldap_err2string
[Fri May 17 14:55:24 2019] [error] [client 10.1.19.88] PHP Warning:  ldap_bind(): Unable to bind to server: Invalid credentials in /var/www/html/ltb-project-self-service-password-1.3/pages/change.php on line 80, referer: http://172.16.9.171/
ldap_err2string
[Fri May 17 14:55:24 2019] [error] [client 10.1.19.88] LDAP - Bind error 49  (Invalid credentials), referer: http://172.16.9.171/
[Fri May 17 14:55:24 2019] [error] [client 10.1.19.88] PHP Notice:  Undefined variable: obscure_failure_messages in /var/www/html/ltb-project-self-service-password-1.3/pages/change.php on line 186, referer: http://172.16.9.171/
[Fri May 17 14:55:24 2019] [error] [client 10.1.19.88] PHP Warning:  in_array() expects parameter 2 to be array, null given in /var/www/html/ltb-project-self-service-password-1.3/pages/change.php on line 186, referer: http://172.16.9.171/
[Fri May 17 14:55:24 2019] [error] [client 10.1.19.88] PHP Notice:  Undefined variable: display_posthook_error in /var/www/html/ltb-project-self-service-password-1.3/pages/change.php on line 193, referer: http://172.16.9.171/
ldap_free_connection 1 1
ldap_send_unbind
ldap_free_connection: actually freed

**Comment by coudot** [comment]
Error seems clear : `Invalid credentials`. Your login or password is incorrect.

**Comment by plewin** [comment]
Hi @lxjmac did you manage to solve your issue with the previous answer ?
