### ISSUE TITLE
SSP and cracklib

### ISSUE THREAD

**Issue by codesmaker** [ltb-project/self-service-password#305]
Hi,

Does SSP support cracklib or pwquality?

**Comment by coudot** [comment]
This need to be implemented in LDAP directory, for example with ppm module in OpenLDAP.

Then you must configure SSP to send the password in cleartext so the quality control can be done by the LDAP directory.

**Comment by codesmaker** [comment]
Thanks for the reply. I see. Is it possible to make it a bit easier by checking the passwords locally against  cracklib or pwquality before sending them to LDAP?  This way, we wouldn't need to install any modules in OpenLDAP.

**Comment by coudot** [comment]
cracklib is not supported, but you have a lot a password policy settings, see https://ltb-project.org/documentation/self-service-password/latest/config_ppolicy

**Comment by codesmaker** [comment]
Thanks again for your quick reply and help. 

Actually what I'm looking for is that something similar to these settings in pwquality:

# Number of characters in the new password that must not be present in the old password.
difok = 1

# Whether to check for the words from the passwd entry GECOS string of the user.
# The check is enabled if the value is not 0.
gecoscheck = 1

# The password entered cannot contain more than 3 characters in a monotonic sequence
# such as abcd, and more than 3 identical consecutive characters, such as 1111
maxsequence = 3

It would be very nice if there are similar settings to what I mentioned above to further strengthen passwords .

**Comment by coudot** [comment]
> Number of characters in the new password that must not be present in the old password.

Not implemented, needs a patch

> Whether to check for the words from the passwd entry GECOS string of the user.

See https://github.com/ltb-project/self-service-password/pull/301

> The password entered cannot contain more than 3 characters in a monotonic sequence such as abcd, and more than 3 identical consecutive characters, such as 1111

Not implemented, needs a patch


Feel free to propose pull requests

**Comment by codesmaker** [comment]
I wish I could help but unfortunately I'm not a programmer. I'm a sysadmin. 

I think the most important one among the three mentioned is "difok". It prevents users from entering the same password with only one character changed. Would it be possible to implement it?

**Comment by coudot** [comment]
All is possible, please open a new issue to request this feature.

Note this is free software, so you can help by giving time or money.

**Comment by codesmaker** [comment]
Will do. Thanks a lot.
