### ISSUE TITLE
feature request: add another password quality check

### ISSUE THREAD

**Issue by codesmaker** [ltb-project/self-service-password#306]
Hi,

First of all, thanks a lot for this very helpful piece of software.

I would like to request a feature where passwords quality is checked to make sure that users don't use the same password with only one character changed.

For example, if a user's password is "Myprecious#", a user can just change one character and it would be accepted just as "Myprecious@".

This check is implemented in pwquality and it is called "difok". This is the explanation provided in its config file:
```
##Number of characters in the new password that must not be present in the old password.
difok = 5
```

**Comment by coudot** [comment]
Note that this rule can only be applied when user change its password by giving the old password. It won't work for password reset (by token, questions, etc.)

**Comment by codesmaker** [comment]
Awesome. I understand.

Many thanks.

**Comment by coudot** [comment]
Done by @faust64
