### ISSUE TITLE
posthook don't get username when using mail as login

### ISSUE THREAD

**Issue by muzzol** [ltb-project/self-service-password#307]
I'm using mail filter trick to be able to retrieve username with uid or mail as indicated here:

You can configure LDAP filter to get the user with uid or mail:
```php
$ldap_filter = (&(objectClass=person)(|(uid={login})(mail={login})))
```

With this, user can enter either mail or uid to change or reset password.

_Originally posted by @coudot in https://github.com/ltb-project/self-service-password/issues/190#issuecomment-369662260_

but posthook script only receives mail, not uid. posthook should receive ldap_login_attribute

**Comment by coudot** [comment]
Hello,

looking at the code, the posthook receives what is posted in login input, so it should be the mail if the user enters his mail. What do you get?

**Comment by muzzol** [comment]
I get mail, but I should receive the RDN so I can work with that LDAP object.

**Comment by coudot** [comment]
You can do a new LDAP search to get the DN from the mail if you need it. Often having the DN is not needed in posthook script because it is used to forward the password to another server.

What do you want to do in posthook script ?

**Comment by muzzol** [comment]
> You can do a new LDAP search to get the DN from the mail if you need it. Often having the DN is not needed in posthook script because it is used to forward the password to another server.
> 

sure, but why the hassle if I already got the UID? I perform several steps when a user changes his password and the only common attribute on all systems is the UID.

I already changed the ofending line in resetbytoken.php:

```
   if ( $result === "passwordchanged" && isset($posthook) ) {
        # $command = escapeshellcmd($posthook).' '.escapeshellarg($login).' '.escapeshellarg($newpassword);
        $command = escapeshellcmd($posthook).' '.escapeshellarg($userdn).' '.escapeshellarg($newpassword);
        exec($command);
    }

```

I also think resetmessage should include UID if is different from login. Something like:

**Hi jdoe@example.com (user001), Click here to reset your password:**

what do you think?

**Comment by coudot** [comment]
It's better to follow this discussion in #190
