### ISSUE TITLE
request: disable password change?

### ISSUE THREAD

**Issue by r2evans** [ltb-project/self-service-password#31]
In 2012 ([reference](http://lists.ltb-project.org/pipermail/ltb-users/2012-December/000263.html), a user by the name of Henning suggested a patch that would allow the admin to require sending a reset-link via email in order to actually change the password. I believe the premise was to protect against brute-force attacks and uncertainty about getting "fail2ban" working.

Did that patch ever materialize? Is there a chance the feature can be instituted?

I admit it defeats some of the immediate usability (and perhaps intent) of the application. I'm willing to disable that functionality to provide a little peace-of-mind.

**Comment by coudot** [comment]
This can be feature added to 1.0. I need some time to work on it.

**Comment by r2evans** [comment]
Thanks, I look forward to seeing it!

**Comment by r2evans** [comment]
Great, I'll be testing this and your patch to #26 over the next couple of days. Thank you!
