### ISSUE TITLE
Password was refused by the LDAP directory Error while changing the password

### ISSUE THREAD

**Issue by gothwalneha22** [ltb-project/self-service-password#310]
I am getting error  "**Password was refused by the LDAP directory** " while changing the password. 
Extended error is 00002077 : SvcErr: DSID-03190F4C, problem:5003 (WILL_NOT_PERFORM), data 0 .

Warning is ldap_modify_batch() : Batch Modify: Server is unwilling to perform in functions.inc.php file .

Thanks for the help.

**Comment by coudot** [comment]
The major causes are:
* You are not using LDAPS
* Your password is too weak

**Comment by gothwalneha22** [comment]
I am running the project in Windows server. When I am accessing at port 389, LDAP successfully binds. However, when I am using LDAPS, FastCGI process exits unexpectedly. I checked the events and observed that  FastCGI application got crashed because of faulty module libcrypto-1_1-x64.dll . Have any idea what can be the issue?

Thanks for the help.

**Comment by gothwalneha22** [comment]
Thanks @coudot.. I used LDAPS and the above problem of fastcgi crashing was due to unstable version of PHP. I installed the PHP stable version and it works now.

**Comment by coudot** [comment]
Good news!
