### ISSUE TITLE
Another Captcha than Google Captcha

### ISSUE THREAD

**Issue by AxtizFR** [ltb-project/self-service-password#311]
Hello,

Thanks for previous help.

I'm looking for integrate another captcha than the google one.

For reasons of company policy and also because I want to stay with independent and free software.

I found this one: BotDetect (https://captcha.com/) but I have trouble integrating it into the SSP program. Could anyone help me please ?

I tried to integrate it directly in self-service-password/pages/sendtoken.php without success..

**Comment by coudot** [comment]
I don't know this captcha, is it free software ?

**Comment by AxtizFR** [comment]
Yes it is, it have a free Licence and one no.

Le mer. 12 juin 2019 à 17:40, Clément OUDOT <notifications@github.com> a
écrit :

**Comment by coudot** [comment]
This one seems a better solution: https://github.com/yasirmturk/simple-php-captcha

**Comment by AxtizFR** [comment]
Good idea, I'm going to try it, can you help me if I find difficulty to
implement it?

Le mer. 12 juin 2019 à 17:49, Clément OUDOT <notifications@github.com> a
écrit :

**Comment by coudot** [comment]
yes, the community here can help you

**Comment by AxtizFR** [comment]
Thank you I will give you a feed back tomorrow

Le mer. 12 juin 2019 à 18:14, Clément OUDOT <notifications@github.com> a
écrit :

**Comment by AxtizFR** [comment]
Hello,
I managed to integrate the image of the captcha and a prompt but I do not have sufficient knowledge to make the mandatory verification test to send the request "submit".
In bash I could do it but I admit that in PHP I do not have sufficient knowledge! :(
Best regards,

**Comment by AxtizFR** [comment]
![image](https://user-images.githubusercontent.com/49306541/59415195-4b1f6a80-8dc3-11e9-9269-c011cb7d62ec.png)

**Comment by AxtizFR** [comment]
![image](https://user-images.githubusercontent.com/49306541/59431565-803cb480-8de5-11e9-9bfa-d8440f1c873d.png)

**Comment by AxtizFR** [comment]
I can not do the verification test of the captcha, it's top of my skills unfortunately.

`
# Test vérification du Captcha
if ($_POST['captcha']['code'] != $_SESSION['captcha_saisi'])
{
        echo "Le resultat du captcha saisi est correct";
}
else
{
        echo "Le resultat du captcha saisi est incorrect";
}

`
`
#Affichage du captcha
  <div class="form-group">
     <div class="col-sm-offset-3 col-sm-8">
        <?php
                echo "<b>Captcha </b>";
        ?>
        <input type="text" name="captcha_saisi">
        <?php
                echo '<img src="' . $_SESSION['captcha']['image_src'] . '" alt="CAPTCHA code">';
        ?>
     </div>
  </div>
`

**Comment by AxtizFR** [comment]
It give this result :  
![image](https://user-images.githubusercontent.com/49306541/59443815-eaad1f00-8dfc-11e9-8f16-551b0cd02f23.png)

but when i submit with nothing in the form it appair this error message :  
![image](https://user-images.githubusercontent.com/49306541/59443908-23e58f00-8dfd-11e9-830e-98ed259ac362.png)
And it's in green color..
