### ISSUE TITLE
Change password in AD and openldap simultaneously

### ISSUE THREAD

**Issue by km1** [ltb-project/self-service-password#313]
Hello, 

I have a question if there is a possibility to do such configuration that during password change process there are 2 LDAP directories updated: 
1. Windows Active directory
2. OpenLdap (Linux  #machine)

**Comment by coudot** [comment]
Hello,

to do that, we use a posthook script: https://ltb-project.org/documentation/self-service-password/latest/config_posthook

**Comment by km1** [comment]
Thank you for the hint! I'll check the possibility.

**Comment by plewin** [comment]
Hi. I'm closing this issue because it has already been answered.
