### ISSUE TITLE
Password was refused by the LDAP directory

### ISSUE THREAD

**Issue by ahrao** [ltb-project/self-service-password#314]
Hi Clement, 

Self-Service-Password works like charm for me if I set who_change_password = manager
but does not work if I set who_change_password = user, below is the error I get

**Password was refused by the LDAP directory**

If I give the user rights to change password in slapd.conf the password policies are by passed
Let me know a solution for this situation.

Hope you have understood my query.  I am using samba + openldap without TLS

Thanks in Advance
Rao

**Comment by coudot** [comment]
Using rootdn (manager) to change password bypasses OpenLDAP password policies.

Check ACLs to be sure your user can change its password.

**Comment by ahrao** [comment]
Thanks for your prompt reply.

Can you send some acls, after the acls are in place will the backend policies come into effect.  Please clarify.

⁣Sent from BlueMail ​

**Comment by itsKV** [comment]
anyboody got answer? Fed up of this REFUSED error. 
Help plz.

**Comment by el3ctrician** [comment]
hello, 
i am facing the same issue. User can access another server with ssh and issue `passwd `and change their password on the LDAP server but can't change it using the ssp. Any ideas on how to debug this further ? 
thanks

**Comment by jaraddowning** [comment]
Same issue showing up here. Running on ubuntu 18.04. LDAP is samba server in AD DC mode running on the same base.

**Comment by meoso** [comment]
sorry to necro-bump, but simple solution for me was install an SSL certificate for ldaps:// port :636
