### ISSUE TITLE
sendtoken email, link not html

### ISSUE THREAD

**Issue by bpinsard** [ltb-project/self-service-password#316]
Problem: the link for reset is not in an <a> html tag, some mail clients convert it to html (gmail for instance) but other do not, making the link not clickable.
Is there a reason for that?

The header of the email already says that it is sent with html mime.

This can be changed with something like:
```
sed -i -E 's/(resetmessage.*)\{url\}/\1\<a href='\{url\}'\>\{url\}\<\/a\>/g' lang/*.inc.php 
```

Thanks

**Comment by coudot** [comment]
By default mails are in plain text. See configuration:
```php
$mail_contenttype = 'text/plain';
```

**Comment by bpinsard** [comment]
Thanks for your quick reply.
The docker I am using mistakenly changed the default to html.
I changed it back, and it seems that when sent with plain text, the url is now converted to a link by outlook.
Sorry for the disturbance and thanks again.
