### ISSUE TITLE
Encrypting answer while registering questions/answers not working

### ISSUE THREAD

**Issue by gothwalneha22** [ltb-project/self-service-password#317]
When crypt_answer is set to true, answer is not getting registered. However, in case when it is set to false, answer is getting registered but it is saved in clear text. Any idea what can be the reason?

Thanks for the help .

**Comment by coudot** [comment]
You need first to change the default passphrase:
```php
$keyphrase = "myownsecret";
```

If it does not work, check log messages.

**Comment by gothwalneha22** [comment]
Passphrase has already been changed. There is nothing in logs related to this.

**Comment by gothwalneha22** [comment]
I think the function encryptWithPassword in defusecrypto.phar called during encryption is not returning any value.

**Comment by coudot** [comment]
So you should have a missing dependency.

Can you check that you have at least PHP 5.6?

See also https://github.com/defuse/php-encryption

**Comment by gothwalneha22** [comment]
I had done some modifications in defusecrypto.phar.  I reinstalled the file. It works now.

Thanks for the help.

**Comment by coudot** [comment]
Can you put here waht you modified? It could help others facing the same issue

**Comment by gothwalneha22** [comment]
The main issue was that extension openssl was disabled in PHP configuration file i.e. php.ini . I enabled the extension for encryption.

Second, I put some breakup points in defusecrypto.phar for debugging whether the function encryptWithPassword is even being called. I think that corrupted my file. So, I changed the file.

**Comment by coudot** [comment]
Thanks!
