### ISSUE TITLE
Does multiple questions/answers work in active directory?

### ISSUE THREAD

**Issue by gothwalneha22** [ltb-project/self-service-password#323]
I have set $multiple_answers = true, $answer_attribute = "info" and $answer_attribute="user" . As of now, in setquestion.php, only one question is being registered . For registering multiple questions/answers, modification is required in the registration form. However, in the latest master code, there is no such modification.

Also, will the "info" attribute be able to store an array of answers? 

Thanks for the help.

**Comment by shawnmckinney** [comment]
> On Aug 8, 2019, at 4:05 AM, gothwalneha22 <notifications@github.com> wrote:
> 
> I have set $multiple_answers = true, $answer_attribute = "info" and $answer_attribute="user" . As of now, in setquestion.php, only one question is being registered . For registering multiple questions/answers, modification is required in the registration form. However, in the latest master code, there is no such modification.
> 
> Also, will the "info" attribute be able to store an array of answers?

Hello, since I coded the support for multiple answers, I’ll chime in here...

The way it works, the answer_attribute must use a multi-valued attribute.

For example:

# attribute Answer should be hidden to users!
$answer_objectClass = "extensibleObject";
$answer_attribute = "l”;


Of course you probably wouldn’t use the ‘l’ attribute on extensibleObject as that usually maps to a location.

Any multivalued string attribute will work.

Also, you must list each question being allowed in the config:
For example:
$messages['questions']['band'] = "What is your favorite band?";
$messages['questions']['bike'] = "What is your favorite bike?”;

—Shawn

**Comment by gothwalneha22** [comment]
Hi,

When I am using $answer_objectClass = "extensibleObject" and $answer_attribute as some attribute which is not present in Active directory attributes., I am getting an error of error in attribute conversion operation.  The "info" attribute which I used in single question/answer is unicode string..

And one more question, how are you registering multiple questions/answer ? 

Can we add customized attribute in AD ?

**Comment by shawnmckinney** [comment]
> On Aug 9, 2019, at 12:48 AM, gothwalneha22 <notifications@github.com> wrote:
> 
> When I am using $answer_objectClass = "extensibleObject" and $answer_attribute as some attribute which is not present in Active directory attributes., I am getting an error of error in attribute conversion operation. The "info" attribute which I used in single question/answer is unicode string..

When you say attribute is not present do you mean not in the AD schema or not present on the user’s entry?

> And one more question, how are you registering multiple questions/answer ?

Registering multiple questions is how I described earlier, setting the $messages param in the config for the app.

> Can we add customized attribute in AD ?

Are you asking if you can add a custom attribute to AD (or any LDAP) schema?  Yes, any multi-valued, directory string attribute will work.

—Shawn

**Comment by gothwalneha22** [comment]
Hi,

I have used a multi-valued attribute which is already present in AD schema. I am able to register multiple questions/answers one by one. Can we register multiple questions/answers simultaneously?

**Comment by shawnmckinney** [comment]
> On Aug 13, 2019, at 6:12 AM, gothwalneha22 <notifications@github.com> wrote:
> 
> I have used a multi-valued attribute which is already present in AD schema. I am able to register multiple questions/answers one by one. Can we register multiple questions/answers simultaneously?

Negative.

**Comment by coudot** [comment]
This will be possible in 1.4, see https://self-service-password.readthedocs.io/en/latest/config_questions.html
