### ISSUE TITLE
I am getting error

### ISSUE THREAD

**Issue by Verakhs** [ltb-project/self-service-password#324]
hello, 

I tried two ways to get this installed. I have a redhat server. 

in both ways I get the error when I do the following 

**rpm --import https://ltb-project.org/wiki/lib/RPM-GPG-KEY-LTB-project**

I get this error 
curl: (7) Failed connect to ltb-project.org:443; Connection timed out
error: https://ltb-project.org/wiki/lib/RPM-GPG-KEY-LTB-project: import read failed(2).

**Comment by coudot** [comment]
Check that you server can access to https://ltb-project.org/

If you have a proxy, export https_proxy env to configure it

**Comment by plewin** [comment]
Hi @Verakhs do you still need assistance on this issue ?

**Comment by Verakhs** [comment]
@plewin I have been trying to install it

**Comment by coudot** [comment]
Is your server connected to Internet?

**Comment by plewin** [comment]
I agree it looks like a network issue, likely a firewall issue on op's server or op's server network in my opinion.
>  curl: (35) TCP connection reset by peer

**Comment by Verakhs** [comment]
Hi, It is behind proxy but i can update or install packages using yum . however, when I ping www.google.com I dont get response . I even tried to install it locally but I could not. So could you please help me to install it?

**Comment by coudot** [comment]
The proxy is configured in yum, but not for the whole system.

Use `export http_proxy=...` and `export https_proxy=...` before your rpm command.
