### ISSUE TITLE
 PHP upgrade required

### ISSUE THREAD

**Issue by gxiaob** [ltb-project/self-service-password#326]
Hi,I have installed the self-service-password on centos7.6，however，when I set $ad_mode = true
the index.php shows "PHP upgrade required"，could you tell me how to solve the problem？the php version is 5.4.16,and the self-service-password version is 1.3.1

**Comment by coudot** [comment]
You need at least PHP 5.6.

Use some backports or extra RPMs repository.

See https://www.mojowill.com/geek/howto-install-php-5-4-5-5-or-5-6-on-centos-6-and-centos-7/

**Comment by JuJuMDX** [comment]
Answered by @coudot
