### ISSUE TITLE
Prefill user login fields with an HTTP header value

### ISSUE THREAD

**Issue by soisik** [ltb-project/self-service-password#329]
Currently, there is no possibility in SSP to prefill login fields in pages with a contextual value passed through SSO mecanism; Users are authenticated but they have to enter again their login to be able to change their password.

We would like SSP to prefill the login fields with a login. The login could be obtained in an HTTP header, such as `Auth-User` by default, or as any other name set config.inc.local.php.

PR following.

**Comment by coudot** [comment]
Doc updated: https://ltb-project.org/documentation/self-service-password/1.4/config_general#prefill_user_login
