### ISSUE TITLE
SMS Twilio Integration

### ISSUE THREAD

**Issue by halkeye** [ltb-project/self-service-password#331]
I think I'm going to right a twilio client for ssp, Its been a long time since I wrote straight up php, but it looks like https://www.twilio.com/docs/libraries/php is pretty easy to use.

Is this something that would be interested upstream in the project? or I should keep it local?

**Comment by coudot** [comment]
Hello @halkeye 

For now, we have a wiki page to provide code samples for differents API providers: https://ltb-project.org/documentation/self-service-password/latest/sms_api
