### ISSUE TITLE
reCAPTCHA v3

### ISSUE THREAD

**Issue by tekvsakdan** [ltb-project/self-service-password#343]
Is there any plan to implement Google reCAPTCHA v3?

**Comment by coudot** [comment]
Not yet but feel free to do it.

We are also looking for another captcha system, independant from Google.

Any idea is welcomed.

**Comment by coudot** [comment]
We will use a built-in captcha in release 1.4 (see #311) and remove reCAPTCHA.

We could reintroduce recaptcha in next versions if someone really need it.

**Comment by fabianostocco** [comment]
Opa.
I'm holding back the SSP upgrade to version 1.4 due to the lack of
reCaptcha.

Would it be possible to release a new version with this feature?

Thanks in advance.

**Comment by coudot** [comment]
There is a built-in captcha, did you try it?

I'm not sure we will spend much time on a proprietary captcha. But if you really need it, you can sponsor the development effort.
