### ISSUE TITLE
Nearly impossible to connect to AD server over SSL

### ISSUE THREAD

**Issue by itsKV** [ltb-project/self-service-password#345]
I am trying to set-up SSP on WinServer2016.

I am getting "Wrong user/pass" error while entering WRONG credentials. But I am getting "Password Refused by LDAP directory" error while I genuinely try to change pass using correct OLD pass. 

Whats wrong??? 

I am using _ldap://192.168.1.1:389_ in url, _tls=false_ and _Administrator_ as username.

PLZ HELP.

**Comment by ricardobf** [comment]
I've the same issue, my AD is refusing password changes. It seems that we've to use ldaps, but I don't know where to import the cer file on my docker server (I'm using docker btw). Any workaround?

**Comment by itsKV** [comment]
There is work-around to disable "_Password change only over LDAPS_" policy. I disabled it. But no use. Problem persist.
Check that work-around [**here**](https://stackoverflow.com/questions/16861664/how-to-disable-password-operations-over-ldaps-only-policy-in-active-directory). May that work for you.
@coudot Any comment?

**Comment by coudot** [comment]
I don't think that decreasing security is a good solution.

Documentation explains how to configure LDAPS : https://ltb-project.org/documentation/self-service-password/latest/config_ldap

If the password is refused by AD, it can not only be linked to LDAPS. It can be also because the password is too simple and does not match AD password policy.

**Comment by itsKV** [comment]
I have confirmed the password policy. No problem with that. 
In _config_lda_p documentation, it's asked to configure certificate in file _C:\OpenLDAP\sysconf\ldap.conf_ But I am using WindowsServer2016 and I am not able to find any _ldap.config_ file, even anywhere on C drive. 
In NETSTAT command, it seems that service is running on port 636 but can't connect to it, even directly from server or over LAN. Only port 389 is accessible over LAN. I also confirmed the same using windows server's inbuilt ldap.exe tool. 

FYI, I have installed Active Directory Domain Service, Active Directory Certificate Service, DNS server, file and storage server on Server.

**Comment by itsKV** [comment]
@coudot any suggestion?

**Comment by coudot** [comment]
https://ltb-project.org/documentation/general/active_directory_certificates

**Comment by shuboGe** [comment]
解决了吗？

**Comment by shuboGe** [comment]
@itsKV  您解决了吗？ 或者你有解决的思路吗？

**Comment by itsKV** [comment]
@shuboGe Sorry, I don't understand Chineese language.
I haven't solved the issue yet. (used Google Translate to understand your typing)

**Comment by itsKV** [comment]
One thing to mention...

Just noticed that, while testing with _ldap.exe_ utility, even on server machine, using IP address with LDAPS:// is not working. Also, we can't use _localhost_ here. We must use reachable IP or FQDN of server. 
For me, using FQDN of server on _ldap.exe_ tool worked. (in my case, it's _server.mainAD.local_)

But using FQDN at _$ldap_url_ still doesn't work.

**Comment by LesserF** [comment]
You must obtain the certificate authority (CA) certificate used to sign the AD server certificate. Ask your AD administrator to provide this for you in PEM format. If this isn’t possible and if you are reasonably sure your network connection isn’t compromised, you can use openssl to retrieve the server certificate from the server. The following example demonstrates how to do this.
`server-01:~$ openssl s_client -connect ad-dc3.en.neo-gpt.com:636 -showcerts < /dev/null`
     Copy and paste the certificate text from the bottom certificate into a file. I use /pki/cacerts.pem. The certificate text will look something like this:
`-----BEGIN CERTIFICATE-----
MIIFdDCCBFygAwIBAgIQJ2buVutJ846r13Ci/ITeIjANBgkqhkiG9w0BAQwFADBv
MQswCQYDVQQGEwJTRTEUMBIGA1UEChMLQWRkVHJ1c3QgQUIxJjAkBgNVBAsTHUFk
ZFRydXN0IEV4dGVybmFsIFRUUCBOZXR3b3JrMSIwIAYDVQQDExlBZGRUcnVzdCBF
pu/xO28QOG8=
-----END CERTIFICATE-----`
  Open ldap.conf with a text editor. Here is where to find it on various operating systems

OS | PATH
-- | --
CentOS | /etc/openldap/ldap.conf
Debian | /etc/ldap/ldap.conf
OpenSUSE | /etc/openldap/ldap.conf

Add the line

`TLS_CACERT /pki/cacerts.pem`
to your file,then test.

**Comment by ocoranes** [comment]
> One thing to mention...
> 
> Just noticed that, while testing with _ldap.exe_ utility, even on server machine, using IP address with LDAPS:// is not working. Also, we can't use _localhost_ here. We must use reachable IP or FQDN of server.
> For me, using FQDN of server on _ldap.exe_ tool worked (from other client machines too). (in my case, FQDN is _server.mainAD.local_)
> 
> But using FQDN at _$ldap_url_ still doesn't work.

I encountered this too..
The problem was that if we used the IP address when trying to connect , while the certificate was issued for a DNS name..
but still ldaps doesn't work.. 

I can connect from SSP to AD Server manually using this command:
openssl s_client -connect server_fqdn:636 -CAfile /etc/ssl/certs/ca.crt

**Comment by coudot** [comment]
Did you check that the TLS_CIPHER_SUITE is compatible with your Active Directory?
