### ISSUE TITLE
missing PHP modules after upgrade to buster 10.1

### ISSUE THREAD

**Issue by schka17** [ltb-project/self-service-password#348]
Just upgraded my server from debian 9.5 to 10.1, 

Now i get the error messages 
"You should install PHP mbstring"
"You should install PHP XML to use this tool"

both packages are installed
php-mbstring is already the newest version (2:7.3+69).
php-xml is already the newest version (2:7.3+69).

Any idea how to solve this problem?

**Comment by coudot** [comment]
Could you try:
```
phpenmod mbstring xml
```

**Comment by schka17** [comment]
doesn't change, may it happened because php was also upgraded to 7.3?
in the apach error log i got this messages:
`PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/xml.so' - /usr/lib/php/20151012/xml.so: cannot open shared object file: No such file or directory in Unknown on line 0`
`PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/mbstring.so' - /usr/lib/php/20151012/mbstring.so: cannot open shared object file: No such file or directory in Unknown on line 0`

**Comment by plewin** [comment]
Hi @schka17 did you manage to solve your issue ?

This is not a SSP issue, it's a php migration issue.
The php.ini is out of sync with the modules, it's possible that some paths coded in php.ini are now missing or modules are now missing.

**Comment by schka17** [comment]
> Hi @schka17 did you manage to solve your issue ?
> 
> This is not a SSP issue, it's a php migration issue.
> The php.ini is out of sync with the modules, it's possible that some paths coded in php.ini are now missing or modules are now missing.

Hi,
no i cant solve it. not enough time to research, But will follow your hint

**Comment by plewin** [comment]
I am closing this issue for not being reproductible and inactive, if this problem happens again please reopen an issue.
Thanks,

**Comment by smo42** [comment]
> > Hi @schka17 did you manage to solve your issue ?
> > This is not a SSP issue, it's a php migration issue.
> > The php.ini is out of sync with the modules, it's possible that some paths coded in php.ini are now missing or modules are now missing.
> 
FYI;
I had the same issue on a fresh debian buster.
To resolve issue uncomment extension=mbstring in  /etc/php/7.3/apache2/php.ini
