### ISSUE TITLE
Your answer has not been registered error for some users

### ISSUE THREAD

**Issue by Isaac-waweru** [ltb-project/self-service-password#349]
I have this error popping up on some users. Could anyone have a clue on what i should check? 
 I installed the tool a month ago so am still learning it.

![image](https://user-images.githubusercontent.com/56978352/67518184-eb0fcd80-f6ac-11e9-8c63-646865396cc7.png)

**Comment by coudot** [comment]
To be able to reset your password with a questio/answer challenge, you must first regiser an answer. See the info box below the error box.

**Comment by coudot** [comment]
If you can't register the answer, it should be because you did not configure the rights for a user to modify its entry. See the logs to know more.

**Comment by Isaac-waweru** [comment]
I have tried with both manager and user. Some users are able to check.
Where is that log file ?

**Comment by coudot** [comment]
Set `$debug` to true to have logs on the web interface, and also see Apache error log

**Comment by plewin** [comment]
@Isaac-waweru did you manage to solve your issue ?

When this message appears there is a technical explanation logged in the logs.
