### ISSUE TITLE
How can handle ldaps with samba dc

### ISSUE THREAD

**Issue by tbs575** [ltb-project/self-service-password#352]
I use docker nowsci/samba-domain to setup samba AD, and I can use ldapadmin tool to connect server with ldaps, but I don't know how to set self-server-password?

**Comment by coudot** [comment]
You need to enable AD mode

**Comment by tbs575** [comment]
@coudot I enable AD mode, can set password if I start nowsci/samba-domain without ssl. will met LDAP error with ssl.

**Comment by coudot** [comment]
SSL is required
