### ISSUE TITLE
default_action set to sendtoken with use_change set to true, can not use change form

### ISSUE THREAD

**Issue by Dan33l** [ltb-project/self-service-password#354]
Hi,

In the file `config.inc.local.php` when we use :
```
$default_action = "change";
$use_change = true;
$use_tokens = true;
```
All works as expected:
 * https://example.com/index.php points to the standard change form.
 * https://example.com/index.php?action=sendtoken points to token via mail form

Now when we use :
```
$default_action = "sendtoken";
$use_change = true;
$use_tokens = true;
```
 * https://example.com/index.php and https://example.com/index.php?action=sendtoken point to token via mail form
 * The standard change form can not be accessed.

We use git tag v1.3

**Comment by coudot** [comment]
Done by @JuJuMDX in #355
