### ISSUE TITLE
Bad directory

### ISSUE THREAD

**Issue by battosai30** [ltb-project/self-service-password#357]
Hi,

When apt is used on Debian, it configures a bad directory in Apache conf.

In Apache conf : /usr/local/self-service-password
Real location : /usr/share/self-service-password

Thanks for your work !

**Comment by battosai30** [comment]
Sorry I understand my mistake : https://ltb-project.org/documentation/self-service-password/1.3/config_apache

I guess it changed on 1.4 ?

**Comment by coudot** [comment]
Hello,

as you have noticed, the documentation on Apache configuration is done for people installing the software from the tarball. In this case, the good practice is to use /usr/local to not mess up with system packages.
