### ISSUE TITLE
Intermittently attempts to use TLS though ldap_starttls is false

### ISSUE THREAD

**Issue by ja-frog** [ltb-project/self-service-password#358]
CentOS 7.7.1908
PHP 7.2.25
AD Server: Windows Server 2012
Self-Service-Password: 1.3.1

I have self-service-password setup and it works on perhaps half of submissions. On the other half it fails with the Cannot access LDAP directory message. When I look at the debug output for the failed attempts, I am seeing it try to use TLS even though I have the ldap_starttls flag set to false. I have included the debug trace and what I hope are the relevant portions of the config below. I am guessing that I am missing something but I haven't been able to determine what.

Config:

```
$debug = true;

$ldap_url = "ldaps://my-dc.me.net";
$ldap_starttls = false;
$ldap_binddn = "CN=LDAP TB User,OU=Our Users,DC=me,DC=net";
$ldap_bindpw = "fRrOYEFnkDPdxC7FaAC9";
$ldap_base = "dc=me,dc=net";
$ldap_login_attribute = "uid";
$ldap_fullname_attribute = "cn";
$ldap_filter = "(&(objectClass=user)(sAMAccountName={login})(!(userAccountControl:1.2.840.113556.1.4.803:=2)))";

$ad_mode = true;
$ad_options['force_unlock'] = false;
$ad_options['force_pwd_change'] = false;
$ad_options['change_expired_password'] = true;

$samba_mode = true;
```

Log:

> 
> ldap_create
> ldap_url_parse_ext(ldaps://my-dc.me.net)
> ldap_sasl_bind_s
> ldap_sasl_bind
> ldap_send_initial_request
> ldap_new_connection 1 1 0
> ldap_int_open_connection
> ldap_connect_to_host: TCP my-dc.me.net:636
> ldap_new_socket: 14
> ldap_prepare_socket: 14
> ldap_connect_to_host: Trying SOME_IP:636
> ldap_pvt_connect: fd: 14 tm: -1 async: 0
> attempting to connect:
> connect success
> TLS trace: SSL_connect:before/connect initialization
> TLS trace: SSL_connect:SSLv2/v3 write client hello A
> TLS trace: SSL_connect:SSLv3 read server hello A
> TLS certificate verification: depth: 0, err: 20, subject: /CN=my-dc.me.net, issuer: /DC=net/DC=me/CN=me-my-dc-CA
> TLS certificate verification: Error, unable to get local issuer certificate
> TLS trace: SSL3 alert write:fatal:unknown CA
> TLS trace: SSL_connect:error in error
> TLS trace: SSL_connect:error in error
> TLS: can't connect: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed (unable to get local issuer certificate).
> ldap_err2string
> ldap_err2string

**Comment by coudot** [comment]
The error is clear:
```
TLS: can't connect: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed (unable to get local issuer certificate).
```

You server cannot trust the certificate of your AD. If this happens not all the time, you may have several AD servers, one with a valid certificate, the other with an unvalid certificate.

**Comment by ja-frog** [comment]
Only one server was specified(the DNS entry points to a single AD server, not a load balancer or anything similar).

The fix was to restart the server after setting "TLS_REQCERT allow" in ldap.conf. I had set this earlier I just hadn't restarted the server. I guess some process needed to be restarted for the change to take effect. I hadn't thought that setting this was necessary since ldap_starttls was set to false.

**Comment by ja-frog** [comment]
It may be worth updating the documentation to note that ldap.conf references to TLS need to be setup correctly even if ldap_starttls is set to false.

My question has been answered. Since the documentation is kept on a separate site I will go ahead and close this issue.

**Comment by coudot** [comment]
This because you must not associate LDAPS to SSL and startTLS to TLS. To be very quick, TLS is a new version of SSL protocol. Now every softwares are using TLS (v1) and no more SSL (v2 or v3). So having LDAPS in URL, or setting startTLS, both options will call the TLS protocol, so the related TLS options in ldap.conf.
