### ISSUE TITLE
Show extended LDAP error message after password change was denied

### ISSUE THREAD

**Issue by abussjae** [ltb-project/self-service-password#359]
Hi,

we are running ODSEE (Oracle Directory Server Enterprise Edition) and we have a global LDAP syntax policy which also compares passwords against bad words list.
The other syntax based rules in selfservice config and LDAP policy are the same so there is no problem.
But if the user chooses a password which contains parts of the bad words list we can see only that the change was refused so it would be better so see additonally the extended error message from LDAP server.

LDAP error message on LDAP server:

RESULT err=19 tag=103 nentries=0 etime=0, invalid password syntax: dictionary word match

I would suggest to add this code :
```diff
*** change.php.orig     2019-12-11 07:27:41.325933610 +0000
--- change.php  2019-12-11 07:16:53.484481885 +0000
***************
*** 190,195 ****
--- 190,210 ----
  <p><i class="fa fa-fw <?php echo get_fa_class($result) ?>" aria-hidden="true"></i> <?php echo $messages[$result]; ?></p>
  </div>

+ <?php
+     if ( $result === "passworderror" ) {
+         $extended_error = null;
+         if ( ldap_get_option($ldap, 0x0032, $extended_error) ) {
+             if ( $extended_error ) {
+                 echo "<div class=\"result alert alert-danger\"><p>";
+                 echo "<i class=\"fa fa-fw fa-exclamation-triangle\"></i> ";
+                 echo $extended_error;
+                 echo "</p>";
+                 echo "</div>\n";
+             }
+         }
+     }
+ ?>
+
  <?php if ( isset($posthook_return) and $display_posthook_error and $posthook_return > 0 ) { ?>

  <div class="result alert alert-warning">

```

-> 

![screenshot 824](https://user-images.githubusercontent.com/29626502/70601128-b078da80-1bf1-11ea-9502-403def9369fa.jpg)

**Comment by coudot** [comment]
Thanks for this proposition. I think we need to have the extended error returned by the change_password method.

**Comment by abussjae** [comment]
As I was not sure where to put the code better (into function or on page level) I posted it here instead of a pull request. So you are free to implement it anywhere you like :-)
Thanks for accepting the enhancement.

**Comment by coudot** [comment]
Patch done in #367 

Doc updated: https://ltb-project.org/documentation/self-service-password/1.4/config_ppolicy#extended_error
