### ISSUE TITLE
Ubuntu APT repositories for self-service-password

### ISSUE THREAD

**Issue by fleish** [ltb-project/self-service-password#361]
I'm wondering if there are specific Ubuntu specific APT repositories for self-service-password these days? The documentation @ https://ltb-project.org/documentation/self-service-password/latest/install_debian says Debian/Ubuntu, but the URL only mentions debian jessie (https://ltb-project.org/debian/jessie) ... and while a repo also seems to exist for debian stretch (https://ltb-project.org/debian/stretch) it is unclear if there is any difference or need to pick one over the other based on the version of Debian being used or if using Ubuntu vs. Debian altogether. The version question would then also come up for the various versions of Ubuntu. Could someone familiar with and/or responsible for the repository please clarify how this is intended to work?

**Comment by coudot** [comment]
As far as I know, the provided debian package is working for any Debian and Ubuntu version.

Other Debian repositories in LTB are not for Self Service Password or White Pages, but for OpenLDAP packages.

**Comment by fleish** [comment]
thanks for clarifying
