### ISSUE TITLE
Minimum privileges to change password

### ISSUE THREAD

**Issue by DenizParlak** [ltb-project/self-service-password#362]
Hi,

I can able to change a user's password via an Administrator group's account while $who_change_password is "manager", if I switch to "user", it doesn't work anymore.

Second question, even using "manager" parameter with a user who is not belongs to "Administrator" group, it's also didn't work.

I don't want to use an Administrator account, what should I do?

**Comment by coudot** [comment]
Read https://ltb-project.org/documentation/self-service-password/latest/config_ldap#active_directory, there is a chapter on AD privileges

**Comment by DenizParlak** [comment]
I did it already but after digging something I found that it happened because of default password policy, now all good, thanks.
