### ISSUE TITLE
Undefined variable: use_pwnedpasswords in /usr/share/self-service-password/index.php

### ISSUE THREAD

**Issue by lsambolino** [ltb-project/self-service-password#363]
Hi, 

We have ltb running on our development infrastructure. At the moment, we are facing issues with the reset password by mail portal.

The installed version is: **self-service-password/unstable,unstable,now 1.3-1 all**
More specifically, the following error is found at **/var/log/nginx/error.log**

`2020/01/20 15:38:10 [error] 737#737: *3572 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: use_pwnedpasswords in /usr/share/self-service-password/index.php on line 35
PHP message: send_mail: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
PHP message: Error while sending token to myusername@myemailprovider.com (user myuser)" while reading response header from upstream, client: OURIP, server: selfcare.ourwebsite.root.it, request: "POST /__changepassword/?action=sendtoken HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "shopping.ourdomain.dev.ourdomain-digital.com", referrer: "https://shopping.ourdomain.dev.ourdomain-digital.com/__changepassword/?action=sendtoken"
2020/01/20 15:50:54 [error] 737#737: *3579 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: use_pwnedpasswords in /usr/share/self-service-password/index.php on line 35" while reading response header from upstream, client: CLIENTIP, server: selfcare-ourwebsite.ourdomain.root.it, request: "GET /__changepassword/?action=sendtoken HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "shopping.ourdomain.dev.ourdomain-digital.com"
2020/01/20 15:50:59 [error] 737#737: *3579 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: use_pwnedpasswords in /usr/share/self-service-password/index.php on line 35`

Any support on this regard ?

**Comment by plewin** [comment]
@lsambolino 

I see 2 issues

1) "SMTP connect() failed. " The configuration for emailing is incorrect or there is a network issue. php could not join your smtp server with this configuration. I recommend double checking these values.

2) Undefined variable: use_pwnedpasswords, nothing worrying the config is out of sync with latest variables. it can be muted by adding $use_pwnedpasswords = false; in the config.

**Comment by lsambolino** [comment]
Hi plewin. Thank you for supporting.
We resolved by checking postfix service (it was down) and starting the postfix service again

**Comment by plewin** [comment]
Thank you for the update, I'm closing this issue because it was fixed.
