### ISSUE TITLE
obscure_failure_messages configuration parameter broken

### ISSUE THREAD

**Issue by espro** [ltb-project/self-service-password#364]
The `obscure_failure_messages` configuration parameter is broken due to it becoming a nested array

In #239 `$obscure_failure_messages` gets wrapped in an `array()` on each page because by default it has no value resulting in an error being thrown by `in_array()`. When initialized it then becomes a nested array and does not work.

The solution is to either define it as a blank array in the default configuration file and remove the `array()` definition on each page (revert #239 ), or in each page check if it exists first.

**Comment by coudot** [comment]
Thanks for the report. Indeed, it may be better to revert #239 and to initialize the parameter instead, to be sure it is an array.

**Comment by coudot** [comment]
Revert done in #365

**Comment by coudot** [comment]
Fix in https://github.com/ltb-project/self-service-password/commit/e3164d43072dae13aee095444c6759ef010c9fcb

@espro could you test it?

**Comment by espro** [comment]
Working as expected on latest master based on my testing

**Comment by coudot** [comment]
Thanks for the feedback!
