### ISSUE TITLE
Password changed but no effect in AD

### ISSUE THREAD

**Issue by Astoria83000** [ltb-project/self-service-password#366]
Hi,

i don't understand, process is clean without error but no change in Active Directory.
For example OWA keep the previous password.

**Comment by coudot** [comment]
As you may know, AD is keeping old password active for some time, so you still can authenticated with it. Did you try to authenticate with the new password?

**Comment by Astoria83000** [comment]
Yes i try to authenticate with it, without AD mode and no ssl.

**Comment by coudot** [comment]
By default, 1 hour. See https://support.microsoft.com/fr-fr/help/906305/new-setting-modifies-ntlm-network-authentication-behavior
