### ISSUE TITLE
how to change the front-end?

### ISSUE THREAD

**Issue by gvikram18** [ltb-project/self-service-password#369]
Hi,
I've been using the self-service-password for a while and it works as expected. But my concern is that the UI is basic. I want to change the background and colors, give it a professional look. Need some help regarding which files can be changed and which ones to be kept untouched.

**Comment by coudot** [comment]
Hello,

there is a work in progress by @JuJuMDX to move to Smarty framework, so it will be easier to adapt the UI (see #109 )

For the moment, you need to adapt HTML code or CSS code from the source. But all these files will be overwritten at next update.

**Comment by coamtaker618** [comment]
If you're writing custom css to make a nicer UI is there any reason not to add your custom files to the .gitignore files so that they're not overwritten next update?

**Comment by coudot** [comment]
Smarty framework is available in 1.4 release
