### ISSUE TITLE
Reset by mail token lifetime issue

### ISSUE THREAD

**Issue by goubelle** [ltb-project/self-service-password#37]
Bonjour,

Nous souhaitons faire évoluer la durée de token de reset de mail de 2 h (par defaut) à 24h.

nous avons modifié dans le fichier config.inc.php

```
# Token lifetime in seconds
$token_lifetime = "7200";

```

à

```
# Token lifetime in seconds
$token_lifetime = "86400";
```

Mais cela ne fonctionne pas, cela semble resté à 2h.

avez vous une idée du problème ?

Cdt
Frederic Goubelle

**Comment by coudot** [comment]
Hello @goubelle ,

please try to use English to exchange on this forum.

You will find some explanations here: http://stackoverflow.com/questions/8311320/how-to-change-the-session-timeout-in-php

There should be a cron script that uses the configuration in php.ini and not the one set in Self Service Password application. You should modifiy the value of `session.gc_maxlifetime` in php.ini (see http://php.net/manual/en/session.configuration.php#ini.session.gc-maxlifetime), or disable the cron job that purges PHP sessions. I would recommend the first option.

**Comment by coudot** [comment]
The proposed solution fixes the issue.

Another possibility is to set a specific directory in session.save_path for SSP: http://php.net/manual/en/session.configuration.php#ini.session.save-path
