### ISSUE TITLE
Old password usage - Policy

### ISSUE THREAD

**Issue by ibou95** [ltb-project/self-service-password#373]
Hello Team, 

Is there a way to block the usage of the 5 old password during the reset ? 

Thanks in advance :)

**Comment by JuJuMDX** [comment]
Hello,
I think it is a setting in your directory. In the config file, we just have this before directory password policy : 
```
# Local password policy
# This is applied before directory password policy
# Minimal length
$pwd_min_length = 0;
# Maximal length
$pwd_max_length = 0;
# Minimal lower characters
$pwd_min_lower = 0;
# Minimal upper characters
$pwd_min_upper = 0;
# Minimal digit characters
$pwd_min_digit = 0;
# Minimal special characters
$pwd_min_special = 0;
# Definition of special characters
$pwd_special_chars = "^a-zA-Z0-9";
# Forbidden characters
#$pwd_forbidden_chars = "@%";
# Don't reuse the same password as currently
$pwd_no_reuse = true;
# Check that password is different than login
$pwd_diff_login = true;
# Complexity: number of different class of character required
$pwd_complexity = 0;
```

**Comment by ibou95** [comment]
Bonjour JuJu,

Tout d'abord, merci pour votre réponse. Ma question est en fait plus su le possibilité ou non d'utiliser les 5 derniers mots de passe. Il me semble que la fonction $pwd_no_reuse = true interdit uniquement le dernier mot de passe, pas les 5. 

Merci bcp

PS : Dites-moi si je dois refaire mon message en anglais :)

**Comment by JuJuMDX** [comment]
SSP ne replace pas la politique de votre annuaire. 
Si votre annuaire n'autorise pas l'utilisation des 5 derniers mots, SSP ne pourra utiliser les 5 derniers mot de passe.
Il en est de même pour les différents paramètres que vous pouvez configurer dans le fichier de configuration.
Il sont utilisé afin d'afficher les message d'aide et effectuer un check avant d'envoyer la requête à votre annuaire.

**Comment by coudot** [comment]
I confirm, the password history is not implemented in SSP, it should be managed by the LDAP directory. For example with OpenLDAP, you can use ppolicy overlay to enable password history.

**Comment by jfoucry** [comment]
Hello,

Back to this old question.

I'm sorry but, I use OpenLDAP, with ppolicy and not reuse 4 last passwords.

With SPP I can change my password to the previous and come back. It seems SPP does not understand the password history implemented in the ppolicy.

Any advise to make it working?

Thanks in advance

**Comment by coudot** [comment]
@jfoucry do not use OpenLDAP rootdn as bind DN in SSP.

**Comment by jfoucry** [comment]
Hello @coudot 

Thanks for your answer and sorry to be so late.

Did I need a special DN for SSP?

**Comment by jfoucry** [comment]
Ooops, I found in the documentation `$ldap_dn`, `$ldap_passwd` and `$who_change` parameters working together.

I change it (`$ldap_dn` and `$ldap_passwd` empty and `$who_change='user'`), but the ppolicy is not use. I still can change my password and back to the old one.
The `$pwd_no_reuse` is set to `true`.
Thanks again for you advices

**Comment by coudot** [comment]
@jfoucry If you use OpenLDAP rootdn, OpenLDAP will not apply password policy, you must use a service account

**Comment by ibou95** [comment]
Thanks for your reply. Sorry I don't find how to create a service account in OpenLdap. Would you know how to do that please ? What is the account type I should use ? 
Best

**Comment by coudot** [comment]
Create any account and set OpenLDAP ACLs to allow this account to change passwords for all users

Accout example:
```
dn: cn=ssp,ou=dsa,dc=example,dc=com
cn: ssp
userPassword: xxxx
objectClass: organizationalRole
objectClass: top
objectClass: simpleSecurityObject
```

**Comment by coudot** [comment]
Note the ppolicy control is now supportedin 1.4 release
