### ISSUE TITLE
Email and login not same

### ISSUE THREAD

**Issue by hudojnick** [ltb-project/self-service-password#374]
How I can send token to another email than login? If I wanna send to outside email...

**Comment by coudot** [comment]
You can configure which LDAP attribute is used for mail: https://ltb-project.org/documentation/self-service-password/latest/config_mail

**Comment by hudojnick** [comment]
No, maybe I'm not correctly said...I wanna send token to outside email, ex. - AD acc and AD email: test1@test.com; Email which I need to send: test2@gmail.com.

**Comment by coudot** [comment]
Store the second email in another AD attribute, and set this attribute as mail attribute

**Comment by hudojnick** [comment]
I can't send without AD attr?

**Comment by coudot** [comment]
No, the goal is that only the user can validate the password reset
