### ISSUE TITLE
LDAP mail attribute problems

### ISSUE THREAD

**Issue by hudojnick** [ltb-project/self-service-password#376]
Hello!
How I can send mail to different mail address? 
Ex. I have my needed mail in ldap - facsimileTelephoneNumber
If I change in `conf/config.inc.php - $mail_attribute = "login";` I take errors.

**Comment by coudot** [comment]
Why don't you set:
```php
$mail_attribute = "facsimileTelephoneNumber"
```

**Comment by hudojnick** [comment]
I need send email token to user, but he is don't know his login, his know only yourself email addr. and what and where I should change in order to do it?

**Comment by hudojnick** [comment]
> Why don't you set:
> 
> ```
> $mail_attribute = "facsimileTelephoneNumber"
> ```

It is not work too...

**Comment by coudot** [comment]
We can't help if you're not providing any logs.
