### ISSUE TITLE
selfservice password integration with AWS Simple AD

### ISSUE THREAD

**Issue by alnhk** [ltb-project/self-service-password#378]
Hello.,

We are trying to setup self service portal for password reset support., integration is AWS Simple AD (which we can see that it is microsoft AD), we set below detail in the conf.ini.php, on testing  password reset , i am getting this exception "Cannot access LDAP directory", did set "$debug = true;" however we dont find the log anywhere, even ssp_error.log is empty., please let me know where log will be. And also, please let me know if theres an issue with below config.

```
# LDAP
$ldap_url = "ldap://hostaddress:389";
$ldap_starttls = false;
$ldap_binddn = "cn=admin,cn=Users,dc=acme,dc=com";
$ldap_bindpw = "restricted";
$ldap_base = "dc=acme,dc=com";
$ldap_login_attribute = "sAMAccountName";
$ldap_fullname_attribute = "cn";
$ldap_filter = "(&(objectClass=user)($sAMAccountName={login}))";


# Active Directory mode
# true: use unicodePwd as password field
# false: LDAPv3 standard behavior
$ad_mode = true;
# Force account unlock when password is changed
$ad_options['force_unlock'] = true;
# Force user change password at next login
$ad_options['force_pwd_change'] = true;
# Allow user with expired password to change password
$ad_options['change_expired_password'] = true;
```

And also did tested using certificate 
```

[root@acme00001 httpd]# openssl s_client -connect hostaddress:389 -CAfile auth3t.pem
CONNECTED(00000003)
write:errno=104
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 332 bytes
Verification: OK
---
```

**Comment by coudot** [comment]
First, you will need to use LDAPS and port 636 to connect to AD, else you will not be able to modify password.

Then, you must be sure that there is no protection (like SELinux) that prevents your PHP application to contact the LDAP server.

**Comment by alnhk** [comment]
Hmm..is LDAPS and port 636 mandatory in order to connect to AD ?

**Comment by coudot** [comment]
Yes, see https://ltb-project.org/documentation/self-service-password/latest/config_ldap#active_directory

**Comment by alnhk** [comment]
Seriously, i created ldaps as well as 636, still continue to encounter "Cannot Access LDAP directory", below is the updated (only LDAPS and 636), despite $debug = true; still its populating the error log file for self service password portal.  Is there anything to correct/debug ? yes, using LDAPS/636, i am able to connect using jxplorer as part of verification.

```
$ldap_url = "ldaps://hostaddress:636";
$ldap_starttls = false;
$ldap_binddn = "cn=admin,cn=Users,dc=acme,dc=com";
$ldap_bindpw = "restricted";
$ldap_base = " OU=people,DC=devsnc-test,DC=com";
$ldap_login_attribute = "sAMAccountName";
$ldap_fullname_attribute = "cn";
$ldap_filter = "(&(objectClass=user)(sAMAccountName={login})(!(userAccountControl:1.2.840.113556.1.4.803:=2)))";

$ad_mode = true;
# Force account unlock when password is changed
$ad_options['force_unlock'] = true;
# Force user change password at next login
$ad_options['force_pwd_change'] = true;
# Allow user with expired password to change password
$ad_options['change_expired_password'] = true;
```

**Comment by alnhk** [comment]
@coudot  : any update please

**Comment by coudot** [comment]
Did you configure ldap.conf to set where your CA certificate is installed?

**Comment by ocoranes** [comment]
Hi! I have the same issue working with Windows AD. Password was refused by the LDAP directory if I used..
$ldap_url = "ldap://hostaddress:389";
$ldap_starttls = false;

 Cannot access LDAP directory if I set to 

$ldap_url = "ldaps://hostaddress:636";
$ldap_starttls = false;

Question: Do we need to install ldap on SPP server? or just hook to windows AD?

**Comment by pcurie** [comment]
Please note that AWS Simple AD is not a MS AD, but a Samba 4 AD.

> Simple AD is a standalone managed directory that is powered by a Samba 4 Active Directory Compatible Server. It is available in two sizes. 

So you might need to use samba mode and not ad mode, but I didn't test either.

**Comment by rhegde1** [comment]
Try this:

$ldap_url = "ldaps://mydc.mydomain.xx.xx/DC=SFA,DC=XX"

I was able to get pass "Cannot access ldap directory"

**Comment by prabhu87** [comment]
I have tried with $ldap_url = "ldaps://mydc.mydomain.xx/DC=xxx,DC=XX" but not working.

Does anybody got success with AWD Directory Service with self password reset tool.

My Setups is, AWD Directory service > AWS Windows AD
