### ISSUE TITLE
Debian packages for buster / new releases?

### ISSUE THREAD

**Issue by rschwebel** [ltb-project/self-service-password#379]
Hi,

I'm interested in debian packages for self-service-password; however, there seem to be no packages for buster, and the 1.3 release is really outdated.

Would you be interested in making a new release and creating new debian packages?

Thanks,
Robert

**Comment by coudot** [comment]
Hello,

you can use the current package for buster, it works well.

We are indeed working on version 1.4, we have a lot a pull requests to check and issues to fix. I can't give any date for the release.

**Comment by rschwebel** [comment]
Hi & thanks for your quick response!

Installing the jessie version (as outlined in the documentation) on buster works, thanks!

However, it is a little bit surprising (especially as there actually _is_ a buster directory on the server), so a short hint in the documentation or - even better - real buster packages would be great! :-)

Robert
