### ISSUE TITLE
Blank page on fresh install

### ISSUE THREAD

**Issue by coamtaker618** [ltb-project/self-service-password#380]
Fresh install of Ubuntu server 18.04.  Followed instructions here:
https://ltb-project.org/documentation/self-service-password/latest/install_debian

Expected:
Something, ideally a screen like this (https://ltb-project.org/documentation/self-service-password) but at least some error message.

Received:
Blank screen

Other info (short):
I believe there's an issue with index.php in self-service-password

How do I go about debugging that issue?
Are there any logs or debug traces available?

Other info (long):
1) I tried installing manually first with same results, deleted /var/www/self-service-password folder from that install (so I don't think anything will be left).  I also successfully setup certbot, so I have HSTS to this server.  Is it possible that cert is interfering somehow?
2) When I run a simple phpinfo.php file (manually inserted to /var/www/self-service-password), I see a long info page (as expected) when I visit domain./phpinfo.php   <--  This leads me to believe that php & certs are functioning properly and that there's an error being thrown on the index.php page.

**Comment by coudot** [comment]
try to set `$debug = true;`

**Comment by coamtaker618** [comment]
coudot thanks for the reply :)   Where do I set the variable?  Is there a place to set it in the index.php file? Is it read from a config file? Is it a bash environment variable?

**Comment by dgeo** [comment]
https://ltb-project.org/documentation/self-service-password/latest/config_general#configuration_files

En thé config file I think

**Comment by coamtaker618** [comment]
*facepalm* thanks dgeo, I totally forgot there was a config file (trying to do too many things at once)  Lemme add that and try!

**Comment by coamtaker618** [comment]
ok, I saw the debug variable in the config file already.  Set it to true (was false).  reloaded apache (sudo systemctl reload apache2). no change :(   Still a blank page.

**Comment by coamtaker618** [comment]
I hope this doesn't make me a terrible person (maybe a tad impatient?) >_> but I'm still getting a totally blank screen after changing the log setting as described above

*bump*

**Comment by coudot** [comment]
Blank screen means there is a PHP error, this could be a missing module (check prerequisites). You should see an error in a log somewhere.

**Comment by coamtaker618** [comment]
Ahhh, makes sense.  Thank you for the response coudot.  I did a quick check and:

1) did not see any log or error file?  I did a search of the conf file and didn't see anywhere to set the path?  I also searched my ssp folder, but maybe I just overlooked it?

2) I am embarrassed to say I double checked and am indeed missing a pre-req >_<  

php-filter, the last one listed.  However I seem to also be missing the repo for it (Ubuntu Server 18-04 LTS), so I cannot merely "apt install php-filter" it as I'd like to :( 

Further when I try to google search for the repo, the only thing I fnd are sketchy websites and "php70" which seems to install a number of other php-extensions I don't want.  Is there a known/recommended Debian repo for the required php-filter?

Thanks!

**Comment by coudot** [comment]
> did not see any log or error file? I did a search of the conf file and didn't see anywhere to set the path? I also searched my ssp folder, but maybe I just overlooked it?

Did you look into Apache log files?

php-filter should be included by default in php main package

**Comment by coamtaker618** [comment]
Hrm, I hope so...I don't see it in

php -i | grep "filter" 

but I hope it's included.  Everything else claims to be up to date when I apt install it!


Per your suggestion, I checked the Apache logs.  I see a common thread:
Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in /var/www/self-service-password/conf/config.inc.local.php on line 332

I edited the php.ini file that the php -i command pointed to (raised max to 2 GB, the cli was set to -1 which I left alone) and "sudo systemctl restart apache2" to restart Apache.  I'm still getting a blank page but not seeing any new entry to the apache error log.

**Comment by coudot** [comment]
Check that you did not just copy config.inc.php to config.inc.local.php, which is not the way to do. There is an inclusion at the bottom of the file, which will create a recursive loop and crash your server.

**Comment by coamtaker618** [comment]
oh! I did exactly that.  What line should be included that I'm leaving out or vice-versa?

**Comment by coamtaker618** [comment]
Ok, wanted to update (maybe close and reopen?).  I started a new installation of this tool (fresh Ubuntu Server install) & now cannot find the config file after the apt install (previously I cloned from github).

My installation steps:
0) php pre-reqs listed here (also, install php)
https://github.com/ltb-project/self-service-password

1) follow this guide:
https://ltb-project.org/documentation/self-service-password/latest/start

1a) do apt install as described here (adding repo)
https://ltb-project.org/documentation/self-service-password/latest/install_debian

1b) update web service (apache) as listed here:
https://ltb-project.org/documentation/self-service-password/latest/config_apache

(note: this would be a good point to ALSO have instructions for certbot as I expect HTTPS is essential to actually using this tool).

1c) change config as listed here:
https://ltb-project.org/documentation/self-service-password/latest/config_general

except---have no idea where the config is.  the apache script lists "DocumentRoot /usr/local/self-service-password" but ls -al (after apt install & apt update) shows the date on the /usr/local folder has not changed, so it seems that path is not correct.

**Comment by coudot** [comment]
With packages, the product is installed in /usr/share and /usr/local. /usr/local is for manual installation

**Comment by coamtaker618** [comment]
Thanks coudot, that'll do it :)  I'm now able to see the page on http!

At this point, I'm happy to file this bug as closed (as I am no longer getting a blank page)--but would appreciate any references you have for getting this to work with https (especially certbot).
