### ISSUE TITLE
create centos 8 package & remove httpd dependency

### ISSUE THREAD

**Issue by lt-holman** [ltb-project/self-service-password#381]
Your website provides a repository for `yum`/`dnf` for updating the software as described [https://ltb-project.org/documentation/self-service-password/1.3/install_rpm](here).  However, it only supports Red Hat / CentOS 7.   Could you provide a package for Red Hat 8 / CentOS 8.

Additionally, when I use the earlier package it has a dependency on 'httpd'.  Could this be removed as the software also works with any web server (for example 'nginx').

**Comment by coudot** [comment]
Note that we will use Smarty for next release, and Smarty is not yet packaged for CentOS 8.

An issue was opened: https://bugzilla.redhat.com/show_bug.cgi?id=1818971

You can comment and vote for it.

**Comment by coudot** [comment]
Package for Smarty is available in LTB repo: https://ltb-project.org/rpm/8/noarch/

**Comment by coudot** [comment]
Removing httpd dependency seems to much work for now, please open a new issue if this is really needed.

Closing this issue for the CentOS8 part.
