### ISSUE TITLE
Expose more PHPMail parameters

### ISSUE THREAD

**Issue by mirkocomparetti-synesis** [ltb-project/self-service-password#382]
Hello,
In my installation I had to work on the $mailer->SMTPOptions manually as they are not exposed in the configuration file. Would it be possible to expose them as well?

Thanks!

**Comment by coudot** [comment]
Should not be difficult, propose a PR if you can.

**Comment by mirkocomparetti-synesis** [comment]
Actually I did the change already; let me find out how to do the PR and I will.
