### ISSUE TITLE
Custom HTML

### ISSUE THREAD

**Issue by lingfish** [ltb-project/self-service-password#385]
Would be nice to have the ability to inject custom HTML (usually in HEAD), like Google Analytics code etc.

**Comment by coudot** [comment]
You can for the moment edit index.php

We are working on using Smarty (see #372)

**Comment by lingfish** [comment]
Hi, I see that Smarty has been implemented, but I must be missing something; I still don't see any easy way (without forking) to change actual HTML?  eg. the title, `sendtokenhelp` etc.  anything set in `$messages` for that stuff just gets stomped on when the code loads language...

**Comment by coudot** [comment]
You can override messages by creating a file like conf/en.inc.php

You can use a custom CSS file: https://self-service-password.readthedocs.io/en/v1.4/config_general.html#custom-css

You can modify HTML templates but indeed they will be replaced at next upgrade.

**Comment by LlGC-szw** [comment]
Hi, is there any news on this redesign?

**Comment by coudot** [comment]
There is no redesign planned for now
