### ISSUE TITLE
 Windows 10 login mask

### ISSUE THREAD

**Issue by Ressort-Informatik** [ltb-project/self-service-password#386]
Hello everybody

Is it technically feasible?
If I connect to the Windows 10 login mask and I press Forgot password, you should go to the specific website to reset the password

![image](https://user-images.githubusercontent.com/61539032/81561780-049c0c80-9394-11ea-926b-e31479b1b656.png)

**Comment by coudot** [comment]
Look maybe at https://github.com/pgina/pgina
