### ISSUE TITLE
Unable to send email

### ISSUE THREAD

**Issue by homero10** [ltb-project/self-service-password#391]
Hi,

I have configured Self Service Password for send emails for password recuperation. But the email doesn't send.

The file configuration (the email part) is:
```php
## Mail
$use_mail = true;
# LDAP mail attribute
$mail_attribute = "mail";
# Get mail address directly from LDAP (only first mail entry)
# and hide mail input field
# default = true
$mail_address_use_ldap = true;
# Who the email should come from
$mail_from = "myuser@gmail.com";
$mail_from_name = "Notification from Self Service Password";
$mail_signature = "";
# Notify users anytime their password is changed
$notify_on_change = true;
# PHPMailer configuration (see https://github.com/PHPMailer/PHPMailer)
$mail_sendmailpath = '/usr/sbin/sendmail';
$mail_protocol = 'smtp';
$mail_smtp_debug = 0;
$mail_debug_format = 'error_log';
$mail_smtp_host = 'mail.google.com';
$mail_smtp_auth = true;
$mail_smtp_user = 'myuser@gmail.com';
$mail_smtp_pass = 'mypass';
$mail_smtp_port = 587;
$mail_smtp_timeout = 30;
$mail_smtp_keepalive = false;
$mail_smtp_secure = 'tls';
$mail_smtp_autotls = true;
$mail_contenttype = 'text/plain';
$mail_wordwrap = 0;
$mail_charset = 'utf-8';
$mail_priority = 3;
$mail_newline = PHP_EOL;
```
Any idea? Thanks

**Comment by coudot** [comment]
You can first set `$mail_smtp_debug` to `2` to have more info on your problem

Check in your Gmail account security settings that you allow this PHP application to send mail

**Comment by homero10** [comment]
Thank you

I have changed the $mail_smtp_debug from 0 to 2, but i don't know where i can see the debug

**Comment by coudot** [comment]
Set also `$debug`to `true` and see what is displayed on the web page

**Comment by homero10** [comment]
Nope, don't work.

PD: The Self Service Password is running on Docker (from the oficial docker-compose)

**Comment by homero10** [comment]
Update: in the Docker container, the sendmail command shows on display:

sendmail: can't connect to remote host (127.0.0.1): Connection refused

**Comment by coudot** [comment]
Maybe this is linked to your Docker setup, the mail host should be `mail.google.com` and not `127.0.0.1`

**Comment by homero10** [comment]
I have tried on a Debian 10 virtual machine install the self service and i works. The problem maybe is in the Docker image

**Comment by homero10** [comment]
The issue has been resolved.

I installed a Debian CT on Proxmox and later the self-service-password and sendmail packages.

The problem maybe is in Docker image.

Tnanks you very much!
