### ISSUE TITLE
Unable to make the application work with weird error

### ISSUE THREAD

**Issue by jas01** [ltb-project/self-service-password#392]
Hi
 I've some issue to make the application work. 

I've running a old version since long time without problem

I just upgrade our ldap server from some very old version to the latest (in debian).

Currently I'm unable to change any password throught the self-service-password.

Here the configuration I put in the config.inc.local.php
```php
<?php
$ldap_url = "ldaps://FQDN";
$ldap_binddn = "DN";
$ldap_filter = "(&(objectClass=person)(uid={login}))";
$ldap_bindpw = "PASSWORD";
$ldap_base = "BASE";
$samba_mode = true;
$shadow_options['update_shadowLastChange'] = true;
$hash = "SSHA";
$pwd_min_length = 8;
$pwd_complexity = 3;
$pwd_show_policy = "onerror";
$who_change_password = "user";
$use_questions = false;
$use_sms = false;
$use_token=true;
$crypt_token=true;
$keyphrase='SOMETHING';
$debug = true;
?>
```

When I try to change a password I always get 
```
Warning: ldap_get_dn() expects parameter 2 to be resource, boolean given in /var/www/password/pages/change.php on line 105

Notice: Undefined variable: obscure_failure_messages in /var/www/password/pages/change.php on line 186

Warning: in_array() expects parameter 2 to be array, null given in /var/www/password/pages/change.php on line 186
 Identifiant ou mot de passe incorrect


Notice: Undefined variable: display_posthook_error in /var/www/password/pages/change.php on line 193
```

I try to manually bind the BIND user on the server with a ldapwhoami and it's working perfectly.

I also try to manually change the password with ldappasswd (bind with the user who want to change the password), and it's working to. 

The server (ldap) running Debian latest (every package are up2date).

I've the feeling the server give the client some answer he didn't expected. When he say «boolean» I've think it's more likely something empty

Regards

**Comment by jas01** [comment]
Thanks for the super fast answer....
But...no I also try with ldap://fqdn

**Comment by coudot** [comment]
then try to find logs

**Comment by jas01** [comment]
I try to enable the log inside ldap, after 1Go of log, I think I find the problem, and it's very weird because I cannot imagine I'm the only one who get this error.

It's seem event with 
```
$who_change_password = "user";
```
It's still the BIND_USER who try to change the password. So I change the acl of my server to add  to BINDUSER the *write* right and it's working. 

Before with the old version It's indeed the user who make the change.
