### ISSUE TITLE
Multiple objectClass on ldap_filter

### ISSUE THREAD

**Issue by maceffi** [ltb-project/self-service-password#393]
I'm trying to do a mulitple object class ldap_filter and it does not seem to work.
here is the error message.
PHP message: LDAP - Search error -7  (Bad search filter)
PHP message: PHP Notice:  Undefined variable: obscure_failure_messages in /var/www/PasswordService/pages/change.php

I added this in the config.inc.php but does not work.
$ldap_filter = "(&(objectClass=person)(!objectClass=mycustomclass)($ldap_login_attribute={login}))";

Is it possible to create a multiple objectclass ?

**Comment by maceffi** [comment]
I also tried removing ! at (!objectClass=mycustomclass). It only works with one objectClass. I want it to search for either or (objectClass=person) OR (objectClass=mycustomclass).

**Comment by maceffi** [comment]
I found the correct way. There should be a pipe. I guess you can close this, Thnks.

(&(|(objectClass=mycustomclass)(objectClass=person))

**Comment by coudot** [comment]
`!` is for negation, like this: `(!(objectClass=mycustomclass))`
