### ISSUE TITLE
Logging resets not functioning

### ISSUE THREAD

**Issue by ehprivacy** [ltb-project/self-service-password#394]
I'm using self-service-password via nginx and php-fpm on a FreeBSD 12.1 system.
I need to have the password resets logged with user and timestamp (not the password itself, of course).  Based on the comments in config.inc.php, I believed that setting $reset_request_log in config.inc.php would accomplish this.

However, that log is never touched, and the only 3 files that even reference that variable are:
sendtoken.php
sendsms.php
config.inc.php

so it seems that it's never being called when the password is reset via the old password.

**Comment by coudot** [comment]
The `$reset_request_log` parameter is indeed only useful when tokens are sent to reset the password, as logging the reset URL allows to change the password on behalf of the user.
There is no such issue when password is changed with old password.

You can use the posthook script to log password changes.

**Comment by TheAshwanik** [comment]
> I'm using self-service-password via nginx and php-fpm on a FreeBSD 12.1 system.
> I need to have the password resets logged with user and timestamp (not the password itself, of course). Based on the comments in config.inc.php, I believed that setting $reset_request_log in config.inc.php would accomplish this.
> 
> However, that log is never touched, and the only 3 files that even reference that variable are:
> sendtoken.php
> sendsms.php
> config.inc.php
> 
> so it seems that it's never being called when the password is reset via the old password.

Hi.. Did you ever get to do this?
I am in similar situation where I want to keep all logs of who tried to reset the password, date, time stamp regardless of the success/failure. This is needed for audit purposes and would be a great addition.
