### ISSUE TITLE
News about version 1.4

### ISSUE THREAD

**Issue by codesmaker** [ltb-project/self-service-password#396]
Hi guys,

Any news about when v1.4 will be released? Will it be compatible with Debian 10?

Thanks for the great work!

**Comment by coudot** [comment]
There is a list of pull requests and issues to review, there is no planned date for the release.

SSP is already compatible with Debian 10.

**Comment by coudot** [comment]
Follow milestone here: https://github.com/ltb-project/self-service-password/milestone/7
