### ISSUE TITLE
SMTP Error: Could not connect to SMTP host.

### ISSUE THREAD

**Issue by bcaxc19921102** [ltb-project/self-service-password#398]
**_When sending a password reset email I get something wrong.The error log is below._**

[Thu Jun 11 21:10:58.917033 2020] [php7:notice] [pid 3727:tid 139726854006528] [client 172.16.20.15:59297] Send reset URL http://172.16.14.81/index.php?action=resetbytoken&token=3vUCAMdTldZPAcz0QVzkSvDW6fzN97XK6a7%2FY%2FrjN02PvV7baDpwuPoUpbe9CW7OeBnrTW7jfWLlxfWCAwRXMLXAKeU4A%2BZz7X1d%2B6g%2FTpb2ov53qpz9i8lcgaBsj60vLz%2BaXr0KuKUvNlTC0adKdj0Xj2I%3D, referer: http://172.16.14.81/?action=sendtoken
[Thu Jun 11 21:10:58.939588 2020] [php7:notice] [pid 3727:tid 139726854006528] [client 172.16.20.15:59297] SERVER -> CLIENT: 220 SH2PR01CA009.partner.outlook.cn Microsoft ESMTP MAIL Service ready at Thu, 11 Jun 2020 13:10:58 +0000\r\n, referer: http://172.16.14.81/?action=sendtoken
[Thu Jun 11 21:10:58.939629 2020] [php7:notice] [pid 3727:tid 139726854006528] [client 172.16.20.15:59297] CLIENT -> SERVER: EHLO 172.16.14.81\r\n, referer: http://172.16.14.81/?action=sendtoken
[Thu Jun 11 21:10:58.949662 2020] [php7:notice] [pid 3727:tid 139726854006528] [client 172.16.20.15:59297] SERVER -> CLIENT: 250-SH2PR01CA009.partner.outlook.cn Hello [202.101.191.115]\r\n250-SIZE 157286400\r\n250-PIPELINING\r\n250-DSN\r\n250-ENHANCEDSTATUSCODES\r\n250-STARTTLS\r\n250-8BITMIME\r\n250-BINARYMIME\r\n250-CHUNKING\r\n250 SMTPUTF8\r\n, referer: http://172.16.14.81/?action=sendtoken
[Thu Jun 11 21:10:58.949723 2020] [php7:notice] [pid 3727:tid 139726854006528] [client 172.16.20.15:59297] CLIENT -> SERVER: STARTTLS\r\n, referer: http://172.16.14.81/?action=sendtoken
[Thu Jun 11 21:10:58.958584 2020] [php7:notice] [pid 3727:tid 139726854006528] [client 172.16.20.15:59297] SERVER -> CLIENT: 220 2.0.0 SMTP server ready\r\n, referer: http://172.16.14.81/?action=sendtoken
### **[Thu Jun 11 21:10:58.986806 2020] [php7:notice] [pid 3727:tid 139726854006528] [client 172.16.20.15:59297] SMTP Error: Could not connect to SMTP host., referer: http://172.16.14.81/?action=sendtoken**
[Thu Jun 11 21:10:58.986836 2020] [php7:notice] [pid 3727:tid 139726854006528] [client 172.16.20.15:59297] CLIENT -> SERVER: QUIT\r\n, referer: http://172.16.14.81/?action=sendtoken
[Thu Jun 11 21:10:58.987754 2020] [php7:notice] [pid 3727:tid 139726854006528] [client 172.16.20.15:59297] SERVER -> CLIENT: \x16\x03\x03, referer: http://172.16.14.81/?action=sendtoken
[Thu Jun 11 21:10:58.987768 2020] [php7:notice] [pid 3727:tid 139726854006528] [client 172.16.20.15:59297] SMTP ERROR: QUIT command failed: \x16\x03\x03, referer: http://172.16.14.81/?action=sendtoken
[Thu Jun 11 21:10:58.988719 2020] [php7:notice] [pid 3727:tid 139726854006528] [client 172.16.20.15:59297] SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting, referer: http://172.16.14.81/?action=sendtoken
[Thu Jun 11 21:10:58.988735 2020] [php7:notice] [pid 3727:tid 139726854006528] [client 172.16.20.15:59297] send_mail: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting, referer: http://172.16.14.81/?action=sendtoken
[Thu Jun 11 21:10:58.988740 2020] [php7:notice] [pid 3727:tid 139726854006528] [client 172.16.20.15:59297] Error while sending token to chencx@pingpongx.com (user chencx), referer: http://172.16.14.81/?action=sendtoken
[Thu Jun 11 21:10:58.988763 2020] [php7:notice] [pid 3727:tid 139726854006528] [client 172.16.20.15:59297] PHP Notice:  Undefined variable: obscure_failure_messages in /data/www/ssp/pages/sendtoken.php on line 212, referer: http://172.16.14.81/?action=sendtoken
[Thu Jun 11 21:10:58.988804 2020] [php7:warn] [pid 3727:tid 139726854006528] [client 172.16.20.15:59297] PHP Warning:  in_array() expects parameter 2 to be array, null given in /data/www/ssp/pages/sendtoken.php on line 212, referer: http://172.16.14.81/?action=sendtoken

**_I think the parameters in the php conf file is correct however I can't connect to the mail server.
Many thanks_**

**Comment by coudot** [comment]
The issue is with your SMTP server, it is written in the logs.

You should see on SMTP server side why your connection is rejected. Maybe an authentication issue.
