### ISSUE TITLE
Password Reset Refused Through Email Token

### ISSUE THREAD

**Issue by jaevan21** [ltb-project/self-service-password#399]
I am using ssp 1.3-1 in RHEL environment.  Basic password changing is working fully okay, however when user follow email token and try to reset password it shows " Password was refused by the LDAP directory". 

Attached the error log. can anyone suggest what might be the issue here ? 
[ssp-error.txt](https://github.com/ltb-project/self-service-password/files/4825777/ssp-error.txt)

**Comment by coudot** [comment]
Your log only show the result of an LDAP search.

When using reset by token, the password cannot not be changed "as user" because old password is no known, so it is changed by application account. Check the rights of this account, it must be able to change password.

**Comment by jaevan21** [comment]
Thanks for reply. 

I'm fairly new in this domain. Did you meant whether user have right to change their password ? yes. all user has right to change their password.  following is example from linux client

```
# ssh testuser@localhost
testuser@localhost's password: 
Last login: Wed Jun 24 22:10:00 2020 from localhost
-bash-4.2$ passwd
Changing password for user testuser.
(current) LDAP Password: 
New password: 
Retype new password: 
passwd: all authentication tokens updated successfully.
```
I am not sure which log to filter for this case. That's why I have attached whole log file. 

[ssp_error_log.txt](https://github.com/ltb-project/self-service-password/files/4826625/ssp_error_log.txt)

**Comment by coudot** [comment]
Configure an application account that can write passwords: https://ltb-project.org/documentation/self-service-password/latest/config_ldap#credentials

**Comment by jaevan21** [comment]
okay I get it. Actually I have user configured for application. But I don't know how to give the user permission to change password of others. I have a admin user with organizational role. But when I configure the admin user as application user, ssp show can't access ldap directory. btw I am using openldap 2.4. I know it may not directly related to your app but would really appreciate your help.

**Comment by coudot** [comment]
You need to define an ACL for this, or if you want a fast (but unsecure) solution, just use the OpenLDAP rootdn as SSP binddn.

Else an ACL could be something like:
```
olcAccess: {0}to attrs=userPassword by dn.base="cn=ssp,ou=dsa,dc=example,dc=com" write by self write by * auth
