### ISSUE TITLE
Keep sending reset requests

### ISSUE THREAD

**Issue by taten14** [ltb-project/self-service-password#401]
On the page "Mail Confirmation has been sent" if i press F5 keeps sending the email over and over.

**Comment by coudot** [comment]
This could be avoided by enabling captcha

**Comment by coudot** [comment]
Seems same issue as #763

**Comment by davidcoutadeur** [comment]
I am going to see if this is the same bug as in #763

**Comment by davidcoutadeur** [comment]
This is the same issue as #763.

Enabling the captcha prevents the resend.

However, without captcha, we could store an additional token for avoiding this behavior.
