### ISSUE TITLE
header Samesite verification on Google Chrome Failed 

### ISSUE THREAD

**Issue by juniper275** [ltb-project/self-service-password#402]
A cookie associated with a cross-site resource at https://www.google.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

I tried with  Header edit on Apache but with no success (on virtualhost)

Header always edit Set-Cookie ^(.*)$ $1;HttpOnly;Secure;SameSite=Strict

Some suggestion?

**Comment by plewin** [comment]
Hi,
I'm thinking this is probably not related to SSP. This warning message literally says that an action may have to be done on www.google.com servers not yours. I am guessing you are using recaptcha, it would explain why there would be a cookie exchange with www.google.com.

I don't think adding
```
Header always edit Set-Cookie ^(.*)$ $1;HttpOnly;Secure;SameSite=Strict
```
In SSP's apache would be of any help, that would configure cookies headers for SSP but not the one from www.google.com where and an issue has been reported.

Also are you able to reproduce your issue in a fresh incognito window ? Perhaps there is an issue with old cookies in your browser.

**Comment by juniper275** [comment]
> Hi,
> I'm thinking this is probably not related to SSP. This warning message literally says that an action may have to be done on [www.google.com](http://www.google.com) servers not yours. I am guessing you are using recaptcha, it would explain why there would be a cookie exchange with [www.google.com](http://www.google.com).
> 
> I don't think adding
> 
> ```
> Header always edit Set-Cookie ^(.*)$ $1;HttpOnly;Secure;SameSite=Strict
> ```
> 
> In SSP's apache would be of any help, that would configure cookies headers for SSP but not the one from [www.google.com](http://www.google.com) where and an issue has been reported.
> 
> Also are you able to reproduce your issue in a fresh incognito window ? Perhaps there is an issue with old cookies in your browser.

You are right, deleting old cookies from browser chrome test works fine, sorry for the misunderstanding, chrome developer tools are not perfect..
