### ISSUE TITLE
Change Interface.

### ISSUE THREAD

**Issue by juniorvsm** [ltb-project/self-service-password#403]
Hello, I would like to remove the blocks marked in red from the image below, from my interface ltb-project.
What files should I edit or remove?

![ltb-image](https://user-images.githubusercontent.com/53951593/88461870-d2bc2180-ce7d-11ea-9dda-41b011a85c1c.PNG)

**Comment by plewin** [comment]
Hi,

1) There is no option to disable this block, this block is where errors are shown if there are any.
If you are serious about hiding this block, you could fork SSP and modify around here https://github.com/ltb-project/self-service-password/blob/v1.3/pages/change.php#L189 and only display the block if get_criticity != 'success'
I would recommend against disabling this block, you can also change the text in the lang file if this can solve your issue.

2) Set show_help = false in config
https://github.com/ltb-project/self-service-password/blob/v1.3/conf/config.inc.php#L247

**Comment by juniorvsm** [comment]
Thanks for the answer.
