### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by PGTBoos** [ltb-project/self-service-password#417]
I'd like the manual to be improved: 

Dont use the $ldap_binddn = "cn=manager,dc=example,dc=com"; 
But use something like  "cn=SSP,dc=users,dc=organization,dc=com"
It leads to confusion when later its said :
To use user's credentials when writing in LDAP directory, replace manager with user in $who_change_password:
$who_change_password = "user";
over-there for manager its apparently not "whoever user you named earlier in the ldap-binddn".
_(better would have been $use_manager_to_Change_password = true; / false; )_

Also 
Make it clear that for people who use AD Samba, that they do not require Samba mode
But just the Active Directory as a windows environment would.

**Comment by coudot** [comment]
Hello, documentation is now included in code, feel free to propose changes by editing https://github.com/ltb-project/self-service-password/blob/master/docs/config_ldap.rst

**Comment by coudot** [comment]
Doc updated
