### ISSUE TITLE
works with admin but not with a specific account. Samba 4.12.6

### ISSUE THREAD

**Issue by PGTBoos** [ltb-project/self-service-password#418]
In a Samva 4.12.6 AD, we get this working using the administrator account, but we want to use it with the user SSP, who is a normal user with delegated rights to change passwords.

The delegation permissions have been granted to SSP, and i can confirm they work.
Because user SSP can use the MMC users and computers, to change passwords of other users.

It fails on ldap_bind(): unable to bind to server: invalid credentials in /usr/share/self-service-password/pages/change.php on line 80 referer https:/xxxxxxxxxxxxxxxxxxxx   
Bind error 49 (invalid credentials)
.
The scripted password matches the login password, there is no typo (verified it).

ldap conf looks like
```batch
TLS_REQCERT never
TLS_CACERT	/etc/ssl/certs/ca-certificates.crt
```
The altered lines of config.inc.local.php :
```php
$ldap_binddn = "cn=SSP,cn=Users,dc=eee,dc=dddddd,dc=com";
# dont write passwords on forums thus ------- same for eee and dddddd
$ldap_bindpw = "---------";     //tested function addslashes as well no effect
$who_change_password = "manager";
$ldap_starttls = false;
$ad_mode = true;
$ldap_base   = "cn=Users,dc=eee,dc=dddddd,dc=com";
$ldap_filter = "(&(objectClass=user)(sAMAccountName={login})(!(userAccountControl:1.2.840.113556.1.4.803:=2)))";
$ad_options['force_unlock'] = true;
$ad_options['change_expired_password'] = true;

```

any ideas ?

**Comment by coudot** [comment]
Hello,

if do you have special characters in the password, like `$`, you should put it into simple quotes and not double quotes, to be sure it is not interpreted by PHP engine.

**Comment by PGTBoos** [comment]
Intrigued by your answer I changed it and then wondered can a user change his password so it contains a *
As there is also ``$login_forbidden_chars = "*()&|";``

I thought that protected against all such logins, but then i tested users can use a * in their password now. You now wanr me for $ which is not in that login forbidden chars (should it be ??).

I'm a bit confused now  (I need to know because on the other side, if people dont use this service but change thheir password through their PC, then i should also forbid those characters to protect this php script against attacks.

**Comment by coudot** [comment]
I was talking about the value in `$ldap_bindpw`, not about user password values

**Comment by PGTBoos** [comment]
Then for who is $login_forbidden_chars ?,  users seam not affected while the ldpan_bindpw doesnt seam to check against it (I had no specific warning about it)

**Comment by coudot** [comment]
See https://self-service-password.readthedocs.io/en/latest/config_general.html#security

**Comment by PGTBoos** [comment]
would have been nice if the warning was presented if any ldap logon used it manager as well... another dive in this repo
