### ISSUE TITLE
Multiple LDAP servers

### ISSUE THREAD

**Issue by flymia** [ltb-project/self-service-password#420]
Hi there,

we are in the middle of migrating our openLDAP to FreeIPA. I choose to use Self-Service-Password for our reset service on the new FreeIPA directory.
Right now we are running two independent LDAP systems, since we are not yet ready to switch to FreeIPA completely. My goal is that when the user enters his new password it get's changed on the FreeIPA-LDAP and on our openLDAP.

Is that somehow possible with this tool? Maybe if I add some code?

It would be very nice if someone could help me.

**Comment by coudot** [comment]
Hello,

we use the posthook script for this: https://ltb-project.org/documentation/self-service-password/latest/config_posthook

**Comment by flymia** [comment]
Thanks, it worked!
