### ISSUE TITLE
Why no logging for any actions taken by users?

### ISSUE THREAD

**Issue by TheAshwanik** [ltb-project/self-service-password#421]
hi @coudot ,  Just trying to understand, why I could not see any logging ( kind of a log file) that can be used for audit purposes.
Users, password change attempts, result of those attempts, date timestamp and obviously omitting any secrets and sensitive data.

Is there a reason?  Or I am missing anything?

**Comment by coudot** [comment]
Currently SSP has logs for errors and reset requests

We could add an audit log, feel free to propose some code

**Comment by coudot** [comment]
I had a new request for an audit log

We can do something similar that what was done for Service Desk: https://github.com/ltb-project/service-desk/issues/72

**Comment by coudot** [comment]
The information that should be logged:
* Date
* IP
* User
* Action
* Result

The log should occur for both Web and REST access.

**Comment by coudot** [comment]
Hello @TheAshwanik 

You can check https://github.com/ltb-project/self-service-password/pull/781

**Comment by TheAshwanik** [comment]
Thank you @coudot
