### ISSUE TITLE
Change menu color

### ISSUE THREAD

**Issue by Ressort-Informatik** [ltb-project/self-service-password#422]
Hello everybody

I would like the first menu to be colored dark gray, as well as other menus when you click on it. Since when you are on the start page, you are automatically on the first menu.

Unfortunately, I can't get it via CSS, can someone help me?

![image](https://user-images.githubusercontent.com/61539032/95180047-b879ba80-07c1-11eb-8670-058bcce13773.png)

**Comment by coudot** [comment]
Sadly it is the navbar band and not one of the menu item. So we can't use the "active" CSS class here.

You can customize CSS with:
```
a.navbar-brand{}
```

But this won't be only applied when the first page is displayed.

**Comment by Ressort-Informatik** [comment]
> Sadly it is the navbar band and not one of the menu item. So we can't use the "active" CSS class here.
> 
> You can customize CSS with:
> 
> ```
> a.navbar-brand{}
> ```
> 
> But this won't be only applied when the first page is displayed.

:(,  but thanks!

**Comment by coudot** [comment]
You can try to edit the index.php to add an "active" CSS class only when the start/change page is displayed.
