### ISSUE TITLE
question features with openldap base, $answer_attribute : not working.

### ISSUE THREAD

**Issue by ledufakademy** [ltb-project/self-service-password#423]
hello,
first thank for this very good tool.
we need to allow user password changing with question features.
we setup openldap with no additional schema or attributes, default schema.

if we follow the documentation "info" attribute seem not working at all.

could you help us, what are we missing ?

**Comment by ledufakademy** [comment]
... perhaps must i use "roomnumber" attribute ?

**Comment by coudot** [comment]
To use "info" attribute you should also add "extsnsibleObject" objectClass. You can also of course use another attribute. Be sure to protect it trough OpenLDAP ACLs.

**Comment by ledufakademy** [comment]
Hello "KPTN" Coudot !
so, can i use this config :  
$answer_objectClass="inetorgperson"
$answer_attribute="roomnumber" attribute

?

Note : i'm very bad with ldap managing ... i have just installed Debian 10 , with overlay memberOf only. No other schema.
Perhaps i'm wrong ... ;-(

**Comment by coudot** [comment]
Yes this should work, but the default configuration should work too:
```
$answer_objectClass = "extensibleObject";
$answer_attribute = "info";
```

`info` attribute is available in OpenLDAP `cosine` schema.

**Comment by ledufakademy** [comment]
ok thank you !
ok, is this config ok without ACi (acl) ?
i read : 
`The user account can only be used for standard password change, when user is giving its old password. For other password changes (token, **_questions_**, …), manager account will always be used, whatever value is set in $who_change_password.`

So **manager** , is my bind user ?
But this bind user do not have write acces to ... people OU, who can i change that easyly ? (sorry being so newbiei with ldap stuff ...)

**Comment by coudot** [comment]
> ok, is this config ok without ACi (acl) ?

No, you must allow users to write this attribute

> So manager , is my bind user ?

Yes.

> But this bind user do not have write acces to ... people OU, who can i change that easyly ?

See https://www.openldap.org/doc/admin24/access-control.html#Access%20Control%20Common%20Examples

**Comment by ledufakademy** [comment]
... ouch , it will be touchy !
thank you for time to answer me.

**Comment by ledufakademy** [comment]
what do you think of that ldif file ?
`dn: olcDatabase={1}mdb,cn=config
changetype: modify
add: olcAccess
olcAccess: to attrs=roomNumber by uid=ssp.manager,ou=applications,dc=domain,dc=com write by * none`

**Comment by ledufakademy** [comment]
ldapmodify -Q -Y EXTERNAL -H ldapi:/// -f add-acl1.ldif

gave me :

> modifying entry "olcDatabase={1}mdb,cn=config"
> ldap_modify: Other (e.g., implementation specific) error (80)
>         additional info: <olcAccess> handler exited with 1

do you have an idea ?

**Comment by coudot** [comment]
You should contact OpenLDAP mailing list for this: https://lists.openldap.org/postorius/lists/openldap-technical.openldap.org/

**Comment by ledufakademy** [comment]
ok thank you.

**Comment by ledufakademy** [comment]
ok, made it, but there is an issue.
I can write in openldap the answer challenge : it's give me ok when recording "question" .
But when i try to change password with question ....
passwors can not be record .... ;-(

**Comment by ledufakademy** [comment]
this is exctaly the same thing for Mail chang (Token) , openldap log :  

> Oct 10 17:14:27 ldap1 slapd[300]: conn=4628 fd=15 ACCEPT from IP=10.10.10.10:47770 (IP=0.0.0.0:636)
> Oct 10 17:14:27 ldap1 slapd[300]: conn=4628 fd=15 TLS established tls_ssf=256 ssf=256
> Oct 10 17:14:27 ldap1 slapd[300]: conn=4628 op=0 BIND dn="uid=ssp.manager,ou=applications,dc=domain,dc=org" method=128
> Oct 10 17:14:27 ldap1 slapd[300]: conn=4628 op=0 BIND dn="uid=ssp.manager,ou=applications,dc=domain,dc=org" mech=SIMPLE ssf=0
> Oct 10 17:14:27 ldap1 slapd[300]: conn=4628 op=0 RESULT tag=97 err=0 text=
> Oct 10 17:14:27 ldap1 slapd[300]: conn=4628 op=1 SRCH base="dc=domain,dc=org" scope=2 deref=0 filter="(&(objectClass=person)(mail=steeve.dart@anotherdomain.com))"
> Oct 10 17:14:27 ldap1 slapd[300]: <= mdb_equality_candidates: (mail) not indexed
> Oct 10 17:14:27 ldap1 slapd[300]: conn=4628 op=1 SEARCH RESULT tag=101 err=0 nentries=1 text=
> Oct 10 17:14:28 ldap1 slapd[300]: conn=4628 op=2 MOD dn="uid=steeve.dart.anotherdomain.com,ou=people,dc=domain,dc=org"
> Oct 10 17:14:28 ldap1 slapd[300]: conn=4628 op=2 MOD attr=userPassword
> Oct 10 17:14:28 ldap1 slapd[300]: conn=4628 op=2 RESULT tag=103 err=50 text=
> Oct 10 17:14:28 ldap1 slapd[300]: conn=4628 op=3 UNBIND
> Oct 10 17:14:28 ldap1 slapd[300]: conn=4628 fd=15 closed

**Comment by ledufakademy** [comment]
Ok definitevly working : but the documentation must mention ...the ldap needs !
i give them to all of you :+1: 

> olcAccess: {0}to attrs=userPassword by self write by dn="uid=ssp.manager,ou=applications,dc=domain,dc=org" write by anonymous auth by * none
olcAccess: {1}to attrs=shadowLastChange by self write by * read
olcAccess: {2}to attrs=roomNumber by dn="uid=ssp.manager,ou=applications,dc=domain,dc=org" write by self write by * read
olcAccess: {3}to * by * read

**Comment by ledufakademy** [comment]
... oh no !
another issue : bind user is not allowed to create user attribute

**Comment by ledufakademy** [comment]
i create "roomNumber" attribute for all my users, and it's ok after that. (no more power to this bind user ;-))

**Comment by coudot** [comment]
> olcAccess: {2}to attrs=roomNumber by dn="uid=ssp.manager,ou=applications,dc=domain,dc=org" write by self write by * read

You really let this attribute readable by all? It contains answers to security question.

**Comment by ledufakademy** [comment]
> > olcAccess: {2}to attrs=roomNumber by dn="uid=ssp.manager,ou=applications,dc=domain,dc=org" write by self write by * read
> 
> You really let this attribute readable by all? It contains answers to security question.

Post edited, thank you.
