### ISSUE TITLE
Why index.php removed?

### ISSUE THREAD

**Issue by Ressort-Informatik** [ltb-project/self-service-password#425]
If you now download the website from Github, the Index.php is simply missing. Why was it removed?

**Comment by coudot** [comment]
It's because we moved to Smarty framework. See #109

**Comment by ryan-25** [comment]
Are there any docs on updating from 1.3 to 1.4 im unable to workout how to get the service working on the latest version after this file has been moved. Does nginx need any changes for this as its currently pointing to a directory where there's no index.php file changing from the provided config to make it point to the file in htdocs still fails with nothing in the logs.

**Comment by coudot** [comment]
The document root is now `/usr/share/self-service-password/htdocs` (instead of `/usr/share/self-service-password`)

**Comment by ryan-25** [comment]
From looking at the documents for nginx config it's still the old location `/var/www/html;` not  `/var/www/html/htdocs;` https://self-service-password.readthedocs.io/en/v1.4/config_nginx.html
Has this config been tested with 1.4?

**Comment by coudot** [comment]
It has been fixed in https://self-service-password.readthedocs.io/en/latest/config_nginx.html
