### ISSUE TITLE
Vulnerabilities

### ISSUE THREAD

**Issue by TheAshwanik** [ltb-project/self-service-password#427]
Hi, 

I had to run few scans bfr I can use this at my work, so thought of highlighting here:

I ran the project against Sonatype NexusIQ scan and it did compain about some vulnerabilites.

![image](https://user-images.githubusercontent.com/2206818/95639134-4a6a1780-0a8f-11eb-8d56-3625710306e4.png)

*Checkmarks scan highlighted some of the below:*

![image](https://user-images.githubusercontent.com/2206818/95639184-6a014000-0a8f-11eb-97e5-b5bcf45fdd7f.png)

e.g;
File Manipulation\Path 1:

The input obtained via <?php in the file self-service-password-master/htdocs/resetbyquestions.php at line 1 is
used to determine the location of a file to be written into by check_username_validity in the file self-servicepassword-
master/lib/functions.inc.php at line 572, potentially allowing an attacker to alter or corrupt the contents of that file, or create a new file altogether.

Code Snippet
```
File Name self-service-password-master/htdocs/resetbyquestions.php
Method <?php
....
48. if (isset($_REQUEST["login"]) and $_REQUEST["login"]) { $login =
strval($_REQUEST["login"]); }
....
55. $result = check_username_validity($login,$login_forbidden_chars);
``` 

File Name self-service-password-master/lib/functions.inc.php
```
Method function check_username_validity($username,$login_forbidden_chars) {
....
572. function check_username_validity($username,$login_forbidden_chars)
{
....
578. error_log("Non alphanumeric characters in username $username");
```

Apologies, I cannot share the full report, but would be willing to help you understand offline, if you need more details.

**Comment by coudot** [comment]
Your report is quite hard to understand. Your example talks about a file written in `check_username_validity` function but there is none.

It would be interesting if you find a way to reproduce an attack. In this case, please to not publish it directly, but let us some time to fix the bug and release a new version.

Thanks.

**Comment by TheAshwanik** [comment]
> Your report is quite hard to understand. Your example talks about a file written in `check_username_validity` function but there is none.
> 
> It would be interesting if you find a way to reproduce an attack. In this case, please to not publish it directly, but let us some time to fix the bug and release a new version.
> 
> Thanks.

What is understand is , check_username_validity is in lib/functions.inc.php  and takes a username param as input.. and username == login parameter which is retrieved from $_REQUEST["login"] resetbyquestions.php when <?php is evaluated.

I think what it means is someone can manipulate the _login name and do something with the contents of the log file that this parameter is getting written into.

**Comment by coudot** [comment]
> do something with the contents of the log file

What exactly? Please explain what value can be used by an attacker that would have a security impact.

**Comment by coudot** [comment]
No news, I close this issue.
