### ISSUE TITLE
Global Catalog configuration - LDAP - Search error 10  (Referral)

### ISSUE THREAD

**Issue by red-erik** [ltb-project/self-service-password#435]
Hello,
when connecting to AD with multiple child domain, we need to connect to Global Catalog with LDAPS on port 3269 but we receive the above error.
Everything works fine using LDAPS on child domain controller on port 636.
Any help greatly appreciated.
Regards,

Red.

**Comment by coudot** [comment]
Global Catalog is read-only, it will not work for Self Service Password

**Comment by red-erik** [comment]
Hello,
Thank you for the explanation so, how can I manage 4 subdomains in my AD with a root domain? Is there any special setting I need to change? Or it is not supported at all ?
Regards,

Red.

**Comment by coudot** [comment]
You can create 4 virtual hosts, and override SSP config for each virtual host. This feature is not yet in SSP 1.3 but will be in next version.

The change is quite simple to add to your existing installation: https://github.com/Worteks/self-service-password/commit/91d6e1d08c36e3a82f590ed3f45081f0aaaccd29

See also https://self-service-password.readthedocs.io/en/latest/config_general.html#multi-tenancy

**Comment by red-erik** [comment]
Hello,
I see  https://self-service-password.readthedocs.io/en/latest/config_general.html#multi-tenancy but really don't know how to use modified headers in web request. Would you be so kind to share an example on how to use the multy-tenancy feature ?
Regards,

Red.

**Comment by red-erik** [comment]
Hello,
would it be possible to enable "follow referral" in LDAP search ? this should solve my problem and, as far as I know, is a PHP Ldap standard feature.
Regards,
Red.

**Comment by coudot** [comment]
You can replace in the code:
```php
ldap_set_option($ldap, LDAP_OPT_REFERRALS, 0);
```
By:
```php
ldap_set_option($ldap, LDAP_OPT_REFERRALS, 1);
```

And check how it works.

**Comment by red-erik** [comment]
Hello,
in witch file ?

**Comment by coudot** [comment]
```
clement@ader-worteks:~/dev/self-service-password$ grep -r LDAP_OPT_REFERRALS
scripts/encrypt_answers.php:ldap_set_option($ldap, LDAP_OPT_REFERRALS, 0);
htdocs/change.php:    ldap_set_option($ldap, LDAP_OPT_REFERRALS, 0);
htdocs/resetbytoken.php:    ldap_set_option($ldap, LDAP_OPT_REFERRALS, 0);
htdocs/resetbyquestions.php:    ldap_set_option($ldap, LDAP_OPT_REFERRALS, 0);
htdocs/setquestions.php:    ldap_set_option($ldap, LDAP_OPT_REFERRALS, 0);
htdocs/sendsms.php:    ldap_set_option($ldap, LDAP_OPT_REFERRALS, 0);
htdocs/sendtoken.php:    ldap_set_option($ldap, LDAP_OPT_REFERRALS, 0);
htdocs/changesshkey.php:    ldap_set_option($ldap, LDAP_OPT_REFERRALS, 0);

**Comment by red-erik** [comment]
Thank you,
sorry but I still have a lot to learn on Linux.
Regards,
Red.

**Comment by red-erik** [comment]
Hello,
same result, it does not work. I'll wait a new release, if available.
Regards,
Red,
