### ISSUE TITLE
Users in different OU's and Ldap search

### ISSUE THREAD

**Issue by PGTBoos** [ltb-project/self-service-password#438]
We are planning to move users into different OU's 
This is to comply to ISO norms, we need to apply different security policies depending on user roles.
However i see in the php code:
```php
//searching Directory
$ldap_base   = "cn=Users,dc=XXX,dc=XXXXXXX.com";
# $ldap_filter = "(&(objectClass=person)(uid={login}))";
$ldap_filter = "(&(objectClass=user)(sAMAccountName={login})(!(userAccountControl:1.2.840.113556.1.4.803:=2)))";
$ad_options['force_unlock'] = true;
$ad_options['change_expired_password'] = true;
```
How would we allow it to search for multiple sub OU's under users ?

PS Its not about different password length's, there is no difference for the OU's, its the same for all users.
We're forced into an OU structure as some people must use bitlockker, and complete locked down PC's (app allow policies) etc..

**Comment by coudot** [comment]
Hello,

the search is done with the scope "subtree", so configure the ldap base to the common base for all users, and it should work.

**Comment by PGTBoos** [comment]
Ok so it should work as is thanks  for the quick reply
