### ISSUE TITLE
Invalid Mail Header, Double To: Field / Outdated PHPMailer Version

### ISSUE THREAD

**Issue by docsteel** [ltb-project/self-service-password#439]
When a User reset a Password via Mail Token the generated Mai via PHPMailer has a Double To: Field.
So Amavis classified this Mail as invalid and marked it as Spam:

**X-Amavis-Alert: BAD HEADER SECTION, Duplicate header field: "To"**

If i have seen this correctly the invalid Header also breaks DKIM Signatures.

On the other Hand the included PHPMailer Version 5.2.23 is outdated. Can this be updated to the recent Version 6.1.8?

**Comment by coudot** [comment]
Hello @docsteel 

Could you try this patch?
```
diff --git a/lib/functions.inc.php b/lib/functions.inc.php
index b13cc4e..e050166 100644
--- a/lib/functions.inc.php
+++ b/lib/functions.inc.php
@@ -566,6 +566,8 @@ function send_mail($mailer, $mail, $mail_from, $mail_from_name, $subject, $body,
         error_log("send_mail: ".$mailer->ErrorInfo);
     }
 
+    $mailer->clearAddresses();
+
     return $result;
 
 }
```

**Comment by docsteel** [comment]
Tried the Patch. Does not solve the Problem.

**Comment by coudot** [comment]
I have no other idea, we only call once addAdress method, so it should work.

We'll see if upgrading PHPMailer has any effect

**Comment by coudot** [comment]
Can you try to set SMTP debug? 

Set `$mail_smtp_debug = SMTP::DEBUG_SERVER;` in your config

**Comment by coudot** [comment]
Assigning to @JuJuMDX to upgrade to latest PHPMailer verion

**Comment by docsteel** [comment]
Managed to locate the issue:

"smtps" is default transport/mailer in self service config examples but not a valid option for PHPMailer 
(see http://phpmailer.github.io/PHPMailer/classes/PHPMailer.PHPMailer.PHPMailer.html#property_Mailer).

Using "smtps" as invalid mechanism triggers PHPMailer fallback to "mail".

"mail" triggers /usr/bin/mail which is mail.mailutils on most linux systems (in my case debian stable)  and does not cope with the to-addresses array and doCallback mechanism of PHPMailer which produces duplicate to and subject entries.

Ways to fix:
- Option 1: Change configuration to sendmail
- Option 2: Change mail binary from mail.mailutils to bsd-mailx which is more robust

On your side this would mean changing the example/default configuration to a valid mechanism as supported in PHPMailer (mail, smtp or sendmail), the rest is probably more on the upstream side.

Thanks for your Help.

**Comment by coudot** [comment]
@docsteel thanks for your feedback.

The default value in SSP config is not `smtps` but `smtp`:
https://github.com/ltb-project/self-service-password/blob/master/conf/config.inc.php#L210

So I don't understand why you had the issue. The default configuration should work fine.

**Comment by coudot** [comment]
PHPMailer upgraded to 6.3.0
