### ISSUE TITLE
Help needed in reset by question

### ISSUE THREAD

**Issue by vitaminBCDE** [ltb-project/self-service-password#440]
Hi all.

I am just curious. Are the answers to the questions stored in the LDAP directory (i am using active directory) or it is stored in a separate database? if they are stored in the LDAP directory, how can I store the answers in a separate database?

**Comment by coudot** [comment]
Hello,

answers are stored in an attribute of the user account, you can choose the one you want or create a schema extension for it. You cannot store it in a separate database.

**Comment by vitaminBCDE** [comment]
Alright. Thank you.

**Comment by ahmet2636** [comment]
> 

I can't store in AD custom attribute, Can you help me ?
