### ISSUE TITLE
typo in show policies dutch

### ISSUE THREAD

**Issue by PGTBoos** [ltb-project/self-service-password#441]
Uw nieuw wachtwoord mag niet gelijk zijn aan uw loginnaam
should be
Uw nieuwe wachtwoord mag niet gelijk zijn aan uw loginnaam

(nieuwe)

shold be something that i could propose a fix in the git code but not clear where the language stuff was done, i saw a lang dir but its not there, i dont had the time to dive deeply into it.

**Comment by coudot** [comment]
You can edit https://github.com/ltb-project/self-service-password/blob/master/lang/nl.inc.php and propose your change

**Comment by PGTBoos** [comment]
Ok I will do,
Btw today I was editing a samba password complexity script to act the same as your ssp. might be handy perhaps for others as well
________________________________
