### ISSUE TITLE
Is it possible to configure two domain directories and change the password simultaneously on both?

### ISSUE THREAD

**Issue by rodrigorenie** [ltb-project/self-service-password#444]
In myh company we are slowly migrating from Samba+LDAP domain to Active Directory and right now we have both domain active and running, with a in house made software to sync both, but we are unable to sync the password.

The solution would be to have a self service password changer, such as your software, in order for the user to change his password himself, but it's necessary that this changes occurs on both Samba+LDAP and AD.

Is this possible?

**Comment by coudot** [comment]
Yes, you should use the posthook feature to forward the password change to the second system.

**Comment by coudot** [comment]
@JuJuMDX is providing a script and a documentation for this, it will be inside 1.4 release.
