### ISSUE TITLE
options should have the form [&quot;wrappername&quot;][&quot;optionname&quot;] = $value

### ISSUE THREAD

**Issue by NoxInmortus** [ltb-project/self-service-password#445]
Hello,

I'm trying to set `$mail_smtp_options = array();`  to allow self-signed certificates server-side. 

In the PHPMailer documentation (https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting) :
```
$mail->SMTPOptions = array(
    'ssl' => array(
        'verify_peer' => false,
        'verify_peer_name' => false,
        'allow_self_signed' => true
    )
);
```

So I just tried `$mail_smtp_options = array('verify_peer' => false,'verify_peer_name' => false,'allow_self_signed' => true);`

Sadly, this doesnt work and PHP logs the following : 
```
PHP Warning:  stream_context_create(): options should have the form [&quot;wrappername&quot;][&quot;optionname&quot;] = $value in /usr/share/self-service-password/lib/vendor/PHPMailer/class.smtp.php on line 285
```

Is my configuration incorrect or is this a bug ?

**Comment by coudot** [comment]
Try 
```php
$mail_smtp_options = array('ssl'=>array('verify_peer' => false,'verify_peer_name' => false,'allow_self_signed' => true));
```

**Comment by NoxInmortus** [comment]
@coudot Hello, it works, thanks you very much
