### ISSUE TITLE
accented characters in password 

### ISSUE THREAD

**Issue by renardarg** [ltb-project/self-service-password#448]
hi , i use ssp with posthook to sync password over Active directory and LDAP , 
i have a problem with all accented characters getting cuts in password 
i try to set éé#iïâê&[\'aaB*e~neiz9fo9e 
i get   #i&[\'aaB*e~neiz9fo9e 

i try to look for locales settings on my server, i have set everythings i could to fr_FR.UTF-8 
in apache i have 

LC_LANG | fr_FR
LC_CTYPE | fr_FR
LC_ALL | fr_FR

is there something i 've missed in config.inc.php ? any ideas ?

**Comment by coudot** [comment]
We use https://www.php.net/manual/fr/function.escapeshellarg.php in posthook, which can strip non ASCII characters.

You can force a local with UTF8, or try the master version of SSP which add an option to encode the password value in base64.

**Comment by coudot** [comment]
See https://self-service-password.readthedocs.io/en/latest/config_preposthook.html for master documentation

**Comment by renardarg** [comment]
thank you very much @coudot  
add $posthook_password_encodebase64 = true;  
and it just work with all accented caracter. 
have a good day

**Comment by coudot** [comment]
Thanks for the feedback
