### ISSUE TITLE
release tag - it should be just 1.0

### ISSUE THREAD

**Issue by wtps0n** [ltb-project/self-service-password#45]
Hello,

I'm a port maintainer of SSP at FreeBSD Ports project. I'm trying to update port source so a new 1.0 version could be installed on FreeBSD.

Unfortunatelly you've made a v1.0 release no just 1.0 (as previous 0.9). So ports framework which uses codeload.github.com is not able to download self-service-password-1.0 automatically.

Could you change it? 

Thanks a lot for your time.

Greetings,

**Comment by coudot** [comment]
I've done that because it is what is suggested by github:

> Tagging suggestions
> 
> It’s common practice to prefix your version names with the letter v. Some good tag names might be v1.0 or v2.3.4. 

I use the standard version number in packages published here: http://ltb-project.org/wiki/download#self_service_password

You should use the tarball published on the website rather than the tarball provided by github, which is a complete archive of the source. The official published tarball is cleaner.

**Comment by wtps0n** [comment]
I've just checked homepage and found that source code is on github :-)

OK. So I'm making chenges to FreeBSD ports tree so ltb-project.org will be pointed instead of github.

Thanks a lot for you time and work of course :-)

**Comment by coudot** [comment]
Great. If you have an URL where FreeBSD packages can be downloaded, I can add it on LDAP Tool Box website.

**Comment by wtps0n** [comment]
Well, it depends on FreeBSD version and architecture. Base url is http://pkg.freebsd.org/

And FreeBSD pkg util will use package depending on particular server (box) settings. For example I've made my own pkg repository - I don't use official one.

**Comment by coudot** [comment]
Thanks for packaging it to FreeBSD.

Indeed I can't do a link on a particular package from LTB Website so I won't do it.
