### ISSUE TITLE
Cannot Access LDAP Directory - SSL, AD & IIS

### ISSUE THREAD

**Issue by sudhakarapn** [ltb-project/self-service-password#450]
My setup is as below:
Web Server IIS on Windows 10
PHP v7.4
SSPR v1.3

So far: I can connect to my AD server on plain LDAP via port 389 but cannot change the password due to AD's restrictions. Yes, I read that AD allows you to change the passwords only on SSL connection. 

I cannot connect to my AD with ldaps and starttls = true;  and via 636 port at all. I receive an error "Cannot access LDAP directory".  Port 636 is open at my AD server since I could connect to my AD Server using SSL using ldp.exe command. 

I have setup Certificate Authority in my AD server and generated the certificate as explained in one of the documents. 

1. Do I need to extract that certificate and mention in any of the config files? If yes, where, please guide. In PHP folders or do I need to install OpenLDAP for Windows and do some configurations there?
2. I assume IIS should not be causing any trouble?
3. Also I have enabled debug mode to check the logs but cannot find much in the IIS logs, where does debug mode store its logs on Windows when using IIS as web server? 

My AD connection settings in config.inc.php is as below: 
```php
$debug = true;

# LDAP
$ldap_url = "ldaps://ad.mydomainit.com:636";
$ldap_starttls = true;
$ldap_binddn = "CN=Administrator,CN=Users,DC=ad,DC=mydomainit,DC=com";
$ldap_bindpw = "password";
$ldap_base = "DC=ad,DC=mydomainit,DC=com";
# $ldap_login_attribute = "uid";
$ldap_login_attribute = "sAMAccountName";
$ldap_fullname_attribute = "cn";
$ldap_filter = "(&(objectClass=person)($ldap_login_attribute={login}))";

# Active Directory mode
# true: use unicodePwd as password field
# false: LDAPv3 standard behavior
$ad_mode = true;
# Force account unlock when password is changed
$ad_options['force_unlock'] = true;
# Force user change password at next login
$ad_options['force_pwd_change'] = false;
# Allow user with expired password to change password
$ad_options['change_expired_password'] = true;
```
Thank you.

**Comment by coudot** [comment]
Do not mix LDAPS and startTLS, they are not compatible, choose LDAPS or LDAP+startTLS.

**Comment by sudhakarapn** [comment]
Thank you Clement Oudot, this solved the issue. Merry Christmas and Happy New Year.
