### ISSUE TITLE
session and token lifetime

### ISSUE THREAD

**Issue by liedekef** [ltb-project/self-service-password#451]
This part of the code:
```
    # Manage lifetime with sessions properties
    if (isset($token_lifetime)) {
        ini_set("session.gc_maxlifetime", $token_lifetime);
        ini_set("session.gc_probability",1);
        ini_set("session.gc_divisor",1);
    }
```
causes lines like this in the php error logfile on ubuntu/debian:
`PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php/sessions) failed: Permission denied (13) in /var/www/html/xxxx/pages/resetbytoken.php on line 78`
Reason is that on debian/ubuntu the session path is not directly writable by php, so they set session.gc_probability=0 and use a cronjob that runs every 30 minutes to clean up sessions older than 1440 seconds.
To avoid this notice I'd suggest to not set the gc_probability option, or make a new config option to try and clean the sessions or not.
Currently the workaround on ubuntu is to set the token_lifetime config option to 0, but I don't think that's the correct thing to do (since you check that lifetime in the session cookie too).

**Comment by coudot** [comment]
Indeed I reproduce the issue. Having an option to force session cleaning by PHP garbage collector is a good idea. I wonder if we still need this as we check the lifetime in the code just after that.

**Comment by liedekef** [comment]
I think removing the ini_set lines should be sufficient.
