### ISSUE TITLE
Advise on how to reset password by emails

### ISSUE THREAD

**Issue by sudhakarapn** [ltb-project/self-service-password#452]
I have setup SSPR on Windows and using IIS as webserver to run the application. I have an SMTP server in my network and tried specifying the relevant SMTP host name, Credentials in the config.inc.php file under ##Mail section like below.

I understand that Sendmail is not available on Windows by default and may need to install one. Please suggest the easy and best solution. 

1. Try and use the existing SMTP server (Zimbra) in my local network? If yes, do I need to comment out $mail_sendmailpath = '/usr/sbin/sendmail'; and $mail_smtp_secure = 'tls'; (not sure about TLS connection) ? 

2. Install and configure Sendmail.ini and php.ini as advised in some blogs and php.net. 

3. Also, where to store the email addresses of users on Active Directory for LDAP to lookup the directory? Any other detailed documentation would be useful. 

The ##Mail section looks like below, please correct if there are any errors -
```php
## Mail
# LDAP mail attribute
$mail_attribute = "mail";
# Get mail address directly from LDAP (only first mail entry)
# and hide mail input field
# default = false
$mail_address_use_ldap = true;
# Who the email should come from
$mail_from = "SysAdmin@mydomain.com";
$mail_from_name = "Self Service Password";
$mail_signature = "";
# Notify users anytime their password is changed
$notify_on_change = false;
# PHPMailer configuration (see https://github.com/PHPMailer/PHPMailer)
$mail_sendmailpath = '/usr/sbin/sendmail';
$mail_protocol = 'smtp';
$mail_smtp_debug = 0;
$mail_debug_format = 'error_log';
$mail_smtp_host = '192.168.1.2';
$mail_smtp_auth = true;
$mail_smtp_user = 'username@mydomain.com';
$mail_smtp_pass = 'password';
$mail_smtp_port = 25;
$mail_smtp_timeout = 30;
$mail_smtp_keepalive = false;
$mail_smtp_secure = 'tls';
$mail_smtp_autotls = true;
$mail_contenttype = 'text/plain';
$mail_wordwrap = 0;
$mail_charset = 'utf-8';
$mail_priority = 3;
$mail_newline = PHP_EOL;
```

**Comment by coudot** [comment]
You can check https://stackoverflow.com/questions/35418448/phpmailer-on-windows-iis

> Also, where to store the email addresses of users on Active Directory for LDAP to lookup the directory? Any other detailed documentation would be useful.

You can just use the standard `mail` attribute
