### ISSUE TITLE
can't change password

### ISSUE THREAD

**Issue by realslh** [ltb-project/self-service-password#455]
I have config all the part, and change the password in the website, it shows me change successfully.
But I try to login the user with newpassword, it failed. If use the old password, and it works.
My LDAP is Windows AD. When the web show the message of change successfully, the log show as below:
```
[Fri Jan 08 14:03:17.121513 2021] [:error] [pid 21792] [client 192.168.1.137:51930] PHP Notice:  Undefined variable: obscure_failure_messages in /usr/share/self-service-password/pages/change.php on line 186, referer: http://192.168.1.215/index.php
[Fri Jan 08 14:03:17.121564 2021] [:error] [pid 21792] [client 192.168.1.137:51930] PHP Warning:  in_array() expects parameter 2 to be array, null given in /usr/share/self-service-password/pages/change.php on line 186, referer: http://192.168.1.215/index.php
[Fri Jan 08 14:03:17.121638 2021] [:error] [pid 21792] [client 192.168.1.137:51930] PHP Notice:  Undefined variable: display_posthook_error in /usr/share/self-service-password/pages/change.php on line 193, referer: http://192.168.1.215/index.php
```

**Comment by coudot** [comment]
These log messages can be ignored, they are not linked with the password change

You can set debug mode and see what is happening when you change password on AD.

**Comment by arthurmueller** [comment]
if I set debug mode, where can I see the debug information? Where is the logfile?

**Comment by coudot** [comment]
Some logs are in WebServer logs, other are managed by Smarty framework and displayed directly on the page

**Comment by arthurmueller** [comment]
@realslh I had the same problem and fixed it by setting $samba_mode = true; and $hash = "SSHA"; since samba uses a different password attribute
