### ISSUE TITLE
Can't connect to ActiveDirectry2K12 using ldaps

### ISSUE THREAD

**Issue by Wawoooooo** [ltb-project/self-service-password#459]
Dear Developer
I tried a lot tests but failed. Maybe there is something wrong with the settings. Can you help me? Thank you very much.   
I  sure that ad port 636 is normal, and the administrator account also has permissions.

config.inc.php
```php
$debug = true;

#LDAP
$ldap_url = "ldaps://10.200.7.235:636";
$ldap_starttls = false;
$ldap_binddn = "cn=administrator,cn=Users,dc=wdsw-test,dc=local";
$ldap_bindpw = "Klzz123";
$ldap_base = "dc=wdsw-test,dc=local";
$ldap_login_attribute = "sAMAccountName";
$ldap_fullname_attribute = "cn";
$ldap_filter = "(&(objectClass=user)(sAMAccountName={login})(!(userAccountControl:1.2.840.113556.1.4.803:=2)))";

#Active Directory mode
#true: use unicodePwd as password field
#false: LDAPv3 standard behavior
$ad_mode = true;
#Force account unlock when password is changed
$ad_options['force_unlock'] = true;
#Force user change password at next login
$ad_options['force_pwd_change'] = false;
#Allow user with expired password to change password
$ad_options['change_expired_password'] = true; 
```

ldap.conf
```
#LDAP Defaults
#See ldap.conf(5) for details
#This file should be world readable but not world writable.

#BASE   dc=example,dc=com
#URI    ldap://ldap.example.com ldap://ldap-master.example.com:666

#SIZELIMIT      12
#TIMELIMIT      15
#DEREF          never

TLS_CACERTDIR   /etc/openldap/certs
TLS_CACERT     /etc/ssl/ldap.crt
#Turning this off breaks GSSAPI used with krb5 when rdns = false
SASL_NOCANON    on
```
I try ldap.crt is work.
```
[root@localhost /]# openssl s_client -connect 10.200.7.235:636 -CAfile /etc/openldap/certs/ldap.crt                                                                  CONNECTED(00000003)
write:errno=104
no peer certificate available
No client certificate CA names sent
SSL handshake has read 0 bytes and written 0 bytes
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
Protocol  : TLSv1.2
Cipher    : 0000
Session-ID: 
Session-ID-ctx: 
Master-Key: 
Key-Arg   : None
Krb5 Principal: None
PSK identity: None
PSK identity hint: None
Start Time: 1610703191
Timeout   : 300 (sec)
Verify return code: 0 (ok)
```

httpd/error.log
```
ldap_url_parse_ext(ldap://localhost/)
ldap_init: trying /etc/openldap/ldap.conf
ldap_init: using /etc/openldap/ldap.conf
ldap_init: HOME env is NULL
ldap_init: LDAPCONF env is NULL
ldap_init: LDAPRC env is NULL
ldap_create
ldap_url_parse_ext(ldaps://10.200.7.235:636)
ldap_bind_s
ldap_simple_bind_s
ldap_sasl_bind_s
ldap_sasl_bind
ldap_send_initial_request
ldap_new_connection 1 1 0
ldap_int_open_connection
ldap_connect_to_host: TCP 10.200.7.235:636
ldap_new_socket: 12
ldap_prepare_socket: 12
ldap_connect_to_host: Trying 10.200.7.235:636
ldap_pvt_connect: fd: 12 tm: -1 async: 0
attempting to connect:
connect errno: 13
ldap_close_socket: 12
ldap_err2string
ldap_err2string
```

Indicates that the LDAP server cannot be accessed.
Thanks

**Comment by coudot** [comment]
Your LDAPS connection does not seem to really work:
```
write:errno=104
no peer certificate available
No client certificate CA names sent
SSL handshake has read 0 bytes and written 0 bytes
```

Your AD SSL configuration is not correct.

**Comment by Wawoooooo** [comment]
@coudot Thank you for your reply
I try reconfigure ad SSL an output CA but has still failed.

I refer to the URL below to generate the certificate and proceed to step 15
https://social.technet.microsoft.com/wiki/contents/articles/2980.ldap-over-ssl-ldaps-certificate.aspx

This is a new result of ca.crt , There still seems to be a problem.
openssl s_client -connect 10.200.7.235:636 -CAfile /ca.crt                                                                                         

CONNECTED(00000003)

depth=0 
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 
verify error:num=21:unable to verify the first certificate
verify return:1
Certificate chain
 0 s:
   i:/DC=local/DC=wdsw-test/CN=wdsw-test-DC-01-CA
Server certificate
-----BEGIN CERTIFICATE-----
MIIFwTCCBKmgAwIBAgITUAAAAAN2tckwLTjQ5AAAAAAAAzANBgkqhkiG9w0BAQUF
ADBPMRUwEwYKCZImiZPyLGQBGRYFbG9jYWwxGTAXBgoJkiaJk/IsZAEZFgl3ZHN3
LXRlc3QxGzAZBgNVBAMTEndkc3ctdGVzdC1EQy0wMS1DQTAeFw0yMTAxMTUxNDQx
NDBaFw0yMjAxMTUxNDQxNDBaMAAwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
AoIBAQDlQTMcECumPMSHce8Q5KLjWpO+HfDHbXGFmxBp7dvKtLI0r2ap9Ts9XFwS
5aFVOEULcG9YWJCIYNTvmL1DpI+ZToLfhyQs5SvwnsFQO+jtfCvszKXGe2opXikU
DFgOoiYTBMgKqHbPDFS/Gg6XpO2vPq1mQvMZyjhvkwR8Eb6K8Kfblpgq41KBY1aJ
FX0Y1lXiHzlVR/fkh/Lu1KQ58AnlEoKIrEt0Yik8gb/lc99lHgQyciZ+YGk/RL9S
+7xib6uULMP4ZdWjFoRB3721TXkwegE6vRaJBBW3+kWSx3C08QhT7T2KUHI+IzxT
iQbfu3ZStqD8jIV7EiWdtDnTDfqvAgMBAAGjggLjMIIC3zA+BgkrBgEEAYI3FQcE
MTAvBicrBgEEAYI3FQiGuf85guKSHYPNiSqDn7hXgZ6hWoEBgvT0I4fp6mYCAWQC
AQIwMgYDVR0lBCswKQYHKwYBBQIDBQYKKwYBBAGCNxQCAgYIKwYBBQUHAwEGCCsG
AQUFBwMCMA4GA1UdDwEB/wQEAwIF4DBABgkrBgEEAYI3FQoEMzAxMAkGBysGAQUC
AwUwDAYKKwYBBAGCNxQCAjAKBggrBgEFBQcDATAKBggrBgEFBQcDAjAdBgNVHQ4E
FgQUT9H8RwMhR1VGi/+nlM//6RjN6iYwHwYDVR0jBBgwFoAUGXlSJwE/2RmabkcV
I2sTgrGU5m4wgc4GA1UdHwSBxjCBwzCBwKCBvaCBuoaBt2xkYXA6Ly8vQ049d2Rz
dy10ZXN0LURDLTAxLUNBLENOPURDLTAxLENOPUNEUCxDTj1QdWJsaWMgS2V5IFNl
cnZpY2VzLENOPVNlcnZpY2VzLENOPUNvbmZpZ3VyYXRpb24sREM9d2Rzdy10ZXN0
LERDPWxvY2FsP2NlcnRpZmljYXRlUmV2b2NhdGlvbkxpc3Q/YmFzZT9vYmplY3RD
bGFzcz1jUkxEaXN0cmlidXRpb25Qb2ludDCBxAYIKwYBBQUHAQEEgbcwgbQwgbEG
CCsGAQUFBzAChoGkbGRhcDovLy9DTj13ZHN3LXRlc3QtREMtMDEtQ0EsQ049QUlB
LENOPVB1YmxpYyBLZXkgU2VydmljZXMsQ049U2VydmljZXMsQ049Q29uZmlndXJh
dGlvbixEQz13ZHN3LXRlc3QsREM9bG9jYWw/Y0FDZXJ0aWZpY2F0ZT9iYXNlP29i
amVjdENsYXNzPWNlcnRpZmljYXRpb25BdXRob3JpdHkwPwYDVR0RAQH/BDUwM4IV
REMtMDEud2Rzdy10ZXN0LmxvY2Fsgg93ZHN3LXRlc3QubG9jYWyCCVdEU1ctVEVT
VDANBgkqhkiG9w0BAQUFAAOCAQEAHs1uWp91UvZMSJzU6cc/v/xDXSnECqnSinxP
I3buwprSG4UTsuLl0Oc/OgmZ34G3hPdbO6OOkb8UNyECO3TQgBntbE9DDtxZRceK
hsFZ6zZ3Q7em9+cF8ZKbSqfwwXW52IsXf565M7tQMAjeInIx7btl7tX+aWtbdLXG
kVb+18S2uKOPuJE12DAmFQo3iRhgoSG29zQ6/cIf2gFCCohtbCLMZw7qQwbccbri
Q4/U3wexgzLex46WD2si7OU1lOJpsihJCN6PfT1Bw2gTMiXVzkBKU4QAvurvP0h9
xtz77se8qAtDRrFro8pawhcqEBbMP77WXoJnnUKuPGBvL3XKaQ==
-----END CERTIFICATE-----
subject=
issuer=/DC=local/DC=wdsw-test/CN=wdsw-test-DC-01-CA
No client certificate CA names sent
Client Certificate Types: RSA sign, DSA sign, ECDSA sign
Requested Signature Algorithms: RSA+SHA256:RSA+SHA384:RSA+SHA1:ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA1:DSA+SHA1
Shared Requested Signature Algorithms: RSA+SHA256:RSA+SHA384:RSA+SHA1:ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA1:DSA+SHA1
SSL handshake has read 1694 bytes and written 659 bytes
New, TLSv1/SSLv3, Cipher is AES128-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : AES128-SHA256
    Session-ID: B1220000A02C4389B47638B4AA8DD724119CE39D501A09E2CFB74705C1280D23
    Session-ID-ctx: 
    Master-Key: 7A0AF2BE1D120B21471C30B7BE7F926150BE21C668BB6BCE2BD3A8435ABC5891944C8BC83160F8B59916C490C6FCDF78
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    Start Time: 1610722496
    Timeout   : 300 (sec)
    Verify return code: 21 (unable to verify the first certificate)
read:errno=104

**Comment by Wawoooooo** [comment]
I seem to have solved the certificate issue, but I still cannot connect to LDAP. The httpd log still indicates that the connection failed. I still can't find the problem,hope to get your help! Thank you!

### **This is openssl info:**
[root@localhost certs]# openssl s_client -connect WIN-9GP9CPLJ0J6.test.local:636 -CAfile certnew.pem                   
CONNECTED(00000003)
depth=1 DC = local, DC = test, CN = test-WIN-9GP9CPLJ0J6-CA
verify return:1
depth=0 CN = WIN-9GP9CPLJ0J6.test.local
verify return:1

Certificate chain
 0 s:/CN=WIN-9GP9CPLJ0J6.test.local
   i:/DC=local/DC=test/CN=test-WIN-9GP9CPLJ0J6-CA
subject=/CN=WIN-9GP9CPLJ0J6.test.local
issuer=/DC=local/DC=test/CN=test-WIN-9GP9CPLJ0J6-CA
Acceptable client certificate CA names
/DC=local/DC=test/CN=test-WIN-9GP9CPLJ0J6-CA
/CN=WIN-9GP9CPLJ0J6.test.local
/C=US/O=VeriSign, Inc./OU=Class 3 Public Primary Certification Authority
/OU=Copyright (c) 1997 Microsoft Corp./OU=Microsoft Corporation/CN=Microsoft Root Authority
/DC=com/DC=microsoft/CN=Microsoft Root Certificate Authority
/CN=NT AUTHORITY
Client Certificate Types: RSA sign, DSA sign, ECDSA sign
SSL handshake has read 2184 bytes and written 627 bytes
New, TLSv1/SSLv3, Cipher is AES128-SHA
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1
    Cipher    : AES128-SHA
    Session-ID: 5748000077EC66D32722EF23FA26C447309FE8807A367CF1679E2DCCE4C53FEF
    Session-ID-ctx: 
    Master-Key: D9865D6DD584C7216E28D9DAEB8E22D6F450D0DE5AAD47981BAD6D18D82E636FDEA482D048560B7B8944675484681F91
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    Start Time: 1611641675
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)

### **This is httpd error.log info:**
[Tue Jan 26 14:29:13.021274 2021] [lbmethod_heartbeat:notice] [pid 39496] AH02282: No slotmem from mod_heartmonitor
[Tue Jan 26 14:29:13.033641 2021] [mpm_prefork:notice] [pid 39496] AH00163: Apache/2.4.6 (CentOS) PHP/5.4.16 configured -- resuming normal operations
[Tue Jan 26 14:29:13.033666 2021] [core:notice] [pid 39496] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
ldap_url_parse_ext(ldap://localhost/)
ldap_init: trying /etc/openldap/ldap.conf
ldap_init: using /etc/openldap/ldap.conf
ldap_init: HOME env is NULL
ldap_init: LDAPCONF env is NULL
ldap_init: LDAPRC env is NULL
ldap_create
ldap_url_parse_ext(ldaps://WIN-9GP9CPLJ0J6.test.local:636)
ldap_bind_s
ldap_simple_bind_s
ldap_sasl_bind_s
ldap_sasl_bind
ldap_send_initial_request
ldap_new_connection 1 1 0
ldap_int_open_connection
ldap_connect_to_host: TCP WIN-9GP9CPLJ0J6.test.local:636
ldap_new_socket: 12
ldap_prepare_socket: 12
ldap_connect_to_host: Trying 10.200.6.236:636
ldap_pvt_connect: fd: 12 tm: -1 async: 0
attempting to connect:
connect errno: 13
ldap_close_socket: 12
ldap_err2string
ldap_err2string

### **This is ldap.conf configuration**
#LDAP Defaults
#See ldap.conf(5) for details
#This file should be world readable but not world writable.
#BASE   dc=example,dc=com
#URI    ldap://ldap.example.com ldap://ldap-master.example.com:666
#SIZELIMIT      12
#TIMELIMIT      15
#DEREF          never
TLS_CACERTDIR   /etc/openldap/certs
TLS_CACERT  /etc/openldap/certs/certnew.pem
#Turning this off breaks GSSAPI used with krb5 when rdns = false
SASL_NOCANON    on

### **This is config.inc.php configuration:**
$debug = true;

#LDAP
$ldap_url = "ldaps://WIN-9GP9CPLJ0J6.test.local:636";
$ldap_starttls = false;
$ldap_binddn = "cn=administrator,dc=test,dc=local";
$ldap_bindpw = "Password1";
$ldap_base = "dc=Users,dc=test,dc=local";
$ldap_login_attribute = "cn";
$ldap_fullname_attribute = "cn";
$ldap_filter = "(&(objectClass=user)(sAMAccountName={login})(!(userAccountControl:1.2.840.113556.1.4.803:=2)))";

#Active Directory mode
#true: use unicodePwd as password field
#false: LDAPv3 standard behavior
$ad_mode = true;
#Force account unlock when password is changed
$ad_options['force_unlock'] = true;
#Force user change password at next login
$ad_options['force_pwd_change'] = false;
#Allow user with expired password to change password
$ad_options['change_expired_password'] = true;

**Comment by coudot** [comment]
If SELinux is enabled, please be sure to have allowed LDAP connections from Apache:
```
setsebool -P httpd_can_connect_ldap 1
```

**Comment by Wawoooooo** [comment]
Wawooooooooo
Cool~ Problem solved @coudot Thank you very much！
The problem is SELinux enabled. After that I encountered two more errors, but found a solution in your other reply.
1.res_errno: 49, res_error: <80090308: LdapErr: DSID-0C0903A9, comment: AcceptSecurityContext error, data 52e, v1db1>, res_matched: <>
This problem is Invalid password or credentials
2. res_errno: 50, res_error: <00002098: SecErr: DSID-03150BB9, problem 4003 (INSUFF_ACCESS_RIGHTS), data 0.
This problem is "who_change_password"need set to "manager".
Now it can be used normally. Thanks @coudot

**Comment by coudot** [comment]
Thanks for the feedback, I close the issue.
