### ISSUE TITLE
Can i use it to change my 2012 ActiveDirectory user pass ?

### ISSUE THREAD

**Issue by inghau** [ltb-project/self-service-password#46]
Hi, 
I'm trying to use this to change my AD user password, 
But keep bumping to 
(i) Cannot access LDAP directory
Can someone point me out where is my mistakes ?

Thanks a bunch

here is my config.inc.php
```
#==============================================================================
# Configuration
#==============================================================================
# LDAP
$ldap_url = "ldap://10.20.2.1:389";
$ldap_starttls = false;
$ldap_binddn = "cn=manager,dc=example,dc=com";
$ldap_bindpw = "secret";
$ldap_base = "dc=mydomain,dc=com";
$ldap_filter = "(&(objectClass=user)(sAMAccountName={login})(!(userAccountControl:1.2.840.113556.1.4.803:=2)))";

# Active Directory mode
# true: use unicodePwd as password field
# false: LDAPv3 standard behavior
$ad_mode = true;
# Force account unlock when password is changed
$ad_options['force_unlock'] = false;
# Force user change password at next login
$ad_options['force_pwd_change'] = false;
# Allow user with expired password to change password
$ad_options['change_expired_password'] = false;



```

**Comment by coudot** [comment]
First check the binddn and the base, you don't seem to have correctly set them.

Then you need LDAPS to be able to change password on AD.

**Comment by coudot** [comment]
Did you succeed to make it work?

**Comment by kosli** [comment]
@inghau i think you need to set the following setting too:
`$who_change_password = "manager";`

**Comment by MacsInSpace** [comment]
Just on this, for Server 2012 (R2), I _had_ to install Certificate Services.
Following this you can pull the cert and reference it in the config, however, I added/set `TLS_REQCERT allow `in my `/etc/ldap/ldap.conf` but it would continue to throw the `(i) Cannot access LDAP directory`until the CA service was installed.

On other option to make it a little easier would be to add the option in `change.php` between line 83 and 84 by adding something like `ldap_set_option($ldap, OPT_X_TLS_REQUIRE_CERT, OPT_X_TLS_ALLOW);` or something but I haven't tested it. 
edit: **(req PHP 7.0.5)**
You could possibly even have the level of trust as an option in the config.
