### ISSUE TITLE
It worked.. :)

### ISSUE THREAD

**Issue by itsKV** [ltb-project/self-service-password#461]
Hello folks.,

I was trying to configure SSP directly (using XAMPP) on Windows Server 2016 since last 4 months. Everytime, I was getting SSL/TLS related errors. 
I was trying with setting ldaps://localhost:636 address with starttls=true option.
Searched so much on internet regarding this. Played with OpenLDAP settings. Checked httpd settings. Tried multiple options in SSP's config setting. Nothing was giving me positive result. Later I had left the hopes that SSP will be useful for me anyhow. 

Yesterday, I was looking at RedHat customer portal pages related to ldap related queries. On [one of](https://access.redhat.com/solutions/459683) those pages, there was a sentense written as...
`
STARTTLS and SSL connections cannot be used at the same time.
`

I was in shock. Was that really correct..?? Would that be the case with me as I was using ldaps and starttls both at the same time?? It is also mentioned as, in ldap, TLS can only be used on plain text data and NOT on SSL data. And in hurry, I just changed in SSP's config page as ldap from ldaps and removed port number. And kept $ldap_starttls=true as it was. And voilla.. **It worked.** I was so happy when I got success message. 

There are too many posts here regarding ssl/tls related errors. I don't know how many post's root cause is the above mentioned statement. But some of these posts can be solved using this remedy. 

Following are the all efforts which got me success. 

1. On windows environment, you should create a file exactly at this location...
_C:\OpenLDAP\sysconf\ldap.conf_
You must use exact capitalization while creating above path's files/folders. e.g. OpenLDAP

2. Type following config into this ldap.conf file...
```
TLS_REQCERT never
TLS_CERT \cer.crt
LDAPNOINIT
```

3. Place AD server's root certificate in CRT format exactly at ldap.config file's location. Name it as cer.crt (yes, I am using Windows AD)
_C:\OpenLDAP\sysconf\cer.crt_

4. Following will be the content of config.inc.php file at #LDAP section
```
$ldap_url = "ldap://localhost";
$ldap_starttls = true;
$ldap_binddn = "CN=Administrator,CN=Users,DC=stargroup,DC=local";
$ldap_bindpw = "password of above user";
$ldap_base = "dc=stargroup,dc=local";
$ldap_login_attribute = "sAMAccountName";
$ldap_fullname_attribute = "cn";
$ldap_filter = "(&(objectClass=user)(sAMAccountName={login})(!(userAccountControl:1.2.840.113556.1.4.803:=2)))";
```
You must use ur ad's admin user name at $ldap_binddn. My ad's admin user name is Administrator. Change DC as per your system. Otherwise, create new user having password change authority and mention it here. 

Now try using the SSP application. It should work. 

### NB - Thank you very much SSP team for such an awesome tool. @coudot @plewin

**Comment by itsKV** [comment]
ldap (afaik, windowsAD) needs queries need to be encrypted. In my case, only using SSL was failed. Using SSL and TLS simultaniously was also failed. 
What worked is using only TLS

**Comment by coudot** [comment]
Using LDAPS or startTLS should work.

In your configuration, you set:
```
TLS_REQCERT never
```

Which is not recommended (this skips certificate verification).

Note that you should probably use the server name in `$ldap_url`, and not `localhost`, because your server certificate is certainly valid only for the server name.

**Comment by itsKV** [comment]
Wow. That was a quick reply.. 
1. I am using SSP in closed office network (LAN only). And SSP is installed on AD server itself. So, for me, it is not necessory to verify server certificate. 
2. Further, verifying certificate could cause error as my AD has self signed cert. And common name in certificate is not localhost. I can't use ip address either.

**Comment by coudot** [comment]
As you are working on localhost, you can indeed keep your current configuration. My answer's goal was to warn about weaknesses of this setup, in case anyone wants to apply it on its own installation.
