### ISSUE TITLE
Feature request: Argon2 support

### ISSUE THREAD

**Issue by simonelbaz** [ltb-project/self-service-password#463]
Hi team,

Thanks for this wonderful tool.

Is it planned to add Argon2 support to SSP ?

**Comment by coudot** [comment]
It's planned yet :)

**Comment by simonelbaz** [comment]
Thanks :)

**Comment by coudot** [comment]
This requires PHP with argon2 support. Then `password_has` method can be used: https://www.php.net/manual/en/function.password-hash.php

```php
<?php
echo 'Argon2i hash: ' . password_hash('rasmuslerdorf', PASSWORD_ARGON2I);
?>
```

But we need to check with OpenLDAP which exact argon2 settings are used.

**Comment by dsclassen** [comment]
I am a bit confused. My PHP 7.4.16 has not been compiled with argon2 support as far as I can tell. My LDAP instance is currently using the {ARGON2} hashing mechanism. It appears that there is a mixture of argon2i and argon2id hashes in the userPassword fields. I have installed SSP 1.4.1 (#754006d) . I have set `$hash = "SSHA";` in my `conf.inc.local.php` because I didn't see ARGON2 as an option. I've reset a few passwords expecting them to be converted to SSHA hashed password, but they are all still ARGON2. I'm wondering why this is the case? Is it because I set `$ldap_use_exop_passwd = true;` ?

**Comment by coudot** [comment]
Either you want to hash the password on SSP side, in this case you choose the hash in SSP config and don't count on LDAP directory to hash it, either you configure OpenLDAP to hash the password (with ppolicy overlay or with password extended modify operation), in this case the hash on SSP side should be "clear".

We could maybe add a warning when extended operation is configured but hash is not "clear".

**Comment by tleuxner** [comment]
What is missing to get this implemented? I checked with the php stanza and this hashes the password. I saw a mention about which settings OpenLDAP uses.

slappasswd -h {ARGON2} -o module-load=pw-argon2 -s rasmuslerdorf
{ARGON2}$argon2i$v=19$m=4096,t=3,p=1$8A7aL+7lzGT359h2lVzJVQ$w15x76itFfwHJcgGf0KuZX1YUg+2gEYanHcwEbBA904

**Comment by coudot** [comment]
This requires to add a test in code to check if ARGON2 is supported, then add the method, configuration parameter and associated documentation. You can provide a pull request if you want to help.

**Comment by tleuxner** [comment]
Unfortunately I don't have time to dig into the full code, but here is the basic function which should be easy enough to implement by someone more familiar with the code. Please take not that per PHP docs manual salting is deprecated for `password_hash`. I have tested the hash output by applying it to a user with an LDIF.

```
<?php

function make_argon2_password($password) {

    // Argon2 default options
    $options = [
        'memory_cost' => 4096,
        'time_cost'   => 3,
        'threads'     => 1,
    ];

    $hash = password_hash($password, PASSWORD_ARGON2I, $options);
    return $hash;
}

$password = 'test_secret';
$password = make_argon2_password($password);
echo'{ARGON2}'.$password;

?>
```

**Comment by tleuxner** [comment]
Not sure this works, but here is a tested version against 1.4. Only `functions.inc.php` updated.

https://github.com/ltb-project/self-service-password/pull/626
