### ISSUE TITLE
Download link for v1.4

### ISSUE THREAD

**Issue by sudhakarapn** [ltb-project/self-service-password#464]
I would like to try SSPR v1.4 since it has feature to prompt multiple questions before resetting the password in AD. Please provide the link to download the .zip file since I am setting this up on Windows Server with IIS. 

I could not find the link here for v1.4 - https://ltb-project.org/download#self_service_password

Tried using latest source code from github but index.php and menu.php are missing in the code and hence unable to load the site. 

I am already using v1.3 - let me know if there is any way to setup multiple questions option in v1.3 without migrating to v1.4

**Comment by coudot** [comment]
v1.4 is in progress, not released yet.

You can indeed use the git master version to test it. Not that we switched to Smarty framework, that's why files have changed.

**Comment by sudhakarapn** [comment]
I tried using the git master code but couldn't load the home page since the index.php is missing and please guide me in detail on how to go about it?

**Comment by coudot** [comment]
New documentation: https://self-service-password.readthedocs.io/en/latest/

Use htdocs/index.php

**Comment by sudhakarapn** [comment]
Thank you Coudot, but unable to configure v1.4 on IIS and copying index.php into root folder from htdocs doesn't work. Do I need to install php-Smarty for Windows and do anything around Smarty?

The documentation is only for Linux, how do I configure v1.4 on IIS running on Windows Server? Any help is appreciated.

**Comment by coudot** [comment]
You indeed need to install Smarty. And don't move any file, just configure you virtual host to start at htdocs/ directory.

Using IIS is maybe not the best option, you could try with XAMPP: https://www.apachefriends.org/
