### ISSUE TITLE
AWS Directory service - Password was refused by the LDAP directory 

### ISSUE THREAD

**Issue by prabhu87** [ltb-project/self-service-password#465]
Hi Team,

We have a setup of AWS Directory service and trying to use this tool to do self service password reset option. But couldn't succeed.

Connecting with LDAPS with AD,
Enabled/Updated all the default configuration but getting below errors,

Error1 : Password was refused by the LDAP directory – all the communications are going fine but AD Is refuse to access the change password request.

Configuration:

```
$ldap_url = "ldaps://xxx.com";
$ldap_starttls = false;
$ldap_binddn = "cn=xxx,ou=xxxx,ou=xxx,dc=xxx,dc=xxx,dc=xxx";
$ldap_bindpw = 'xxxxxxx';
$ldap_base = "dc=xxx,dc=xxxx,dc=xxx";
$ldap_login_attribute = "sAMAccountName";
$ldap_fullname_attribute = "cn";
$ldap_filter = "(&(objectClass=user)(sAMAccountName={login})(!(userAccountControl:1.2.840.113556.1.4.803:=2)))";

$ad_mode = true;
```

Error 2: Modify password error 50 (Insufficient access) – Even given the right permission for the user.

Could you please help.

**Comment by coudot** [comment]
If you get error 50, it means that the user doing the modification has not enough rights. Check what is configured in `$who_change_password`.

**Comment by prabhu87** [comment]
Am using admin user which has all the rights.

and my $who_change_password is admin

**Comment by coudot** [comment]
The modify operation is refused by AD, there should be something to do on AD to allow the password change.

**Comment by prabhu87** [comment]
Ok am not sure AWS directory services have any limitations for password change
