### ISSUE TITLE
Language selection issue

### ISSUE THREAD

**Issue by spalekg** [ltb-project/self-service-password#474]
If I configure:
```
$lang = "rs";
$allowed_lang = array("rs");
```
It should ignore language from the browser and it will be shown Serbian (rs) language. But this always shows the English language instead.

I took a look into lib/detectbrowserlanguage.php and there is no logic about using **$allowed_lang** and also in htdocs/index.php, there is no using **$allowed_lang** at all. Then I have a search in all PHP files about using **$allowed_lang** and still, there is not any place where it is used.

This should be fixed, so when I want to be shown ONLY one language (no matter of browser language or whatever) it should be possible.

**Comment by coudot** [comment]
Indeed, this should have be broken by our switch to Smarty. We need to fix it.
