### ISSUE TITLE
Corrections proposed to index.php and pages/* files

### ISSUE THREAD

**Issue by asimos70** [ltb-project/self-service-password#48]
1) In the top directory, file index.php, line 65, change from:
   $dependency_check_results = [];
   to
   $dependency_check_results = array();

2) In the /pages subdirectory, files:
   change.php line 68, resetbyquestions.php line 69, resetbytoken.php line 106, sendsms.php line 119, sendtoken.php line 56, setquestions.php line 63, change from:
   $recaptcha = new \ReCaptcha\ReCaptcha($recaptcha_privatekey);
   to
   $recaptcha = new \ReCaptcha($recaptcha_privatekey);

**Comment by coudot** [comment]
Thanks for the tips.

What is the advantage of using array() instead of [] ?

**Comment by plewin** [comment]
array() allows support for php < 5.4 and it's the traditional way. I don't
think there is other differences.

@coudot what is the minimum php version required for ssp ?
I assumed it's 5.4 based on the travis file.

Is it possible that op is using php <= 5.2 and also edited the recaptcha
lib to make it work on its platform ? (no short notation, no namespace)

**Comment by coudot** [comment]
I did not test SSP for PHP versions under 5.4, but this version should be enough for most of people. Do you need to use SSP with older PHP version?

**Comment by asimos70** [comment]
I use php 5.2.10 and I am not sure if the correction for recaptcha files I proposed is correct! It just worked! When it was "\Recaptcha\Recaptcha..." I was getting a syntax error. If a php >= 5.4 is needed then the developper should mention it on a "Requirements" section.

**Comment by coudot** [comment]
I will test your change to see if it works also for php >= 5.4

**Comment by plewin** [comment]
It will not work. The recaptcha will be unresolved with this change (i
think i can safely assume op is not using recaptcha). the recaptcha needs
5.4 because it uses namespaces.

**Comment by coudot** [comment]
Seems Recaptcha patch does not work:
````
[Fri Nov 11 15:18:29.258129 2016] [:error] [pid 3340] [client 127.0.0.1:52290] PHP Fatal error:  Uncaught Error: Class 'ReCaptcha' not found in /home/clement/dev/self-service-password/pages/change.php:68\nStack trace:\n#0 /home/clement/dev/self-service-password/index.php(206): include()\n#1 {main}\n  thrown in /home/clement/dev/self-service-password/pages/change.php on line 68, referer: http://ssp.example.com/index.php
````

So I will not apply it.

**Comment by asimos70** [comment]
Sorry for being too fast to propose the recaptcha tip and too slow to
answer your posts! :-)
Indeed all depended on me having an old php version (5.2). I switched to
5.4 and everything worked out of the box! Again, sorry for your time!

Nikos Asimos

2016-11-11 16:20 GMT+02:00 Clément OUDOT <notifications@github.com>:

**Comment by coudot** [comment]
Thanks for the feedback.
