### ISSUE TITLE
generating a one-time link for each user

### ISSUE THREAD

**Issue by graceastrid** [ltb-project/self-service-password#495]
in order to limit users' ability to change their password whenever they like, the idea came up to generate one-time links to the self-service-password installed on my server: then each user will have a one-time link that will take effect after a certain time. and the user cannot change the password without such a link

is there such a function in the self-service-password?

**Comment by coudot** [comment]
Not at all.

I don't really see the benefit of avoiding a user changing its password.

Note that the LDAP password policy has a `pwdMinAge` parameter to disallow changing the password if it was changed too recently.

**Comment by graceastrid** [comment]
> Not at all.
> 
> I don't really see the benefit of avoiding a user changing its password.
> 
> Note that the LDAP password policy has a `pwdMinAge` parameter to disallow changing the password if it was changed too recently.

thanks a lot for the pwdMinAge attribute hint!
pwdMinAge helped to do exactly what I added to do temporary links
