### ISSUE TITLE
I have a little problem - I can't use SMS for the next step

### ISSUE THREAD

**Issue by fuyangqing** [ltb-project/self-service-password#506]
Sorry, I'm here again...
Today,I deploy self-service，have a little problem
1. At present, I plan to use the service only through old passwords and SMS

2. There is no problem in using through old passwords ; But when I use the way of SMS: SMS can be received normally, but when I modify the password, it is similar to the old password. I try a lot of passwords, even if the password is completely different, it will be reported wrong. I also find different friends to help me try, but there is still a problem. So I want to ask you boss, what should I do

3.  I checked the log and found that there was no obvious error. I think there is something wrong with SMS file, but I can receive SMS normally，I downloaded the configuration file and SMS file, only hiding some key information
4. The following is the configuration file and related information
[smsapi.txt](https://github.com/ltb-project/self-service-password/files/6392718/smsapi.txt)
[111.txt](https://github.com/ltb-project/self-service-password/files/6392702/111.txt)
![1111](https://user-images.githubusercontent.com/34743908/116423647-74d8c200-a873-11eb-8b62-c365c99d7b20.PNG)
[config.txt](https://github.com/ltb-project/self-service-password/files/6392716/config.txt)

Regards,
A learner

**Comment by coudot** [comment]
Maybe a bug.

Could you try this patch?
```
diff --git a/lib/functions.inc.php b/lib/functions.inc.php
index be55e6b..9506d0b 100644
--- a/lib/functions.inc.php
+++ b/lib/functions.inc.php
@@ -278,7 +278,7 @@ function check_password_strength( $password, $oldpassword, $pwd_policy_config, $
     # Same as login?
     if ( $pwd_diff_login and $password === $login ) { $result="sameaslogin"; }
 
-    if ( $pwd_diff_last_min_chars > 0 ) {
+    if ( $pwd_diff_last_min_chars > 0 and strlen($oldpassword) > 0 ) {
        $similarities = similar_text($oldpassword, $password);
        $check_len    = strlen($oldpassword) < strlen($password) ? strlen($oldpassword) : strlen($password);
        $new_chars    = $check_len - $similarities;
```

**Comment by fuyangqing** [comment]
> Maybe a bug.
> 
> Could you try this patch?
> 
> ```
> diff --git a/lib/functions.inc.php b/lib/functions.inc.php
> index be55e6b..9506d0b 100644
> --- a/lib/functions.inc.php
> +++ b/lib/functions.inc.php
> @@ -278,7 +278,7 @@ function check_password_strength( $password, $oldpassword, $pwd_policy_config, $
>      # Same as login?
>      if ( $pwd_diff_login and $password === $login ) { $result="sameaslogin"; }
>  
> -    if ( $pwd_diff_last_min_chars > 0 ) {
> +    if ( $pwd_diff_last_min_chars > 0 and strlen($oldpassword) > 0 ) {
>         $similarities = similar_text($oldpassword, $password);
>         $check_len    = strlen($oldpassword) < strlen($password) ? strlen($oldpassword) : strlen($password);
>         $new_chars    = $check_len - $similarities;
> ```



> Maybe a bug.
> 
> Could you try this patch?
> 
> ```
> diff --git a/lib/functions.inc.php b/lib/functions.inc.php
> index be55e6b..9506d0b 100644
> --- a/lib/functions.inc.php
> +++ b/lib/functions.inc.php
> @@ -278,7 +278,7 @@ function check_password_strength( $password, $oldpassword, $pwd_policy_config, $
>      # Same as login?
>      if ( $pwd_diff_login and $password === $login ) { $result="sameaslogin"; }
>  
> -    if ( $pwd_diff_last_min_chars > 0 ) {
> +    if ( $pwd_diff_last_min_chars > 0 and strlen($oldpassword) > 0 ) {
>         $similarities = similar_text($oldpassword, $password);
>         $check_len    = strlen($oldpassword) < strlen($password) ? strlen($oldpassword) : strlen($password);
>         $new_chars    = $check_len - $similarities;
> ```

Thanks, but I need to go on a business trip tomorrow.  there is no environment at hand, I'll try this method to repair it in a few days.
