### ISSUE TITLE
ssh-pub-key verification while change

### ISSUE THREAD

**Issue by suchAdemon** [ltb-project/self-service-password#509]
Hello,
my question is related to the ssh-pub-key change possibility.
I have seen that sometimes users are pasting broken (incomplete keys or even miss pasted values) pub keys into the self-service-password tool which of course causes than issue during the ssh authentication on servers.

Is it possible to let self-service-password tool validate the newly inserted ssh-pub-key like
```bash
ssh-keygen -l -f ./id_ed25519_newuserkey.pub
```
Or how could this be implemented?

Many thanks in advance

**Comment by coudot** [comment]
Hi @suchAdemon 

@faust64 just proposed a pull reques( #510). Could you try it?

**Comment by suchAdemon** [comment]
Hello @coudot ,
sure, will test that now and let you know the outcome.

**Comment by suchAdemon** [comment]
Hello @coudot  , Hello @faust64 ,
I have tested that now with an rsa 8k key and with an ed25519 key.
For both I did the following tests:
- insert proper key with comment : works fine - ldapsearch returned new key
- insert proper key without comment: works fine - ldapsearch returned new key
- insert key without type : key denied as expected
- insert key which modified content : key denied as expected
- insert key with mixed type and content (e.g. ed25519 type with content from rsa): key denied as expected
- insert random data : key denied as expected

Hope that helps, anything else you would like me to test there?

**Comment by suchAdemon** [comment]
Hi @faust64 ,
one more thing that I forgot to mention, maybe you want to add an error if it was not updated, so that the users see that it could not perform the change. During the tests it just displayed me the change mask again but without any information or something like that.

**Comment by faust64** [comment]
This makes me realize, sshPublicKey is usually multi-valued.
Current checks may need additional fixing, allowing insertion of more than one pubkey.

**Comment by suchAdemon** [comment]
but that could also be on purpose, like if  a use has for example two old 2k rsa keys which are insecure and wants to replace them with one 4k rsa key. What about if you add a " + " button to add more keys fields so that more than one can be added?
Right now all keys would be replaced if one key is added in there and as I sad, it can be even beneficial if all are getting replaced

**Comment by coudot** [comment]
I would indeed prefer that old keys are replaced by the new one, this will be consistent with current behavior.
