### ISSUE TITLE
[Security:high] Reset by SMS can be used to change any account password

### ISSUE THREAD

**Issue by fuyangqing** [ltb-project/self-service-password#520]
Hi:
I found a bug that can modify the password, operation method and steps of ad users. I will put it in a manual. I am worried that if it is displayed on GitHub, there will be risks.

How can I contact you  ltb-users@ow2.org
Is this the mail?

**Comment by coudot** [comment]
You can send me a mail to clem.oudot@gmail.com

**Comment by fuyangqing** [comment]
I have sent the bug content to the mailbox, please check



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ltb-project/self-service-password"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月12日(星期三) 下午4:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ltb-project/self-service-password] I found a bug that can change the password of ad users (#520)





 
You can send me a mail to ***@***.***

**Comment by coudot** [comment]
I reproduce the issue, thanks a lot for the report.

**Comment by coudot** [comment]
Hello @fuyangqing 

thanks again for the report and the details provided. I just released version 1.4.3 which contains the fix.

**Comment by fuyangqing** [comment]
> Hello @fuyangqing
> 
> thanks again for the report and the details provided. I just released version 1.4.3 which contains the fix.

Thank you very much for your efforts!

Tomorrow, I will synchronize the docker image and conduct penetration test again. At that time, I will give you feedback on the results
