### ISSUE TITLE
Notify on change password doesn't work with link email

### ISSUE THREAD

**Issue by evertonpavan** [ltb-project/self-service-password#527]
Hi guys!

When I use index.php?action=change, I receive the email corretcly.

But when a send a token for email in index.php?action=sendtoken, I access the email with link, change the password, but I dont recevei the email notify that my password were changed.

Some help?

**Comment by coudot** [comment]
Do you have any log? Can you try to set `$debug` to `true`?

**Comment by evertonpavan** [comment]
Here hte logs: https://gist.github.com/evertonpavan/6d348b5a68f6502fd2432053c55349d1

**Comment by faust64** [comment]
I think your issue is over there: https://github.com/ltb-project/self-service-password/pull/529/commits/934c17f4acfb48810d4b7551b79ed7e67581ae4e

We would not get into that if clause, due to a typo checking password change return value.

**Comment by evertonpavan** [comment]
The notification still not working when I change my password in /index.php?action=resetbytoken&token

**Comment by coudot** [comment]
@evertonpavan I was able to make it work with patch provided by @faust64:
https://github.com/ltb-project/self-service-password/pull/529/commits/934c17f4acfb48810d4b7551b79ed7e67581ae4e
