### ISSUE TITLE
Is there any option to encrypt the password in the config file.

### ISSUE THREAD

**Issue by arun767** [ltb-project/self-service-password#528]
hi

Currently for ldap binding, we are passing the username and password in the config file. Is there any way to encrypt it.

**Comment by coudot** [comment]
No but you can use `getenv()` to get the password value from env.

**Comment by arun767** [comment]
Hi Coudot

Thanks could you please share any link which i can refer

**Comment by coudot** [comment]
A simple search on internet gives me this: https://dev.to/fadymr/php-create-your-own-php-dotenv-3k2i
