### ISSUE TITLE
reset password Link sent by mail is contained in the attachement

### ISSUE THREAD

**Issue by tmkklivecom** [ltb-project/self-service-password#531]
Is it possible to send the reset password Link in the mail body instead of in an attachement?

**Comment by tmkklivecom** [comment]
![image](https://user-images.githubusercontent.com/24814483/118360239-0b50f700-b587-11eb-854c-b4a6b5f9671e.png)

**Comment by coudot** [comment]
By default mail is sent in text/plain, see `$mail_contentype`. You can try to set it to HTML but in this case you need to set HTML content in corresponding lang keys.

**Comment by tmkklivecom** [comment]
Unfortunately I installed the application in a docker container. I have no access to the content of the emails. Defining the $mail_contentype variable as text/html or text/css without changing the content of the mails obviously did not have any results. A mail with an attachment that doesn't even have an extension looks suspicious and requires some level of computer skills (the attachment must be downloaded and then opened with a non default (no extension) text editor). Ordinary users can't handle it.

**Comment by tmkklivecom** [comment]
A quick fix I can think of is to add a txt extension and rename the attachment to something more descriptive (e.g. a link to change the password).

**Comment by coudot** [comment]
The real issue is you mail reader, it should display directly the text content of the message.

To test HTML, you can build your docker image with a volume for the conf directory, you will be able to put cusomized lang files in it.

**Comment by tmkklivecom** [comment]
Both most popular email clients - Web Outllok  and Web Gmail have the same behaviour. They don't show the content of the plain text attachements in ta mail body. They show  it as a unnamed unfriendly attachement that cannot be opened easily.

**Comment by tmkklivecom** [comment]
![image](https://user-images.githubusercontent.com/24814483/118657533-dc878a80-b7eb-11eb-991a-ed4648224ced.png)

**Comment by coudot** [comment]
Other users do not seem to have the same issue.

Could you tell us which SMTP server do you use?

**Comment by tmkklivecom** [comment]
I finally set the $mail_contenttype = "text/html" and the recovery link appeared in the mail body.
