### ISSUE TITLE
I have a question about apache service in docker

### ISSUE THREAD

**Issue by fuyangqing** [ltb-project/self-service-password#532]
Hello:

I'm sorry to disturb you again. I have a problem. Now I use docker to run the service.

However, it is found that the Apache service in docker is 2.4.38, and then a vulnerability is found in the official website of Apache   http://httpd.apache.org/security/vulnerabilities_24.html

Although I know the operation will bring trouble to you, in order to better use the service, can you help me.

I have two methods here. 1. Please update docker images. 2. If it's not convenient, can you send me the related software package and dockerfile? My email address is 729176723@qq.com . Emmm... I try to deploy it myself

**Comment by coudot** [comment]
See Docker section in https://github.com/ltb-project/self-service-password/blob/master/packaging/README

**Comment by fuyangqing** [comment]
Thank you very much
