### ISSUE TITLE
Password policy display problem

### ISSUE THREAD

**Issue by jeffaryhe** [ltb-project/self-service-password#533]
```php
# Show policy constraints message:
# always
# never
# onerror
$pwd_show_policy = "onerror";
```

I have configured the password policy. When the password policy is not met, the prompt message will pop up. But version 1.4.3 is not trusted. Please correct the problem.

![image](https://user-images.githubusercontent.com/26104831/118622142-99ccaf00-b7f9-11eb-9110-68ba9e20e32d.png)

**Comment by coudot** [comment]
Unable to reproduce, I see the password policy panel if the new password is refused.

Of course it is not displayed if the error is about the login or current password.
