### ISSUE TITLE
Plus characters in encrypted tokens can accidentally be decoded by email clients/browsers

### ISSUE THREAD

**Issue by pR0Ps** [ltb-project/self-service-password#534]
When encrypted tokens have `+` characters in them, they can be accidentally decoded by email clients/browsers, making them fail when being clicked.

Example (Gmail and Firefox 89.0b14):
------------------------------------
1. I reset my password and a plaintext email is sent with the following link: `https://server/index.php?action=resetbytoken&token=3vUCAKtE2TUDWPFRAh0II61OTycstQfRsrky8tVBZKwY1XMv6zhu862h92oANIwL17AKynH0ckIRvcGzoTr%2BTPreicZddRe0%2BEczfpE5H%2FdxoYQNYGtSCSdLfBGK2HrKLrQh9pNzKL5BZn9P25A%3D`

2. This plaintext email is rendered by Gmail and the link is make clickable. When clicking the link I am sent to `https://server/index.php?action=resetbytoken&token=3vUCAKtE2TUDWPFRAh0II61OTycstQfRsrky8tVBZKwY1XMv6zhu862h92oANIwL17AKynH0ckIRvcGzoTr+TPreicZddRe0+EczfpE5H/dxoYQNYGtSCSdLfBGK2HrKLrQh9pNzKL5BZn9P25A=` (notice the unencoded `+`s)

3. The token is retrieved from the URL as: `3vUCAKtE2TUDWPFRAh0II61OTycstQfRsrky8tVBZKwY1XMv6zhu862h92oANIwL17AKynH0ckIRvcGzoTr TPreicZddRe0 EczfpE5H/dxoYQNYGtSCSdLfBGK2HrKLrQh9pNzKL5BZn9P25A=` (notice the spaces)

4. Decrypting this token results in an `crypto: decryption error Integrity check failed.` error and displays a "Token is not valid" message to the user.

Workarounds
-------------
- Turn `crypt_tokens` off
- Copy/paste URL from the email instead of clicking it
- Right click, copy link from email instead of clicking it

Proposal
---------
Using [Base62](https://en.wikipedia.org/wiki/Base62) instead of Base64 to encode the encrypted token would prevent this from happening.

**Comment by coudot** [comment]
I think the correct fix would be to URL encode the value

**Comment by pR0Ps** [comment]
The value is already urlencoded (the `%`-encoded `+`s in the first URL above). The issue is that something in Gmail/the browser is automatically decoding it when the link is clicked. This means the URL you actually navigate to is already decoded, making the `+` characters get interpreted as spaces by the backend.

**Comment by pR0Ps** [comment]
I don't have that issue - I see the link properly displayed in the email body.

I've just done some more testing and it looks like the bug is actually in Firefox (due to an interaction with Gmail's link redirector service). If I click the link in Chrome and Safari it works fine. If I click the link in Firefox, it urldecodes the token value in the URL.

In Firefox, if I edit the DOM and set the `data-saferedirecturl` attribute on the link to `""` (previously it contained `https://www.google.com/url?q=http://server/index.php?action%3Dresetbytoken%2526token%253D...`, then clicking it works fine too.

If I take that Google redirector link (`https://www.google.com/url?q=...`) and resolve it with `curl`, it returns a 302 with a `Location` header. Copying the contents of that header into a new Firefox tab properly keeps the `+`'s encoded and the token is accepted. Also, allowing `curl` to process the redirect using the `--location` flag also causes the token to be accepted.

From all this, it seems like Firefox is somehow decoding the urlencoded parameters in the Location header when it processes the redirect. I am using a beta version (89.0b14) so it might just be a bug. I'll test the normal release soon and edit this comment with the results.

**Comment by coudot** [comment]
I think we can close this issue, thanks for the feedback
