### ISSUE TITLE
Helping with SMTP auth NTLM

### ISSUE THREAD

**Issue by xJoaan** [ltb-project/self-service-password#543]
Can someone give me a guide on how to make emails can be sent using auth NTLM? I needed to use exchange emails and auth NTLM is mandatory.
I have been looking to add the ntlm_sasl_client.php class, but I have no idea how to do it or what to modify in the self service files, if someone can give me a guide it would help me a lot. Thanks!

**Comment by faust64** [comment]
I'm not sure the library we use sending emails (PHPMailer) still supports NTLM.
They have an old issue, closed, over there: https://github.com/PHPMailer/PHPMailer/issues/1145

Digging in our code, we would find comments:

```
$ grep -Ri authtype lib/vendor/
...
lib/vendor/phpmailer/phpmailer/src/SMTP.php:     * @param string $authtype The auth type (CRAM-MD5, PLAIN, LOGIN, XOAUTH2)
...
```

I'm not sure setting the AuthType to NTLM would work - while it may have, in the past.
Also, self-service-password doesn't set that AuthType, which then defaults to `LOGIN`.

You could try adding `$mailer->SMTPAuth = 'NTLM';` and `$mailer->Realm = 'domain.lan';` (in the `htdocs/index.php`, after the `use PHPMailer` lines) though looking at PHPMailer code, I doubt this would have any effect.

Another way to get this working may be to configure some SMTP relay on your SelfServicePassword server, that would listen for messages from PHP on its loopback, and relay everything to your regular SMTP server, dealing with NTLM authentication on its own.
Sadly, I don't have any configuration sample either way. Postfix should be able to do this, I think.
