### ISSUE TITLE
Rate limit not working on Ubuntu 20.04 apt install

### ISSUE THREAD

**Issue by gnuguy87** [ltb-project/self-service-password#544]
I installed the password reset tool using the apt directions here https://self-service-password.readthedocs.io/en/latest/installation.html. The server was a fresh install of Ubuntu 20.04 with all the latest updates installed. Everything works as expected except the rate limit option. Below is the config I copied from the readthedocs.io page. The DB file never appears to get created. I changed the dbdir to a different folder and changed the permissions to 777. In either case, I can successfully reset passwords, but no file appears in the directory path.

`$enable_ratelimit = true;
$ratelimit_dbdir = '/tmp';
$max_attempts_per_user = 2;
$max_attempts_per_ip = 2;
$max_attempts_block_seconds = "60";
$client_ip_header = 'REMOTE_ADDR';`

**Comment by faust64** [comment]
Isn't this somewhat related to systemd private tmp directories? Checking an ubuntu:20.04 container, installing apache2:

```
# grep PrivateTmp /usr/lib/systemd/system/apache2.service 
PrivateTmp=true
```

I think the file you're looking for is hidden in some subdirectory (specific to your Apache, or PHP-FPM, ...)

You could comment it out, `systemctl daemon-reload`, restart your web server, check back on your `/tmp` directory.

**Comment by gnuguy87** [comment]
Thanks for the quick reply! I did try turning off PrivateTmp as well as point the $ratelimit_dbdir to a different location. I only went looking for the file because even though the limit should be 2 per hour, I was able to reset the same password from the same computer multiple times. I think this is happening because that DB file is not being created. I may not be looking in the correct place. In that case, the lockout is not working for a different reason.

**Comment by faust64** [comment]
Running selfservicepassword (1.4.3) installed from debian packages:

```
$ grep -E '(max_|ratelim)' /usr/share/self-service-password/conf/config.inc.local.php 
$max_attempts = 3;
$use_ratelimit = true;
$max_attempts_block_seconds = "60";
$max_attempts_per_ip = 2;
$max_attempts_per_user = 2;
$ ls -l /tmp
[...]
-rw-r--r-- 1 www-data daemon   17 Jun  6 19:06 ssp_rrl_ips.json
-rw-r--r-- 1 www-data daemon    0 Jun  6 19:06 ssp_rrl_ips.json.lock
-rw-r--r-- 1 www-data daemon   24 Jun  6 19:06 ssp_rrl_users.json
-rw-r--r-- 1 www-data daemon    0 Jun  6 19:06 ssp_rrl_users.json.lock
$ cat /tmp/ssp_rrl_users.json ; echo
{"tssptwo":[1622999180]}
```

Checking back your initial post, you mention setting `$enable_ratelimit` : that variable won't be checked. Maybe a typo? Or you want to change this to `$use_ratelimit`.
Otherwise I don't see it. But I'm pretty confident those db files are properly written, where I was expecting them.
