### ISSUE TITLE
Can I support PHP8.0 or above as soon as possible? I really need it.

### ISSUE THREAD

**Issue by liugang926** [ltb-project/self-service-password#550]
My test project currently does not support PHP8.0 or higher.Can I support PHP8.0 or above as soon as possible? I really need it.

**Comment by faust64** [comment]
At first glance, I don't see any error loading SelfServicePassword pages when installed on a PHP-8 base, ldap functions are there, ... could you elaborate: have you seen an error? In which context? What are you trying to do?

**Comment by liugang926** [comment]
I don’t know the situation, I checked the error log,display：Fatal error: __autoload() is no longer supported, use spl_autoload_register() instead in /var/www/service_password/lib/vendor/PHPMailer/PHPMailerAutoload.php on line 45

**Comment by faust64** [comment]
Are you still using 1.3?
`lib/vendor/PHPMailer` was replaced by `lib/vendor/phpmailer/phpmailer/`, in 1.4.

**Comment by liugang926** [comment]
I see that the installation package of version 1.4 seems to be incomplete, whether it is the official website or github, it seems that there is a lack of key files like index.php.

**Comment by liugang926** [comment]
This seems to affect the file routing relationship, how should I adjust the file path? Can the file be adjusted and provided for download? Because in this case, many people really can't realize the operation of the project.

**Comment by liugang926** [comment]
I tried to copy all the files in the htdocs directory to the root directory of the project, and an error was reported, prompting:Warning: require_once(../conf/config.inc.php): 
Failed to open stream: No such file or directory in /var/www/service_password/index.php on line 11

Fatal error: Uncaught Error: Failed opening required '../conf/config.inc.php' (include_path='.:/usr/share/pear:/usr/share/php:/usr/share/pear:/usr/share/php') in /var/www/service_password/index.php:11 Stack trace: #0 {main} thrown in /var/www/service_password/index.php on line 11

**Comment by faust64** [comment]
Yes, moving php files out of htdocs won't work, as they won't know where to load their libraries or configuration from.

If you're using Apache, the `DocumentRoot` should be changed from `/usr/share/self-service-password` to `/usr/share/self-service-password/htdocs`
With Nginx, same goes for the `root` of the server block used serving Self-Service-Password.

There's no virtualhost configuration shipping with Self-Service-Password: there are a couple documented samples (https://self-service-password.readthedocs.io/en/v1.4/config_webserver.html - there's a typo in the nginx, the root points to `/var/www/html`, should be `/usr/share/self-service-password/htdocs`, I've just sent a PR, ...)

**Comment by liugang926** [comment]
I am using nginx, try to configure root as /usr/share/self-service-password/htdocs, but it seems to be unsuccessful and an error is reported:
Warning: Undefined variable $use_captcha in /var/www/service_password/htdocs/index.php on line 19

Warning: Undefined variable $questions_use_default in /var/www/service_password/htdocs/index.php on line 55

Warning: Undefined variable $ldap_use_exop_passwd in /var/www/service_password/htdocs/index.php on line 76

Warning: Undefined variable $ldap_use_ppolicy_control in /var/www/service_password/htdocs/index.php on line 78

Warning: Undefined variable $mail_smtp_options in /var/www/service_password/htdocs/index.php on line 119

Warning: Undefined variable $pwd_diff_last_min_chars in /var/www/service_password/htdocs/index.php on line 144

Warning: Undefined variable $pwd_no_special_at_ends in /var/www/service_password/htdocs/index.php on line 148

Warning: Undefined variable $pwd_forbidden_words in /var/www/service_password/htdocs/index.php on line 149

Warning: Undefined variable $pwd_forbidden_ldap_fields in /var/www/service_password/htdocs/index.php on line 150

Warning: Undefined variable $max_attempts_per_user in /var/www/service_password/htdocs/index.php on line 157

Warning: Undefined variable $max_attempts_per_ip in /var/www/service_password/htdocs/index.php on line 158

Warning: Undefined variable $max_attempts_block_seconds in /var/www/service_password/htdocs/index.php on line 159

Warning: Undefined variable $presetLogin in /var/www/service_password/htdocs/change.php on line 29

Warning: Undefined variable $use_captcha in /var/www/service_password/htdocs/change.php on line 40

Fatal error: Uncaught Error: Undefined constant "SMARTY" in /var/www/service_password/htdocs/index.php:187 Stack trace: #0 {main} thrown in /var/www/service_password/htdocs/index.php on line 187

**Comment by faust64** [comment]
Sounds like the `config.inc.php` doesn't initializes v1.4 defaults: are you still using a copy from 1.3?

```
/self-service-password$ git diff v1.3..master conf/config.inc.php
...
+$ldap_use_exop_passwd = false;
+$ldap_use_ppolicy_control = false;
...
+# Should the built-in questions be included?
+$questions_use_default = true;
...
+## Captcha
+$use_captcha = false;
...
+if (!defined("SMARTY")) {
+    define("SMARTY", "/usr/share/php/smarty3/Smarty.class.php");
+}
...
```


You should define your site variables in `config.inc.local.php`, and keep the default `config.inc.php` from whichever self-service-password version you are running, otherwise upgrade would have side-effects like these. See https://self-service-password.readthedocs.io/en/v1.4/config_general.html#configuration-files

**Comment by liugang926** [comment]
Hi，Excuse me, I still encounter a key problem, the error message:
Warning: require_once(/usr/share/php/smarty3/Smarty.class.php): Failed to open stream: No such file or directory in /var/www/service_password/htdocs/index.php on line 184

Fatal error: Uncaught Error: Failed opening required '/usr/share/php/smarty3/Smarty.class.php' (include_path='.:/usr/share/pear:/usr/share/php:/usr/share/pear:/usr/share/php') in /var/www/service_password/htdocs/index.php:184 Stack trace: #0 {main} thrown in /var/www/service_password/htdocs/index.php on line 184

I can't find the location of this file Smarty.class.php

**Comment by faust64** [comment]
Sure, Smarty is a dependency. If you installed Self-Service-Password using RPM or DEB packages, Smarty should be installed as a dependency (`php-Smarty` on el8, `smarty3` on deb).
The Docker image would do something like this:

```
RUN mkdir -p /usr/share/php/smarty3/ && \
    curl -Lqs https://github.com/smarty-php/smarty/archive/v3.1.35.tar.gz | \
    tar xzf - -C /usr/share/php/smarty3/ --strip-components=2
```

If you're not using docker, nor the debian/rpm packages: you would need to install Smarty yourself.

**Comment by stevleibelt** [comment]
Looks like this issue is solved and can be closed. Am I right @liugang926? If so, would you be so kind and close it?

**Comment by faust64** [comment]
You're right... let me.

**Comment by liugang926** [comment]
> Looks like this issue is solved and can be closed. Am I right @liugang926? If so, would you be so kind and close it?
I'm very sorry, my Issue has not been solved yet. I can't solve the dependency installation of Smarty for the time being.

**Comment by faust64** [comment]
> I can't solve the dependency installation of Smarty for the time being.

You did not answer my last follow-up though. How did you install self-service-password?

self-service-password packages should pull smarty as a dependency.
Without packages: you should still be able to install smarty using your distro package manager (`php-Smarty` on el8, `smarty3` on deb).
Or: pulling some smarty release from their github repository.

You were mentioning the following error:

```
Fatal error: Uncaught Error: Failed opening required '/usr/share/php/smarty3/Smarty.class.php'
```

Let me run the commands I suggested you to run in response:

```
# mkdir -p /usr/share/php/smarty3
# curl -Lqs https://github.com/smarty-php/smarty/archive/v3.1.35.tar.gz | tar xzf - -C /usr/share/php/smarty3/ --strip-components=2
# ls -l /usr/share/php/smarty3/Smarty.class.php 
-rw-r--r-- 1 root root 38506 Apr 14  2020 usr/share/php/smarty3/Smarty.class.php
```

Now, if you still have an issue, please let us know what's going on.

**Comment by coudot** [comment]
Could you enable debug and send logs?

**Comment by coudot** [comment]
Ok, you commented an issue on PHP 8.0 and your problem is that php-Smarty package is not available on EL9, you should open a new issue for this.
