### ISSUE TITLE
Cannot access to LDAP (Active Directory)

### ISSUE THREAD

**Issue by adocampo** [ltb-project/self-service-password#553]
I'd used self-service-password on the past against OpenLDAP servers, but now I need to use with an AD server. I'm not quite an expert on MS products (nor LDAP), but I have LDAPS on AD and tested with ldp.exe locally on the domain controller.
![imagen](https://user-images.githubusercontent.com/2266612/122184210-4e570080-ce8c-11eb-9019-a2599073c875.png)
![imagen](https://user-images.githubusercontent.com/2266612/122184324-662e8480-ce8c-11eb-82d6-3c35ccfd99c6.png)
![imagen](https://user-images.githubusercontent.com/2266612/122184423-7cd4db80-ce8c-11eb-9f53-406e596098fd.png)
![imagen](https://user-images.githubusercontent.com/2266612/122184458-84948000-ce8c-11eb-83e4-73b1fa2cc513.png)
![imagen](https://user-images.githubusercontent.com/2266612/122184737-cc1b0c00-ce8c-11eb-8267-81d80792a761.png)

So far, I would say it's working.

The problem is self-service-password is complaining it cannot access to the LDAP directory.
I've tried with several accounts, even the Administrator itself, to see if it was something related to permissions, but with the same error. I've tried with ldapsearch, but I can't manage to work either.

I do not know how can I see the exact error, so far, I've tested connectivity through telnet and I can reach the 636 port, but I don't know really how to connect, if I need some certificate (I'd installed openldap-client and obtained the certs from the server with 
```
openssl s_client -connect dc01.eoniantec.lan:636 -showcerts < /dev/null
CONNECTED(00000003)
depth=0 CN = DC01.eoniantec.lan
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = DC01.eoniantec.lan
verify error:num=21:unable to verify the first certificate
verify return:1
---
Certificate chain
 0 s:CN = DC01.eoniantec.lan
   i:DC = lan, DC = eoniantec, CN = eoniantec-DC01-CA
-----BEGIN CERTIFICATE-----
MIIF7zCCBNegAwIBAgITFwAAAAc6FBSCpHpUsQAAAAAABzANBgkqhkiG9w0BAQsF
ADBMMRMwEQYKCZImiZPyLGQBGRYDbGFuMRkwFwYKCZImiZPyLGQBGRYJZW9uaWFu
dGVjMRowGAYDVQQDExFlb25pYW50ZWMtREMwMS1DQTAeFw0yMTAzMjAwMTAwNTFa
Fw0yMjAzMjAwMTAwNTFaMB0xGzAZBgNVBAMTEkRDMDEuZW9uaWFudGVjLmxhbjCC
ASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAL7XTOgvw07nadvwnKTE34fP
jyNQA+mneG2/mLjZW0QS5ou7ByG6X4UimfjYZ1FO/uLz9VOsxRPyVGOCKJUqLIsj
MTY2vCdtgobsrYrAOHYDFYQl++gFinKAJPnbhGb9yIzKuRc7obWm9j/pgq1/1NqC
J7m8tHPjWJNkDRPv4bebyImdecJEeXkhxkXilVdXjTygi9lQ58vUyIGLJXUQQgY8
VSC5AWhcno6EpNAGiR9ch9qakagmnYLdoSRhJvmyau/Hfc1MFw+Dsy+0d8UwyPtU
SmbkZGDN5ZIIT/w6iVTp5avylVrxjAqQVFle8NMZhHy4z5groy90VdTcyUNXj88C
AwEAAaOCAvcwggLzMC8GCSsGAQQBgjcUAgQiHiAARABvAG0AYQBpAG4AQwBvAG4A
dAByAG8AbABsAGUAcjAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDgYD
VR0PAQH/BAQDAgWgMHgGCSqGSIb3DQEJDwRrMGkwDgYIKoZIhvcNAwICAgCAMA4G
CCqGSIb3DQMEAgIAgDALBglghkgBZQMEASowCwYJYIZIAWUDBAEtMAsGCWCGSAFl
AwQBAjALBglghkgBZQMEAQUwBwYFKw4DAgcwCgYIKoZIhvcNAwcwPgYDVR0RBDcw
NaAfBgkrBgEEAYI3GQGgEgQQz3TU6cT6NEmwobweJhqG24ISREMwMS5lb25pYW50
ZWMubGFuMB0GA1UdDgQWBBSMRz4i51g/W/VtwYsBoATLUnW5gjAfBgNVHSMEGDAW
gBRlQziM3R7ru9sgPjfmRr5L6UdBszCBzgYDVR0fBIHGMIHDMIHAoIG9oIG6hoG3
bGRhcDovLy9DTj1lb25pYW50ZWMtREMwMS11QSxDTj1EQzAxLENOPUNEUCxDTj1Q
dWJsaWMlMjBLZXklMjBTZXJ2aWNlcyxDTj1TZXJ2aWNlcyxDTj1Db25maWd1cmF0
aW9uLERDPWVvbmlhbnRlYyxEQz1sYW4/Y2VydGlmaWNhdGVSZXZvY2F0aW9uTGlz
dD9iYXNlP29iamVjdENsYXNzPaNSTERpc3RyaWJ1dGlvblBvaW50MIHFBggrBgEF
BQcBAQSBuDCBtTCBsgYIKwYBBQUHMAKGgaVsZGFwOi8vL0NOPWVvbmlhbnRlYy1E
QzAxLUNBLENOPUFJQSxDTj1QdWJsaWMlMjBLZXklMjBTZXJ2aWNlcyxDTj1TZXJ2
aWNlcyxDTj1dd25maWd1cmF0aW9uLERDPWVvbmlhbnRlYyxEQz1sYW4/Y0FDZXJ0
aWZpY2F0ZT9iYXNlP29iamVjdENsYXNzPWNlcnRpZmljYXRpb25BdXRob3JpdHkw
DQYJKoZIhvcNAQELBQADggEBAFS/z4ZUbthyLWbWTtED6I/+gNPoPrj0GCD2LIqM
uHSwJFfQTxtP7A7PYA4fpDfJAVRlzxhmGiJKYt6mtt/2GZAYpebMpMU+DOLskG51
H2RmEuOxEDlWCNAmZFzS2CdCufvFn+xGA65klycio9xUN+0NHeTq8RLQlQSw0hP3
3geQMJrmfAGDSo4b90SPrNAqrMjFN5OzJMyOkCi/aTaEASYjcoWotaTVS4AONAoy
ddMhYafocAbBeF6zx/IvOfrfzre7mQVwWaxgioIskMupZv+dbOhw0JFv/l5zXP01
KE81x/KSwDWig5XQKKj8HNgh3vNTKcfyDUSeDbHOeQVSQvM=
-----END CERTIFICATE-----
---
Server certificate
subject=CN = DC01.eoniantec.lan

issuer=DC = lan, DC = eoniantec, CN = eoniantec-DC01-CA

---
No client certificate CA names sent
Client Certificate Types: RSA sign, DSA sign, ECDSA sign
Requested Signature Algorithms: RSA+SHA256:RSA+SHA384:RSA+SHA1:ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA1:DSA+SHA1:RSA+SHA512:ECDSA+SHA512
Shared Requested Signature Algorithms: RSA+SHA256:RSA+SHA384:RSA+SHA1:ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA1:RSA+SHA512:ECDSA+SHA512
Peer signing digest: SHA256
Peer signature type: RSA
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 2008 bytes and written 421 bytes
Verification error: unable to verify the first certificate
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 731A000074A7920B750C6FF856A0E32FF883356731A04AF4B99FFF096D711E4E
    Session-ID-ctx: 
    Master-Key: D397843194D76B11CA0553168EFF354B6DDAE2EC24C5D4FD230A2B942BDE7027AE980A69410295826FB0C388A97E8A0F
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1623831896
    Timeout   : 7200 (sec)
    Verify return code: 21 (unable to verify the first certificate)
    Extended master secret: yes
---
DONE
``` 
And saved the `-----BEGIN CERTIFICATE-----` `-----END CERTIFICATE-----` block on /pki/cacerts.pem and configured openldap with the `TLS_CACERT /pki/cacerts.pem` option.

On the SSP configuration file, I set this:
```php
# LDAP
$ldap_url = "ldaps://dc01.eoniantec.lan:636";
$ldap_starttls = true;
$ldap_binddn = "CN=Angel Docampo,OU=Users,OU=IT Department,OU=Eoniantec,DC=eoniantec,DC=lan";
$ldap_bindpw = 'passwordhidden';
$ldap_base = "DC=eoniantec,DC=lan";
$ldap_login_attribute = "sAMAccountName";
$ldap_fullname_attribute = "cn";
$ldap_filter = "(&(objectClass=person)($ldap_login_attribute={login})(!(userAccountControl:1.2.840.113556.1.4.803:=2)))";
$ldap_use_exop_passwd = false;
$ldap_use_ppolicy_control = false;

$ad_mode = true;
$ad_options['force_unlock'] = true;
$ad_options['change_expired_password'] = true;
$who_change_password = "user"
```
I've tried with a user with the privileges to change password as per documentation, with my own AD user, which is an admin user and with the domain administrator itself. 
I also tried `$ldap_starttls` to `true` and `false` and `$who_change_password` both `user` and `manager`. On the `$ldap_url` I've tried the DC fqdn and IP and both specifying the 636 port and not.

After filling the fields and sending the form, this error message appears:
![imagen](https://user-images.githubusercontent.com/2266612/122187039-f40b6f00-ce8e-11eb-9b95-b45a86161e94.png)

So, I have no clue what am I doing wrong, or how can I see any logs (smarty console is quite unfathomable for me). Any help would be much appreciated.

**Comment by faust64** [comment]
Which action are you testing? Regular password change, right?
Could you share webserver + php logs when changing a password?

I would say `$ldap_starttls` should be false, since you're already using ldaps.

Also, the certificate you're showing is not a CA (using `openssl x509 -text -noout -in <cert-file>`, a CA would mention som x509v3 extension `CA:TRUE`, which is not our case here).

I'm not clear where the 2nd, 4th and 5th screenshots came from. Is this ldp.exe output?
Have you tried to use ldapsearch on your SelfServicePassword instance?

**Comment by adocampo** [comment]
I've tried ldapsearch but without success
# ldapsearch -H ldaps://dc01.eoniantec.lan -W -D "CN=Angel
Docampo,OU=Users,OU=IT Department,OU=Eoniantec,DC=eoniantec,DC=lan" -b
"dc=eoniantec,dc=lan" "(sAMAccountName=angel.docampo)"
Enter LDAP Password:
ldap_sasl_bind(SIMPLE): Can't contact LDAP server (-1)

But if I don't have the proper CA cert, perhaps I can't because of that? In
any case, SSP needs the certificate? I didn't see it anywhere on the
documentation

Angel Docampo

***@***.***>

**Comment by faust64** [comment]
In your `/etc/ldap/ldap.conf` (deb) or `/etc/openldap/ldap.conf` (el), have you tried to add something like `TLS_REQCERT never` ?
Although for sure, it would be better to have the proper CA trusted, if you can figure out where it is.

**Comment by adocampo** [comment]
> Which action are you testing? Regular password change, right?

Yes, regular password change with an unlocked account and unexpired password.
> Could you share webserver + php logs when changing a password?
> 

Sure. Apache error logs shows nothing, access log shows nothing relevant either
```
192.168.10.25 - - [16/Jun/2021:11:40:09 +0200] "GET / HTTP/1.1" 200 69414 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0"
192.168.10.25 - - [16/Jun/2021:11:40:10 +0200] "GET /robots.txt HTTP/1.1" 404 196 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0"
192.168.10.25 - - [16/Jun/2021:11:40:27 +0200] "POST / HTTP/1.1" 200 69462 "https://ssp.eoniantec.com/" "Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0"
192.168.10.25 - - [16/Jun/2021:11:40:27 +0200] "GET /robots.txt HTTP/1.1" 404 196 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0"
```
php-fpm perhaps is more relevant
with `$ldap_starttls = true;` the error is this one
```
[16-Jun-2021 09:42:03 UTC] PHP Notice:  Undefined index: HTTP_X_FORWARDED_PROTO in /usr/share/self-service-password/conf/config.inc.local.php on line 75
[16-Jun-2021 09:42:03 UTC] PHP Notice:  Undefined index: HTTP_X_FORWARDED_HOST in /usr/share/self-service-password/conf/config.inc.local.php on line 75
[16-Jun-2021 09:42:20 UTC] PHP Notice:  Undefined index: HTTP_X_FORWARDED_PROTO in /usr/share/self-service-password/conf/config.inc.local.php on line 75
[16-Jun-2021 09:42:20 UTC] PHP Notice:  Undefined index: HTTP_X_FORWARDED_HOST in /usr/share/self-service-password/conf/config.inc.local.php on line 75
[16-Jun-2021 09:42:20 UTC] PHP Warning:  ldap_start_tls(): Unable to start TLS: Can't contact LDAP server in /usr/share/self-service-password/htdocs/change.php on line 83
[16-Jun-2021 09:42:20 UTC] LDAP - Unable to use StartTLS
```
while `$ldap_starttls = false;` gives this other error
```
[16-Jun-2021 09:43:27 UTC] PHP Notice:  Undefined index: HTTP_X_FORWARDED_PROTO in /usr/share/self-service-password/conf/config.inc.local.php on line 75
[16-Jun-2021 09:43:27 UTC] PHP Notice:  Undefined index: HTTP_X_FORWARDED_HOST in /usr/share/self-service-password/conf/config.inc.local.php on line 75
[16-Jun-2021 09:43:39 UTC] PHP Notice:  Undefined index: HTTP_X_FORWARDED_PROTO in /usr/share/self-service-password/conf/config.inc.local.php on line 75
[16-Jun-2021 09:43:39 UTC] PHP Notice:  Undefined index: HTTP_X_FORWARDED_HOST in /usr/share/self-service-password/conf/config.inc.local.php on line 75
[16-Jun-2021 09:43:39 UTC] PHP Warning:  ldap_bind(): Unable to bind to server: Can't contact LDAP server in /usr/share/self-service-password/htdocs/change.php on line 90
[16-Jun-2021 09:43:39 UTC] LDAP - Bind error -1  (Can't contact LDAP server)
```
> I would say `$ldap_starttls` should be false, since you're already using ldaps.

I've tried both with the same error
> Also, the certificate you're showing is not a CA (using `openssl x509 -text -noout -in <cert-file>`, a CA would mention some x509v3 extension `CA:TRUE`, which is not our case here).

So, I need no certificate to make SSP work, right?
> 
> I'm not clear where the 2nd, 4th and 5th screenshots came from. Is this ldp.exe output?

yes, it's a ldap query made with ldp.exe after connecting via ldaps and entering my administrator credentials, and showing a query for my user
> Have you tried to use ldapsearch on your SelfServicePassword instance?

Yes, it works after setting `TLS_REQCERT never` as you mentioned
```
# ldapsearch -H ldaps://dc01.eoniantec.lan -W -D "CN=Angel Docampo,OU=Users,OU=IT Department,OU=Eoniantec,DC=eoniantec,DC=lan" -b "dc=eoniantec,dc=lan" "(sAMAccountName=angel.docampo)"
Enter LDAP Password: 
# extended LDIF
#
# LDAPv3
# base <dc=eoniantec,dc=lan> with scope subtree
# filter: (sAMAccountName=angel.docampo)
# requesting: ALL
#

# Angel Docampo, Users, IT Department, Eoniantec, eoniantec.lan
dn: CN=Angel Docampo,OU=Users,OU=IT Department,OU=Eoniantec,DC=eoniantec,DC=la
 n
objectClass: top
objectClass: person
objectClass: organizationalPerson
objectClass: user
cn: Angel Docampo
sn: Docampo
givenName: Angel
distinguishedName: CN=Angel Docampo,OU=Users,OU=IT Department,OU=Eoniantec,DC=
 eoniantec,DC=lan
...
```

**Comment by faust64** [comment]
Allright. Having set `TLS_REQCERT`, and disabled start-tls, do you still have that ldap_bind error showing in webserver logs?

**Comment by adocampo** [comment]
> Allright. Having set `TLS_REQCERT`, and disabled start-tls, do you still have that ldap_bind error showing in webserver logs?
> 

Yes, with `TLS_REQCERT` set to `never` on  `/etc/openldap/ldap.conf` (so I can ldapsearch against my AD via ldaps) and `$ldap_starttls = false;` the error on php-fpm (apache doesn't complaints, just php) is this one
```
[16-Jun-2021 09:43:27 UTC] PHP Notice:  Undefined index: HTTP_X_FORWARDED_PROTO in /usr/share/self-service-password/conf/config.inc.local.php on line 75
[16-Jun-2021 09:43:27 UTC] PHP Notice:  Undefined index: HTTP_X_FORWARDED_HOST in /usr/share/self-service-password/conf/config.inc.local.php on line 75
[16-Jun-2021 09:43:39 UTC] PHP Notice:  Undefined index: HTTP_X_FORWARDED_PROTO in /usr/share/self-service-password/conf/config.inc.local.php on line 75
[16-Jun-2021 09:43:39 UTC] PHP Notice:  Undefined index: HTTP_X_FORWARDED_HOST in /usr/share/self-service-password/conf/config.inc.local.php on line 75
[16-Jun-2021 09:43:39 UTC] PHP Warning:  ldap_bind(): Unable to bind to server: Can't contact LDAP server in /usr/share/self-service-password/htdocs/change.php on line 90
[16-Jun-2021 09:43:39 UTC] LDAP - Bind error -1  (Can't contact LDAP server)
```
And the red banner on the web still appears.

Anyway, I see nowhere on the documentation to install openldap-client (which is the one who creates the `/etc/openldap/ldap.conf` files) so I understand that `TLS_REQCERT` is not the culprit here, isn't it?

> > So, I need no certificate to make SSP work, right?
> 
> You don't need one, no.
> Although trusting the remote CA would be recommended, ideally.

Understood, if I'm able to make it work without CA, it's a first step, I would deal with that afterwards.

**Comment by faust64** [comment]
Indeed. Now, maybe try to copy that ldap.conf to your webserver root directory. See: https://stackoverflow.com/a/6046800/5607207

Alternatively, in your `config.inc.local.php`, we could try adding some putenv, such as shown here:
https://stackoverflow.com/a/7586808/5607207

**Comment by adocampo** [comment]
> Indeed. Now, maybe try to copy that ldap.conf to your webserver root directory. See: https://stackoverflow.com/a/6046800/5607207
> 

I've copied the ldap.conf file both on `/var/www/html` and `/usr/share/self-service-password/htdocs/`. Same result.
> Alternatively, in your `config.inc.local.php`, we could try adding some putenv, such as shown here:
> https://stackoverflow.com/a/7586808/5607207
> 
No idea how to do this, what I did is modify `/usr/share/self-service-password/htdocs/change.php` and just before the bind I've added that... 
```php
# Bind
    putenv('LDAPTLS_REQCERT=never');
    if ( isset($ldap_binddn) && isset($ldap_bindpw) ) {
        $bind = ldap_bind($ldap, $ldap_binddn, $ldap_bindpw);
    } else {
        $bind = ldap_bind($ldap);
    }
```

no luck either. Same error on php.
> Now, if you can figure out where's the public key for the CA that did sign your AD server certificate, it would be safer to just trust it on your system.

I think I've exported the CA public key of my DC
```bash
openssl x509 -text -noout -in cacerts.pem  | grep -B5 CA
    Data:
        Version: 3 (0x2)
        Serial Number:
            27:94:30:c5:e7:12:af:8c:48:19:1c:84:ab:29:8f:5b
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: DC = lan, DC = eoniantec, CN = eoniantec-DC01-CA
        Validity
            Not Before: Jun 12 12:32:23 2019 GMT
            Not After : Jun 12 12:42:23 2044 GMT
        Subject: DC = lan, DC = eoniantec, CN = eoniantec-DC01-CA
--
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Key Usage: 
                Digital Signature, Certificate Sign, CRL Sign
            X509v3 Basic Constraints: critical
                CA:TRUE
```
ldapsearch now works with `TLS_REQCERT demand` so it's the good one, but unfortunately, SSP still fails with the same errors with the combinations `$who_change_password = "user";` and `$who_change_password = "manager";` and testing with several binddn names (domain admin, my user, a user with reset password permissions and even commenting binddn and bindpw).

**Comment by faust64** [comment]
Allright. If you remove the CA cert path from your ldap.conf: does it still work?
If not, we would have to trust that certificate, rather than add it to ldap client configuration:

el:

```
# cp /your/cert.pem /etc/pki/ca-trust/source/anchors/ad-ca.crt
# update-ca-trust
```

debian:

```
# cp /your/cert.pem /usr/local/share/ca-certificates/
# update-ca-certificates
```

Next, check back on your webserver logs: Do you still have that bind error?

**Comment by adocampo** [comment]
> Allright. If you remove the CA cert path from your ldap.conf: does it still work?

no, if I remove the path or rename the cert file, ldapsearch fails again.
> If not, we would have to trust that certificate, rather than add it to ldap client configuration:
> 
> el:
> 
> ```
> # cp /your/cert.pem /etc/pki/ca-trust/source/anchors/ad-ca.crt
> # update-ca-trust
> ```
> 
> Next, check back on your webserver logs: Do you still have that bind error?

Yes, same error, with all the combinations (user, manager and different binddn credentials), even restarting apache and php-fpm daemons, and even restarting the SSP server itself

**Comment by adocampo** [comment]
OH!
DONE!!!

I had to remove the `TLS_CACERT` on the `/usr/share/self-service-password/htdocs/.ldaprc`

**Comment by faust64** [comment]
Oh, nice!
Weird, I though it was not used. Or maybe still pointing to the server certificate, rather than the actual CA?

Thanks for your follow-up.

**Comment by adocampo** [comment]
> Oh, nice!
> Weird, I though it was not used. Or maybe still pointing to the server certificate, rather than the actual CA?
No it was pointing to the CA cert (i just renamed the "bad" one at the beginning for the good one)

I've even commented all lines on `/etc/openldap/ldap.conf`, so my bet just `/etc/pki/ca-trust/source/anchors/ad-ca.crt` is the key here, because now I can ldapsearch and change the passwords on SSP just normal.
> 
> Thanks for your follow-up.
Thank you to you for your help! You're awesome!
