### ISSUE TITLE
ssp question sms

### ISSUE THREAD

**Issue by Gashir** [ltb-project/self-service-password#554]
Good afternoon! Tell me, is it possible in ssp, when resetting a question, to be able to have the user create his own question and register it ? Also a question about resetting by SMS , is it possible to add two-factor authentication for example SMS + question? Thanks.

**Comment by faust64** [comment]
Hi,

Regarding the first question, yes, users should be able to populate their own questions, having added `question_populate_enable`, and assuming that either manager (if `who_change_password=manager`) or user (`who_change_password=user`) has enough privileges adding/replacing the `$answer_attribute` attribute to your users objects.

see: https://self-service-password.readthedocs.io/en/v1.4/config_questions.html#populate-questions

Regarding SMS password reset: no, there is currently no way to combine this with questions. A PR would be welcome, if you're up for it.

**Comment by Gashir** [comment]
Thank you, about the question I meant that the user could write his own question and not choose from ready-made options? Thanks.

![image](https://user-images.githubusercontent.com/23556857/122207624-01ceed80-ceab-11eb-8b22-acf32ccc118c.png)

**Comment by coudot** [comment]
No, user can't wirte its own questions.

**Comment by Gashir** [comment]
Thank you very much for your reply
