### ISSUE TITLE
Avoid sending email tokens if there are one token alive

### ISSUE THREAD

**Issue by adocampo** [ltb-project/self-service-password#555]
I've just activated the email token sending and, yet it is working, I see I can ask for a token continuously, so, if an atacker wants to flood my inbox by entering just my username, I think is possible (I've sent 6 petitions one after another just by pressing "Send" button, and 6 emails arrived to my inbox.

Is there any way to avoid this behaiour? Something like, if the previous token is still alive, you can't, or set a limit per day/hour of requests?

**Comment by faust64** [comment]
Have you tried to enable rate limitting?
See: https://self-service-password.readthedocs.io/en/v1.4/config_general.html#security

Although I think there's a typo in docs: by default, it would allow for 2 resets (sms or mail) in 60 seconds, not 1 hour.

**Comment by adocampo** [comment]
Sorry for the delay. 
Yes, I set this
```
$enable_ratelimit = true;
$ratelimit_dbdir = '/tmp';
$max_attempts_per_user = 2;
$max_attempts_per_ip = 2;
$max_attempts_block_seconds = "60";
$client_ip_header = 'REMOTE_ADDR';
```
But I can just keep going clicking and sending emails

![imagen](https://user-images.githubusercontent.com/2266612/122549608-f8708d00-d032-11eb-9f41-2549eb75200c.png)

**Comment by adocampo** [comment]
Sorry for the delay. 
Yes, I set this
```
$enable_ratelimit = true;
$ratelimit_dbdir = '/tmp';
$max_attempts_per_user = 2;
$max_attempts_per_ip = 2;
$max_attempts_block_seconds = "60";
$client_ip_header = 'REMOTE_ADDR';
```
But I can just keep going clicking and sending emails

![imagen](https://user-images.githubusercontent.com/2266612/122549608-f8708d00-d032-11eb-9f41-2549eb75200c.png)

I wonder if there is a way to avoid asking for tokens

**Comment by coudot** [comment]
Hello @adocampo

There is a typo in the doc that has been fixed: https://github.com/ltb-project/self-service-password/commit/91748bfe13b2c14bac247a5303d37a0d0e14a0f0

Set `$use_ratelimit` instead of `$enable_ratelimit`

**Comment by adocampo** [comment]
If I set `$use_ratelimit` then SSP website shows a blank page and no email is sent. 
Apache logs shows this
```
"POST /?action=sendtoken HTTP/1.1" 500 - "https://iforgotmypassword.example.com/?action=sendtoken" "Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0"
```

**Comment by coudot** [comment]
Set debug to see what is the error. You may not have the right to modify file in /tmp.

**Comment by adocampo** [comment]
debug shows a popup windows where I cannot see if there is any error, smarty is called?
I did a quick test on /tmp
```
[root@ssp tmp]# id apache
uid=124204676(apache) gid=124200513(domain users) groups=124200513(domain users)
[root@ssp tmp]# sudo -u apache touch test
Creating home directory for apache.
[root@ssp tmp]# ls -lart
total 0
dr-xr-xr-x. 18 root   root         255 Jun 16 10:08 ..
drwx------   3 root   root          17 Jun 16 12:47 systemd-private-bfe892bca45942dbbe2611ef556e5e5c-chronyd.service-9EoK8i
drwx------   3 root   root          17 Jun 16 12:47 systemd-private-bfe892bca45942dbbe2611ef556e5e5c-php-fpm.service-5YgJii
drwx------   3 root   root          17 Jun 16 15:06 systemd-private-bfe892bca45942dbbe2611ef556e5e5c-httpd.service-SFE1xh
-rw-r--r--   1 apache domain users   0 Jun 29 14:31 test
drwxrwxrwt.  5 root   root         253 Jun 29 14:31 .
[root@ssp tmp]# id apache
uid=124204676(apache) gid=124200513(domain users) groups=124200513(domain users)
```

note: I've enrolled ssp host on the AD, I don't know really why apache user belongs to "domain users", but anyway I can create and hav persmissions on /tmp

**Comment by adocampo** [comment]
On smarty I cannot see nor `$use_ratelimit` neither `$enable_ratelimit` but I can see other variables set on config file, I guess that's normal. As I said, I do not know how to interpret this debug...

**Comment by coudot** [comment]
Check the errors in apache error log file

**Comment by adocampo** [comment]
I already posted the error on Apache, it's an error 500
```
"POST /?action=sendtoken HTTP/1.1" 500 - "https://iforgotmypassword.example.com/?action=sendtoken" "Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0"
```

**Comment by coudot** [comment]
No, this is your access log, not your error log.

**Comment by adocampo** [comment]
Sorry for the delay, they are combined, as per apache config example. ssp_error.log is an empty file.
```
    LogLevel warn
    ErrorLog /var/log/httpd/ssp_error.log
    CustomLog /var/log/httpd/ssp_access.log combined
```
Perhaps should I put `debug` in LogLevel?

**Comment by coudot** [comment]
I close this issue because the documentation has been fixed
