### ISSUE TITLE
LDAP Password Policy - Password History

### ISSUE THREAD

**Issue by flhoest** [ltb-project/self-service-password#56]
Dear Team,

I'm having an issue with SSP. I have deployed the SSP on a corporate directory with a lot of people and we love it until we discovered that our users can change their password to basically anything. We have a password history settings which does not seem to be taken into account.

I did some research and it look like in the configuration file there is an interesting parameter : 

$who_change_password = "manager";

That can be changed into "user".

Indeed, if the manager (Administrator) is changing the password this is actually not a "change" but a "set" performed by the LDAP Admin, then no history taken into account (even if complexity is still applied).

Then, I decided to change the parameter to "user" which then should become a "change" and no more a "set".

I did it on our test platform but unfortunately, the screen remain blank and nothing appears on it (expected the top banner).

Questions : 
- Is there a way to have SSP a little bit more "chatty" and have some debug logs ?
- Is the user being setup in the configuration the right way to address my issue ?

Thanks for this very nice product !

Fred.

**Comment by plewin** [comment]
Hi @flhoest,

On your test platform, you can try to add these lines in the config file and try again to check if there is an explanation to your blank page : 
``
ini_set('display_startup_errors',1);
ini_set('display_errors',1);
error_reporting(E_ALL | E_NOTICE | E_WARNING);
``

**Comment by flhoest** [comment]
Hi @plewin ,

I just did it and it does not change anything. I even checked my httpd/error_log file ....

All is too much quite for me :(

Anything else ?

**Comment by flhoest** [comment]
![image](https://cloud.githubusercontent.com/assets/22977759/20610642/b757f4ba-b29c-11e6-9144-bdb98e1f5940.png)

This is what I see when I change the password as "user"

**Comment by plewin** [comment]
Are you using Active Directory ?

**Comment by flhoest** [comment]
Yes and no ... This is a Samba4 deployment and yes, the AD_Mode is on : 

$ad_mode = true;
$samba_mode = true;

**Comment by plewin** [comment]
I believe what you want is not supported. According to this [blog post](https://laviefrugale.blogspot.fr/2013/01/enforcing-active-directory-password.html) some ldap options must be set to tell an AD server to verify the password history. These options are not mentionned in the code of SSP.
I'm not a LDAP Servers expert, does Samba4 requires the same options as an AD ?

**Comment by flhoest** [comment]
Yes this is the goal of Samba4, it is 99,9% the same as a Windows 2008 R2 AD.

Is there a plan to have this supported ? In my opinion, if SSP is trying to change a password which is not compliant with the password history feature, LDAP/AD should return an error. Which is apparently the case here but not handled as it should.

What do you think ?

**Comment by plewin** [comment]
I found an interesting comment [here](https://github.com/silverstripe/silverstripe-activedirectory/blob/master/code/services/LDAPService.php#L62)

``
/**
     * For samba4 directory, there is no way to enforce password history on password resets.
     * This only happens with changePassword (which requires the old password).
     * This works around it by making the old password up and setting it administratively.
     *
     * A cleaner fix would be to use the LDAP_SERVER_POLICY_HINTS_OID connection flag,
     * but it's not implemented in samba https://bugzilla.samba.org/show_bug.cgi?id=12020
     *
``

**Comment by flhoest** [comment]
So, it means the issue is not the SSP itself by Samba :(

This is ... a problem :(

**Comment by plewin** [comment]
In my understanding for your specific case of AD/Samba4, the password history check should work in ad_mode + who_change_password = user in the change password only. It will not work in who_change_user = manager until this [samba issue](https://bugzilla.samba.org/show_bug.cgi?id=12020) is solved. Even if it is not fixed, SSP could make this work with a similar dirty hack patch by setting a random complex password to generate a fake old password.

For some reason ad_mode + who_change_password = user do not work for you and produces no logs and no output (try checking the html source, just in case)

Just a random thought is your page black because you are trying to change your password to an invalid one according to your ldap server ? Have you tried several complex passwords ?

**Comment by flhoest** [comment]
I'm trying to change the password the same way I do it with the "manager" in the config. So, no this is a password which match complexity but not history. This is what I'm trying to mimic. When you change the password with a Windows machine it tells you that the password is known as already used and therefore cannot be changed. This is what I'm expecting as error message and not a blank page.
Btw, I've tried to change the password with something that is not matching history and valid in term of complexity and I have the same behavior, that blank page without any other messages.

What you are proposing is very relevant and unfortunately already been tested before. View source code, check logs, add ini_set, .... but nothing :(

Would it help if I paste my config file here ?

**Comment by plewin** [comment]
Yes please post your config file with passwords / url censored in a gist + precise platform (distro, php version, how you installed ssp)

You want the password history policy to be check also when resetting via email/SMS also or only when changing on the main page ?

**Comment by plewin** [comment]
@flhoest oops ! Please try again with $debug = true in the config file. With the default, errors are not reported.

**Comment by flhoest** [comment]
Ok, it looks like SSP is more chatty now !

Notice: Use of undefined constant LDAP_MODIFY_BATCH_REMOVE - assumed 'LDAP_MODIFY_BATCH_REMOVE' in /var/www/html/ssp/lib/functions.inc.php on line 320 Notice: Use of undefined constant LDAP_MODIFY_BATCH_ADD - assumed 'LDAP_MODIFY_BATCH_ADD' in /var/www/html/ssp/lib/functions.inc.php on line 325 Fatal error: Call to undefined function ldap_modify_batch() in /var/www/html/ssp/lib/functions.inc.php on line 330

**Comment by flhoest** [comment]
Here is my current configuration file : 

`<?php
#==============================================================================
# LTB Self Service Password
#
# Copyright (C) 2009 Clement OUDOT
# Copyright (C) 2009 LTB-project.org
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# GPL License: http://www.gnu.org/licenses/gpl.txt
#
#==============================================================================

ini_set('display_startup_errors',1); 
ini_set('display_errors',1); 
error_reporting(E_ALL | E_NOTICE | E_WARNING);

#==============================================================================
# Configuration
#==============================================================================
# LDAP
$ldap_url = "ldaps://192.168.1.1";
$ldap_starttls = false;
$ldap_binddn = "CN=Administrator,CN=Users,DC=archi,DC=local";
$ldap_bindpw = "***********************************";
$ldap_base = "OU=**,DC=archi,DC=local";
$ldap_login_attribute = "sAMAccountName";
$ldap_fullname_attribute = "cn";
$ldap_filter = "(&(objectClass=person)($ldap_login_attribute={login}))";

# Active Directory mode
# true: use unicodePwd as password field
# false: LDAPv3 standard behavior
$ad_mode = true;
# Force account unlock when password is changed
$ad_options['force_unlock'] = false;
# Force user change password at next login
$ad_options['force_pwd_change'] = false;
# Allow user with expired password to change password
$ad_options['change_expired_password'] = false;

# Samba mode
# true: update sambaNTpassword and sambaPwdLastSet attributes too
# false: just update the password
$samba_mode = true;
# Set password min/max age in Samba attributes
#$samba_options['min_age'] = 5;
#$samba_options['max_age'] = 45;

# Shadow options - require shadowAccount objectClass
# Update shadowLastChange
$shadow_options['update_shadowLastChange'] = false;

# Hash mechanism for password:
# SSHA
# SHA
# SMD5
# MD5
# CRYPT
# clear (the default)
# auto (will check the hash of current password)
# This option is not used with ad_mode = true
$hash = "SSHA";

# Prefix to use for salt with CRYPT
$hash_options['crypt_salt_prefix'] = "$******$";

# Local password policy
# This is applied before directory password policy
# Minimal length
$pwd_min_length = 8;
# Maximal length
$pwd_max_length = 0;
# Minimal lower characters
$pwd_min_lower = 1;
# Minimal upper characters
$pwd_min_upper = 1;
# Minimal digit characters
$pwd_min_digit = 1;
# Minimal special characters
$pwd_min_special = 0;
# Definition of special characters
$pwd_special_chars = "^a-zA-Z0-9";
# Forbidden characters
#$pwd_forbidden_chars = "@%";
# Don't reuse the same password as currently
$pwd_no_reuse = true;
# Check that password is different than login
$pwd_diff_login = true;
# Complexity: number of different class of character required
$pwd_complexity = 0;
# Show policy constraints message:
# always
# never
# onerror
$pwd_show_policy = "always";
# Position of password policy constraints message:
# above - the form
# below - the form
$pwd_show_policy_pos = "below";

# Who changes the password?
# Also applicable for question/answer save
# user: the user itself
# manager: the above binddn
$who_change_password = "user";

## Standard change
# Use standard change form?
$use_change = true;

## Questions/answers
# Use questions/answers?
# true (default)
# false
$use_questions = true;

# Answer attribute should be hidden to users!
$answer_objectClass = "user";
$answer_attribute = "comment";

# Extra questions (built-in questions are in lang/$lang.inc.php)
#$messages['questions']['ice'] = "What is your favorite ice cream flavor?";

## Token
# Use tokens?
# true (default)
# false
$use_tokens = true;
# Crypt tokens?
# true (default)
# false
$crypt_tokens = true;
# Token lifetime in seconds
$token_lifetime = "3600";

## Mail
# LDAP mail attribute
$mail_attribute = "mail";
# Who the email should come from
$mail_from = "****@******.*****";
$mail_from_name = "Self-Service Password";
# Notify users anytime their password is changed
$notify_on_change = true;
# PHPMailer configuration (see https://github.com/PHPMailer/PHPMailer)
$mail_sendmailpath = '/usr/sbin/sendmail';
$mail_protocol = 'smtp';
$mail_smtp_debug = 0;
$mail_debug_format = 'html';
$mail_smtp_host = '192.168.8.136';
$mail_smtp_auth = false;
$mail_smtp_user = '';
$mail_smtp_pass = '';
$mail_smtp_port = 25;
$mail_smtp_timeout = 30;
$mail_smtp_keepalive = false;
#$mail_smtp_secure = 'tls';
$mail_contenttype = 'text/plain';
$mail_charset = 'utf-8';
$mail_priority = 1;
$mail_newline = PHP_EOL;

## SMS
# Use sms
$use_sms = true;
# GSM number attribute
$sms_attribute = "mobile";
# Partially hide number
$sms_partially_hide_number = true;
# Send SMS mail to address
#$smsmailto = "{sms_attribute}@service.provider.com";
$smsmailto = "sms@pccwg.com";
# Subject when sending email to SMTP to SMS provider
$smsmail_subject = "{sms_attribute}";
# Message
$sms_message = "{smsresetmessage} {smstoken}";

# SMS token length
$sms_token_length = 6;

# Max attempts allowed for SMS token
$max_attempts = 3;

# Reset URL (if behind a reverse proxy)
#$reset_url = $_SERVER['HTTP_X_FORWARDED_PROTO'] . "://" . $_SERVER['HTTP_X_FORWARDED_HOST'] . $_SERVER['SCRIPT_NAME'];

# Display help messages
$show_help = true;

# Language
$lang ="en";

# Display menu on top
$show_menu = true;

# Logo
$logo = "images/pccwglobal-logo.png";

# Background image
#$background_image = "images/unsplash-space.jpeg";

# Debug mode
$debug = false;

# Encryption, decryption keyphrase
$keyphrase = "secret";

# Where to log password resets - Make sure apache has write permission
# By default, they are logged in Apache log
#$reset_request_log = "/var/log/self-service-password";

# Invalid characters in login
# Set at least "*()&|" to prevent LDAP injection
# If empty, only alphanumeric characters are accepted
$login_forbidden_chars = "*()&|";

## CAPTCHA
# Use Google reCAPTCHA (http://www.google.com/recaptcha)
$use_recaptcha = false;
# Go on the site to get public and private key
$recaptcha_publickey = "";
$recaptcha_privatekey = "";
# Customization (see https://developers.google.com/recaptcha/docs/display)
$recaptcha_theme = "light";
$recaptcha_type = "image";
$recaptcha_size = "normal";

## Default action
# change
# sendtoken
# sendsms
$default_action = "change";

## Extra messages
# They can also be defined in lang/ files
#$messages['passwordchangedextramessage'] = NULL;
#$messages['changehelpextramessage'] = NULL;

# Launch a posthook script after successful password change
#$posthook = "/usr/share/self-service-password/posthook.sh";

?>`

**Comment by plewin** [comment]
So,
Please post your config in on https://gist.github.com/ and edit your last comment with the link instead.

It looks like when you are using who_change_password = user you get a similar issue to [this one](http://tools.ltb-project.org/issues/880). What is your php version by curiosity ?

**Comment by flhoest** [comment]
[root@SelfService conf]# php -v
PHP 5.3.3 (cli) (built: Aug 11 2016 20:33:53) 
Copyright (c) 1997-2010 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2010 Zend Technologies

**Comment by flhoest** [comment]
PHP Version 5.3.3

**Comment by flhoest** [comment]
Indeed it look very similar; I can go back to manager and the SSP will work like a charm, but this is not a change password in that case, this is a set password and then history is not taken into account :(

**Comment by coudot** [comment]
Seems in this cas you need PHP 5.4 >= 5.4.26, PHP 5.5 >= 5.5.10, PHP 5.6 >= 5.6.0, PHP 7 (see http://php.net/manual/fr/function.ldap-modify-batch.php)

**Comment by plewin** [comment]
Great,
I found this : who_change_password = user work only on php >= 5.4.26
(cc @coudot maybe this should be SSP readme)

You can upgrade to php >= 5.4.26 (or better because 5.4 doesn't have security fixes anymore) and it should work and verify the password history. Anyway who_change_password = user is a bad practice and I believe when using who_change_password, you can't use the reset password by email/sms/questions features (cc @coudot please correct me if I'm wrong)

To support AD password history check in SSP it will require a bit of code. Unfortunately a samba4 server does not support the password history verfication using a manager account unless we use a dirty hack. @coudot is this an acceptable feature request ?

**Comment by flhoest** [comment]
Wow ... guys .... thanks a lot ! let me upgrade ;)

**Comment by coudot** [comment]
Indeed, who_change_password = user works only on php >= 5.4.26 for Active Directory/Samba 4, this works well in any PHP version with a standard LDAP directory.

When using reset password by email/sms/questions, then this option is ignored as we don't have the old password, change is made with manager account

And yes, of course we could add some code to support samba4, if we create a configuration option to activate it.

**Comment by flhoest** [comment]
Ok, we are progressing ;)

![image](https://cloud.githubusercontent.com/assets/22977759/20626804/4e0052b6-b31c-11e6-98b1-b31b59a02aab.png)

I think history is now taken into account, let me test further !

I'm running php 5.5.38

**Comment by flhoest** [comment]
Ok, I have tricky password policy : 

# samba-tool domain passwordsettings show
Password informations for domain 'DC=archi,DC=local'

Password complexity: on
Store plaintext passwords: off
**Password history length: 24**
Minimum password length: 7
**Minimum password age (days): 1**
Maximum password age (days): 42
Account lockout duration (mins): 30
Account lockout threshold (attempts): 0
Reset account lockout after (mins): 30

I will change it .... to proof that it works.

**Comment by plewin** [comment]
Notice 1) I fixed it recently, update your config similar [to this](https://github.com/ltb-project/self-service-password/commit/157e15c61a8f2fa330fed8bc08aad9b2f529c119)
Notice 2) Uncomment [this line](https://gist.github.com/flhoest/435d96d2ccb4f6ba42ba5ffb7b1d6197#file-config-file-L166)

For the warning, it will disappear with debug = false;

**Comment by flhoest** [comment]
Ok, case closed !

![image](https://cloud.githubusercontent.com/assets/22977759/20627037/d829324a-b31d-11e6-9a32-24d19c43b142.png)

Issue was : 

Php version must be > 5.4
and who_changed_password must be set to user !

Thanks a lot for your efficient support, I really appreciate it !

**Comment by coudot** [comment]
Thanks for the feedback. I close the issue.

**Comment by plewin** [comment]
Note that the password history check will not work with reset by email / sms / questions.

**Comment by flhoest** [comment]
Yes, but I think this can be acceptable ...
