### ISSUE TITLE
LDAPS connection issues

### ISSUE THREAD

**Issue by scylla999** [ltb-project/self-service-password#568]
Hello,
I can't seem to get LDAPS to my AD server.   I'm able to do an authenticated ldapsearch to LDAPS on command line.

Here's the sanitized section to my config file:

$debug = false;
$ldap_url = "ldaps://ad.example.com";
$ldap_starttls = false;
$ldap_binddn = "CN=ltb manager,OU=Non_Managed_Accounts,DC=example,DC=com";
$ldap_bindpw = "Secret";
$ldap_base = "DC=example,DC=com";
$ldap_login_attribute = "sAMAccountName";
$ldap_fullname_attribute = "cn";
$ldap_filter = "(&(objectClass=user)(sAMAccountName={login})(!(userAccountControl:1.2.840.113556.1.4.803:=2)))";
$who_change_password = "manager";

$ad_mode = true;
$ad_options['force_unlock'] = false;
$ad_options['force_pwd_change'] = false;
$ad_options['change_expired_password'] = false;

$keyphrase = "blahblahblah!!!";
$lang = "fr";
$allowed_lang = array(fr,en);
$display_footer = false;
$use_questions = false;
$use_sms = false;
$use_tokens = true;
$crypt_tokens = true;
$pwd_min_length = 6;
$reset_request_log = "/var/lib/ssp/ssp.log";

**Comment by faust64** [comment]
Hi,

The `$allowed_lang = array(fr,en);` should be `$allowed_lang = array('fr','en');`, I think. Otherwise your configuration looks good.

You mentioned ldapsearch works: is there anything special in your /etc/ldap/ldap.conf? Like  some `TLS_CACERT`, or `TLS_REQCERT never`?

**Comment by scylla999** [comment]
I've corrected the 'allowed_lang' configuration.   

Here's what I've got in my /etc/openldap/ldap.conf:

REFERRALS off
TLS_REQCERT allow

I'm running CentOS8-Stream and using version 1.43 LTB-SSP.

**Comment by faust64** [comment]
Ah, CentOS8 ... then you have crypto policies?

Maybe something like this would help:

```
 update-crypto-policies --set LEGACY
```

**Comment by faust64** [comment]
Have you tried to set `$debug = true` in your configuration?
Anything in your webserver logs?

**Comment by scylla999** [comment]
Updating the crypto policies did the trick:

update-crypto-policies --set DEFAULT:AD-SUPPORT

Thank You everyone for your help!

**Comment by faust64** [comment]
Weird. I hesitate to suggest going with the DEFAULT policy, as you told us about CentOS 8 ...
Then deleted my message, realizing/remembering that: you could use ldapsearch.

So: ldapsearch was working, against your AD, regardeless of crypto policies, while php-ldap did not?!
I definitely hate CentOS ...

**Comment by scylla999** [comment]
In my job I have to support multiple OS's ans Linux distros...  They all have their problems.   I can't participate in such 'guerre de clochés', I hate them all equally ;-)
