### ISSUE TITLE
$ad_options['force_unlock'] = true; not working

### ISSUE THREAD

**Issue by glorenzutti** [ltb-project/self-service-password#569]
I there! Im using 1.4.3 version, and I can't get to work the force_unlock option.
Everything works, besides this.
Im only using the reset by email token feature.
The password its changed, but the user its still disable.

This is the relevant part of my config.

If anyone can give me a clue, it would be awesome.
tnxs in advance.

root@ltb01:/usr/share/self-service-password/conf# grep -v '#' config.inc.php |grep -v ^$
<?php
$debug = true;
$ldap_url = "ldap://MYLDAP:MYPORT";
$ldap_starttls = false;
$ldap_binddn = "CN=MYCUSTOMDN";
$ldap_bindpw = "MYWILDPASSWORD";
$ldap_base = "DC=MYDB";
$ldap_login_attribute = "sAMAccountName";
$ldap_fullname_attribute = "displayName";
$ldap_filter = "(&(objectClass=person)($ldap_login_attribute={login}))";
$ldap_use_exop_passwd = false;
$ldap_use_ppolicy_control = false;
$ad_mode = true;
$ad_options['force_unlock'] = true;
$ad_options['force_pwd_change'] = false;
$ad_options['change_expired_password'] = true;
$samba_mode = false;
$shadow_options['update_shadowLastChange'] = false;
$shadow_options['update_shadowExpire'] = false;
$shadow_options['shadow_expire_days'] = -180;
$hash = "auto";
$hash_options['crypt_salt_prefix'] = "$6$";
$hash_options['crypt_salt_length'] = "6";
$use_ratelimit = true;
$max_attempts_per_user = 4;
$max_attempts_per_ip = 4;
$max_attempts_block_seconds = "60";
$client_ip_header = 'REMOTE_ADDR';
$pwd_min_length = 8;
$pwd_max_length = 0;
$pwd_min_lower = 0;
$pwd_min_upper = 1;
$pwd_min_digit = 0;
$pwd_min_special = 0;
$pwd_special_chars = "^a-zA-Z0-9";
$pwd_no_reuse = true;
$pwd_diff_login = true;
$pwd_diff_last_min_chars = 0;
$pwd_forbidden_words = array();
$pwd_forbidden_ldap_fields = array();
$pwd_complexity = 0;
$use_pwnedpasswords = false;
$pwd_show_policy = "always";
$pwd_show_policy_pos = "above";
$pwd_no_special_at_ends = false;
$who_change_password = "manager";
$show_extended_error = false;
$use_change = true;
$change_sshkey = false;
$change_sshkey_attribute = "sshPublicKey";
$who_change_sshkey = "user";
$notify_on_sshkey_change = false;
$use_questions = false;
$multiple_answers = false;
$multiple_answers_one_str = false;
$answer_objectClass = "extensibleObject";
$answer_attribute = "info";
$crypt_answers = true;
$questions_use_default = true;
$questions_count = 1;
$question_populate_enable = false;
$use_tokens = true;
$crypt_tokens = true;
$token_lifetime = "3600";

**Comment by faust64** [comment]
Hi,

Your configuration does not show, I assume you did set `$ad_mode = true` as well?
The force_unlock option should remove the lockoutTime attribute from an user, when changing its password.
Can you tell which attribute is used to disable accounts in your AD?

**Comment by glorenzutti** [comment]
Okey, sorry. Now I understand. The force_unlock dosen't enable disabled accounts.
Tnxs, sorry again.

**Comment by faust64** [comment]
No problem.
Managing attributes such as pwdAccountLockedTime, you could look into https://github.com/ltb-project/service-desk -- though that one is not meant to be self-service, like ssp, rather admin-oriented.
Or if your attribute disabling accounts is neither pwdAccountLockedTime nor lockoutTime, we could consider adding support, ... let us know.

**Comment by faust64** [comment]
Thanks for your follow-up.
Actually, I don't think that service-desk already handles `userAccountControl` management. That project is more recent, and probably lacks completion in some aspects. Though we could look into this ...

Could you confirm: you want to take the original `userAccountControl` value, and remove out 0x0002 / ACCOUNTDISABLE (https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/useraccountcontrol-manipulate-account-properties#list-of-property-flags), keeping whatever else was set?
Or should we force-set a new value instead, like 0x0200 / NORMAL_ACCOUNT (which may be customized in config.php).
... Or maybe do something in between, like ensure we're not 0-ing that field (having quickly checked their docs, I'm not sure yet what a "0" would imply there)
I might look into this, at least for service-desk. And check with an owner how relevant it would be to implement something like this in self-service-password.

Also, doc would suggest that `userAccountControl` attribute refers to older active directories (2012). A note (with what I guess is a typo, 2003 / 2013), points to another doc: https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/useraccountcontrol-manipulate-account-properties , which mentions something like: https://docs.microsoft.com/en-us/windows/win32/adschema/a-msds-useraccountdisabled
I'm not much familiar with active directories, ... shouldn't we look into this as well? (instead?) Are you still running 2012 servers?

**Comment by faust64** [comment]
I've opened a new case.
Feel free to answer here, or over there: https://github.com/ltb-project/service-desk/issues/48

**Comment by glorenzutti** [comment]
Sorry for the delay. This is exactly what I need.
Even yesterday, after I understood that the application did not comply with this, I took advantage of the post_hook option.
The post_hook that I put together activates the user.
In fact I was going to report a bug that I found with this, which I am not going to put here to avoid mixing things up.

**Comment by glorenzutti** [comment]
Adding to what has already been said, the need to activate the user has many more use cases than to change the attributes that the application already does.
I appreciate very much that you have read what I shared, and that you have analyzed the case. Hopefully you can include the functionality also in the service-desk application.

The weak point that I found the service-desk is that it does not handle profiles. It would be great if the application has profiles, and also be able to have a record of who did what.

If the two apps were related, it would be another breakthrough. Because you could see in the service-desk who used the application to request a password reset, among many other things.
