### ISSUE TITLE
How to reset password via api

### ISSUE THREAD

**Issue by ilanni2460** [ltb-project/self-service-password#573]
How to reset password via api

I don’t know if it’s written like this：

curl -H "Content-Type: application/x-www-form-urlencoded" -X POST -d '{ "login":"abc","newpassword": "Wer123456", "oldpassword":"Wquy507"}' http://ssp.ilanni.com/rest/v1/changepassword.php

**Comment by faust64** [comment]
Note that you are setting a content type ton form-urlencoded while posting a JSON object.
First I would try to change the Content-Type, or reformat the posted data.

Let us know how that goes

**Comment by ilanni2460** [comment]
@faust64 
I now use this to make a request, and no information is returned

curl -X POST -d '{ "login":"abc","newpassword": "Wer123456", "oldpassword":"Wquy507"}' http://ssp.ilanni.com/rest/v1/changepassword.php


The ssp error log is：

192.168.0.24 - - [08/Sep/2021:15:20:11 +0800] "POST /rest/v1/changepassword.php HTTP/1.1" 500 - "-" "curl/7.29.0"

**Comment by ilanni2460** [comment]
@faust64 Actually I don’t know how to reset the user password through the curl command

can you help me,tks

**Comment by faust64** [comment]
In JSON, should be something like:

```
curl -X POST https://xxx/rest/v1/changepassword.php
   -H 'Content-Type: application/json'
   -d '{"login":"username","oldpassword":"my_old_password","newpassword":"my_new_password"}'
```

Or keeping the form/url-encoded

```
curl -X POST https://xxx/rest/v1/changepassword.php
   -H 'Content-Type: application/x-www-form-urlencoded'
   -d 'login=username&oldpassword=my_old_password&newpassword=my_new_password'
```

If your error 500 persist with proper input:

- Make sure your configuration sets `$use_restapi = true;`.
- Make sure you are already able to change passwords, using web UI.

**Comment by coudot** [comment]
Link to OpenAPI spec: https://github.com/ltb-project/self-service-password/blob/v1.4/rest/v1/doc/openapi-spec.yaml

**Comment by ilanni2460** [comment]
@coudot @faust64 

i use the command:
`curl -X POST -H 'Content-Type: application/x-www-form-urlencoded' -d 'login=abc&oldpassword=Wquy507&newpassword=Wer123456' http://ssp.ilanni.com/rest/v1/changepassword.php
`

the ssp access log:
`
192.168.0.24 - - [09/Sep/2021:17:28:04 +0800] "POST /rest/v1/changepassword.php HTTP/1.1" 500 - "-" "curl/7.29.0"
`



the ssp error log:
`
[Thu Sep 09 17:28:04.245272 2021] [php7:error] [pid 10359] [client 192.168.0.24:45172] PHP Fatal error:  Uncaught Error: Class 'PHPMailer\\PHPMailer\\PHPMailer' not found in /usr/share/self-service-password/rest/v1/include.php:83\nStack trace:\n#0 /usr/share/self-service-password/rest/v1/changepassword.php(2): require_once()\n#1 {main}\n  thrown in /usr/share/self-service-password/rest/v1/include.php on line 83
`


the ssp config file:

`
## Rest API
$use_restapi = true;
`


the ssp  apache config file:

`
<VirtualHost *:80>
        ServerName ssp.ilanni.com

        DocumentRoot /usr/share/self-service-password/htdocs
        DirectoryIndex index.php

        AddDefaultCharset UTF-8

        <Directory /usr/share/self-service-password/htdocs>
            AllowOverride None
            <IfVersion >= 2.3>
                Require all granted
            </IfVersion>
            <IfVersion < 2.3>
                Order Deny,Allow
                Allow from all
            </IfVersion>
        </Directory>

        Alias /rest /usr/share/self-service-password/rest

        <Directory /usr/share/self-service-password/rest>
            AllowOverride None
            <IfVersion >= 2.3>
                Require all granted
            </IfVersion>
            <IfVersion < 2.3>
                Order Deny,Allow
                Allow from all
            </IfVersion>
`

**Comment by ilanni2460** [comment]
@faust64 @coudot 
I am sure I can change the password via webui
tks

**Comment by faust64** [comment]
Could you try to add this, to your configuration file:

```
use_pwnedpasswords = true;
```

In rest/v1/include.php, the ../../lib/vendor/autoload.php file is only included when pwnedpasswords is enabled.
This is a bug.

**Comment by faust64** [comment]
Otherwise, you may try the patch I've submitted in the PR above ( #576 )

**Comment by ilanni2460** [comment]
@faust64 @coudot 
I have modified it according to this PR (#576 ), and now I can reset my password, thank you very much

![git](https://user-images.githubusercontent.com/5058391/132786005-8b012abc-bab3-4245-8148-d78713b66d43.png)


![git1](https://user-images.githubusercontent.com/5058391/132786447-e92d9c74-e4e5-4c3f-bc07-7b2f08b84b5c.png)
