### ISSUE TITLE
How to reset password via api

### ISSUE THREAD

**Issue by ilanni2460** [ltb-project/self-service-password#574]
How to reset password via api

I don’t know if it’s written like this：

curl -H "Content-Type: application/x-www-form-urlencoded" -X POST -d '{ "login":"abc","newpassword": "Wer123456", "oldpassword":"Wquy507"}' http://ssp.ilani.com/rest/v1/changepassword.php

**Comment by faust64** [comment]
Closing this, as it duplicates https://github.com/ltb-project/self-service-password/issues/573
