### ISSUE TITLE
Updated catalan translation

### ISSUE THREAD

**Issue by muzzol** [ltb-project/self-service-password#575]
As I was upgrading my current SSP version I took the chance to correct and update catalan version.

I've pasted the translation here, sorry for not following the whole PR process:

https://zerobin.net/?e33cbe8161b0e57b#Ln+4QagfqfrZRmkpWLAsJ9mGuS3LMryQULSrzHDt/v4=

**Comment by coudot** [comment]
Imported, thanks!
