### ISSUE TITLE
Some suggestions about rest api

### ISSUE THREAD

**Issue by ilanni2460** [ltb-project/self-service-password#578]
1. The password can be changed through the adminchangepassword.php interface, but this is not safe. hope to add the SMS or email verification function
2. After the password is successfully modified, try to add the SMS reminder function

**Comment by coudot** [comment]
>     1. The password can be changed through the adminchangepassword.php interface, but this is not safe. hope to add the SMS or email verification function

REST API should not be reacheable without authentication, protect it in your webserver configuration. Adding SMS et email verification won't increase much the security.

> 
>     2. After the password is successfully modified, try to add the SMS reminder function

This something you already said in #577
