### ISSUE TITLE
I want to submit a new sms interface, such as Alibaba. What should I do?

### ISSUE THREAD

**Issue by ilanni2460** [ltb-project/self-service-password#580]
I want to submit a new sms interface, such as Alibaba. What should I do?

**Comment by coudot** [comment]
Hello,

you need to submit a pull request with a module like https://github.com/ltb-project/self-service-password/blob/master/lib/smsapi-signal-cli.inc.php and associated documentation like https://github.com/ltb-project/self-service-password/blob/master/docs/sms_api.rst#signal

**Comment by ilanni2460** [comment]
@coudot ok,tks
