### ISSUE TITLE
"Partly working" for my inetOrgPerson

### ISSUE THREAD

**Issue by VanguardAX1** [ltb-project/self-service-password#581]
Hello here,
Seems my sspr do not change the "Password" attribution, instead something else.
For example, I have a user `cn=Jack`, with `objectClass=inetOrgPerson`, `Password=123456`
I changed password to `1234567` via sspr, and everything seems fine.
But, when I check from ldapadmin, there is still `Password=123456` and no change recognized.
In short, only sspr accepts the new `1234567` password (for next time password change).
That's really confusing for me. AFAIS, the new password is stored somewhere sspr read, but Attribution `Password` isn't changed.
My local config file:
```
# LDAP
$ldap_url = "ldap://localhost";
$ldap_starttls = false;
$ldap_binddn = "cn=Manager,dc=my-domain,dc=com";
$ldap_bindpw = 'myadminpassword';
$ldap_base = "dc=my-domain,dc=com";
$ldap_login_attribute = "dn";
$ldap_fullname_attribute = "cn";
$ldap_filter = "(&(objectClass=inetOrgPerson))";
$ldap_use_exop_passwd = false;
$ldap_use_ppolicy_control = false;

$who_change_password = "manager";
```

**Comment by coudot** [comment]
The password is changed in `userPassword` LDAP attribute.

Check your LDAP logs.

**Comment by VanguardAX1** [comment]
Yeah I got it. Thank you!
I didn't understand `{login}` in `$ldap_filter = "(&(objectClass=inetOrgPerson)($ldap_login_attribute={login}))";`
So I used `$ldap_filter = "(&(objectClass=inetOrgPerson))";` , and LDAP throw me first inetOrgPerson on the tree (accidentally has same password).

**Comment by coudot** [comment]
`{login}` is replaced by user login, it is mandatory in the filter
