### ISSUE TITLE
Ca de samba dc en self

### ISSUE THREAD

**Issue by adrian-agp** [ltb-project/self-service-password#584]
how can I make self service password user the samba ca.pem for tls ldaps: //

**Comment by faust64** [comment]
On debian/ubuntu/alpine/... systems, you would add that CA to `/usr/local/share/ca-certificates/<your-ca>.crt`, then run `update-ca-certificates`.
On rhel/centos/fedora/..., you would add your CA to `/etc/pki/ca-trust/source/anchors/<your-ca>.crt`, then run `update-ca-trust`.
You may also try to edit `/etc/ldap/ldap.conf` (`/etc/openldap/ldap.conf`), setting `TLS_CACERT /path/to/ca.crt`.

**Comment by adrian-agp** [comment]
thanks for the answer I whistled
