### ISSUE TITLE
Docker openldap enables rest api function

### ISSUE THREAD

**Issue by ilanni2460** [ltb-project/self-service-password#585]
Docker openldap enables rest api function

**Comment by coudot** [comment]
Is this a question?

To enable REST API, you just need to configure `$use_restapi = true;`

**Comment by ilanni2460** [comment]
@coudot yes,this is a question.
Use the official docker image, if you want to enable api rest, in addition to the configuration file to be modified, whether the apache configuration file also needs to be modified

**Comment by ilanni2460** [comment]
@coudot the docker image is osixia/docker-openldap

**Comment by coudot** [comment]
You should be able to mount a custom apache config when running the container

**Comment by ilanni2460** [comment]
@coudot 
I use this command, it is ok

`docker run -dit --name ssp -p 80:80 -v /opt/soft/ssp/ssp.conf.php:/var/www/conf/config.inc.php -v /opt/soft/ssp/lib/:/var/www/lib/ -v /opt/soft/ssp/self-service-password.conf:/etc/apache2/sites-enabled/self-service-password.conf -u root --restart=always ltbproject/self-service-password`

this is  apache config file:
[self-service-password.zip](https://github.com/ltb-project/self-service-password/files/7160624/self-service-password.zip)

**Comment by ilanni2460** [comment]
@coudot tks
