### ISSUE TITLE
Show sucessful message even if password change failed when exop and ppolicy enabled

### ISSUE THREAD

**Issue by tonny1983** [ltb-project/self-service-password#589]
Due to [known issue of `ldap_exop_passwd` method](https://bugs.php.net/bug.php?id=80820), the current implementation always returns successful page even if the password has not been changed due to the restrictions of `ppolicy`.

That is to say, the return value of Line 459 of `functions.inc.php` is always `0` even if `ldap_exop_passwd` failed. Therefore, the `error_code` checking routine never works in the case.

I'm not sure whether it is a solution to force the `error_code` value to `19` when `exop_passwd` is not `TURE`.

**Comment by coudot** [comment]
Indeed, for now, you should not use ppolicy and ldap_exop_password. As the bug is in PHP, I don't know if we should apply a workaround in our code, this will break once the bug is fixed in PHP.

**Comment by tonny1983** [comment]
In my case, it is one of the reasons to use `ldap_exop_password` method that password history check mechanism is currently implemented by OpenLDAP server itself. It is difficult to store and check history password in the ldap client side. I'm afraid it is also a common requirement that is worth making a workaround.

**Comment by coudot** [comment]
`ldap_exop_password` is not required for password history, or any password policy feature of OpenLDAP ppolicy overlay. Just use the control.

**Comment by tonny1983** [comment]
If I set `$ldap_use_exop_passwd = false;` and `$ldap_use_ppolicy_control = true;`, the log of LDAP server shows:
```
61511dad conn=1056 op=4 MOD dn="uid=xxxx,ou=xxx,dc=xxx,dc=xxx,dc=xx"
61511dad conn=1056 op=4 MOD attr=userPassword
```
It seems that the  `userPassword` attribute has been changed without ppolicy check because using `MOD` command. If `$ldap_use_exop_passwd = true;` and `$ldap_use_ppolicy_control = true;`, the log changed as follows:
```
61511ed2 conn=1061 op=4 EXT oid=1.3.6.1.4.1.4203.1.11.1
61511ed2 conn=1061 op=4 PASSMOD id="uid=xxxx,ou=xxx,dc=xxx,dc=xxx,dc=xx" old new
61511ed2 check_password_quality: module error: (pqchecker.so) The password does not pass quality check..[1]
61511ed2 conn=1061 op=4 RESULT oid= err=19 text=
```
I'm not sure whether I'm misunderstanding some points or it is the correct result as design.

**Comment by coudot** [comment]
You need to pass cleartext password to the LDAP directory. This option is forced when using exop but not when using standard modification. So change your config with:
```
$hash = "clear";
```

**Comment by tonny1983** [comment]
Thanks a lot for your kind information. With the following config:
```
$ldap_use_exop_passwd = false;
$ldap_use_ppolicy_control = true;
$hash = "clear";
```
the ppolicy seems to be applied. Therefore, there is no need to use  `ldap_exop_password` method in my case then.

**Comment by dhoffend** [comment]
Just to let you know: I've tested a few combinations (with php7.4):

# test 1
```
$ldap_use_exop_passwd = true;
$ldap_use_ppolicy_control = true;

Apr  1 12:47:58 ldap1 slapd[1926096]: conn=1035 op=3 EXT oid=1.3.6.1.4.1.4203.1.11.1
Apr  1 12:47:58 ldap1 slapd[1926096]: conn=1035 op=3 PASSMOD id="uid=tuser,ou=accounts,dc=mgmt,dc=dotlan,dc=de" old new
Apr  1 12:47:58 ldap1 slapd[1926096]: conn=1035 op=3 RESULT oid= err=19 text=Password fails quality checking policy
```
**Result:** exop gets triggered, Self Service Portal reports password has been modified

# test 2
```
$ldap_use_exop_passwd = true;
$ldap_use_ppolicy_control = false;

Apr  1 12:50:19 ldap1 slapd[1926096]: conn=1038 op=3 EXT oid=1.3.6.1.4.1.4203.1.11.1
Apr  1 12:50:19 ldap1 slapd[1926096]: conn=1038 op=3 PASSMOD id="uid=tuser,ou=accounts,dc=mgmt,dc=dotlan,dc=de" old new
Apr  1 12:50:19 ldap1 slapd[1926096]: conn=1038 op=3 RESULT oid= err=19 text=Password fails quality checking policy
```
**Result:** exop gets triggered, Self Service Portal reports error "Password fails quality checking policy", but no details

# test 3
```
$ldap_use_exop_passwd = false;
$ldap_use_ppolicy_control = true;
$hash = 'clear';

Apr  1 13:03:11 cmp-ldap1 slapd[1926096]: conn=1044 op=3 MOD dn="uid=tuser,ou=accounts,dc=mgmt,dc=dotlan,dc=de"
Apr  1 13:03:11 cmp-ldap1 slapd[1926096]: conn=1044 op=3 MOD attr=userPassword
Apr  1 13:03:11 cmp-ldap1 slapd[1926096]: conn=1044 op=3 RESULT tag=103 err=19 text=Password fails quality checking policy
```
**Result:** no exop gets triggered, Self Service Portal reports error "Password fails quality checking policy", with details "passwort to short"

I've to digg into the code again to see why ldap_exop_password() return value changes the behaviour if we pass $ctrls as option.

My main problem is the fact that I'm required to use EXOP because of custom slapd-modules that have their hooks on exop operations. Those modules would not work if i change the userPassword attributes using the cleartext hash method.

**Comment by coudot** [comment]
As you can see in the issue, there is a bug in PHP: https://bugs.php.net/bug.php?id=80820

You can't use EXPO and ppolicy control together for the moment
