### ISSUE TITLE
SSH key mail sent even if ldap attribut is not change

### ISSUE THREAD

**Issue by roumano** [ltb-project/self-service-password#591]
If it's a issue on ldap (Like missing ldap permission to update ssh PublicKey ) 

The SSP send a mail to user about ssh key change 
For me, it's should send this kind of mail only if it's really change in the ldap.

**Comment by coudot** [comment]
Hello, this has been fixed in master: https://github.com/ltb-project/self-service-password/commit/982cafad6d9994a0502d42de0ec9c82590a585b1
