### ISSUE TITLE
Password not effect although password was changed

### ISSUE THREAD

**Issue by nguamay** [ltb-project/self-service-password#597]
Could you help me with this issue! :(
password was changed but not effect, when login with old pass is still working, not working with new password. 
Ex. user **test1** pass **123456** change **abcxyz**. then login success with **123456** not with **abcxyz**.
![image](https://user-images.githubusercontent.com/11470118/138205449-c620a5ee-8fc8-4dbd-a458-311b79747efc.png)
My config
# LDAP
$ldap_url = "ldap://xxx.2";
$ldap_starttls = false;
$ldap_binddn = "CN=test1,OU=xxx,OU=xxx,OU=xxxser,DC=xxx,DC=local";
$ldap_bindpw = 'xxx';
$ldap_base = "DC=xxxDC=local";
#$ldap_login_attribute = "uid";
$ldap_login_attribute = "sAMAccountName";
$ldap_fullname_attribute = "cn";
$ldap_filter = "(&(objectClass=person)($ldap_login_attribute={login}))";
#$ldap_filter = "($ldap_login_attribute={login})";
$ldap_use_exop_passwd = false;
$ldap_use_ppolicy_control = false;

**Comment by DSantonastaso** [comment]
Hello, here the same problem. I use docker installation and logs do not detect any problems:

[Wed Aug 24 08:35:45.695912 2022] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.53 (Debian) PHP/7.4.30 configured -- resuming normal operations
[Wed Aug 24 08:35:45.707033 2022] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
192.168.0.4 - - [24/Aug/2022:08:35:55 +0000] "GET / HTTP/1.1" 200 1742 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36"
192.168.0.4 - - [24/Aug/2022:08:36:10 +0000] "POST / HTTP/1.1" 200 1356 "http://192.168.0.124:8000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36"

Any idea?
Thank you

Daniele

**Comment by coudot** [comment]
Enable debug and check apache error log

**Comment by DSantonastaso** [comment]
Thank you for reply.
This is docker logs after enabled log:

AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
[Wed Aug 24 08:50:55.714086 2022] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.53 (Debian) PHP/7.4.30 configured -- resuming normal operations
[Wed Aug 24 08:50:55.716411 2022] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
ldap_url_parse_ext(ldap://localhost/)
ldap_init: trying /etc/ldap/ldap.conf
ldap_init: HOME env is NULL
ldap_init: trying ldaprc
ldap_init: LDAPCONF env is NULL
ldap_init: LDAPRC env is NULL
[Wed Aug 24 08:51:01.437155 2022] [php7:notice] [pid 18] [client 192.168.0.4:22513] PHP Notice:  Undefined index: msg_changehelpextramessage in /var/www/templates_c/3ba7131c51edfe0cef48341f1409d3c1a60d3c16_2.file.change.tpl.php on line 43
[Wed Aug 24 08:51:01.437541 2022] [php7:notice] [pid 18] [client 192.168.0.4:22513] PHP Notice:  Trying to get property 'value' of non-object in /var/www/templates_c/3ba7131c51edfe0cef48341f1409d3c1a60d3c16_2.file.change.tpl.php on line 43
192.168.0.4 - - [24/Aug/2022:08:51:01 +0000] "GET / HTTP/1.1" 200 1742 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36"
[Wed Aug 24 08:51:14.737074 2022] [php7:notice] [pid 19] [client 192.168.0.4:22515] PHP Notice:  Undefined index: msg_changehelpextramessage in /var/www/templates_c/3ba7131c51edfe0cef48341f1409d3c1a60d3c16_2.file.change.tpl.php on line 43, referer: http://192.168.0.124:8000/
[Wed Aug 24 08:51:14.737577 2022] [php7:notice] [pid 19] [client 192.168.0.4:22515] PHP Notice:  Trying to get property 'value' of non-object in /var/www/templates_c/3ba7131c51edfe0cef48341f1409d3c1a60d3c16_2.file.change.tpl.php on line 43, referer: http://192.168.0.124:8000/
ldap_msgfree
ldap_free_connection 1 1
ldap_send_unbind
ldap_free_connection: actually freed
192.168.0.4 - - [24/Aug/2022:08:51:14 +0000] "POST / HTTP/1.1" 200 1768 "http://192.168.0.124:8000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36"
[Wed Aug 24 08:51:27.274003 2022] [php7:notice] [pid 17] [client 192.168.0.4:22516] PHP Notice:  Undefined index: msg_passwordchangedextramessage in /var/www/templates_c/3ba7131c51edfe0cef48341f1409d3c1a60d3c16_2.file.change.tpl.php on line 139, referer: http://192.168.0.124:8000/
[Wed Aug 24 08:51:27.274470 2022] [php7:notice] [pid 17] [client 192.168.0.4:22516] PHP Notice:  Trying to get property 'value' of non-object in /var/www/templates_c/3ba7131c51edfe0cef48341f1409d3c1a60d3c16_2.file.change.tpl.php on line 139, referer: http://192.168.0.124:8000/
ldap_msgfree
ldap_free_connection 1 1
ldap_send_unbind
ldap_free_connection: actually freed
192.168.0.4 - - [24/Aug/2022:08:51:27 +0000] "POST / HTTP/1.1" 200 1356 "http://192.168.0.124:8000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36"

**Comment by coudot** [comment]
```
ldap_url_parse_ext(ldap://localhost/)
```

I don't think your LDAP server is on localhost in your docker

**Comment by DSantonastaso** [comment]
You are right but i have change configuration (config.inc.php):
...
$ldap_url = "ldap://192.168.0.1";
...

Where i can change ldap_url_parse_ext?

**Comment by coudot** [comment]
You need to mount your configuration as docker volume, not edit the built-in config.

See https://self-service-password.readthedocs.io/en/v1.4.5/installation.html#docker

**Comment by DSantonastaso** [comment]
OK,
when i use config.inc.local, docker return this error:
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
[Wed Aug 24 09:26:38.983647 2022] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.53 (Debian) PHP/7.4.30 configured -- resuming normal operations
[Wed Aug 24 09:26:38.984428 2022] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
[Wed Aug 24 09:26:48.690530 2022] [php7:error] [pid 18] [client 192.168.0.4:24016] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in /var/www/conf/config.inc.local.php on line 386
192.168.0.4 - - [24/Aug/2022:09:26:46 +0000] "GET / HTTP/1.1" 500 211 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0

Any idea?

**Comment by coudot** [comment]
Read the doc and the warning here: https://self-service-password.readthedocs.io/en/v1.4.5/config_general.html#configuration-files

**Comment by DSantonastaso** [comment]
ok, now i have create a 
ssp.php (only with ldap configuration and secret and debug option) and i have use it in docker cmd but i have the same beaviours:

AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
[Wed Aug 24 10:05:37.806604 2022] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.53 (Debian) PHP/7.4.30 configured -- resuming normal operations
[Wed Aug 24 10:05:37.817497 2022] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
ldap_url_parse_ext(ldap://localhost/)
ldap_init: trying /etc/ldap/ldap.conf
ldap_init: HOME env is NULL
ldap_init: trying ldaprc
ldap_init: LDAPCONF env is NULL
ldap_init: LDAPRC env is NULL
[Wed Aug 24 10:05:40.366358 2022] [php7:notice] [pid 17] [client 192.168.0.4:24220] PHP Notice:  Undefined index: msg_changehelpextramessage in /var/www/templates_c/3ba7131c51edfe0cef48341f1409d3c1a60d3c16_2.file.change.tpl.php on line 43
[Wed Aug 24 10:05:40.366785 2022] [php7:notice] [pid 17] [client 192.168.0.4:24220] PHP Notice:  Trying to get property 'value' of non-object in /var/www/templates_c/3ba7131c51edfe0cef48341f1409d3c1a60d3c16_2.file.change.tpl.php on line 43
192.168.0.4 - - [24/Aug/2022:10:05:40 +0000] "GET / HTTP/1.1" 200 6615 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36"
[Wed Aug 24 10:05:50.520586 2022] [php7:notice] [pid 18] [client 192.168.0.4:24221] PHP Notice:  Undefined index: msg_passwordchangedextramessage in /var/www/templates_c/3ba7131c51edfe0cef48341f1409d3c1a60d3c16_2.file.change.tpl.php on line 139, referer: http://192.168.0.124:8000/
[Wed Aug 24 10:05:50.520797 2022] [php7:notice] [pid 18] [client 192.168.0.4:24221] PHP Notice:  Trying to get property 'value' of non-object in /var/www/templates_c/3ba7131c51edfe0cef48341f1409d3c1a60d3c16_2.file.change.tpl.php on line 139, referer: http://192.168.0.124:8000/
ldap_msgfree
ldap_free_connection 1 1
ldap_send_unbind
ldap_free_connection: actually freed
192.168.0.4 - - [24/Aug/2022:10:05:50 +0000] "POST / HTTP/1.1" 200 6233 "http://192.168.0.124:8000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36"

where i can change ldap_url_parse_ext(ldap://localhost/) ?
Thanks for support

**Comment by coudot** [comment]
> where i can change ldap_url_parse_ext(ldap://localhost/) ?

This should be with configuration. There must be an error in your configuration, you LDAP server URL is not taken into account.

**Comment by DSantonastaso** [comment]
This is my configuration

$debug = true;

# LDAP
$ldap_url = "ldap://192.168.0.1";
$ldap_starttls = false;
$ldap_binddn = "CN=userbind,CN=Users,DC=DSP,DC=it";
$ldap_bindpw = '**********';
$ldap_base = "dc=DSP,dc=it";
$ldap_login_attribute = "sAMAccountName";
$ldap_fullname_attribute = "cn";
$ldap_filter = "(&(objectClass=person)($ldap_login_attribute={login}))";
$ldap_use_exop_passwd = false;
$ldap_use_ppolicy_control = false;
$keyphrase = "********";
$show_extended_error = true;
$smarty_debug = true;

Using adexplorer
