### ISSUE TITLE
Encryption without authentication

### ISSUE THREAD

**Issue by jvoisin** [ltb-project/self-service-password#60]
Encryption and decryption [is implemented]( https://github.com/ltb-project/self-service-password/blob/master/lib/functions.inc.php#L407 ) without any kind of authentication, allowing attackers to perform a large panel of attacks to compromise the confidentiality of the material.

Please either use [authenticated modes]( https://en.wikipedia.org/wiki/OCB_mode ), or some kind of [integrity measure]( https://en.wikipedia.org/wiki/Authenticated_encryption )

**Comment by coudot** [comment]
Could you give an example on how an attacker can compromise the software?

Could you send some patches?

**Comment by jvoisin** [comment]
An attacker can flip bit in the encrypted text, and since you're using [ofb]( https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#Output_Feedback_.28OFB.29 ) mode, this will result in a flipped bit in the clear text, leading to all kind of fun things.

I fail to understand why you want to actually encrypt such tokens in the first place, so I can't elaborate an attack scenario, but you should either provide secure encryption, or not use it at all, not something in between.

A lot of projects have been [vulnerable]( https://security.stackexchange.com/questions/2202/lessons-learned-and-misconceptions-regarding-encryption-and-cryptology/2206#2206 ) to this kind of attacks in the past.

**Comment by coudot** [comment]
Done by @plewin in PR #92
