### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by rharriscenteredge** [ltb-project/self-service-password#600]
Hello, all I am looking for some help here after configuring the program and using user and manager I keep getting this error. 

Password was refused by the LDAP directory (0000052D): AtrErr: DSID-03190FD6, #1:0:0000052D: DSID-03190FD6, problem 1005 (constraint_Att_TYPE), data 0, att 9005a (unicodePwd)

**Comment by coudot** [comment]
The password submitted to AD should not respect password policy constraints

**Comment by rharriscenteredge** [comment]
The password I am trying to use passes the password constraints. But I have disabled the complexity requirements and set the min password age to 0 and still get the above error.

**Comment by rharriscenteredge** [comment]
The test user we used had admincount set to 1. We deleted the user and created a new test user and now everything is working. Thanks for your help.
