### ISSUE TITLE
Undefined index: smstoken in /www/ltb-ssp/htdocs/resetbytoken.php

### ISSUE THREAD

**Issue by bsiara** [ltb-project/self-service-password#601]
I get this error i app log
`2021/11/05 11:30:04 [error] 27#27: *20 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: smstoken in /www/ltb-ssp/htdocs/resetbytoken.php on line 62" while reading response header from upstream, client: 192.168.168.168, server: , request: "GET /index.php?action=resetbytoken&token=3vUCADtsj8Rq7IZnM8wffwdLuu%2BolxK144HJOe0fwuL6p1UVADmYOGZSG39AoQcgZa3zO%2F0rn9ssdJpBshEqSHNkkva3y%2FNuQF6Kj3qjHzA%2BXXxOs8xeNrr8OU47fTfSQpX7zyhAmySEN7HeRL4%3D HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000"`

**Comment by coudot** [comment]
This is a notice message and should not have any impact on the application.
