### ISSUE TITLE
Smarty template cache write error

### ISSUE THREAD

**Issue by Eiskasten** [ltb-project/self-service-password#604]
Using the provided nginx configuration with fastcgi, I receive the following errors in nginx when accessing the root page which returns 500 and remains emtpy:

```
2021/11/11 18:17:47 [error] 117621#117621: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught  --> Smarty: unable to write file /usr/share/webapps/self-service-password/templates_c/wrt618d503b7c3ed4_16215797 <--
  thrown in /usr/share/php/smarty3/sysplugins/smarty_internal_runtime_writefile.php on line 60" while reading response header from upstream, client: 128.130.241.4, server: selfservice.***.***, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/self-service/self-service.sock:", host: "selfservice.***.***"
```

The file permissions are correct, even when I `777` it, this error remains.

To be clear, I am not comfortable enough with neither nginx nor php-fpm to determine exactly where the error is, but I suspect it to be more a configuration issue, because smarty wants to write outside of the `root` directive of nginx? Maybe I need to set a `fastcgi_param` directive in nginx for that?

Furthermore, wouldn't it be a better idea to generate the smarty template renders into a temporary directory such as `/tmp`?

The versions of my stack are:
* self-service-password: 1.4.3
* 1.20.1
* php-fpm: 8.0.12

I hope, I provided sufficient information, if not feel free to ask.
Thank you in advance.

**Comment by coudot** [comment]
Do you have SELinux enabled?

**Comment by Eiskasten** [comment]
No, it is not even installed on my system. I am on Arch if that helps.

**Comment by coudot** [comment]
You can configure Smarty cache directories:
```php
# Cache directory
#$smarty_compile_dir = "/var/cache/self-service-password/templates_c";
#$smarty_cache_dir = "/var/cache/self-service-password/cache";
```

**Comment by Eiskasten** [comment]
Thank you, overriding these to the php configured temporary directories works. So it was indeed a configuration error, wouldn't it be a good idea to at least mention that in the nginx configuration documentation? Or even better, provide the necessary configuration options to allow writing outside of root?

Nevertheless, I will adjust the default configuration in the Arch package to use the temporary directories.
