### ISSUE TITLE
Display value associative table with line break HTML element <br>

### ISSUE THREAD

**Issue by pcensfea** [ltb-project/self-service-password#605]
**- Description of the problem encountered:**

In Self-Service-Password 1.3 (PHP 5.5.14) / config.inc.php :
$messages['changehelpextramessage'] = "abcd <br> 1234";
display, as expected, in browser :
    abcd
    1234
...but display :
    abcd <br> 1234
for Self-Service-Password 1.4.3 (PHP 7.4.6)

What's wrong ?
(Tested in Chromium and Firefox. Linux OS.)

scripttest.php :
<?php
$messages = [
        'changehelpextramessage' => "abcd <br> 1234",
        'passwordchangedextramessage' => ""
        ];
echo $messages ['changehelpextramessage'];
?>
.../self-service-password-1.4.3/htdocs/scripttest.php works properly and display in browser :
    abcd
    1234

**- Operational solution proposed by the team:**

the Smarty framework is configured to escape HTML, see https://github.com/ltb-project/self-service-password/blob/master/htdocs/index.php#L193

That's why you face this behavior change.

Could you try this patch?

diff --git a/templates/change.tpl b/templates/change.tpl
index 9c9f8a8..3a9a8cb 100644
--- a/templates/change.tpl
+++ b/templates/change.tpl
@@ -13,7 +13,7 @@
         <div class="result alert alert-warning">
         <p><i class="fa fa-fw fa-exclamation-circle" aria-hidden="true"></i> {$msg_changehelp}</p>
         {if $msg_changehelpextramessage}
(Delete)          <p>{$msg_changehelpextramessage}</p>
(Add)             <p>{$msg_changehelpextramessage|unescape: "html" nofilter}</p>
         {/if}
         {if !$show_menu and ($use_question or $use_tokens or $use_sms or $change_sshkey) }
             <p>{$msg_changehelpextramessage}</p>

**=> To be included in the next version**

**Comment by coudot** [comment]
Thanks for the report, fixed in master
