### ISSUE TITLE
Problem with the mail service in Docker

### ISSUE THREAD

**Issue by gcpmendez** [ltb-project/self-service-password#607]
Actually I'm receiving the next error:
**"The email address does not match the submitted user name"**

With mail field
````bash
$ cat /var/log/apache2/ssp_error.log
[Wed Nov 17 14:11:11.709273 2021] [php7:notice] [pid 19] [client 10.5.22.49:42566] Mail gpaz@iter.es does not match for user gpaz, referer: http://10.254.0.8/?action=sendtoken
````

Without mail field
````bash
$ cat /var/log/apache2/ssp_error.log
[Thu Nov 18 13:03:38.358379 2021] [php7:notice] [pid 21] [client 10.5.22.49:59086] Mail not found for user gpaz, referer: http://10.254.0.8/index.php?action=sendtoken
````

````bash
dn: uid=gpaz,ou=Users,dc=hpc,dc=iter,dc=es
objectClass: top
objectClass: posixAccount
objectClass: inetOrgPerson
uid: gpaz
cn: gpaz
sn: gpaz
loginShell: /bin/bash
uidNumber: 1137
gidNumber: 1137
gecos: gpaz
homeDirectory: /home/gpaz
mail: gpaz@iter.es
````

This is my configuration:
![image](https://user-images.githubusercontent.com/10725162/142420604-894a1954-cafa-4e1c-ac1e-222f78767769.png)

I got change the password from the main method but this mail method doesn't work

Any solution?

**Comment by coudot** [comment]
Which account is used by SSP to request LDAP directory? Maybe an ACL is preventing this account to read the mail attribute?

**Comment by gcpmendez** [comment]
We don't have ACL configured

**Comment by gcpmendez** [comment]
`root@e9afb06efb04:/var/www/html# cat /var/log/apache2/ssp_error.log 
[Mon Nov 22 09:36:12.799198 2021] [php7:notice] [pid 19] [client 10.5.22.49:38492] PHP Notice:  Undefined variable: mail_attributes in /var/www/html/sendtoken.php on line 121, referer: http://10.254.0.8/index.php?action=sendtoken
[Mon Nov 22 09:36:12.799298 2021] [php7:warn] [pid 19] [client 10.5.22.49:38492] PHP Warning:  sizeof(): Parameter must be an array or an object that implements Countable in /var/www/html/sendtoken.php on line 121, referer: http://10.254.0.8/index.php?action=sendtoken
[Mon Nov 22 09:36:12.799321 2021] [php7:notice] [pid 19] [client 10.5.22.49:38492] Mail not found for user gpaz, referer: http://10.254.0.8/index.php?action=sendtoken
`

**Comment by coudot** [comment]
There is a change in master, `$mail_attribute` is no more valid, use `$mail_attributes` array instead, see https://github.com/ltb-project/self-service-password/issues/494
