### ISSUE TITLE
objectClass: ldapPublicKey should be added when needed

### ISSUE THREAD

**Issue by roumano** [ltb-project/self-service-password#608]
Hi,

To add a ssh-key, the object class `ldapPublicKey` should added on the account,  
Otherwise the SelfServicePassword will get a `error 65` when trying to add the attribut ssh PublicKey on the Ldap directory.

Can you add a test if the object class is exist and if not add it before adding the ssh key ? 

Error without the objecClass : 
```
#!ERROR [LDAP: error code 65 - attribute 'sshPublicKey' not allowed]
dn: uid=dsmith,ou=People,dc=embl,dc=fr
changetype: modify
add: sshPublicKey
sshPublicKey:: ZGZzIGRmcyBkZxxxxxxx
```

Should be change to something like this :  
```
dn: uid=dsmith,ou=People,dc=embl,dc=fr
changetype: modify
add: sshPublicKey
sshPublicKey:: ZGZzIGRmcyBkZxxxxxxx
-
add: objectClass
objectClass: ldapPublicKey
-
```

Error on the apache log : 
```
PHP Warning:  ldap_mod_replace(): Modify: Object class violation in /var/www/password/lib/functions.inc.php on line 531, referer: https://XXXX/index.php?action=changesshkey
LDAP - Modify sshPublicKey error 65 (Object class violation), referer: https://XXXX/index.php?action=changesshkey
```

**Comment by doc-slice** [comment]
I also need this extension and have programmed it out. How can I make this available?

**Comment by coudot** [comment]
Saw your contribution, I made some comments in it
