### ISSUE TITLE
security: service discloses existence of user accounts

### ISSUE THREAD

**Issue by scrwr** [ltb-project/self-service-password#610]
Nessus security scanner alerted with HIGH severity (7.5) 

Reason: self-service-password discloses existence of user accounts due to alert messages in case of non-existing user accounts.

Recommendation: hidden failure and generic responses like "Email sent if account exists".

**Comment by artlog** [comment]
This look like to have been implemented in https://github.com/ltb-project/self-service-password/issues/196 but not activated by default.

./conf/config.inc.php:#$obscure_failure_messages = array("mailnomatch");

this is commented by default.

**Comment by coudot** [comment]
Indeed, it is already available!

Documentation: https://self-service-password.readthedocs.io/en/stable/config_general.html#security
