### ISSUE TITLE
docker: image build fails and/or ldap config missing

### ISSUE THREAD

**Issue by phoenix0984** [ltb-project/self-service-password#611]
Hi,
I'm having a hard time building the image with the default DOCKERFILE. 
It errors out when trying to install apache2 from the buster backports repo:
`E: Packages were downgraded and -y was used without --allow-downgrades.`

The strange thing is, when allowing downgrades, the final image is lacking the /etc/ldap directory altogether.
Consequently all binds to AD via ldaps fail with "Cannot access LDAP directory":
`[Sat Dec 18 10:37:06.422253 2021] [php7:warn] [pid 19] [client 10.0.1.3:60684] PHP Warning:  ldap_bind(): Unable to bind to server: Can't contact LDAP server in /var/www/html/sendtoken.php on line 89`

Please let me know, if more details are needed. Any help is highly appreciated.

**Comment by faust64** [comment]
https://hub.docker.com/_/php?tab=tags&page=1&name=7.4
Turns out the 7.4 tag is now an alias for some 7.4-bullseye.
Dockerfile currently installs apache2 from buster backports.

**Comment by phoenix0984** [comment]
Hi,

yes, that's fixing the build but ldap.conf is still missing. Don't know, if this is related, but if I pull the official image, I can connect to the domain controller just fine. Also /etc/ldap directory is there. So some dependencies seems to be missing, when building the image.

**Comment by faust64** [comment]
Allright ... then we should be able to install libldap-common? -- PR updated, can you try to install that package as well?
The official image was probably built before PHP images switching their 7.4 from debian buster to bullseye. We can see it's 6 months old. Bullseye is stable since last august.

**Comment by phoenix0984** [comment]
Yes, installing libldap-common fixed the issue. Thanks for your help @faust64
