### ISSUE TITLE
Docker image missing 1.5.0 tag

### ISSUE THREAD

**Issue by thisgarryhas2rs** [ltb-project/self-service-password#616]
The "latest" docker image tag (d9dd42812bca) should also have a 1.5.0 tag

```
docker pull ltbproject/self-service-password:latest
docker tag ltbproject/self-service-password:latest ltbproject/self-service-password:1.5.0
docker push ltbproject/self-service-password:1.5.0
```

**Comment by coudot** [comment]
1.5.0 is not released yet

**Comment by thisgarryhas2rs** [comment]
Thanks for the update @coudot . Using the latest docker image with tag latest (digest d9dd42812bca) shows v1.5 in the WebUI. 

![image](https://user-images.githubusercontent.com/3791758/147953793-aaf52244-923f-48b0-ac2c-25f70a258cbb.png)

**Comment by coudot** [comment]
Yes it is because the image comes from the master branch, which is work in progress

The latest stable is 1.4.3, see https://hub.docker.com/layers/ltbproject/self-service-password/1.4.3/images/sha256-8dc6fa118b91064d70c1a11ed37aed710f20c772db5fd6f861f692da23129a90?context=explore
