### ISSUE TITLE
Repo: Where are the packages hosted now?

### ISSUE THREAD

**Issue by lrosenman** [ltb-project/self-service-password#617]
The instructions for picking up the DEB/RHEL packages now point to invalid locations for the keys. 

Did that go away?

**Comment by coudot** [comment]
We have moved the server tonigth but all files should be here, which url is not working ?

**Comment by lrosenman** [comment]
The URL for the Repo Key. 

key 'https://ltb-project.org/wiki/lib/RPM-GPG-KEY-LTB-project'

**Comment by coudot** [comment]
Documentation has been updated, key.is now at https://ltb-project.org/documentation/_static/RPM-GPG-KEY-LTB-project

We will create an alias

**Comment by coudot** [comment]
Alias done and documentation updated
