### ISSUE TITLE
Allowing users to change PW via questions with openLDAP

### ISSUE THREAD

**Issue by dev-loki** [ltb-project/self-service-password#623]
Hey and thank your for readin.

I'm kind of completely new to LDAP and have the problem, that it seems, that my users don't have the permission to set their own questions/answers.

How can I give users the ability to change their answers?

I know this might be completely basic, but I really appreciate some help or a pointer in the right direction :).

**Comment by coudot** [comment]
This depends on which LDAP server you are using.

With OpenLDAP, you need to configure `olcAccess` to allow users to write on the attribute storing the answer. See https://www.openldap.org/doc/admin25/access-control.html
