### ISSUE TITLE
Missing Documentation

### ISSUE THREAD

**Issue by kylegordon** [ltb-project/self-service-password#635]
Hi,

The link within the phrase "See this documentation to manage Active Directory certificates." at https://self-service-password.readthedocs.io/en/v1.4/config_ldap.html leads to a 404 at https://self-service-password.readthedocs.io/documentation/general/active_directory_certificates

I used the search box and could not find any documentation relating to Active Directory certificates.

**Comment by coudot** [comment]
Indeed the new link is https://ltb-project.org/documentation/active_directory_certificates.html

I will fix current doc
