### ISSUE TITLE
Where to customize reset email format and content

### ISSUE THREAD

**Issue by WWY507** [ltb-project/self-service-password#636]
i test self-service-password recently, it 's very functional。
 I can't find a custom mail reset page，anyone help me,thanks !!!

**Where to customize reset email format and content**
<img width="635" alt="WhereDefineResetMailFormat" src="https://user-images.githubusercontent.com/38350934/152911043-a8558a11-015d-4b54-b8f7-0f87c6947642.png">

**Comment by WWY507** [comment]
i wanna use ldap attr **displayName** to replace wwy

**Comment by coudot** [comment]
Hello,

the text of the mail (subject and body) is in lang/ files and can be overriden in configuration or in custom mang files installed in conf/.

But the data available to replace variables in mail are only login, mail and url (see https://github.com/ltb-project/self-service-password/blob/master/htdocs/sendtoken.php#L222).

**Comment by WWY507** [comment]
conf/config.inc.php i found
 $ldap_fullname_attribute = "cn";  

could i change it to
$ldap_fullname_attribute = "displayName";

**Comment by coudot** [comment]
Seems you did not read my previous answer. `$ldap_fullname_attribute` is not used in email template.
