### ISSUE TITLE
Getting internal server error

### ISSUE THREAD

**Issue by dnyamy** [ltb-project/self-service-password#637]
<img width="1436" alt="Sans titre 2" src="https://user-images.githubusercontent.com/43039376/153734788-43d37b0d-9f88-49af-be35-cc9048510229.png">
Hello,

I have installed the tool, following instructions here https://self-service-password.readthedocs.io/en/latest/installation.html
(The Debian/Ubuntu part).

Install complete well, and I have set up apache's conf file. 

But when trying to acces, I get an Internal Server Error. There is no error in apache's logs.
Please how can I find the issue ?

Really desperate. 

Regards

Dn

**Comment by coudot** [comment]
There should be a dependency missing. Try to set `$debug` to `true`.

**Comment by coudot** [comment]
You need to allow the system user running the web server to write smarty cache directories (templates_c and cache).

**Comment by dnyamy** [comment]
That was the issue !
Working fine now
Thanks a lot @coudot for your help
Regards
Dn
