### ISSUE TITLE
Plain text "userPassword" attribute added instead of password being updated. 

### ISSUE THREAD

**Issue by AddChickpeas** [ltb-project/self-service-password#639]
Hello, 

I'm running into an issue where, instead of updating the password itself, a plain text userPassword field is added to the user in AD. 

I literally entered "plain-text-password" as the new password in the ssp GUI and you can see it when viewing the record with ASDI edit. 

![image](https://user-images.githubusercontent.com/32724595/155375964-a67b2bb8-b8bb-4e55-a5ed-799e92e854fd.png)

I swear it has worked and updated the password on a handful of tests, but most of the time it seems to just be doing this. 

Here are the AD settings. I've changed very little besides the login attribute. Password is being reset by the "manager". 
```
# Debug mode
# true: log and display any errors or warnings (use this in configuration/testing)
# false: log only errors and do not display them (use this in production)
$debug = true;

#LDAP
$ldap_url = "ldap://10.x.x.x";
$ldap_starttls = false;
$ldap_binddn = "CN=svc-passwordreset,OU=Service Accounts,OU=Org,DC=example,DC=com";
$ldap_bindpw = "password";
// for GSSAPI authentication, comment out ldap_bind* and uncomment ldap_krb5ccname lines
//$ldap_krb5ccname = "/path/to/krb5cc";
$ldap_base = "dc=example,dc=com";
$ldap_login_attribute = "SAMAccountName";
$ldap_fullname_attribute = "cn";
$ldap_filter = "(&(objectClass=person)($ldap_login_attribute={login}))";
$ldap_use_exop_passwd = false;
$ldap_use_ppolicy_control = false;

# Active Directory mode
# true: use unicodePwd as password field
# false: LDAPv3 standard behavior
$ad_mode = false;
$ad_options=[];
# Force account unlock when password is changed
$ad_options['force_unlock'] = false;
# Force user change password at next login
$ad_options['force_pwd_change'] = false;
# Allow user with expired password to change password
$ad_options['change_expired_password'] = true;
```

**Comment by coudot** [comment]
You forgot to configure AD mode.

https://self-service-password.readthedocs.io/en/v1.4/config_ldap.html#active-directory

**Comment by AddChickpeas** [comment]
Yep, we've got it configured now. Blocker turned out to be some configuration stuff on our end that was preventing that option from working. 

Thanks!
