### ISSUE TITLE
[AD] Reset by mail send url to mananger mail address

### ISSUE THREAD

**Issue by pierre-guillot** [ltb-project/self-service-password#640]
Hi LTB team.

It's just an idea, but in ou hospital, many many people have an Active Directy account whithout email address.

So, if they forgets password, they need to contact IT support for reset the password.

Maybe you can add a system where, if people haven't email but have a manager (https://dovestones.com/setting-manager-attribute/) configured, email whit reset URL is send to manager mailbox (because every mananger has mailbox).

What did you think?

Regards

**Comment by coudot** [comment]
Seems not a good idea from a security point of view. Manager should not be able to reset password from another user.
