### ISSUE TITLE
Can not to connect by LDAPS

### ISSUE THREAD

**Issue by legolego621** [ltb-project/self-service-password#641]
Hello.
I have problem with connect by LDAPS to my openldap server.
I am using docker image.

My config:

$keyphrase = "123456";
$ldap_url = "ldaps://ldap.server.local:636";
$ldap_starttls = false;
$who_change_password = "user";
$ldap_binddn = "cn=ssp_connector,ou=services,dc=mydomain,dc=local";
$ldap_bindpw = "Passw0rd";
$ldap_base = "ou=users,ou=people,dc=mydomain,dc=local";
//$hash = "SSHA";
$ad_mode = false;
$ldap_login_attribute = "cn";
$ldap_filter = "(&(objectClass=inetOrgPerson)($ldap_login_attribute={login}))";

I have warning is "Cannot access LDAP directory" and log of docker container " PHP Warning:  ldap_bind(): Unable to bind to server: Can't contact LDAP server in /var/www/html/change.php on line 91, referer: http://10.10.10.10/index.php".

My configuration of LDAP server is correct. I enabled LDAPS and configure certificate.

Please, help my with thi

**Comment by coudot** [comment]
> My configuration of LDAP server is correct. I enabled LDAPS and configure certificate.

If all was correct, you would not have any error. There should be an issue with the certificate trust chain.

**Comment by legolego621** [comment]
> > My configuration of LDAP server is correct. I enabled LDAPS and configure certificate.
> 
> If all was correct, you would not have any error. There should be an issue with the certificate trust chain.

Is the issue related to certificate trust?
Is it possible to specify the public key of the certificate somewhere in the settings?

**Comment by coudot** [comment]
See documentation: https://self-service-password.readthedocs.io/en/v1.4/config_ldap.html#server-address

**Comment by legolego621** [comment]
> See documentation: https://self-service-password.readthedocs.io/en/v1.4/config_ldap.html#server-address
Thanks for the answer :)
Is this setting for the server?
I successfully configured TLS_CACERT on the server. I use TLS in many other applications.

**Comment by coudot** [comment]
This setting is for the server hosting SSP application. Check with openssl s_client your connection and CA certificate

**Comment by legolego621** [comment]
> This setting is for the server hosting SSP application. Check with openssl s_client your connection and CA certificate

I have this answer

```
root@sr-test:/test#  openssl s_client -connect ldap.server.local:636
CONNECTED(00000003)
depth=0 C = AU, ST = Some-State, O = ldap.server.local, CN = ldap.server.local
verify error:num=18:self signed certificate
verify return:1
depth=0 C = AU, ST = Some-State, O = ldap.server.local, CN =ldap.server.local
verify return:1
---
Certificate chain
 0 s:C = AU, ST = Some-State, O = ldap.server.local, CN = ldap.server.local
   i:C = AU, ST = Some-State, O = ldap.server.local, CN = ldap.server.local
---
Server certificate
-----BEGIN CERTIFICATE-----
.....................................................
-----END CERTIFICATE-----
subject=C = AU, ST = Some-State, O = ldap.server.local, CN = ldap.server.local

issuer=C = AU, ST = Some-State, O = ldap.server.local, CN = ldap.server.local

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 1467 bytes and written 389 bytes
Verification error: self signed certificate
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 18 (self signed certificate)
---


```

**Comment by coudot** [comment]
So copy the server certificate on SSP server and configure it as CACERT in your ldap.conf

**Comment by legolego621** [comment]
> So copy the server certificate on SSP server and configure it as CACERT in your ldap.conf

I am sorry. 
Do I understand correctly what you mean about adding TLS_CACERT on the LDAP server?
If so, then my certificate has already been added to the LDAP server configuration (/etc/ssl/ldapserver.crt).

```
root@dc1:/home/rootvang# cat /etc/ldap/ldap.conf
#
# LDAP Defaults
#
# Any configs........

TLS_CACERT      /etc/ssl/ldapserver.crt

```

**Comment by coudot** [comment]
Yes.

Check that the security level of your linux distribution is compatible with the AD certificate

**Comment by adrian-agp** [comment]
what do i have to inst
Hello, I have a question in centos 7 if I had the configuration file.

What do I have to install to find this /etc/ldap/ldap.conf file on debian 11?all to find this /etc/ldap/ldap.conf file on debian 11

**Comment by faust64** [comment]
In debian 11, /etc/ldap/ldap.conf is part of the libldap-common package.

**Comment by adrian-agp** [comment]
> In debian 11, /etc/ldap/ldap.conf is part of the libldap-common package.

Thanks friend always and I worked centos and now I'm dealing with debian.
