### ISSUE TITLE
Can't resolve ldap_search error .../change.php on line 105

### ISSUE THREAD

**Issue by 20GTson** [ltb-project/self-service-password#645]
I've been working on this for a few days and am stuck. Any help is appreciated. Running version 1.4.3 and using Apache on Ubuntu 20.04.

My config is straight forward. Want to set this up for an internal Active Directory to be used exclusively for password change capability (when current pwd is known), by using the user's own password for the auth (avoid service account with pwd in clear text within the conf file). I don't seem to have any issues with certs. Regarless of ldap or ldaps config, I continue to get PHP Warning:  ldap_search(): Search: Operations error in /usr/share/self-service-password/htdocs/change.php on line 105

Has anyone seen/solved this?

**Comment by 20GTson** [comment]
I should add that with this error, the gui result is perpetually:  Cannot access LDAP directory

**Comment by 20GTson** [comment]
Using the following values...

$ldap_url = "ldaps://mydc.acme.local";
$ldap_starttls = false;
$ldap_base = "OU=Users,OU=Special,OU=Accounts,DC=acme,DC=local";
$ldap_filter = "(&(objectClass=user)(sAMAccountName={login})(!(userAccountControl:1.2.840.113556.1.4.803:=2)))";

**Comment by coudot** [comment]
Set debug to true and check logs

Most of the time, the issue comes from a bad configuration of SSL options

**Comment by 20GTson** [comment]
I have debug = true and I don't see any new clues in the log. Same ldap error reported related to line 105 of the change.php file. The log entry that follows includes "LDAP - Search error 1  (Operations error)". That's about it.

**Comment by 20GTson** [comment]
I'm going to have to abandon this solution for our use case and find something else. Best of luck all. Cheers.
