### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: ldap_get_dn()

### ISSUE THREAD

**Issue by JesusHerreraUS** [ltb-project/self-service-password#648]
When I try to reset the password, if I enter a user that doesn't exist in my ldap directory, I get a 500 error on the web. The error in logs is: 
**PHP Fatal error:  Uncaught TypeError: ldap_get_dn(): Argument #2 ($entry) must be of type resource, bool given in /usr/share/self-service-password/htdocs/change.php:115\**

There seems to be no error handling.

Any idea? 
Thanks a lot

**Comment by coudot** [comment]
Could you share your configuration and some logs in debug mode?

**Comment by coudot** [comment]
I can't reproduce with latest version of SSP.

Could you share the logs?

**Comment by GeJ** [comment]
We have encountered the same error on our setup.

After some debugging, it seems that using a bogus user id doesn't trigger an error in [htdocs/change.php](https://github.com/ltb-project/self-service-password/blob/68a5f241fe3409fb3445304804a8cacda3ccf9df/htdocs/change.php#L112).

Then the `$entry` value is set to `false` when calling `ldap_first_entry()` and `ldap_get_dn()` will croak.

I slightly modified the code  with : 
```php
113     # Get user DN
114     $entry = ldap_first_entry($ldap, $search);
115     if ( !$entry ) {
116         $result = "ldaperror";
117         error_log("LDAP - Search error $errno  (".ldap_error($ldap).")");
118         $userdn = false;
119     }
120     else {
121         $userdn = ldap_get_dn($ldap, $entry);
122     }
```

and my server logs returned the following : 

```
2022/06/22 12:05:02 [error] 768#100096: *1593 FastCGI sent in stderr: "PHP message: LDAP - Search error 0  (Success)PHP message: LDAP - User jhdljkbsxm not found"
```

PHP version : 8.0.18
System : FreeBSD 13.1
Nginx : 1.20.2
OpenLDAP : 2.4.59

**Comment by coudot** [comment]
Thanks for the update. For information on my side it is not a fatal error but a warning:
```
[Wed Jun 22 17:41:11.292745 2022] [php7:warn] [pid 1320] [client 127.0.0.1:60752] PHP Warning:  ldap_get_dn() expects parameter 2 to be resource, bool given in /usr/local/ssp/htdocs/change.php on line 115, referer: http://ssp.example.com/
[Wed Jun 22 17:41:11.292782 2022] [php7:notice] [pid 1320] [client 127.0.0.1:60752] LDAP - User test not found, referer: http://ssp.example.com/
```

We indeed need to test the entry before getting the DN, I will push a patch

**Comment by cmuller** [comment]
I have no idea if this is related but when I ugraded from 1.4.3 to 1.4.4 => we couldn't change passwords in AD (with starttls in config) and that was working well before.
I could see in the logs:
~~~
[...]: PHP Warning:  ldap_get_dn() expects parameter 2 to be resource, array given in /usr/share/self-service-password/htdocs/change.php on line
 140
[...]: PHP Warning:  ldap_mod_replace(): Modify: Server is unwilling to perform in /usr/share/self-service-password/lib/functions.inc.php on lin
e 499
[...]: LDAP - Modify password error 53 (Server is unwilling to perform)
~~~

So I rollback to the 1.4.3 version and everything worked ok again! I checked the diffs but apart from bootstrap and `smarty_debug` the only changes I could see are the ones mentioned above in `change.php`.. (?)

**Comment by coudot** [comment]
Indeed, there is a big bug in 1.4.4, patch is coming

**Comment by cmuller** [comment]
It's working perfectly now! thanks :+1:
