### ISSUE TITLE
Can't register answers for reset by question

### ISSUE THREAD

**Issue by Carminuch** [ltb-project/self-service-password#651]
Hello,

I've been trying to complete my Self Service Password project. I have configured reset by email, however reset by question is failing me. I've tried to change $who_change_password from both manager, and user. I've followed the instructions on the self service password website to a tee. No matter what I've tried, it fails to register an answer when I want to register one.

Can anyone help me?

Thanks so much.

**Comment by Carminuch** [comment]
These are the full logs. Do you notice anything I haven't been able to find? @coudot 

![image](https://user-images.githubusercontent.com/105734327/168852975-76cd913b-0b92-4aa6-9d3f-a8fbb13a6ab4.png)
![image](https://user-images.githubusercontent.com/105734327/168853041-f97df7b0-5328-4571-bd39-1d3302f2aa92.png)
![image](https://user-images.githubusercontent.com/105734327/168853081-e6b07b22-eeeb-4d7c-a328-6be7bf6789a2.png)
![image](https://user-images.githubusercontent.com/105734327/168853128-9105935a-4040-48eb-b006-0467f801fff5.png)
![image](https://user-images.githubusercontent.com/105734327/168853186-cfa692d5-f5d1-4b9b-bfb6-909be8f6cb87.png)
![image](https://user-images.githubusercontent.com/105734327/168853237-def41ef5-7a11-43d9-8e79-ec6d2dc3911c.png)
![image](https://user-images.githubusercontent.com/105734327/168853268-1e05a1df-e7c7-445b-994e-d8779288825f.png)

**Comment by coudot** [comment]
The important logs are on server side

**Comment by Carminuch** [comment]
I'm relatively new to this. What is the best way to view the server side logs? @coudot

**Comment by Carminuch** [comment]
![thumb-Clipboard - May 17, 2022 1_53 PM](https://user-images.githubusercontent.com/105734327/168879059-481d91e2-925a-4784-b8d2-e1a32a61378a.png)
@coudot 
Here are the logs

**Comment by Carminuch** [comment]
![logs](https://user-images.githubusercontent.com/105734327/168880022-74cc50f8-d351-4080-a214-b03e30dea9a6.png)
might be better viewed here

**Comment by coudot** [comment]
Sadly we can' t read anything.

Logs are text, just paste the text in the issue.

**Comment by Carminuch** [comment]
[Fri May 20 14:02:23.808562 2022] [php7:notice] [pid 22119] [client 10.10.1.64:56140] PHP Notice:  Undefined index: msg_changehelpextramessage in /var/cache/self-service-password/templates_c/f6b50b13b91599a6d59a20cb1147ad5af3c8d817_2.file.change.tpl.php on line 43
[Fri May 20 14:02:23.808703 2022] [php7:notice] [pid 22119] [client 10.10.1.64:56140] PHP Notice:  Trying to get property 'value' of non-object in /var/cache/self-service-password/templates_c/f6b50b13b91599a6d59a20cb1147ad5af3c8d817_2.file.change.tpl.php on line 43
[Fri May 20 14:02:41.413071 2022] [php7:warn] [pid 22116] [client 10.10.1.64:56148] PHP Warning:  ldap_get_values(): Cannot get the value(s) of attribute Decoding error in /usr/share/self-service-password/htdocs/setquestions.php on line 174, referer: https://192.168.10.121/?action=setquestions
[Fri May 20 14:02:42.061448 2022] [php7:warn] [pid 22116] [client 10.10.1.64:56148] PHP Warning:  ldap_mod_replace(): Modify: Invalid syntax in /usr/share/self-service-password/htdocs/setquestions.php on line 216, referer: https://192.168.10.121/?action=setquestions
[Fri May 20 14:02:42.061498 2022] [php7:notice] [pid 22116] [client 10.10.1.64:56148] LDAP - Modify answer (error 21 (Invalid syntax), referer: https://192.168.10.121/?action=setquestions

Here is the complete log.

**Comment by coudot** [comment]
It seems you have multiple problems:
* Check the Bind DN / Bind Password
* Check the question/answer configuration, the attribute/objectclass must fit your LDAP schema

**Comment by Carminuch** [comment]
The bind DN/ Bind Password should be correct.

I changed my objectclass, not sure what to change the attribute to? @coudot

**Comment by coudot** [comment]
If you really read the doc, you'll see : 
> On Active Directory, extensibleObject is not known. You can use for example...

You are not on Active Directory, right?

**Comment by Carminuch** [comment]
No I am not sorry. I have tried user and comment as well though. I tried both and neither worked for me. @coudot

**Comment by coudot** [comment]
info / extensibleObject should work with OpenLDAP. If not, you have another issue.

As always, logs are your friend.

**Comment by Carminuch** [comment]
Logs seem to be the same as they were before @coudot so same errors
