### ISSUE TITLE
Prehook is not called before password change

### ISSUE THREAD

**Issue by demogorgonz** [ltb-project/self-service-password#652]
Scenario:
- Disable account on AD
- Set prehook with content:

```
#!/usr/bin/pwsh

$username = "CORP\Administrator"
$password = ConvertTo-SecureString "SOMEPASSWORDHERE" -AsPlainText -Force
$creds = New-Object System.Management.Automation.PSCredential -ArgumentList ($username, $password)
$acc = $args[0]
Invoke-Command -ComputerName corp.localdev -ScriptBlock {Enable-ADAccount -Identity $using:acc} -Credential $creds

```

What should happen is that prehook should enable AD user which would allow it to change password in request. Otherwise it fails while the account is disabled.

**Comment by demogorgonz** [comment]
@coudot sorry for a ping, correct me if i am wrong [docs](https://self-service-password.readthedocs.io/en/latest/config_preposthook.html) clearly says:


>You can write a script that will be called before changing a password (pre hook) or after a successful password change (post hook).

**Comment by demogorgonz** [comment]
I have jammed :

```
    if ( isset($prehook) ) {
        $command = hook_command($prehook, $login, $newpassword, $oldpassword, $prehook_password_encodebase64);
        exec($command, $prehook_output, $prehook_return);
    }
```
bellow `Check captcha` in change.php  to achieve what i needed.

**Comment by coudot** [comment]
Which version are you using? Prehook feature was introduced in 1.4

**Comment by demogorgonz** [comment]
> Which version are you using? Prehook feature was introduced in 1.4

Latest. Actually it was running before change password, but after verify which caused prehook not to run as password can't be verified for disabled accounts :)

**Comment by coudot** [comment]
Indeed, the old password is checked before calling prehook.
