### ISSUE TITLE
PHP Notice:  Trying to access array offset on value of type resource

### ISSUE THREAD

**Issue by coudot** [ltb-project/self-service-password#682]
We can see this warnings in logs:
```
[Tue Jul 19 17:43:00.015952 2022] [php7:notice] [pid 281685] [client 127.0.0.1:51084] PHP Notice:  Trying to access array offset on value of type resource in /usr/local/ssp/lib/functions.inc.php on line 316, referer: http://ssp.example.com/index.php?action=resetbytoken&token=3vUCAFVlvrpHKewJhMzzOwaplkgNHr1NK2pktLFWSNof5Xn1KzZPgtjmtk5Aql9KF12cftSWZW2FLTXXrREzDLDLW6%2BXyWqBxNuz91Y4whodeOYtzERcCD7LjNJvO2hkLsKyjGOqm5Vo4swUkjg%3D
[Tue Jul 19 17:43:00.015980 2022] [php7:notice] [pid 281685] [client 127.0.0.1:51084] PHP Notice:  Trying to access array offset on value of type resource in /usr/local/ssp/lib/functions.inc.php on line 317, referer: http://ssp.example.com/index.php?action=resetbytoken&token=3vUCAFVlvrpHKewJhMzzOwaplkgNHr1NK2pktLFWSNof5Xn1KzZPgtjmtk5Aql9KF12cftSWZW2FLTXXrREzDLDLW6%2BXyWqBxNuz91Y4whodeOYtzERcCD7LjNJvO2hkLsKyjGOqm5Vo4swUkjg%3D
[Tue Jul 19 17:43:00.015990 2022] [php7:notice] [pid 281685] [client 127.0.0.1:51084] PHP Notice:  Trying to access array offset on value of type resource in /usr/local/ssp/lib/functions.inc.php on line 318, referer: http://ssp.example.com/index.php?action=resetbytoken&token=3vUCAFVlvrpHKewJhMzzOwaplkgNHr1NK2pktLFWSNof5Xn1KzZPgtjmtk5Aql9KF12cftSWZW2FLTXXrREzDLDLW6%2BXyWqBxNuz91Y4whodeOYtzERcCD7LjNJvO2hkLsKyjGOqm5Vo4swUkjg%3D
```
This notice appears with PHP 7.4

**Comment by artlog** [comment]
This comes for php 7.2 change that issue a notice or a warning, this does not change internal handling that was to return a null value. https://wiki.php.net/rfc/notice-for-non-valid-array-container

It indeed highlight that function check_password_strength( $password, $oldpassword, $pwd_policy_config, $login, $entry ) does not specify type of $entry. 

$entry is a resource as returned by ldap_first_entry  and an array if returned by ldap-get-entries or ldap_get_attributes.

resource can't be accessed by index so will return null.

**Comment by coudot** [comment]
Thanks for looking at it, it means the check are unavailable in some cases, we should fix this

**Comment by artlog** [comment]
working on

**Comment by artlog** [comment]
reset by token are actualy not checked for ldap attribute match

Checked with reset by mail : password configured to check ldap 'sn' does not check it, while it it is correctly refused with using change password.

and confirmed trace (PHP 7.4.30) :

`[Thu Jul 21 11:45:02.200601 2022] [php7:notice] [pid 21] [client 172.18.0.1:56870] PHP Notice:  Trying to access array offset on value of type resource in /var/www/lib/functions.inc.php on line 319, referer: http://0.0.0.0:6080/index.php?action=resetbytoken&token=....`

**Comment by coudot** [comment]
Thanks for the fix @artlog !
