### ISSUE TITLE
rest api checkpassword bugs

### ISSUE THREAD

**Issue by artlog** [ltb-project/self-service-password#687]
with rest api enabled and password complexity set in conf/config.inc.local.php

```
$use_restapi = true;
$pwd_complexity = 3;
```

( and rest api exposed into apache : Alias /rest /var/www/rest )

when checkpassword rest api check password to no be complex enough : 

```
curl -X POST -H 'Content-Type: application/x-www-form-urlencoded' -d 'newpassword=Aaaa' http://localhost:6080/rest/v1/checkpassword.php
{"error":0,"result":"notcomplex","message":"Your password does not have enough different classes of characters"}
```

it logs such error

`
[Mon Jul 25 08:49:41.661076 2022] [php7:notice] [pid 16] [client 172.20.0.1:39610] PHP Notice:  Trying to access array offset on value of type bool in /var/www/lib/functions.inc.php on line 319`

when checkpassword rest api check password to be fine

```
curl -X POST -H 'Content-Type: application/x-www-form-urlencoded' -d 'newpassword=Aaaa6' http://localhost:6080/rest/v1/checkpassword.php
{"error":0,"result":"","message":null}
```
message is null

and it logs such error

`[Mon Jul 25 08:49:48.044273 2022] [php7:notice] [pid 17] [client 172.20.0.1:39618] PHP Notice:  Trying to access array offset on value of type bool in /var/www/lib/functions.inc.php on line 319`

**Comment by artlog** [comment]
$entry variable in checkpassword.php should somehow be undefined but it is a global coming from lang. this variable should be $entry_array with empty array.
and if res is empty, message should be empty too, not null.

**Comment by coudot** [comment]
Seems ok but I opened a new issue so we can close this one: #695
