### ISSUE TITLE
ldap_get_dn() expects parameter 2

### ISSUE THREAD

**Issue by vboilloux** [ltb-project/self-service-password#698]
Hello,
In the sendsm form, when the identifier does not exist in the directory, an error is written in the log:

`AH01071: Got error 'PHP message: PHP Warning:  ldap_get_dn() expects parameter 2 to be res$urce, bool given in /srv/self-service-password-1.4.3/htdocs/sendsms.php on line 162
PHP message: LDAP - User grognon not foundPHP message: PHP Warning:  ldap_get_values() expects parameter 2 to be resource, bool given in /srv/self-service-password-1.4.3/htdocs/sendsms.php on line 170
PHP message: PHP Notice:  Trying to access array offset on value of type null in /srv/ssp-test/self-service-password-1.4.3/htdocs/sendsms.php on line 173
PHP message: No SMS number found for user grognon', `

Versions : Debian 11.4, PHP-FMP 7.4.30
self-service-password 1.4.3 or  1.4.5

**Comment by coudot** [comment]
Hello @vboilloux, thanks for the report.
This has been fixed here: https://github.com/ltb-project/self-service-password/pull/571
Will be available in 1.5, we are working hard on this new version, hope we can release it in few weeks.
