### ISSUE TITLE
Issue with AD "reset password on next logon"

### ISSUE THREAD

**Issue by Scifire** [ltb-project/self-service-password#700]
Hi,

we´re currently facing the issue that a user can´t change their password if the attribute "User have to change password at next logon" is set in AD. Without this attribute changing password works.

Our setup is:
- Docker Container
- AD_mode = true

What also confuses me is the log where it is written "invalid credentials" but i double checked both account (manager account and user account) for using the correct password. 

```
[23/Aug/2022:14:55:41 +0000] "-" 408 0 "-" "-"
[Tue Aug 23 14:56:39.130921 2022] [php7:warn] [pid 17] [client 10.10.4.228:17282] PHP Warning:  ldap_bind(): Unable to bind to server: Invalid credentials in /var/www/html/change.php on line 144, referer: http://docker-01/index.php
[Tue Aug 23 14:56:39.131155 2022] [php7:notice] [pid 17] [client 10.10.4.228:17282] LDAP - Bind user error 49  (Invalid credentials), referer: http://docker-01/index.php
[Tue Aug 23 14:56:39.131183 2022] [php7:notice] [pid 17] [client 10.10.4.228:17282] LDAP - Bind user extended_error 80090308: LdapErr: DSID-0C09044E, comment: AcceptSecurityContext error, data 773, v2580  (Invalid credentials), referer: http://docker-01/index.php
[Tue Aug 23 14:56:39.131194 2022] [php7:notice] [pid 17] [client 10.10.4.228:17282] LDAP - Bind user password needs to be changed, referer: http://docker-01/index.php
[Tue Aug 23 14:56:39.246643 2022] [php7:warn] [pid 17] [client 10.10.4.228:17282] PHP Warning:  ldap_modify_batch(): Batch Modify: Operations error in /var/www/lib/functions.inc.php on line 450, referer: http://docker-01/index.php
[Tue Aug 23 14:56:39.246929 2022] [php7:notice] [pid 17] [client 10.10.4.228:17282] LDAP - Modify password error 1 (Operations error), referer: http://docker-01/index.php
[Tue Aug 23 14:56:39.248464 2022] [php7:notice] [pid 17] [client 10.10.4.228:17282] PHP Notice:  Undefined index: msg_changehelpextramessage in /var/www/templates_c/3ba7131c51edfe0cef48341f1409d3c1a60d3c16_2.file.change.tpl.php on line 43, referer: http://docker-01/index.php
[Tue Aug 23 14:56:39.248552 2022] [php7:notice] [pid 17] [client 10.10.4.228:17282] PHP Notice:  Trying to get property 'value' of non-object in /var/www/templates_c/3ba7131c51edfe0cef48341f1409d3c1a60d3c16_2.file.change.tpl.php on line 43, referer: http://docker-01/index.php
```

No sure what setting could be missing for that case since as I understood this should work automatic https://github.com/ltb-project/self-service-password/issues/216#issuecomment-399009554

Anyone have a hint for me?

**Comment by coudot** [comment]
Could you try to apply this commit: https://github.com/ltb-project/self-service-password/commit/6a838ab2d9ef40f9f9bcda5a3cabcbf0747e95dd ?

**Comment by Scifire** [comment]
@coudot I applied only the changes in the `change.php` but with those it is working, password can be changed  also if "User have to change password at next logon" is checked.
After the change the attribute is unchecked (which I expected).

I noticed one thing: We have the policy in AD that the password can´t be one of the last three. When manager changes it it can be the any password also one of the last three. But I guess this is by design and can´t be solved right?

**Comment by coudot** [comment]
> @coudot I applied only the changes in the change.php but with those it is working, password can be changed also if "User have to change password at next logon" is checked.
After the change the attribute is unchecked (which I expected).

Thanks for the test.

> I noticed one thing: We have the policy in AD that the password can´t be one of the last three. When manager changes it it can be the any password also one of the last three. But I guess this is by design and can´t be solved right?

I think so, this is linked to AD and the privileges of your manager account. I don't know if this behavior can be configured.
