### ISSUE TITLE
Error 404 with bootstrap.min.css.map

### ISSUE THREAD

**Issue by vboilloux** [ltb-project/self-service-password#709]
Hello,

The file 'bootstrap.min.css' is missing in the folder 'htdocs/vendor/bootstrap/css/' which generates a 404 error. 
Downloading it from the Boostrap sources fixes the problem.

**Comment by coudot** [comment]
Hello @vboilloux 

how did you install the software?

**Comment by vboilloux** [comment]
Hello Clement,
From Source : https://ltb-project.org/archives/ltb-project-self-service-password-1.5.0.tar.gz

**Comment by coudot** [comment]
Strange, because the file is present in the archive. I don't see anything to fix on our side.

**Comment by vboilloux** [comment]
Sorry, I got the file name wrong: bootstrap.min.css.map

**Comment by coudot** [comment]
Ok, this file is not needed in production, it is just used with browser debugger. You should not have 404 error with the debugger off.

**Comment by vboilloux** [comment]
Correct, debug was $true.
If I pass debug to $false, the error still appears in the browser's developer tools but no longer in the web server logs.

It doesn't matter, we can close on request, and sorry for the noise!

**Comment by coudot** [comment]
We will add the map files in next release, I let this issue opened.

**Comment by coudot** [comment]
Should be ok with latest commit. Thanks for the report.
