### ISSUE TITLE
Error 500 when user is not found in directory for password reset by mail

### ISSUE THREAD

**Issue by coudot** [ltb-project/self-service-password#711]
Reported by @evertonpavan in #571 

Logs:
```
172.17.0.1 - - [13/Sep/2022:07:13:41 +0000] "GET /index.php?action=sendtoken HTTP/1.1" 200 1737 "http://localhost:8080/index.php" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
[Tue Sep 13 07:13:47.368622 2022] [php:error] [pid 18] [client 172.17.0.1:57220] PHP Fatal error:  Uncaught TypeError: ldap_get_dn(): Argument #2 ($entry) must be of type LDAP\\ResultEntry, bool given in /var/www/html/sendtoken.php:104\nStack trace:\n#0 /var/www/html/sendtoken.php(104): ldap_get_dn()\n#1 /var/www/html/index.php(183): require_once('...')\n#2 {main}\n  thrown in /var/www/html/sendtoken.php on line 104, referer: http://localhost:8080/index.php?action=sendtoken
172.17.0.1 - - [13/Sep/2022:07:13:47 +0000] "POST /index.php?action=sendtoken HTTP/1.1" 500 210 "http://localhost:8080/index.php?action=sendtoken" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"

**Comment by coudot** [comment]
@evertonpavan could you confirm that this patch solve the issue on your side? https://github.com/ltb-project/self-service-password/pull/712/files#diff-60c04a04215ce092db74c81c7eaf4bf5e6c49f796b4ae6e3c526ce70758f33f6

**Comment by evertonpavan** [comment]
@coudot Yes, now it's working properly! Well done! Thank you! 👍🏻

**Comment by evertonpavan** [comment]
> @evertonpavan could you confirm that this patch solve the issue on your side? https://github.com/ltb-project/self-service-password/pull/712/files#diff-60c04a04215ce092db74c81c7eaf4bf5e6c49f796b4ae6e3c526ce70758f33f6

@coudot Yes, now it's working properly! Well done! Thank you! 👍🏻

**Comment by coudot** [comment]
Thanks for the confirmation, we will release a new version soon.
