### ISSUE TITLE
Error 500 after apt update/upgrade on Debian

### ISSUE THREAD

**Issue by sumoo13** [ltb-project/self-service-password#713]
Hi

after an apt update and apt upgrade i have an error 500

PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in /usr/share/self-service-password/lib/vendor/symfony/polyfill-php80/bootstrap.php on line 29

**Comment by coudot** [comment]
What is your current PHP version?

**Comment by sumoo13** [comment]
PHP Version 7.0.33-0+deb9u12

**Comment by coudot** [comment]
Sadly this version is really too old, it is in Debian stretch (https://packages.debian.org/stretch/php7.0), which is not maintained anymore: https://www.debian.org/releases/stretch/index.en.html
