### ISSUE TITLE
Debian package not in the Apt repo

### ISSUE THREAD

**Issue by reshippie** [ltb-project/self-service-password#716]
It's on the download page (https://ltb-project.org/download.html), but none of the Web UI packages are actually in the repository for installation.

**Comment by coudot** [comment]
They are in the "stable" repository: https://ltb-project.org/debian/stable/pool/main/

**Comment by reshippie** [comment]
Ah, ok.  Thanks for pointing that out.  The Download page links to the LTB documentation, which doesn't have that URL.

**Comment by coudot** [comment]
You are right, the link in the website is incorrect, we will fix it.

**Comment by coudot** [comment]
See https://github.com/ltb-project/website/commit/735b060bc1723b681d350fc95a0fe0df6069a62d
