### ISSUE TITLE
Custom language files for SSP

### ISSUE THREAD

**Issue by radasys** [ltb-project/self-service-password#726]
Hello!

We have been using Self Service Password (SSP) for a while and is an excellent solution for our users. However, in our environment, we have tailored the es.inc.php language file to match our needs.

Before a SSP upgrade, we backup our custom es.inc.php, then upgrade and finally copy back the custom es.inc.php.

We were just wondering if would be possible to load our custom es.inc.php 

However, we must backup the file prior a SSP upgrade and then copy back our customized language file after it. As we have automated upgrades in our servers, we would like to automatically upgrade SSP too without losing our custom messages (or manually backing up them).

So, would be possible to set up custom language files that do not get overridden after upgrades?

Thank you for your support!

**Comment by coudot** [comment]
You can put your customized lang file in config/, it will not be erased by update

**Comment by radasys** [comment]
Thank you, @coudot! So I can put my es.inc.php in the lang folder and that's it? Or should the file have a different name?

**Comment by radasys** [comment]
Totally understood. 

My concern was regarding to a SSP upgrade that may replace my custom es.inc.php with a new stock one from the new version. 

So a new SSP upgrade won't break my custom lang file nor replace it, right?

Thanks!

**Comment by coudot** [comment]
No, the update will not replace files that are not part of the package.

**Comment by radasys** [comment]
Thank you so much!
