### ISSUE TITLE
Can Smarty3 be part of the dependencies managed by Composer?

### ISSUE THREAD

**Issue by alcorwalter** [ltb-project/self-service-password#728]
I can't install SSP by a system package, Smarty3 either, especially since it forces the installation of PHP which is already installed by a third party application.
This makes the installation and maintenance of SSP very tedious.
If Smarty3 could be installed by Composer, like other components, it would be easier. Is this technically possible?

**Comment by coudot** [comment]
Removing dependencies is not a good solution, the SSP package is tested in latest distributions and it works great (except current bug in Debian, see #681).

To us your own PHP/Smarty, either install from sources, or build your own packages or Docker image.

**Comment by alcorwalter** [comment]
If installed by system package, you can keep package dependency.
If installed manually, you can add composer dependency ?
It can really help when using shared hosting (plesk, etc)

**Comment by coudot** [comment]
Sorry, this is not clear for me. If you can install SSP manually, you should be able to install composer.

**Comment by alcorwalter** [comment]
I thought that your lib/composer.json may add smarty3 in his dependencies ; so i can execute composer install to get the right version of smarty3, in the right place. but i'm not a coder so i may misunderstood the usage of composer.

**Comment by alcorwalter** [comment]
OK I understand. (I must confess I do regret that Smarty3 is not managed this way).
That's not hard to add and configure with SSP but it would be transparent if it came with it. 
I think we can close this issue / request.

**Comment by stevleibelt** [comment]
@coudot as @alcorwalter mentioned it, would it make sense to close this issue?

**Comment by coudot** [comment]
Indeed, I close this issue.

Smarty can be installed as package on RHEL / Debian, or from an archive (see the Dockerfile).
