### ISSUE TITLE
LDAP Configuration - Password or User is not modified

### ISSUE THREAD

**Issue by uftk** [ltb-project/self-service-password#729]
I am configuring the LDAP but I get a password changed successfully message but it is not making the change.

In my config file I have placed this but I don't know what I could be doing wrong or missing.

#LDAP
$ ldap_url = " ldap://mysrv.srv.com.pe:389 ";
$ ldap_starttls = falso ;
$ ldap_binddn = " cn=user,ou=sote,ou=IT,dc=srv,dc=com, dc=pe ";
$ ldap_bindpw = 'secret' ;
// para la autenticación GSSAPI, comente ldap_bind* y descomente las líneas ldap_krb5ccname
//$ldap_krb5ccname = "/ruta/a/krb5cc";
$ ldap_base = " dc=srv,dc=com, dc=pe ";
$ ldap_login_attribute = " samAccountName ";
$ ldap_fullname_attribute = " cn ";
$ ldap_filter = " (&(objectClass=user)( $ ldap_login_attribute ={login})) ";
$ ldap_use_exop_passwd = falso ;
$ ldap_use_ppolicy_control = falso ;

$ ad_mode = falso ;
$ hash = " claro ";
$ quien_cambia_contraseña = " usuario ";

The user has administrator permissions.
Thanks.

**Comment by coudot** [comment]
You can't write password in AD without LDAPS enabled.

**Comment by uftk** [comment]
I checked by prefacing ldaps:// but I hey the message of unable to access LDAP directora
