### ISSUE TITLE
Dependency check for function ldap_modify_batch()

### ISSUE THREAD

**Issue by nafai** [ltb-project/self-service-password#73]
Hi,

After setting up SSP and attempting to change a password, I got a page with the menu, icon, and no messages. The error_log file had the following messages:

[Thu Jan 05 14:38:06.521936 2017] [:error] [pid 8695] [client (me):1257] PHP Notice:  Use of undefined constant LDAP_MODIFY_BATCH_REMOVE - assumed 'LDAP_MODIFY_BATCH_REMOVE' in /usr/share/self-service-password/lib/functions.inc.php on line 333, referer: http://ssp.saintelizabeth.com/index.php
[Thu Jan 05 14:38:06.522011 2017] [:error] [pid 8695] [client (me):1257] PHP Notice:  Use of undefined constant LDAP_MODIFY_BATCH_ADD - assumed 'LDAP_MODIFY_BATCH_ADD' in /usr/share/self-service-password/lib/functions.inc.php on line 338, referer: http://ssp.saintelizabeth.com/index.php
[Thu Jan 05 14:38:06.522031 2017] [:error] [pid 8695] [client (me):1257] PHP Fatal error:  Call to undefined function ldap_modify_batch() in /usr/share/self-service-password/lib/functions.inc.php on line 343, referer: http://ssp.saintelizabeth.com/index.php

CentOS 7's latest version of PHP is 5.4.16. ldap_modify_batch() [was introduced](http://php.net/manual/en/function.ldap-modify-batch.php) in PHP 5.4.26 (in the 5.4 branch). After upgrading my PHP version, it ran successfully.

The dependency checker should look for this function as it's a critical dependency. And hopefully it'll help others who use the PHP version that comes standard in CentOS 7.

Thanks!

**Comment by coudot** [comment]
Done by @plewin in PR #95
