### ISSUE TITLE
Dockerfile builds broken image due to Smarty4 being installed (also image hosted on docker.io)

### ISSUE THREAD

**Issue by miukumac** [ltb-project/self-service-password#732]
The Dockerfile included in the 1.5.2 release is broken due to it attempting to install Smarty4.

Simple fix is to replace the paths and download the latest 3.1.47 Smarty from Github;

```
--- self-service-password-1.5/Dockerfile	2022-10-06 12:23:13.000000000 +0300
+++ Docker-Toimiva	2022-11-10 09:06:49.352271735 +0200
@@ -34,16 +34,16 @@
     && apt-get purge -y --auto-remove $buildDeps \
     && rm -r /var/lib/apt/lists/* \
     && a2enmod rewrite
-RUN mkdir -p /usr/share/php/smarty4/ && \
-    curl -Lqs https://github.com/smarty-php/smarty/archive/refs/tags/v4.2.0.tar.gz | \
-    tar xzf - -C /usr/share/php/smarty4/ --strip-components=2
+RUN mkdir -p /usr/share/php/smarty3/ && \
+    curl -Lqs https://github.com/smarty-php/smarty/archive/refs/tags/v3.1.47.tar.gz | \
+    tar xzf - -C /usr/share/php/smarty3/ --strip-components=2
 RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"
 COPY . /var/www
 RUN rmdir /var/www/html && \
     mv /var/www/htdocs /var/www/html && \
     mkdir -p /var/www/templates_c && \
     chown -R www-data: /var/www/templates_c && \
-    sed -i 's/smarty3/smarty4/' /var/www/conf/config.inc.php
+    sed -i 's/smarty3/smarty3/' /var/www/conf/config.inc.php
 ENV LC_CTYPE=en_US.UTF-8
 EXPOSE 80
```

Patch builds a working docker image. 

The docker image currently hosted at docker.io also has the same problem and is non-functional due to index.php trying to use Smarty3 but the image only contains Smarty4.

**Comment by coudot** [comment]
Hello,

I justed tester the latest docker image and it works great. Maybe your local config is incorrect?

Which log message do you have when launching the image?

**Comment by miukumac** [comment]
Hello,

We can write this up to "problem exists between chair and keybord" - for some reason Docker wasn't properly building the local image and when I completely pruned everything it started working properly. 

My apologies for the needless bug rep.
