### ISSUE TITLE
User account disclosure risk (Token method)

### ISSUE THREAD

**Issue by philhagen** [ltb-project/self-service-password#736]
Currently, if a nonexistent or otherwise incorrect username is specified for the "token" reset method, an error message of "Login or password incorrect" is displayed. If an existing username is specified, a message of "A confirmation email has been sent" is displayed.

This discloses the existence of the specified username.  While the rate-limiting features can mitigate this risk to some extent, this still reflects an account disclosure risk.

Instead, the response should be something along the lines of "If an account with that name exists, a confirmation email has been sent to the associated email address" regardless of whether the address was found or not.

**Comment by coudot** [comment]
Did you look at the configuration parameter `

**Comment by philhagen** [comment]
aha - that didn't click as the possible setting I was looking for.  however, how can you determine the exact message that needs to be obfuscated?  I can see the lists of message slugs at https://github.com/ltb-project/self-service-password/blob/12617c61480ac5c4382de7581094ec1c2f235540/lib/functions.inc.php#L158-L169

The `mailnomatch` message is already obfuscated by default but it's not immediately clear which one this specific case uses.

**Comment by philhagen** [comment]
The above configuration cannot prevent this account disclosure situation.  The `$obscure_failure_messages` setting replaces named error messages with text from the `badcredentials` message.  However, the behavior described in this issue is that `tokensent` is displayed when a valid username is submitted and `badcredentials` is displayed when an invalid one is submitted.

Preventing this account disclosure situation would require that **both** of these conditions display a notional `tokensent_ifexists` message such as "If an account with that name exists, a confirmation email has been sent to the associated email address".

**Comment by coudot** [comment]
You are right, this can be an improvement

**Comment by philhagen** [comment]
Thanks and please let me know if I can be of assistance in testing anything!

**Comment by coudot** [comment]
Hello @philhagen, could you test #749?

**Comment by philhagen** [comment]
Hello! Just gave that a test and it looks great - thank you!!

**Comment by coudot** [comment]
Thanks for the feedback!

I need to see if the  `$obscure_failure_messages` is still needed, as we now manage the `mailnotfound` with this new parameter

**Comment by coudot** [comment]
To avoid any regression in a "patch" version, I postponed the `$obscure_failure_messages` problem.
