### ISSUE TITLE
unable to reset password after update to 1.5.2-1

### ISSUE THREAD

**Issue by slapplebags** [ltb-project/self-service-password#737]
After updating a previously working install on debian 10 i am no longer able to reset passwords. Log message from nginx error.log:
`2022/12/20 11:59:12 [error] 761#761: *21 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: mail_attributes in /usr/share/self-service-password/htdocs/sendtoken.php on line 114PHP message: PHP Warning:  sizeof(): Parameter must be an array or an object that implements Countable in /usr/share/self-service-password/htdocs/sendtoken.php on line 114PHP message: Mail (username@email) does not match for user (username)PHP message: PHP Notice:  Undefined variable: smarty_debug in /usr/share/self-service-password/htdocs/index.php on line 198PHP message: PHP Notice:  Undefined variable: background_image in /usr/share/self-service-password/htdocs/index.php on line 210" while reading response header from upstream, client: ip-address, server: (url), request: "POST / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "(servername)", referrer: "https://(url)/"
2022/12/20 12:00:19 [error] 761#761: *25 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: smarty_debug in /usr/share/self-service-password/htdocs/index.php on line 198PHP message: PHP Notice:  Undefined variable: background_image in /usr/share/self-service-password/htdocs/index.php on line 210" while reading response header from upstream, client: 128.111.106.5, server: (servername), request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "(servername)", referrer: "https://(url)/"`

installation was done via apt per the documentation provided.

**Comment by faust64** [comment]
Can you share your configuration?
Have you checked for release notes, I think there are instructions regarding some variables changing (in your error, some sizeof, ,,, expects an array?)

**Comment by slapplebags** [comment]
ah, i missed the bit about $mail_attribute with $mail_attributes for the upgrade. I've since rolled back to the previous version and its working for the time being. I'll try the upgrade during our next upgrade window and let you know if the mail attribute change doesnt fix it.
