### ISSUE TITLE
Clean install - SSP site doesn't load

### ISSUE THREAD

**Issue by wicknet** [ltb-project/self-service-password#739]
Unable to get SSP site to load on Apache with a plain vanilla new Ubuntu 22.04 vm (2vCPU, 4Gb vRAM, 25Gb Disk), using install steps as outlined. The default Apache site comes up, but after enabling self-service-password.conf I get nothing. Apachectl configtest passes fine. Even tried purging Apache and using Nginx with the conf as provided on Github, but SSP site doesn't load. This is before any customization has been done.

I'm fairly familiar with the project and have used LTB SSP for 2+ years to reset AD passwords using mail tokens on a highly customized install on an older Ubuntu 20.04 VM with PHP 7. That vm was purged to create a brand new server but I can't get beyond the initial install to get the site up.

A clean VM with a Docker install does load the default SSP site, but I prefer using plian Ubuntu and Apache or Nginx instead of docker containers for ease of customization.

Any advice would be appreciated. Thanks!

**Comment by wicknet** [comment]
For anyone facing this issue with Ubuntu 22.04, simply use Ubuntu 20.04 instead. LTB-SSP installs PHP 7.4 instead of 8.1 and the Apache SSP site loads straight out of the box, instead of giving a blank white screen as on Ubuntu 22.04.

**Comment by coudot** [comment]
See https://github.com/ltb-project/self-service-password/issues/681
