### ISSUE TITLE
session token with nginx

### ISSUE THREAD

**Issue by roumano** [ltb-project/self-service-password#74]
Hi,

the ssp is not working on my nginx.

i got this kind of error  when i use the link reset via mail : 

[error] 12#12: *5 FastCGI sent in stderr: "PHP message: PHP Warning:  session_start(): Cannot send session cache limiter - headers already sent (output started at /var/www/html/index.php:155) in /var/www/html/pages/sendtoken.php on line 147

due to this error, the session file ( like tmp/sess_e06b0cf4dd2e8c95428d09a2bd061211  ) are empty, so the email reset link is not working with this error :  " invalid token" (due to session token file empty, due to previous error)

a ugly workarround is to to this line as first line on the /var/www/html/index.php : 

<?php session_start(); ?>

**Comment by coudot** [comment]
What is the workaround?

**Comment by roumano** [comment]
<?php session_start(); ?>
at the begin of index.php of the ssp

**Comment by roumano** [comment]
at the begin of index.php of the ssp : 
   <?php session_start(); ?>

**Comment by roumano** [comment]
at the begin of index.php of the ssp
 " <?php session_start(); ?>"

**Comment by roumano** [comment]
start php ( <? php )    session_start();  end php   (   ?> ) 
sorry github remove caracterer <? ...

**Comment by roumano** [comment]
start php session_start(); end php 
sorry github remove caracterer <? ...

**Comment by coudot** [comment]
Could confirm which SSP version you are using? And if the bug only occurs with Nginx?

**Comment by roumano** [comment]
I'm using the lastest version ( 1.0 ) and the bug only occurs with nginx, it's working like a charm on apache/httpd

**Comment by coudot** [comment]
Maybe the ini_set in index.php line 59 is not taken into account by Nginx/FastCGI. You can try to configure output_buffering in your php.ini to test.

**Comment by roumano** [comment]
Tested with output_buffering = 4096 it's fixing the issue
the default value is 0 :  http://php.net/manual/fr/outcontrol.configuration.php

**Comment by coudot** [comment]
Strange, but this is a nicer workaround.

**Comment by roumano** [comment]
Exact mush nicer.
Ideally, you can fix the ssp code to avoid this issue
Otherwise, we can update the documentation to add a nginx information 

if yes, maybe we should rename http://ltb-project.org/wiki/documentation/self-service-password/latest/config_apache to /config_web and add 2 paragraph  1) apache 2) nginx

**Comment by coudot** [comment]
Documentation updated: http://ltb-project.org/wiki/documentation/self-service-password/1.1/config_webserver

I don't understand why setting output_buffering to 4096 works. We set it to 0 to ensure that no output is done before session_start.

**Comment by coudot** [comment]
Could you share your Nginx configuration file?

**Comment by roumano** [comment]
My php.ini configuration file :   

php.ini 
session.save_path = /tmp
upload_max_filesize = 10M
post_max_size = 16M
max_execution_time = 600
request_terminate_timeout = 600
expose_php = Off
output_buffering = 4096

My nginx configuration :   

server {
	listen 80;

	root /var/www/html;
	index index.php index.html index.htm;

	# Make site accessible from http://localhost/
	server_name _;
	
	# Disable sendfile as per https://docs.vagrantup.com/v2/synced-folders/virtualbox.html
	sendfile off;

        gzip on;
        gzip_comp_level 6;
        gzip_min_length 1000;
        gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript application/javascript text/x-js;
        gzip_vary on;
        gzip_proxied any;
        gzip_disable "MSIE [1-6]\.(?!.*SV1)";

	# Add stdout logging

	error_log /dev/stdout warn;
	access_log /dev/stdout main;


	# pass the PHP scripts to FastCGI server listening on socket
	#
	location ~ \.php {
		fastcgi_pass unix:/var/run/php-fpm.socket;
		fastcgi_split_path_info       ^(.+\.php)(/.+)$;
		fastcgi_param PATH_INFO       $fastcgi_path_info;
		fastcgi_param PATH_TRANSLATED $document_root$fastcgi_path_info;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		fastcgi_index index.php;
		fastcgi_read_timeout 600;
		include fastcgi_params;
	}

        error_page 404 /404.html;
        location = /404.html {
                root /usr/share/nginx/html;
                internal;
	}

	# deny access to . files, for security
	#
	location ~ /\. {
    		log_not_found off; 
    		deny all;
	}

}

It's running on a minimal docker (via alpine OS ) instance

**Comment by coudot** [comment]
Documentation updated: http://ltb-project.org/wiki/documentation/self-service-password/1.1/config_nginx
