### ISSUE TITLE
Error with AD mode : DSID-03191072, problem 1005 (CONSTRAINT_ATT_TYPE), data 0, Att 9005a

### ISSUE THREAD

**Issue by thomasalary** [ltb-project/self-service-password#740]
Hello,

I'm looking for help with this error occuring when attempting to change the password of a user :

DSID-03191072, problem 1005 (CONSTRAINT_ATT_TYPE), data 0, Att 9005a

The change works directly from Active Directory user console management ...

Maybe the probleme is that I'm trying to use it to change Domain Admin password.
Is there an issue with that ?

**Comment by coudot** [comment]
Did you use LDAPS ?

**Comment by thomasalary** [comment]
Yes,
This is my config :

#
# Parametres LDAP
#
$ad_mode = true;
$ldap_url = "ldaps://ip";
$ldap_binddn = "xxxxxxx@xxxxxx.fr";
$ldap_bindpw = "secret";
$ldap_base = "DC=xxx,DC=xxx,DC=xx";
$ldap_filter = "(&(objectClass=user)(sAMAccountName={login})(!(userAccountControl:1.2.840.113556.1.4.803:=2)))";

$keyphrase = "BSYNNnEHFon7DPBJtHatB3zK48q63!PnpjG";
$ldap_login_attribute = "cn";
$ldap_fullname_attribute = "sn";
$who_change_password = "user";

But maybe I forgot something somewhere, I was just looking if SSP is working for Domain Admin account with adminCount attribut set to 1.

**Comment by coudot** [comment]
Myabe the binddn should be set as DN

**Comment by thomasalary** [comment]
I'll try thanks. But I have succeeded binds in the Events Logs on my DC ...
So not sure of that

**Comment by coudot** [comment]
So it should be a permission issue on AD side. You can try to reproduce with ldapmodify

**Comment by thomasalary** [comment]
I tried with this account as Domain Admin.
But don't worry I will check other things, the first one I want to check is that SSP is able to change Domain Admin password

**Comment by thomasalary** [comment]
Then, I tried to change the password of a "normal account" and it works.
So the problem seems to be with the privileged of the Domain Admin account. Maybe with the use of unicodePwd ?

**Comment by thomasalary** [comment]
OK, that was a problem with password policies
