### ISSUE TITLE
Update php version

### ISSUE THREAD

**Issue by jul-fls** [ltb-project/self-service-password#742]
Hello, we use this project (docker image version) in my company but have found out that php 8.1.9 has security breaches that are solved in php 8.2.1, is it possible to update the php version in the dockerfile and push a new build to dockerhub ?
Thanks by advance and Best regards from France !

**Comment by coudot** [comment]
We will have a look. We should check if there is no impact switching to 8.2.

**Comment by artlog** [comment]
i will test it.

**Comment by jul-fls** [comment]
Nice, thank you very much all for your work on this project !

**Comment by jul-fls** [comment]
The security team just reported that the minimum required version is the latest one so the 8.2.1 version, see here :
[](https://www.cert.ssi.gouv.fr/avis/CERTFR-2023-AVI-0009/)

**Comment by artlog** [comment]
Ah ... did test on 8.2

**Comment by coudot** [comment]
I see that PHP 8.1.14 was released: https://www.php.net/archive/2023.php#2023-01-05-1

It is maybe enough to solve security issues?

**Comment by jul-fls** [comment]
According to the anssi report, yes this is sufficient

**Comment by artlog** [comment]
with current image php8.2 it is latest 8.2.1 that is shipped

root@163d1b1580f8:/var/www/html# php --version
PHP 8.2.1 (cli) (built: Jan 11 2023 07:25:22) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.1, Copyright (c) Zend Technologies
with Zend OPcache v8.2.1, Copyright (c), by Zend Technologies

**Comment by coudot** [comment]
@jul-fls could you give the link to ANSSI report / CVE?

**Comment by coudot** [comment]
Thanks. There is not much information in it, we can't know if we use a component/class impacted.

Anyway, we'll provide an updated version when releasing 1.5.3

**Comment by coudot** [comment]
There is no fixed release date.

Anyway, I just took the 1.5.2 tag and regenerate new docker images, which use PHP 8.1.14. You can update from docker hub.

**Comment by jul-fls** [comment]
Thanks for your help !

**Comment by coudot** [comment]
Done by @davidcoutadeur in 99afec6aa1429945d82f2d2b90313c8a2802b84d
