### ISSUE TITLE
Image installation 

### ISSUE THREAD

**Issue by georgesefen** [ltb-project/self-service-password#747]
Hello, I'm experiencing problem with running the container, I get the below message then it hangs 
[core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND' 
when I open the webpage, I see message about  Token encryption requires a random string in keyphrase setting'
I appreciate all your help

**Comment by coudot** [comment]
Mount your config file and change the secret phrase: https://self-service-password.readthedocs.io/en/latest/config_general.html#security

**Comment by stevleibelt** [comment]
@georgesefen where you able to solve your issue?

If so, please be so kind and close this issue :-).
