### ISSUE TITLE
SHA512 in password encryption

### ISSUE THREAD

**Issue by ifleg** [ltb-project/self-service-password#75]
Hi,
In our ldap we want to use SHA512 for security reasons.
I thus modified the source code to add it.
In lib/functions.inc.php

```
# Create SHA512 password
function make_sha512_password($password) {
    $hash = "{SHA512}" . base64_encode(pack("H*", hash('sha512', $password)));
    return $hash;
}
.
.

if ( $hash == "SHA512" ) {
            $password = make_sha512_password($password);
        }
```

I would suggest you to implement such a mecanism in future versions.
F.

**Comment by coudot** [comment]
Indeed, will add this to next version

**Comment by ifleg** [comment]
Wonderfull !

**Comment by coudot** [comment]
Done by @plewin in PR #93
