### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by cleberanderson** [ltb-project/self-service-password#752]
Hello, I have a server with centos-web-panel, it has configured nginx, varnish and apache, in addition to php-fpm81, all the necessary php modules are also installed, I performed the settings, however, it shows error 500 when try to load the page. Could someone give me a light? Detail, in my scenarios, it is not possible to run docker.

---
`Olá, tenho um servidor com centos-web-panel, o mesmo possui configurado nginx, varnish e apache, além do php-fpm81, todos os módulos php necessários, também estão instalados, realizei as configurações, porém, o mesmo apresenta erro 500 ao tentar carregar a página. Alguém poderia me dar uma luz? Detalhe, em meu cenário, não é possível rodar o docker.`

**Comment by coudot** [comment]
Set debug and check the logs

**Comment by cleberanderson** [comment]
Problem solved,

Analyzing the logs, I found the error in Smarty.
Solved by making a copy of smarty's default folder.

\cp -r /usr/share/php/Smarty /usr/share/php/smarty3

---
`Problema resolvido,

Analisando os logs, encontrei o erro no Smarty.
Resolvido, fazendo uma cópia da pasta padrão do smarty.

\cp -r /usr/share/php/Smarty /usr/share/php/smarty3`

**Comment by coudot** [comment]
You could also update the config:
```php
define("SMARTY", "/usr/share/php/Smarty/Smarty.class.php");
