### ISSUE TITLE
SSP does not change password in AD

### ISSUE THREAD

**Issue by cleberanderson** [ltb-project/self-service-password#753]
I performed all the settings, integrated with LDAP Active Directory.

When performing a user query to change the password, it works just fine, however, in any of the available options, it does not change the password on the server, but the SSP displays a message confirming that the password has been changed.

What can it be? Is there any specific configuration for LDAP AD?

---
```
Realizei todas as configurações, intregei com LDAP Active Directory.

Ao realizar a consulta de usuário, para troca de senha, funciona certinho, porém, em qualquer uma das opções disponíveis, não altera a senha no servidor, mas, o SSP, apresenta mensagem confirmando que a senha foi alterada.

O que pode ser? Existe alguma configuração expecífica para LDAP AD
```

**Comment by coudot** [comment]
If SSP confirms that the password has been changed, it means AD has validated the changes (LDAP return code 0). Check logs on AD side to know more.
