### ISSUE TITLE
Authentication token manipulation error

### ISSUE THREAD

**Issue by amar61** [ltb-project/self-service-password#759]
Hi Team, I have changed the password via  self-service portal (LTB), and the password changed successfully
when we try to ssh with the new password on server we are facing below error   

PFA my Configuration 
amar@% ssh divya.dyuti@1x.2x.12x.4x
divxx.dxx@1x.2x.1xx.xx's password: 
You are required to change your password immediately (password aged)
Password expired 869 days ago
WARNING: Your password has expired.
You must change your password now and login again!
Changing password for user dxxx.dxxx.
(current) LDAP Password: 
New password: 
Retype new password: 
password change failed: Constraint violation
passwd: Authentication token manipulation error
Connection to xx.x.x.x closed.

[configuration.txt](https://github.com/ltb-project/self-service-password/files/10909199/configuration.txt)

**Comment by coudot** [comment]
For the expiration warning, you should try to enable shadow options:
```php
$shadow_options['update_shadowLastChange'] = false;
$shadow_options['update_shadowExpire'] = false;
```

For the constraint violation, I don't see how it is related with Self Service Password. Check your UNIX or LDAP password policy.

**Comment by amar61** [comment]
Thanks, working fine now
