### ISSUE TITLE
Polish translation error

### ISSUE THREAD

**Issue by JQu80** [ltb-project/self-service-password#764]
I found an error in the Polish translation. In the pl.inc.php file there is a line:

$messages['resetsubject'] = "[BSD Serwis][Zmiana hasła] Ustaw ponownie swoje hasło";

It should look like the line below. Delete the text in square brackets.

$messages['resetsubject'] = "Ustaw ponownie swoje hasło";

**Comment by coudot** [comment]
Fixed, thanks for the report!
