### ISSUE TITLE
Help Menu vs PHP Version issues?

### ISSUE THREAD

**Issue by aleguedes1983** [ltb-project/self-service-password#766]
HI All,
I have beem using the SSP for many year and the tool is really good...
Due security vulnerabilities I needed to upgrade the SSP to the version 1.5.2
Everything seems to be working fine, but i think that I found a bug:

I use the "help" to show my users a more detailed information about their password issues. 

In my older version, I have configured this message bellow.... Note that it recognized the HTML Tags. I can see the bold, the lines breaks, etc...
![image](https://user-images.githubusercontent.com/21367963/230989405-522e3aae-1731-4916-a85d-bf75fa0e23b2.png)

In the version 1.5.2, seems that PHP tries to show everything as text, It does not understand the HTML tags:
![image](https://user-images.githubusercontent.com/21367963/230989988-ee0939a8-b278-420b-bb51-153ff027e0cf.png)

Please, disregard the black rectangles. I am try to anonymizing my company name =)

Since I am not good in PHP or HTML at all, I am reaching our you guys.

Any idea about this problem?

**Comment by coudot** [comment]
Hello,

the message in Smarty template should be escaped with: `unescape: "html" nofilter`

We should have miss some messages, maybe:
```
--- a/templates/change.tpl
+++ b/templates/change.tpl
@@ -91,6 +91,6 @@
 {/if}
 {elseif $msg_passwordchangedextramessage}
     <div class="result alert alert-{$result_criticity}">
-    <p><i class="fa fa-fw {$result_fa_class}" aria-hidden="true"></i> {$msg_passwordchangedextramessage}</p>
+    <p><i class="fa fa-fw {$result_fa_class}" aria-hidden="true"></i> {$msg_passwordchangedextramessage|unescape: "html" nofilter}</p>
     </div>
 {/if}
 ```
 
 Could you confirm that it fixes your issue?
