### ISSUE TITLE
Missing dependence in debian package breaks installation experience

### ISSUE THREAD

**Issue by paulignari** [ltb-project/self-service-password#773]
In #760 the package dependence on smarty3 was removed for rpm based distributions as well for deb base ones.

The issue was only on dep based distribution, while in debian stable smarty3 package is present and working, the missing dependence breaks the installation experience as the package is not working without manual steps.

It is possible to restore the smarty3 dependence in the deb package config packaging/debian/control?

**Comment by coudot** [comment]
The bug is still opened on Ubuntu side: https://bugs.launchpad.net/ubuntu/+source/smarty3/+bug/1986916

The documentation now clearly indicates to install smarty package: https://self-service-password.readthedocs.io/en/latest/installation.html#debian-ubuntu

I don't know what is the best solution, as installing with the buggy package also breaks the installation.

**Comment by paulignari** [comment]
This is a weird situation, as there is no uniform behavior across distributions.

I hit this problem purging unused packages after upgrading from 1.5.2-1 to  1.5.3-1, so smarty3 packages was unistalled.

Some breaking changes in deb packages are advertised at installation time, this can be useful for interactive installation. Maybe it can be useful even for non-interactive installation (like mine, with ansible) if apt-list-changes is installed.

I have to dig deeper to understand how to do this.

**Comment by paulignari** [comment]
The Best Packaging Practices of Debian [1]  states to put such changes in NEWS.Debian files, so programs like apt-listchanges can advertise the sysop.

There are debconf notes too[2], but are less recommended in the above document. Maybe these can be useful for people without apt-listchanges installed.

I think that implementing both is a sufficient advertise of the need to manually install smarty3 package.

What do you think about it?

1. https://www.debian.org/doc/manuals/developers-reference/best-pkging-practices.en.html#supplementing-changelogs-with-news-debian-files
2. http://www.fifi.org/doc/debconf-doc/tutorial.html#AEN34

**Comment by coudot** [comment]
Would be ok, you propose a PR to add the NEWS to Debian packaging

**Comment by paulignari** [comment]
I created the PR, sure its need some tweaks but I tested it building a new package and it works.
