### ISSUE TITLE
How do we use HTTP_X_FORWARDED_FOR for $client_ip_header?

### ISSUE THREAD

**Issue by alanorth** [ltb-project/self-service-password#776]
The [rate limit documentation](https://self-service-password.readthedocs.io/en/latest/config_rate_limit.html) mentions the client IP header, which defaults to PHP's `REMOTE_ADDR`. In our case, the self service password application is hosted behind a reverse proxy that is forwarding the original client IP as `HTTP_X_FORWARDED_FOR`.

Is it sufficient to set this in `config.inc.local.php`?

```php
$client_ip_header = 'HTTP_X_FORWARDED_FOR';
```

I don't see any indication in the debug logs that the self service password application is using it. Other than trying to reset my own password very quickly (!), how can I be sure it is being used?

**Comment by coudot** [comment]
This information is not written in the logs.

You can trust the code: https://github.com/ltb-project/self-service-password/blob/1.5/htdocs/sendtoken.php#L153

**Comment by alanorth** [comment]
> You can trust the code: https://github.com/ltb-project/self-service-password/blob/1.5/htdocs/sendtoken.php#L153

Ah great, that's exactly what I needed. I verified that the correct header is indeed being sent, so the code should be behaving correctly in this case. Thank you!
