### ISSUE TITLE
LDAP - Modify password error 19

### ISSUE THREAD

**Issue by RPDJF** [ltb-project/self-service-password#779]
Hey,

For some reason, i'm not able to change user password when I set $who_change_password to "user".
`[Tue Jun 13 12:34:28.239811 2023] [php:warn] [pid 21] [client 192.168.100.2:63133] PHP Warning:  ldap_modify_batch(): Batch Modify: Constraint violation in /var/www/lib/functions.inc.php on line 475, referer: http://192.168.1.15:8080/index.php`

`[Tue Jun 13 12:34:28.239889 2023] [php:notice] [pid 21] [client 192.168.100.2:63133] LDAP - Modify password error 19 (Constraint violation), referer: http://192.168.1.15:8080/index.php`

But it works when using "manager" instead.
Idealy, we don't want to use manager for security purposes.

More details :
- Active Directory is freshly installed and only used for this
- I'm using the latest docker container on a linux host
- Password complexity is disabled on the AD

I found that it may be because of the password complexity on the AD server side, but as I said, it's disabled, and it works when using the manager for password reset.

My configuration file :
```<?php // My SSP configuration
$keyphrase = "secret";
$debug = true;
$smarty_debug = true;

// server address
$ldap_url = "ldaps://server.domain.lan";
$ldap_starttls = false; // only if ldap instead of ldaps

// credentials
$ldap_binddn = "user";
$ldap_bindpw = "secret"; // ""
$who_change_password = "user";
$ldap_base = "dc=domain,dc=lan";

$ldap_login_attribute = "userPrincipalName"; // then users just type their email address
$ldap_filter = "(&(objectClass=user)($ldap_login_attribute={login}))";

// extensions
$ldap_use_exop_passwd = false; // set to false for debug purpose
$dlap_use_ppolicy_control = false; // set to false for debug purpose

// Active Direcotry mode
$ad_mode = true;
$ad_options['force_unlock'] = true;
$ad_options['force_pwd_change'] = false;
$ad_options['change_expired_password'] = true;

// Password policy
$use_pwnedpasswords = true;
$pwd_no_reuse = true;

// web interface
// feature
$use_captcha = false; // set to false for debug purpose
$show_help = false;
$lang = "fr";
// methods
$default_action = "change";
$use_change = true;
$use_questions = false;
$use_tokens = false;
$use_sms = false;
// cosmetic
$logo = "logo.png";
$background_image = "";
$display_footer = false;
?>```

**Comment by coudot** [comment]
It indeed looks like a password policy constraint.

You can set debug mode on SSP side, but I don't think it will add more info.

The best would be to have the log on AD side.

**Comment by RPDJF** [comment]
Yep ! You were right after all
Setting up the project on the prod AD seemed to fix the issue

Tbh I've set up a debian server this time, without using docker, but I don't think it was the problem
