### ISSUE TITLE
Allow sending SMS through web-based API instead of Email2SMS Gateway

### ISSUE THREAD

**Issue by jaydio** [ltb-project/self-service-password#78]
Rather than sending SMS via email it would be great to have the functionality to execute an external script and pass the mobile number and token as arguments. Most SMS providers do not support SMS via email either for reasons of security or lack of demand (see NEXMO for instance).

**Comment by coudot** [comment]
Yes this is an old request that we need to address (see http://tools.ltb-project.org/issues/542)

**Comment by ypathak7** [comment]
Can we integrate web based api instead of emailtosms gateway

**Comment by coudot** [comment]
If we implement the call to a script, this will then be possible to call a web API. Work to be done.

**Comment by ypathak7** [comment]
It would be great if you can add functionality to make it more flexible, waiting for your action toward this.

**Comment by coudot** [comment]
We can try to do it for 1.1. Any help is welcome.

**Comment by ypathak7** [comment]
Hi,

Any update on this ?

**Comment by coudot** [comment]
Not yet, we need time to work on it. You can propose a pull request if you want to have it quicker.

**Comment by coudot** [comment]
Code pushed in https://github.com/ltb-project/self-service-password/commit/83bfb40b51ab6b60ebe9d8fbdbe5755d4af3cbef

I think it is enough for everyone to code it's own SMS API call.

Any feedback welcome @jaydio @ypathak7 @plewin

**Comment by coudot** [comment]
Documentation updated: https://ltb-project.org/documentation/self-service-password/1.1/config_sms

**Comment by coudot** [comment]
The default SMS API code is now in lib/smsapi-example.inc.php. A note has been added in documentation.
