### ISSUE TITLE
[question] Preset login username

### ISSUE THREAD

**Issue by RPDJF** [ltb-project/self-service-password#780]
Hey, small question here
According to the documentation, by setting up the $header_name_preset_login parameter to "username", it should be possible to preset the username box with https://server/?username=testuser, right ?

**Comment by coudot** [comment]
An HTTP header is not a GET parameter

**Comment by RPDJF** [comment]
Right, I've got myself all mixed up
So, there is no solution to preset the username box from the URL itself ?

**Comment by coudot** [comment]
It works with the GET parameter but it has nothing to do with the HTTP header option

Open Source is great because you can directly check it: https://github.com/ltb-project/self-service-password/blob/1.5/htdocs/change.php#L47

**Comment by RPDJF** [comment]
I've already tried the login parameter, but it does send a request, right ? (and according to the code)
I was asking if it was possible to preset the "username" box only, without trying to change it already

I guess it isn't, it would be a feature request then

**Comment by coudot** [comment]
> I've already tried the login parameter, but it does send a change request, right ? (and according to the code)

No, it just ask to enter the old password.

> I was asking if it was possible to preset the "username" box only, without trying to change it already

There is no communication with LDAP server until the form is complete.

> I guess it isn't, it would be a feature request then

You need to explain what is needed, I don't understand

**Comment by RPDJF** [comment]
I mean, the login paremeter send a warning message that the user needs to first enter the old password as you said thanks to the "$result = "loginrequired"

It would be nice if there was a "username" parameter that only fill the username box without sending a warning message
the idea is to post the link on an email for each users

the login parameter does fill the username box, but with a warning message because it isn't intended for this specific usage

**Comment by coudot** [comment]
This could indeed be an improvement

**Comment by coudot** [comment]
Done in #795
