### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined function Gregwar\\Captcha\\imagecreatetruecolor()

### ISSUE THREAD

**Issue by AGI-chandler** [ltb-project/self-service-password#784]
Suddenly am seeing the error below and the captcha is unable to be generated, essentially killing the service.
<details><summary>PHP Fatal error</summary><pre>
[datetime] [php7:error] [pid] [client IP] PHP Fatal error:  Uncaught Error: Call to undefined function Gregwar\\Captcha\\imagecreatetruecolor() in /usr/share/self-service-password/lib/vendor/gregwar/captcha/src/Gregwar/Captcha/CaptchaBuilder.php:423
Stack trace:
#0 /usr/share/self-service-password/htdocs/captcha.php(39): Gregwar\\Captcha\\CaptchaBuilder->build()
#1 {main}
  thrown in /usr/share/self-service-password/lib/vendor/gregwar/captcha/src/Gregwar/Captcha/CaptchaBuilder.php on line 423, referer: https://oursite/selfservice/</pre></details>

I read it could be caused by GD library missing. However:
<details><summary>GD Library was found</summary><pre>
# cat test.php 
&lt;?php 
echo function_exists('imagecreatetruecolor') ? 'GD Library was found!' : 'GD Library was not found!';
<br>
# php ./test.php 
GD Library was found!
</pre></details>

Any idea why this started and how to fix?
Thanks!

**Comment by coudot** [comment]
Could you try to run your test script trough your webserver? It may be a configuration difference between php cli and php  webserver

**Comment by AGI-chandler** [comment]
Yes, good idea! ​ ​In that case `GD Library was **not** found!` is returned.
Now to figure out what caused that, since the system is mostly left alone. ​ ​Maybe a security update to a package, that is basically the only thing set for automation... ​ ​but: nothing new in the `/var/log/apt/history.log` for the last 2 months, and `self-service.log` shows it was working on 5/26...

**Comment by AGI-chandler** [comment]
Hmm well I couldn't figuer it out yet @coudot might you have any ideas?&nbsp;&nbsp;When I check on command line php (below), it says it's an internal function... why can't Apache PHP find it then?&nbsp;&nbsp;Also it was working find before, not sure what could cause this change in behavior.&nbsp;&nbsp;For the same code, the following shows up in Apache error.log:
```
PHP Fatal error:  Uncaught ReflectionException: Function imagecreatetruecolor() does not exist in /var/www/html/test.php:5\nStack trace:\n#0 /var/www/html/test.php(5): ReflectionFunction->__construct()\n#1 {main}\n  thrown in /var/www/html/test.php on line 5
```

```
# php -r 'print new ReflectionFunction("imagecreatetruecolor");'
Function [ <internal:gd> function imagecreatetruecolor ] {

  - Parameters [2] {
    Parameter #0 [ <required> $x_size ]
    Parameter #1 [ <required> $y_size ]
  }
}
# 
```

**Comment by dgeo** [comment]
Hi, you just miss gd module for php.

add php-gd package (or whatever it's called for your distrib)

Le 13 juillet 2023 19:58:38 UTC, Chandler ***@***.***> a écrit :
>Hmm well I couldn't figuer it out yet @coudot might you have any ideas?&nbsp;&nbsp;When I check on command line php (below), it says it's an internal function... why can't Apache PHP find it then?&nbsp;&nbsp;Also it was working find before, not sure what could cause this change in behavior.&nbsp;&nbsp;For the same code, the following shows up in Apache error.log:
>```
>PHP Fatal error:  Uncaught ReflectionException: Function imagecreatetruecolor() does not exist in /var/www/html/test.php:5\nStack trace:\n#0 /var/www/html/test.php(5): ReflectionFunction->__construct()\n#1 {main}\n  thrown in /var/www/html/test.php on line 5
>```
>
>```
># php -r 'print new ReflectionFunction("imagecreatetruecolor");'
>Function [ <internal:gd> function imagecreatetruecolor ] {
>
>  - Parameters [2] {
>    Parameter #0 [ <required> $x_size ]
>    Parameter #1 [ <required> $y_size ]
>  }
>}
># 
>```
>

-- 
geoffroy desvernay (mobile)

**Comment by AGI-chandler** [comment]
Thanks!&nbsp;&nbsp;I got it eventually, after many PHP package upgrades to 8.2, also upgraded to latest SSP version, but in the process many of my modifications were lost!&nbsp;&nbsp;Ooops, I had made many changes to files outside of the `conf` directory and can look in my backup data to restore it, is there a proper way to make such changes so they aren't lost when SSP is upgraded, or maybe at least be asked if I want to replace the file and compare it to the new one, like I see sometimes with other conf files during package upgrade?&nbsp;&nbsp;Thanks

**Comment by dgeo** [comment]
This is a very generic answer for any open-source project:

If you have to make changes in the code, there are 2 options:

- If your changes can help someone else, you may contribute your changes to the project here
- Else, you may use git, clone the project and maintain your own fork, merging (better: rebasing) your fork to update it

Any of these options require you to learn basic use of git, but this is quite easy nowadays ;)

Most of time, you should be able to find out how to stick to config file(s) only, if the software is good enought (and SSP is one of these, IMHO ;)

**Comment by AGI-chandler** [comment]
Hi @dgeo,
Yes, of course, I'm happy to (and always do) share any changes that could be beneficial to any project or its users.  The changes I made here were more internal and specific for our department, such as:

- `lang/en.inc.php`
  - Many changes to the verbiage here to customize it for our department and users
- `htdocs/sendtoken.php`
  - added a variable to store a time stamp (`$ts = date('Y-m-d H:i:s');`)
  - added `$ts` to the `error_log()` calls

To prevent the changes getting overwritten when package is updated, I came up with the workaround below, which I don't recall if it has been tested yet to see if my changes survive a package upgrade.

First, I moved the original into `conf/<original dir>`, then made a backup of the original there, then created a symlink where the original initially was -> the copy in `conf`.  For example:
```
cd /usr/share/self-service-password
mkdir conf/lang
mv lang/en.inc.php conf/lang/
ln -s ../conf/lang/en.inc.php lang/en.inc.php
cp conf/lang/en.inc.php conf/lang/en.inc.php~
```
The idea is: reads/writes from/to `lang/en.inc.php` are linked with/read from/written to `conf/lang/en.inc.php` where it is safe.  When `lang/en.inc.php` gets upgraded from a new package, only the symbolic link will be replaced with the upgraded file.  After upgrade, differences between the old package's version and new one could be checked with `diff conf/lang/en.inc.php~ lang/en.inc.php` then appropriate/required changes could be made to the customized internal copy at `conf/lang/en.inc.php`.  Finally, `lang/en.inc.php` could be moved to `conf/lang/en.inc.php~` to backup the latest upgraded version, and a new symlink created `lang/en.inc.php -> conf/lang/en.inc.php`.

**Comment by coudot** [comment]
Hello @AGI-chandler 

you can easily override any message by putting your lang file in conf/, so no workaround in needed here.

For the timestamp in error_log, I don't see the need as the date should already be stored in the log by Apache or PHP-FPM. If not, it should only be some log configuration.
