### ISSUE TITLE
ssp indicates success, but openldap failed to change password

### ISSUE THREAD

**Issue by dsclassen** [ltb-project/self-service-password#788]
PHP = 8.2.8
SSP = 1.5.3
Smarty = 4.3.1
OpenLDAP 2.5.14

These are the relevant setting in my `config.inc.local.php`

```
$ldap_use_exop_passwd = true;
$ldap_use_ppolicy_control = true;
$hash = "clear";
```

ppolicy on my LDAP server has `pwdInHistory` set to 4. When I attempt to change a password to one that exists in the previous 4 I see these messages in the Apache error log file:

```
[Fri Jul 14 10:51:33.765766 2023] [php:warn] [pid 8050] [client xxxxxxx:48390] PHP Warning:  ldap_exop_passwd(): Passwd modify extended operation failed: Password is in history of old passwords (19) in /xxxxxxx/self-service-password/lib/functions.inc.php on line 482, referer: https://xxxxxxxxxx/ssp/index.php?action=change
[Fri Jul 14 10:51:33.765835 2023] [php:notice] [pid 8050] [client xxxxxxx:48390] LDAP - Ppolicy error code: 8, referer: https://xxxxxx/ssp/index.php?action=change
[Fri Jul 14 10:51:33.831317 2023] [php:warn] [pid 8050] [client xxxxxxx:48390] PHP Warning:  Undefined array key "msg_passwordchangedextramessage" in /xxxxxxx/self-service-password/templates_c/f1cb75be2d1134aea5b255da1b01119a1ae859b6_2.file.change.tpl.php on line 137, referer: https://xxxxxxx/ssp/index.php?action=change
[Fri Jul 14 10:51:33.831370 2023] [php:warn] [pid 8050] [client xxxxxxx:48390] PHP Warning:  Attempt to read property "value" on null in /xxxxxxx/self-service-password/templates_c/f1cb75be2d1134aea5b255da1b01119a1ae859b6_2.file.change.tpl.php on line 137, referer: https://xxxxxxx/ssp/index.php?action=change
```

Which is promising. It tells me that SSP is aware that password changing was rejected because "Password is in history of old passwords"

However the web interface for SSP indicates that the password was changed successfully "Your password was changed"

I did turn on `$smarty_debug = true;` and it looks like the value of `$error` is getting set... but the Value is clearly incorrect.

```
$error                           Value
Origin: "Smarty object"          "Your password was changed"
```

**Comment by coudot** [comment]
Hello,

there is a bug in PHP-LDAP: https://bugs.php.net/bug.php?id=80820

You can vote for it to increase the priority

Until it is fixed, I see no other solution than not using exop with ppolicy.

**Comment by dsclassen** [comment]
OK. Thanks for the heads up.
