### ISSUE TITLE
Button for regenerate Captcha

### ISSUE THREAD

**Issue by artiq6** [ltb-project/self-service-password#789]
Is there any option to reload the Captcha using for example a button? 
Instead, the only way to refresh the Captcha is to reload the entire web page (after the user has already entered all the required fields) what's inconvinient. 
Reloading Captcha is sometimes necessary when users have difficulty reading the image.

**Comment by davidcoutadeur** [comment]
This would be done by #894

**Comment by davidcoutadeur** [comment]
The refactoring done in #894 allows to generate a new captcha by clicking on a double-arrow refresh button.
