### ISSUE TITLE
openLDAP config

### ISSUE THREAD

**Issue by AmeliaEnslin** [ltb-project/self-service-password#80]
hi there, 
Im new to all this, followed the installation manual and successfully launched the self service password, im not sure how to check if my openLDAP connects? As it doesnt seem to pickup my details? This is my config: ( I use openLDAP)

```
# LDAP
$ldap_url = "ldap://ldap.ostb.co.za:389";
$ldap_starttls = false;
$ldap_binddn = "cn=manager,dc=kses,dc=net";
$ldap_bindpw = "jetset";
$ldap_base = "ou=Users,dc=kses,dc=net";
$ldap_login_attribute = "uid";
$ldap_fullname_attribute = "cn";
$ldap_filter = "(&(objectClass=person)(uid={login}))";

# Active Directory mode
# true: use unicodePwd as password field
# false: LDAPv3 standard behavior
$ad_mode = false;
# Force account unlock when password is changed
$ad_options['force_unlock'] = false;
# Force user change password at next login
$ad_options['force_pwd_change'] = false;
# Allow user with expired password to change password
$ad_options['change_expired_password'] = false;


```

**Comment by AmeliaEnslin** [comment]
I keep on getting, Password was refused by LDAP directory

**Comment by coudot** [comment]
You can check the logs of Apache and OpenLDAP to have more information.

Try also to set `$debug = true` in config.inc.php

**Comment by AmeliaEnslin** [comment]
I got it to work, in the self-service-password it asks you who can change a password where its set to "user" i changed it to "manager" it works 100%

**Comment by coudot** [comment]
Great to know! I close the issue.
