### ISSUE TITLE
Reset password with token doesn't work

### ISSUE THREAD

**Issue by Iwios** [ltb-project/self-service-password#800]
Hello,

I try to configure reset password with token.

When I try to reset, I have this message:

PHP message: PHP Warning:  ldap_exop_passwd(): Passwd modify extended operation failed: Insufficient access (50)

It's because my openldap doesn't have ssl activate?

With the stndard form to reset, this work fine

**Comment by coudot** [comment]
The service account you configured must have the rights to write the password. Check your ACLs.

**Comment by Iwios** [comment]
I try with the domain admin

**Comment by Iwios** [comment]
To complete, in the web page, the massage is "Password was refused"

**Comment by coudot** [comment]
Set debug to true and check the logs.

**Comment by Iwios** [comment]
Sorry, debug was set to "true", but where is the default file for log ?

**Comment by Iwios** [comment]
In my ldap log I have this message :

Sep  7 22:06:17 srv-ldap-1 slapd[4153]: conn=1000 op=2 MOD attr=userPassword
Sep  7 22:06:17 srv-ldap-1 slapd[4153]: slap_global_control: unrecognized control: 1.3.6.1.4.1.42.2.27.8.5.1
Sep  7 22:06:17 srv-ldap-1 slapd[4153]: conn=1000 op=2 RESULT tag=103 err=50 text=
Sep  7 22:06:17 srv-ldap-1 slapd[4153]: conn=1000 op=3 UNBIND
Sep  7 22:06:17 srv-ldap-1 slapd[4153]: conn=1000 fd=12 closed

**Comment by coudot** [comment]
The error 50 means the account doing the modification has no rights to do it. Configure your ACLs.

**Comment by Iwios** [comment]
Hello,
Sorry... In fact I config with a user wihtout right. 

Have a good day
