### ISSUE TITLE
Display reasons why new password is not accepted from LDAP

### ISSUE THREAD

**Issue by webtrader** [ltb-project/self-service-password#805]
Hi,

I came across this utility and it is exactly what I needed. Thank you to the developers! I have a feature request. I am using this tool to allow users to change their own AD password on the web. If LDAP does not allow the new password, would it be possible to allow the error message reason to flow through to the user?

For example, suppose the user enters a new password that was already used. On the self-service website, it says:
Password was refused by the LDAP directory

However in debug, the message is given:
res_errno: 19, res_error: <0000052D: Constraint violation - check_password_restrictions: the password was already used (in history)!>, res_matched: <>

It would be nice if this could flow through to the web page, so that the user sees a message such as:
New password was refused by the LDAP directory: Constraint violation - check_password_restrictions: the password was already used (in history)!

(BTW, it would also be more clear if the error started with "New password" instead of "Password", since the latter is not clear whether it's the old or new password that was refused)

Thank you

**Comment by coudot** [comment]
Hello,

you can try this option:
```php
# Show extended error message returned by LDAP directory when password is refused
$show_extended_error = true;
```

**Comment by webtrader** [comment]
That's exactly what I was looking for. I enabled that and I see the message now. Thank you for your fast reply!
