### ISSUE TITLE
Cannot use signal as SMS method

### ISSUE THREAD

**Issue by koznov** [ltb-project/self-service-password#809]
Greetings!
I am facing issue with sending SMS via signal. 

In error.log for nginx I see that error:
`2023/10/04 19:52:26 [error] 944#944: *17 FastCGI sent in stderr: "PHP message: PHP Warning:  Array to string conversion in /usr/share/self-service-password/lib/smsapi-signal-cli.inc.php on line 49PHP message: Error sending message: ArrayPHP message: Error while sending sms by api to +49XXXXXXX60 (user username)" while reading response header from upstream, client: 172.31.251.31, server: _, request: "POST /?action=sendsms HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php-fpm.sock:", host: "sspr.localdomain.local", referrer: "https://sspr.sclabs.cloud/?action=sendsms"`

My local config contains configuration for signal api:

```
$use_sms = true;
$sms_method = "api";
$sms_api_lib = "lib/smsapi-signal-cli.inc.php";
$signal_user = '+7xxxxxxxx03';
$signal_config = '/opt/signal-cli-0.12.2/etc/';
$signal_cli = '/usr/local/bin/signal-cli';
```

When I am combining string from smsapi-signal-cli.inc.php ($signal_cli -u $signal_user --config $signal_config send -m $message $mobile) for manual sending message - there is no error and message can be successfully send:

```
root@sspr:/home/username@localdomain.local# /usr/local/bin/signal-cli -u +7xxxxxxxx03 --config /opt/signal-cli-0.12.2/etc/ send -m DemoMessage +49XXXXXXX60 
INFO  AccountHelper - The Signal protocol expects that incoming messages are regularly received.
1696449807628
root@sspr:/home/username@localdomain.local#
```
Inside Active Directory for that user I add only one phone number (+49XXXXXXX60).
What can be the reason for not sending message via signal api calls?

Versions of products : 
Self Service Password: 1.5.3
Signal CLI: 0.12.2
OS: Ubuntu 22.04 LTS with PHP 8.1 FPM and nginx/1.18.0

**Comment by coudot** [comment]
This is a bug in the code, the exec command put an array in the output, not a string. This must be fixed by printing the array correctly in the error message.

**Comment by koznov** [comment]
If you need something additional from my side to reproduce error - let me know. I will try my best to assist with that.

**Comment by coudot** [comment]
The bug is in the display of the error, which means you have an error running the command from php code. You should check permissions of signal-cli command

**Comment by koznov** [comment]
I've added 777 -R options - and Signal now can send the message. Thanks!

Russian Encoding is broken, btw :-D

![image](https://github.com/ltb-project/self-service-password/assets/16073136/7ff95e86-34e2-4f07-a188-550ead25d9f9)

**Comment by coudot** [comment]
Could you enable debug and show the logs?
