### ISSUE TITLE
arm64 build

### ISSUE THREAD

**Issue by barsikus007** [ltb-project/self-service-password#810]
Can you provide arm64 build of your service, please?

**Comment by coudot** [comment]
I don't see the point as we are a PHP project, it should run directly on arm64

**Comment by coudot** [comment]
We are not the provider of this docker image.

The best is to build a new docker image from sources.

**Comment by barsikus007** [comment]
But who is building https://hub.docker.com/r/ltbproject/self-service-password then?

**Comment by coudot** [comment]
> But who is building https://hub.docker.com/r/ltbproject/self-service-password then?

This one is indeed built by us, but we only provide the default platform. If you need a specific platform, just check out the code and build the docker image.
