### ISSUE TITLE
Use DNS SRV record for ldap

### ISSUE THREAD

**Issue by arozmarin** [ltb-project/self-service-password#811]
Hi team would be possible to use DNS SRV record? 
for example
$ldap_url = "ldap://_ldap._tcp.example.org";
and not URL:
$ldap_url = "ldap://ldap.example.org";

Thanks

**Comment by coudot** [comment]
You can first try to rely on the ldap lib used in PHP LDAP:
```php
$ldap_url = "ldap:///dc%3Dexample%2Cdc%3Dorg";
```

It this does not work, use `dns_get_record` function in your config file to build the LDAP URL you need (see https://www.php.net/manual/fr/function.dns-get-record)

**Comment by arozmarin** [comment]
Thank you for quick replay, I'll test this, but for now I find a way through kerberos for my solution.
