### ISSUE TITLE
Dockerfile fails to build

### ISSUE THREAD

**Issue by pljeff** [ltb-project/self-service-password#813]
`docker build .` fails to build (at least for me) for due to the following two issues:

1. The `libweb6` package is not found.  As the `php:8.1-apache` image is based on Debian 12 slim (bookworm), there is no `libweb6` package (line 24 in the Dockerfile).  It has been replaced with the `libwebp7` package.
2. Line 33 in the Dockerfile, `docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu/` results in "Cannot find ldap libraries in /usr/lib/x86_64-linux-gnu/".  Changing to just `docker-php-ext-configure ldap` successfully builds for me, but I have not yet verified the functionality of the container.  

This may be due to lack of knowledge on my part, so if there is something I'm doing wrong, I would love to know so I can build updated containers with security patches.  Thanks!

**Comment by davidcoutadeur** [comment]
Thanks for your PR.

**Comment by davidcoutadeur** [comment]
Ok, thanks for the fix. I have merged it right now.

**Comment by davidcoutadeur** [comment]
(see also #807)
