### ISSUE TITLE
 PHP Parse error:  syntax error, unexpected variable "$ldap_bindpw"

### ISSUE THREAD

**Issue by sk3pp3r** [ltb-project/self-service-password#822]
```FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected variable "$ldap_bindpw" in /var/www/self-service-password/conf/config.inc.local.php on line 28" while reading response header from upstream, client: x.x.x.x, server: my-super-cool-server.compute.amazonaws.com, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "my-super-cool-ec2.compute.amazonaws.com"```

**config.inc.local.php**
```
# LDAP
$ldap_url = "ldap://172.31.19.114:389";
$ldap_starttls = false;
$ldap_binddn = "CN=root,CN=Users,DC=test,DC=local"
$ldap_bindpw = "Z321321z"
$who_change_password = "user"

$audit_log_file = "/var/log/self-service-password/audit.log";


# Debug
$smarty_debug = true;
```

**Comment by davidcoutadeur** [comment]
You are missing a `;` at the end of `$ldap_binddn`, `$ldap_bindpw`, and `$who_change_password` lines

Please don't open issue for configuration problems. You can use the mailing list for that: https://www.ltb-project.org/contact.html
