### ISSUE TITLE
LDAP - Bind error 49 (Invalid credentials)

### ISSUE THREAD

**Issue by Lulan1999** [ltb-project/self-service-password#838]
i need help that works perfectly i can connect to ldap
ldapsearch -D "cn=lonalu ,cn=Users,dc=zuzu,dc=local" -x -w "password" -h 10.0.0.139 -b "cn=Users,dc=zuzu,dc=local"

but configuration what i have is showing that problem LDAP - Bind error 49 (Invalid credentials), when try to do anything on site as change password or send e-mail, anyone could explain me where is the problem? what do i do wrong? i am using docker version, configuration for sure is working ,because i tested on 2 diffrent ad one on linux and one on windows when i changed ip i had two difrent messages but now i stuck on that problem. please give me some advice
$ldap_url = "ldap://10.0.0.139";
$ldap_binddn = "cn=lonalu ,ou=Users,dc=zuzu,dc=local";
$ldap_bindpw = "password";
$keyphrase = "mysecret";
$ldap_starttls = false;
$ldap_base = "dc=zuzu,dc=local";
$debug = true;

whem i leave binddn and bindpw empty error is
LDAP - Search error 1 (Operations error), referer

**Comment by davidcoutadeur** [comment]
Please don't use the issue system for questions, there is the mailing list for that.

Error 49 means wrong authentication: either wrong password or DN.

**Comment by coudot** [comment]
See https://github.com/ltb-project/self-service-password/discussions/836

**Comment by Lulan1999** [comment]
credientals is good i will not make a mistake if i already checked ldapsearch -D "cn=lonalu ,cn=Users,dc=zuzu,dc=local" -x -w "password" -h 10.0.0.139 -b "cn=Users,dc=zuzu,dc=local" and have no problem to connect please help me
