### ISSUE TITLE
Add functionality (SSH PUB Key)

### ISSUE THREAD

**Issue by eperry** [ltb-project/self-service-password#84]
I was thinking about adding a "page" To add the SSH Pub Key. We have extended our User schema to add SSH Key pairs  and now we would like to add to the self service site to upload their key's after they confirm their user id and password.

We know how to do it from the shell using the openldap  ldapmodify command  , 

I was wondering if you had suggestions to what I would modify to implement this before I dove in

I presume add a new <GITROOT>/pages , and add to the functions page to add the appropriate code to update the ssh key.  Maybe even add a config line to enable it.

Anything else?

here is the shell script we wrote, of course all specific data has been changed. 

> #!/bin/bash
> export LDAPTLS_REQCERT=never
> BIND_USER='yourusername@ad.example.com'
> BIND_PASS='xxxxxxxxxxxxxxx'
> echo -n "Enter Userid: "
> read user
> dnuser=`ldapsearch  -Zh $HOSTNAME -D $BIND_USER -w $BIND_PASS -b "CN=Users,DC=ad,DC=examplel,DC=com" "(sAMAccountName=$user)" dn | grep -oP '(dn: CN.+)'`
> echo -n "Enter Key filename"
> #stty -echo
> read keyfile
> key=$(<$keyfile)
> echo "--------------------------------------------"
> echo $key
> echo "--------------------------------------------"
> #stty echo
> if [[ -z $dnuser || -z $key ]]
> then
>         echo "-----------------------------"
>         echo "ERROR: userid or PubKey not set"
>         echo "-----------------------------"
>         exit 1
> fi
> ldapmodify -vvv  -Zh $HOSTNAME -D $BIND_USER -w $BIND_PASS  << _EOF_
> $dnuser
> changetype: modify
> add: sshPublicKeys
> sshPublicKeys: $key
> _EOF_
> echo "------------------------------------------------------------------"
> echo "Verification"
> echo "------------------------------------------------------------------"
> set -x
> ldapsearch  -Zh $HOSTNAME -D $BIND_USER -w $BIND_PASS -b "CN=Users,DC=ad,DC=example,DC=com" "(sAMAccountName=$user)" sshPublicKeys
>

**Comment by coudot** [comment]
Hello @eperry, see this pull request from @praymann: https://github.com/ltb-project/self-service-password/pull/81

I did not have the time to merge it yet, but I think this is an interesting feature. If you can test the pull request, it would be great.

**Comment by eperry** [comment]
Even better, I will check it out today or tomorrow. and let you know if it looks to work.

**Comment by eperry** [comment]
Closing ticket, I am happy with the PR/81  I hope to have it merged to the main branch soon
