### ISSUE TITLE
error: SvcErr: DSID-03190F9E,

### ISSUE THREAD

**Issue by kanenses** [ltb-project/self-service-password#840]
Hi there,

After config Self Service Password I getting error:

`The password as refused from LDAP. (00002077: SvcErr: DSID-03190F9E, problem 5003 (WILL_NOT_PERFORM), data 0 ) `

Our AD do not use SSL Certificates (and is not possible config at this time).

How can I fix this error please?

**Comment by coudot** [comment]
> Our AD do not use SSL Certificates (and is not possible config at this time).
> How can I fix this error please?

The answer is in your message: use SSL certificate on AD. AD refuses any password change on LDAP. LDAPS is mandatory.

**Comment by kanenses** [comment]
> > Our AD do not use SSL Certificates (and is not possible config at this time).
> > How can I fix this error please?
> 
> The answer is in your message: use SSL certificate on AD. AD refuses any password change on LDAP. LDAPS is mandatory.

Is there any way for by pass the use of SSL?

**Comment by coudot** [comment]
> Is there any way for by pass the use of SSL?

No
