### ISSUE TITLE
Password policy javascript checker

### ISSUE THREAD

**Issue by coudot** [ltb-project/self-service-password#854]
Hello,

testing the latest changes on master, I see the following problems:
* "Same password as older" check does not work
* Checker is broken on reset by questions page

**Comment by davidcoutadeur** [comment]
Thanks for the feedback, giving a look.

**Comment by davidcoutadeur** [comment]
* "Same password as older" check does not work

This one seems to work well on my side. Maybe the confusion comes from the fact that the criterium is checked only when both old password length, and new password length are strictly superior to 0?

**Comment by coudot** [comment]
> This one seems to work well on my side. Maybe the confusion comes from the fact that the criterium is checked only when both old password length, and new password length are strictly superior to 0?

Indeed, I was not testing the correct thing.

It works well.

I was thinking that we have a check checking that password confirmation is correct (means that there is the same value between new password and confirm password) but we don't have this in the policy panel

**Comment by davidcoutadeur** [comment]
For information, I have just pushed a commit to trigger the check even when the old password, login, and new password length are zero. It's more logic for a user.

**Comment by davidcoutadeur** [comment]
> Checker is broken on reset by questions page

This one should be ok now. The problem was due to a test not checking correctly the absence of oldpassword field in the form. Everything seems ok now.

Tell me if you face other problems, else I think we can close this issue.

**Comment by coudot** [comment]
We may need to remove the test on old password when old password is not available.

**Comment by davidcoutadeur** [comment]
> We may need to remove the test on old password when old password is not available.

That's what is done currently. We bypass the check and always display a check near the criteria.

Maybe you mean removing the criterium from the list?

**Comment by coudot** [comment]
Yes, as we can't check it I think it should not be displayed. This can be a new issue/PR as this is a change.

**Comment by davidcoutadeur** [comment]
Done in https://github.com/ltb-project/self-service-password/issues/855

@coudot Could you test all is ok for you?
