### ISSUE TITLE
"syntax error, unexpected token class" on Debian 10

### ISSUE THREAD

**Issue by wanglin86769** [ltb-project/self-service-password#862]
On Debian 10, when running command “apt install self-service-password”, error message "syntax error, unexpected token class" will display.

I tried to install the latest version of smarty3 manually, but it does not work.

I tried php 7.3, php7.4 and php8.2, but it does not work.

What should be the problem?

![微信图片_20240313144558](https://github.com/ltb-project/self-service-password/assets/62229607/974603dc-098b-4d0e-a129-c43fb6cc432c)

**Comment by davidcoutadeur** [comment]
Hello, the message in the screenshot is just a warning that tells you that you must install smarty3 package manually. There is no error at this step.

Also, please don't use the issue system for asking questions, there is the mailing list for that.

**Comment by wanglin86769** [comment]
Thanks for the quick response.
I was not asking questions, I was intended to submit issues that I encountered when I use this client tool. If you do not think it is an issue, just close it.

**Comment by davidcoutadeur** [comment]
> Thanks for the quick response. I was not asking questions, I was intended to submit issues that I encountered when I use this client tool. If you do not think it is an issue, just close it.

Thanks for the report. I was just pointing that when using/installing a software for the first time, you should first:
- read the documentation carefully
- ask for help on the mailing list, including if you have strange behavior at step1 of installation.
