### ISSUE TITLE
Erreurs de Français

### ISSUE THREAD

**Issue by 0noon1** [ltb-project/self-service-password#89]
Bonjour a tous,

J'ai noté quelques fautes de Français dans la traduction du logiciel : 

"Votre nouveau mot de passe **de** doit pas être identique à l'ancien"
"Votre nouveau mot de passe ne doit pas être identique à votre **identifant**"

Merci pour votre travail !

**Comment by coudot** [comment]
Done by @plewin in #90

**Comment by plewin** [comment]
Thank you @0noon1
