### ISSUE TITLE
refactor the captcha system for integrating external captcha

### ISSUE THREAD

**Issue by davidcoutadeur** [ltb-project/self-service-password#894]
Currently, there is captcha system based on a backend PHP library: `Gregwar\Captcha\PhraseBuilder`

It would be nice to have a generic system for integrating external captcha libraries.

It implies:
- to have a new option for selecting internal or external captcha
- coding a generic system for external captcha easily

**Comment by davidcoutadeur** [comment]
See also #895

**Comment by coudot** [comment]
See if we can solve #789 when working on captcha system

**Comment by coudot** [comment]
There is also #343 issue dealing with reCaptcha
