### ISSUE TITLE
Cannot build RPM from sources

### ISSUE THREAD

**Issue by coudot** [ltb-project/self-service-password#896]
When trying to build RPM from our sources, we get this error:
```
+ cp -a 'vendor/*' /home/clement/build/BUILDROOT/self-service-password-1.6.0-1.el7.x86_64//usr/share/self-service-password/vendor
cp: cannot stat 'vendor/*': No such file or directory
erreur : Mauvais statut de sortie pour /var/tmp/rpm-tmp.rY0WvD (%install)


Erreur de construction de RPM :
    Mauvais statut de sortie pour /var/tmp/rpm-tmp.rY0WvD (%install)
```

This is because `vendor/` is no more in sources but only in distribution tarball

**Comment by coudot** [comment]
@xavierba I think we should not depend on internet when building a package, so running composer inside %build step will not be an option...

How would you solve this?

**Comment by davidcoutadeur** [comment]
I see 3 options:

- either we consider that tests *must* be done during package build. In this case, we must manage in the package all the removal phase of the test libraries (which means listing all the test libraries)
- or we consider that tests must not be executed by the packaging process, but before -> in this case, we could simply remove the test phase.
- or we try to run the test in best-effort: if the test libraries are here, we launch them

Also, I don't think we can safely rely on internet for the tests/CheckPasswordTest.php test

**Comment by coudot** [comment]
I choose for release 1.6.0 to build RPM from distribution tarball and not from sources.

Tests are disabled for now.
