### ISSUE TITLE
Docker listening on port 80

### ISSUE THREAD

**Issue by 3d7l** [ltb-project/self-service-password#898]
I have one question regarding the docker 

```
docker run -p 80:80 \
    -v $PWD/ssp.conf.php:/var/www/conf/config.inc.local.php \
    -it docker.io/ltbproject/self-service-password:latest
```

I was wondering why using port 80 and not port 443 ?

**Comment by coudot** [comment]
Changing port to 443 will not magically add security. It's up to you to configure a reverse proxy or any other solution to deploy you certificates and enable HTTPS.

**Comment by 3d7l** [comment]
Does it mean  the docker cannot face the internet directly ?

If so,  I can indeed use a reverse-proxy to provide https between the client and the reverse-proxy, but what if I also want https between the reverse-proxy  and the docker ?
