### ISSUE TITLE
Unable to install on RockyLinux 8

### ISSUE THREAD

**Issue by junnnhaooo** [ltb-project/self-service-password#904]
Is there any option to install on RockyLinux 8?

Getting the following error :
LTB project packages (noarch)                                                                                                                                                                                2.4 kB/s | 3.0 kB     00:01
Error:
 Problem: cannot install the best candidate for the job
  - nothing provides /usr/bin/python needed by self-service-password-1.6.0-1.el8.noarch from ltb-project-noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

**Comment by coudot** [comment]
Hello @junnnhaooo 

I just updated the RPM repo for EL8, could you test?

**Comment by coudot** [comment]
No feedback, good feedback...
