### ISSUE TITLE
Can email reset use AD user's FirstName, instead of login ID?

### ISSUE THREAD

**Issue by wicknet** [ltb-project/self-service-password#91]
Not a usability issue per se, but thought it would improve the overall aesthetics if the user got a password reset email beginning "Hi John", instead of "Hi JDoe".

This is a wonderful project. SO glad I stumbled on it. Thank you for all your hard work!

**Comment by dlang9159** [comment]
See #71

**Comment by wicknet** [comment]
Got it. I should change the current .php files with your modifications to make this work, right?

Q: When upgrading to the next version of LTB, will those changes stick or I'd have to do them again?

Thanks!

**Comment by dlang9159** [comment]
You can change your current .php files to make it work. For our installation it works without problems.
Answer to your question: I can not guarantee it, but I hope this PR will make it to the next release. In this case the upgrade includes the new code.

**Comment by wicknet** [comment]
Perfect. Thanks again.

**Comment by coudot** [comment]
Yes, should be in 1.1

No release date for the moment, need to work on it

**Comment by wicknet** [comment]
I've changed all php files except sendtoken.php in which the following line could NOT be found:

if (!$mail_address_use_ldap) {

Any pointers?

**Comment by dlang9159** [comment]
Oh, this is from a previous PR where a feature is added that pulls the mail adress from ldap instead of the user input. Can you work around this? This part of the code can be ignored .
