### ISSUE TITLE
Vendor directory missing from tar.gz distribution

### ISSUE THREAD

**Issue by unquietwiki** [ltb-project/self-service-password#917]
Tried upgrading 1.5.0 to 1.6.0; web server logs were complaining about trying to access a "vendor" directory, that I don't see in the tar.gz or current Github repo. Switching over to a DEB-based install did have the "vendor" directory though.

**Comment by davidcoutadeur** [comment]
Hello,

vendor is generated by composer by doing a `composer update` at the root of the project.

Should be available in the *.tar.gz though. @coudot can you check?

Regards

**Comment by coudot** [comment]
Yes, from distribution tarball available here: https://ltb-project.org/archives/ltb-project-self-service-password-1.6.0.tar.gz

Installation from git repository is not documented.

Use tarball or packages.

**Comment by unquietwiki** [comment]
@coudot Clarifying, I was trying to install from tarball & not git. Just happened to notice it was missing in the Github too. Due apologies for the confusion.

**Comment by coudot** [comment]
`vendor/` is not provided in sources (git or source tarball attached to https://github.com/ltb-project/self-service-password/releases/tag/v1.6.0)

The official installation is documented on https://self-service-password.readthedocs.io/en/stable/installation.html

**Comment by unquietwiki** [comment]
@coudot It looks like from what @davidcoutadeur said, maybe there needs to be a step added to do a **composer update** as part of a tarball install process?

**Comment by coudot** [comment]
No. This is only needed when installing from sources (assets provided in https://github.com/ltb-project/self-service-password/releases/tag/v1.6.0 are sources)

**Comment by unquietwiki** [comment]
Acknowledged. Well, thank you for looking into this for me.
