### ISSUE TITLE
Question: Config file gets ignored /etc/self-service-password/config.inc.local.php

### ISSUE THREAD

**Issue by liszca** [ltb-project/self-service-password#941]
I struggle with the setting up the configuration following this installation method:
https://self-service-password.readthedocs.io/en/latest/installation.html#debian-ubuntu

In general it looks like the configuration file /etc/self-service-password/config.inc.local.php is not used. I disabled captcha but it still shows up.

I bet its an easy fix, but I have no idea how to get the config file in /etc working.

**Comment by liszca** [comment]
That file exists, and in the config.inc.php are the lines:
```
if (file_exists (__DIR__ . '/config.inc.local.php')) {
    require_once __DIR__ . '/config.inc.local.php';
}
```

File Rights: 
```
-rw-r--r-- 1 root root 16072 Jul 12 13:45 config.inc.local.php
-rw-r--r-- 1 root root 16066 Jul 12 13:26 config.inc.php
```

**Comment by davidcoutadeur** [comment]
config.inc.php is loaded first. This is kind of "default configuration"
Then at the end, config.inc.local.php loads config.inc.local.php. These parameters overloads those in config.inc.php.

For example for captcha: it is disabled by default (in config.inc.php).
Then, if you want to enable it, you should create a config.inc.local.php file (if it does not exist), and overload the parameter $use_captcha to true.

Hopes it's clearer now.

**Comment by liszca** [comment]
> config.inc.php is loaded first. This is kind of "default configuration" Then at the end, config.inc.local.php loads config.inc.local.php. These parameters overloads those in config.inc.php.
> 
> For example for captcha: it is disabled by default (in config.inc.php). Then, if you want to enable it, you should create a config.inc.local.php file (if it does not exist), and overload the parameter $use_captcha to true.
> 
> Hopes it's clearer now.

Yes thats how I think its working, but somehow captcha "false" isn't set as in the configuration file, also all other parameters are not taken from this file.

**Comment by davidcoutadeur** [comment]
I didn't encounter this behavior before.

I suggest you continue debugging to understand why your parameter is not taken into account. (adding logs in htdocs/index.php or htdoc/change.php can help)

**Comment by liszca** [comment]
> I didn't encounter this behavior before.
> 
> I suggest you continue debugging to understand why your parameter is not taken into account. (adding logs in htdocs/index.php or htdoc/change.php can help)

Can you give me an example where logs are placed in /var/log/ssp.log

**Comment by liszca** [comment]
I only found:
https://self-service-password.readthedocs.io/en/latest/config_general.html#debug

but those settings are ignored

**Comment by coudot** [comment]
How did you install the software?

**Comment by liszca** [comment]
> How did you install the software?

https://self-service-password.readthedocs.io/en/latest/installation.html#debian-ubuntu

**Comment by liszca** [comment]
running apachectl -s my DocumentRoot doesn't look right. I try to fix that I bet this will solve my problem ...

**Comment by liszca** [comment]
Hi coudot thanks for your help, the reverseproxy pointed to the docker version. And I had forgot about my tries with docker. But now it was successful with Docker.
