### ISSUE TITLE
Freezing the background process on the phone leads to duplicate sending of verification codes

### ISSUE THREAD

**Issue by cccsora** [ltb-project/self-service-password#942]
After deploying the SMS API service, I tested it on my iPhone. However, when I switched to the backend application to view the verification code and then switched back to the browser, the phone reloaded the verification code input interface, causing the verification code to be sent again. I am unable to use the previously copied verification code for verification. How can I configure to solve this problem?

**Comment by cccsora** [comment]
The phone model I am using is iphone 12 pm

**Comment by coudot** [comment]
Seems linked to Safari, a lot of forums are talking about this.

We can't do anything on server side, change browser or mobile.
