### ISSUE TITLE
How to remove favicon, change title + header and remove the Change password box?

### ISSUE THREAD

**Issue by wutz-dot-io** [ltb-project/self-service-password#956]
Hi,

as title says, see this picture:

![photo_2024-08-06_19-20-09](https://github.com/user-attachments/assets/7211ad4a-a050-46a6-926f-875f4c57f952)

which variables would I modify to achieve this?

I'm using docker...

Thanks for this great project

Tim

**Comment by wutz-dot-io** [comment]
I'm using docker because I'm lazy

**Comment by love6875520** [comment]
you can modify the lang file to change text

**Comment by wutz-dot-io** [comment]
> you can modify the lang file to change text

I'm using docker. But nevermind, I will close this issue and leave things as they are. I know I could achieve all those things when I would use the deb repo but I'm too busy with other things. Thanks anyway :)

**Comment by wutz-dot-io** [comment]
> you can modify the lang file to change text

I'm using docker. But nevermind, I will close this issue and leave things as they are. I know I could achieve all those things when I would use the deb repo but I'm too busy with other things. Thanks anyway :)
