### ISSUE TITLE
Version that seems up to date but not on the login page

### ISSUE THREAD

**Issue by cp61** [ltb-project/self-service-password#976]
Good morning, 

I updated toolsbox to v1.6.1 via the apt install self-service-password command.

If I place the order again, it tells me that I am up to date.

On the other hand, on the Toolsbox page it always shows me a version 1.5.4

Is this just a display problem or should I place another order to be completely up to date?

I had the same problem when I upgraded to 1.6.0

![2024-09-06_08_12_10-admintool@SRV-TOOLSBOX_~](https://github.com/user-attachments/assets/a638f0d2-2e22-47f4-8395-4591895dc3da)

![2024-09-06_08_39_35-Gestion_du_mot_de_passe_et_11_pages_de_plus_-_Trav](https://github.com/user-attachments/assets/1b9a86a1-d906-4979-9b19-0a3f8b0e8068)

**Comment by coudot** [comment]
Check your Apache configuration to be sure that your vhost is pointing to the correct installation and not a manual one.

**Comment by cp61** [comment]
My vhost points to /var/www/html/ssp/htdocs
and the index.html indicates a 1.5.4

Knowing that it was an intern who installed the server for us and that he is no longer there, I think it is a manual installation.

What should be the right path or where can I find the files for 1.6.1

**Comment by coudot** [comment]
This is indeed a manual installation

The packaged installation is in /usr/share/self-service-password

**Comment by cp61** [comment]
Thank you very much for your responsiveness. I'm going to put this all in order
