### ISSUE TITLE
Bug in resetbytoken.php

### ISSUE THREAD

**Issue by copecalo** [ltb-project/self-service-password#98]
Hi,

I think there is a bug in resetbytoken.php.

The variable $source is not changed when page is called and the help message is not the good one when called by sendsms.php. So it talks about a mail but the media used is SMS.

Regards

**Comment by coudot** [comment]
Hi @copecalo 

source is set as GET parameter in reset_url in sendsms.php:
````php
    $reset_url .= "?action=resetbytoken&token=$token&source=sms";
````

It should then set the source parameter in resetbytoken.php. Where is the bug?

**Comment by copecalo** [comment]
I confirm that the GET parameter is set in sendsms.php, there is no bug in that script. But resetbytoken.php does not affect it to $source variable.

The $source variable is initiated as empty at the beginning of the script and is then tested from line 222 to line 231 but only the first test is available because the value of this variable is empty.

But I may be mistaken as I am not a developer, just a guy who wants to debug a fresh install of that great tool.

For testing, I have just changed line 38 from
`$source = "";`
to
`$source = $_REQUEST["source"];`
and it works but it may be not very beautiful or secure...

**Comment by coudot** [comment]
@copecalo you are right. Indeed, the $source parameter in set in index.php but is then reset in resetbytoken.php

Can you try to remove line 38 of resetbytoken.php?

**Comment by copecalo** [comment]
I've removed line 38 of resetbytoken.php and it works

**Comment by coudot** [comment]
Thanks for the feedback, I will commit the patch.
