### ISSUE TITLE
Add ltb-common to composer.json

### ISSUE THREAD

**Issue by cccsora** [ltb-project/self-service-password#993]
When I tested the restAPI in version 1.6.1, I found that there was no ’search-with-scope‘ function in the current dependency file. I noticed that ltb-common was mentioned in the recent Issues. At present, there is only 'ltb-project/ldap' in composer.json， Can you add the newly used dependency files to composer.json on GitHub?

**Comment by coudot** [comment]
We just released 1.7 with ltb-common 0.3, you should use this new version.
