### ISSUE TITLE
Rest API in Docker

### ISSUE THREAD

**Issue by rlljorge** [ltb-project/self-service-password#996]
I am using the Docker version tag 1.7, and the Apache server is missing a configuration:

Alias /rest /var/www/rest

After manually adding the Alias, another issue appears in an include:

```PHP Fatal error:  Uncaught Error: Failed opening required '../../lib/detectbrowserlanguage.php' (include_path='.:/usr/local/lib/php') in /var/www/rest/v1/include.php:24\nStack trace:\n#0 /var/www/rest/v1/checkpassword.php(2): require_once()\n#1 {main}\n  thrown in /var/www/rest/v1/include.php on line 24```

**Comment by coudot** [comment]
Thanks for the report, we will look at it

**Comment by coudot** [comment]
There is a fix in #997 for the PHP Fatal error

Regarding the vhost configuration, the Alias seem present but the location is disabled by default. How did you change the configuration?

**Comment by rlljorge** [comment]
Hello,

I simply added the following configuration:

Alias /rest/ /var/www/rest/

In the file /etc/apache2/sites-enabled/000-default.conf

**Comment by coudot** [comment]
Issue with language detection is fixed.

Enabling REST services by default in docker image does not seems a good idea. REST endpoints should be protected at least by a basic auth.
